code/game/objects/structures/tables_racks.dm
code/modules/food_and_drinks/food/snacks.dm
code/modules/jobs/job_types/roguetown/yeomen/artificer.dm
code/modules/roguetown/roguecrafting/structure.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
code/modules/roguetown/roguejobs/engineer/anvil_recipes/mechanical.dm

- added 3x flint recipe for 1 iron 1 stone
- added chain recipe for 1 iron
- shifted lockpicks and lockpick rings to engineering
- locks now give 2 (up from 1)
- Cogs now give 2 (up from 1)
- Bronze lampterns now give 3 (Up from 1)
- cooling backpacks now cost 1 bone, 1 gear, 1 backpack (down from 1 ingot, 3 gear, 1 backpack)
- smokebombs now give 2 (up from 1)
- bronze limbs now cost 1 ingot and 2 gears (down from 2 ingots and 2 gears)
- serf stone ring for 1 cog and 1 toper
- place holders for houndstone, scom rings, and gemerald necklace
- Arrow/bolt Ammo increased to 10 and now requires 1 iron ingot and 2 sticks
- cooling table can now be made with one log, one iron ingot, and 1 cog to keep food fresh on it. this table is weak though, careful not to hit it too hard.
By request (and …

Artificer / Smithing recipe tweaks

---

code/modules/flufftext/Hallucination.dm
code/modules/reagents/chemistry/reagents/alcohol_reagents.dm

Expanded and fleshed out admin hallucinations, tweaked some, finished two more hallucinations.
Builds atmosphere in spooki scenarios

Hallucinations pt 2

---

code/game/objects/items/candle.dm
code/game/objects/items/rogueitems/bouquet.dm
code/game/objects/items/rogueitems/cup.dm
code/game/objects/items/rogueitems/keyrings.dm
code/game/objects/items/rogueitems/keys.dm
code/game/objects/items/rogueitems/natural/clothfibersthorn.dm
code/game/objects/items/rogueitems/natural/stones.dm
code/game/objects/items/rogueitems/needle.dm
code/modules/clothing/rogueclothes/armor.dm
code/modules/clothing/rogueclothes/cloaks.dm
code/modules/clothing/rogueclothes/feet.dm
code/modules/clothing/rogueclothes/gloves.dm
code/modules/clothing/rogueclothes/hats.dm
code/modules/clothing/rogueclothes/mask.dm
code/modules/clothing/rogueclothes/neck.dm
code/modules/clothing/rogueclothes/pants.dm
code/modules/clothing/rogueclothes/rings.dm
code/modules/clothing/rogueclothes/robes.dm
code/modules/clothing/rogueclothes/shirts.dm
code/modules/clothing/rogueclothes/storage.dm
code/modules/clothing/rogueclothes/wrists.dm
code/modules/farming/produce.dm
code/modules/reagents/reagent_containers/glass.dm
code/modules/roguetown/roguecrafting/alchemy/alch_items.dm
code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
code/modules/roguetown/roguecrafting/alchemy/mortarpestle.dm
code/modules/roguetown/roguejobs/blacksmith/items.dm
code/modules/roguetown/roguejobs/miner/rogueores.dm
code/modules/roguetown/roguemachine/scomm.dm
modular_azurepeak/code/game/objects/items/ritechalk.dm

* Turns off experimental-inhands for a lot of small items that don't really need it & clothing.
Might not actually do anything for performance, but should put less strain on the game to render & offset sprites that you can't see anyways.

removes exp inhands from small objects

---

code/modules/admin/verbs/adminpm.dm

It was set to blank.ogg for some reason..I guess some sort of findreplace shinnigans.
*BWOINK*

Fixes bwoink noise not playing to players

---

code/__DEFINES/traits.dm
code/modules/clothing/rogueclothes/neck.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/wretch.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/roguetown/heretic_commune.dm
code/modules/roguetown/roguecrafting/alchemy/alch_items.dm

* Comments out heretic tab.
* Adjusts Raider stat.
* Turns off Experimental hip for vials & amulets
Careless merges on my part. Had christian epiphanies that the heretic tab was going to be annoying really fast & don't want accessible brain comms. Code should be repurposed elsewhere in the future.

comments out heretic commune

---

code/datums/gods/patrons/divine_pantheon.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
code/modules/jobs/job_types/roguetown/church/druid.dm
code/modules/spells/roguetown/acolyte/dendor.dm

Tame Animals is a broken, useless miracle—nothing more than a wasted slot. It barely works, and when it does, it's underwhelming. Druids are known for shapeshifting, and that’s where their true power lies. Swap it out and actually make an impact.

Gives Druid shapeshifting

---

code/modules/roguetown/roguecrafting/structure.dm

Fixes cooling table not taking materials
Fixes Cooling table not taking resources
Corrects a bug where the cooling table wasn't taking the materials required to make it.
you shouldn't have infinite cooling tables

Cooling Table resource fix

---

code/modules/spells/roguetown/acolyte/dendor.dm

-Fixes the cooldown once you shift back into your human form, as of right now the spell stays on CD forever.

Bugfix for druid shapeshift cooldown

---

code/modules/spells/roguetown/acolyte/dendor.dm

Shapeshift - Commented out level 6 transofmrations at staff request

---

code/modules/spells/roguetown/acolyte/dendor.dm

No longer needed + help with lag

Remove debug messages from shapeshifting

---

code/modules/spells/roguetown/acolyte/dendor.dm

Remove psicross check from shapeshifting

---

code/modules/spells/roguetown/acolyte/dendor.dm

Fixes the transformation back

---

_maps/map_files/dun_manor/dun_manor.dmm

Repairs buggy tile near keep excidium

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/wretch.dm

forgot to actually remove raider from wretch subclass selection

wretch subclass selection

---

code/modules/client/customizer/customizers/bodypart_feature/misc.dm

The athletic leotard is made the default option, to be naked you have to change this in the character creation menu.
Let us never have a robbery = prefbreaking convo again.

Makes nudity opt in

---

code/modules/jobs/job_types/_job.dm
code/modules/mob/dead/dead.dm

Stops Wretches from showing up in the pre-round ready list. Also prevents their tip in Actors list.
Go and check the excidium like a normal bounty hunter

Patches some wretch meta leaks

---

code/_onclick/other_mobs.dm

Triples the length of time to 'accept' somebody giving you an item from 100 ticks to 300
This is an RP server. People write long emotes and miss 'Give' responses a lot.

Longer 'Give To' response time

---

code/game/objects/items/rogueitems/instruments.dm

***READY FOR MERGE*** Lets those with 4 or more music skill upload custom songs

---

code/modules/spells/roguetown/acolyte/dendor.dm

Now 60 seconds, uses proper recharging tracking to fix.
Fixes the wandering

Bugfix for beastform CD

---

code/datums/mind.dm
code/modules/roguetown/roguemachine/bounty.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Sorts the lists for the Known People, bounty selector and message spells so that names in it are alphabetical
Simpu an Creen

List sorter sorting lists

---

_maps/map_files/dun_manor/dun_manor.dmm

Fixes the weird fucking bathhouse bug spawning water in the corners.
Another bug squashed.

Map Fix | Bathhouse

---

code/modules/jobs/job_types/roguetown/nobility/steward.dm

idk the steward doesn't have a rat anymore in his stewardy and someone offered me like 100 Indian rupees if I did this so i want my like 3 cents.
rat is gone from stewardry so round-start text doesn't make sense anymore. plus yeah, 3 cents is 3 cents.

De-Rattifies the Steward

---

code/game/objects/items/rogueweapons/melee/knives.dm
code/modules/mob/living/carbon/carbon.dm

silly little oversight on my part there

makes snip intent override surgery

---

code/game/objects/items/rogueitems/bells.dm
code/game/objects/items/toys.dm
code/game/objects/structures/roguetown/handcart.dm
code/modules/reagents/reagent_containers/powderspice.dm
code/modules/roguetown/roguejobs/engineer/items.dm

BIG HONKIN' COGS
Lying about how big your cogs are is the number one cause of rhabdomyolysis among artificers.
Compiles.

Fixes some small item grid sizes

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/noble.dm

helmets
Knight Errant gets to pick a helmet!
Someone did the wise thing of letting RG players pick what sort of helmet they'd like their character to spawn with. We've so many helmets and they are lovely. I Knight Errant also deserves this treatment, I see no reason why not let them pick their flavor of helmet, since we've so many pretty helmets!
Oh and I gave them a nicer belt, because come on, the KE is already weaker, let em have some drip, no self respecting noble should wear a belt below their stature.

Errant Knight Hemlets.dm

---

_maps/map_files/dun_manor/dun_manor.dmm

Another cheeky turf/closed underneath a door.

fixes bugged tile on dunmanor south gate 2ndfloor

---

code/__DEFINES/mobs/simplemob_attack_speed.dm
code/modules/mob/living/simple_animal/rogue/game/saiga.dm

they didn't have a defined attack speed so they just had no delay between attacks lol
Lmao

i died to a saiga so now i am nerfing them

---

code/modules/jobs/job_types/roguetown/adventurer/wretch.dm

Added the possibility of being a Graggar/Baotha Heretic Wretch.
That's it.
Woe, more heretic types upon thee.

Heretic Update | Graggar + Baotha options

---

code/datums/emotes.dm
code/datums/stress/positive_events.dm
code/modules/mob/living/emote.dm

Nobles get a slight mood buff when bowed to

I LOVE LIFEGAME

---

code/modules/mob/living/living.dm

Can be easy to forget in the heat of the moment

Sends you a gentle reminder not to break rule #4 when you are revived

---

code/modules/clothing/rogueclothes/mask.dm

i accidentally used 'seconds' instead of 'minutes'
oops

fixes penance mask timer 

---

code/modules/mob/living/grabbing.dm

It's a bit of a complicated one. 
This makes it so you can constantly re-apply the pin stun at the cost of high stamina.
**The progress bar matches the stun duration (initially).**
Overtime, each new pin reduces the stun time, allowing the person to resist more often.
You can still use your other hand (for stabbing or chaining) as the pinner.
The stun depends on the skill and stat differences between the two. Mostly STR:
15 STR pining 10 STR:
https://github.com/user-attachments/assets/23f501c1-353c-4f83-9d86-97ac676fb213
Again, the progress bar is as long as the stun.
10 STR trying to pin a 15 STR person:
https://github.com/user-attachments/assets/ca157de1-25d0-4f55-a198-3760f0664098
10 STR trying to pin a 9 STR person:
https://github.com/user-attachments/assets/e965659f-2cb6-4c75-8c35-220 …

Pinning changes (clarity, higher stamina loss, lower stun times the longer the pin)

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/vaquero.dm

Vaqueros, the bard of the mercenaries, now has an instrument selection with which to play their lonely cowboy tunes with. 
CEASELESS MERCENARY POWERCREEP PR. (I love music classes)

Instrument choice for Vaqueros

---

code/game/objects/items/rogueweapons/shields.dm

gives buckler a grid size

---

code/game/objects/items/rogueitems/instruments.dm

Excellent news! I've learned to test things with more than 2 clients! This should fix a little hiccup which caused some issues when syncing more than 2 instruments. *hopefully*. Tested on local and working fine. 
Yeag we love function

Multiinstrument sync fix(?)

---

code/modules/surgery/_surgery_step.dm
code/modules/surgery/surgeries/healing.dm

Sets surgery heal to auto attempt to repeat on failure. Removes incision flag dependency, avoiding collision with miraclespam. You still have to incise first to clamp.
MY INCISION! MY INCISION! PRIEST, STOP CASTING MIRACLE! MY INCISION IS GONE! MY INCISION!
By the way, we've never needed to retract in order to do the tending step.

Quality of life change to surgery heal

---

_maps/map_files/dun_manor/dun_manor.dmm

adds back the BM vault area to the bath house, seems to have been accidentally removed by another mapping-related PR
bug fix 🐛

Fixes bathmaster vault

---

code/modules/farming/crafting_recipes.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm
code/modules/roguetown/roguejobs/cook/ingredients/misc.dm
modular/Neu_Food/code/raw/NeuFood_processed.dm

tweaks some farm creation time and 
This adds
- 5x drying and zig creation,
- Slightly decreases milk time based on farm skill,
- Allows for faster cheese and butter creation based on if your farm or cooking skill is higher,
- Gives a good meal buff to aged cheese
removes some of the tediousness stuff and also rewards people for aging cheese

Farm Tweaks

---

_maps/map_files/dun_manor/dun_manor.dmm

I left the puritan ID access instead of the Inquisition one in the private bedrooms.
OOPS.
BUGS BAD

Hot Fix | Inquisition Doors

---

_maps/map_files/dun_manor/dun_manor.dmm
code/game/gamemodes/objective_items.dm
code/game/gamemodes/roguetown/roguetown.dm
code/game/objects/effects/landmarks.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm
code/modules/jobs/jobs.dm
modular_hearthstone/code/game/objects/items/signal_horn.dm

Royal Guards are Knights again. The 'Royal Guard' flavoring kind of implies they aren't really ever allowed to leave the keep at all - to the point where it's become a regular sight to see duke/duchess players demanding the RG inform them every time they need to leave the keep for any reason.
This sucks. Nobody likes being glued to the keep. I'd like to re-flavor the role from 'Royal Guard' back to 'Knight' to encourage the idea that they don't necessarily have to sit around the keep for the entire round.
With the guard captain recently being renamed to 'Knight Captain' - I think renaming the Royal Guard back to 'Knight' feels appropriate enough.
There's some balance changes in here as well. I feel like currently heavy knight is kind of just objectively the best RG class, so I went …

Reworks 'Royal Guard'

---

code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm

Hello! I've been sat upon this Tiefling Lore for nearly four months now, I've been given feedback and been given mostly praise for its change over the outdated and not so fitting lore we currently have for Tieflings. The current Tiefling lore does not entirely fit our dedicated server lore, while this lore change is nothing amazing or different. It would at least give it a fresh coat of paint making it more friendly with our existing lore without causing any unnecessary changes to current Tiefling players. 
The offspring of demons with mortal races, a consequence of demonic incursions into the mortal realm and dark pacts. Their origins dating back to the demonic invasion of Archdevil Vheslyn who pillaged and ravaged the mortal lands and its people before being stopped by Psydon. These …

Tiefling Description/Lore Change

---

code/modules/clothing/rogueclothes/mask.dm
code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm

i didn't give concubines a nightmaiden key

---

_maps/map_files/dun_manor/dun_manor.dmm

Added a water barrel, wash basin, and three chairs upstairs on the Inquisition chambers entrance.
I forgor

Map Update | More things I forgot.

---

code/game/area/roguetownareas.dm

fixes a silly bug related to the trait knights get that's meant to give them a temporary buff inside the keep
bugfix. responding to a bug report on discord.

Knightsman trait bugfix

---

code/modules/clothing/rogueclothes/neck.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
modular_azurepeak/code/datums/loadout.dm

it's a cute piece of jewelry
downgraded from steel to iron since it's not protective just aesthetic

Removes armor from cursed collar and makes it a loadout item

---

code/game/gamemodes/roguetown/chaosmode.dm

Roguelite spawns bandits OR werewolves. Roguemedium spawns bandits AND werewolves.

Adds roguemedium and caps bandits at 4

---

modular_azurepeak/virtues/utility.dm

let's be honest this is the real reason people pick blacksmith's apprentice and steal the static spawn hammers

FaIled squire virtue + makes it so adventurers with resident start in tavern

---

modular_azurepeak/code/modules/spells/pantheon/inhumen/zizo.dm

With this list updated, Rituos Zizoids will be able to actually choose from one of the ACTUAL REAL UPDATED list of spells. No longer do you need to literally shed your skin whole to cast uhh.
IDK. Fortify. Or Guidance.
Seems fitting to update the list. That's it.

Update Rituos' spell list to put the ""new"" spells in!

---

modular_azurepeak/virtues/utility.dm

Resident mercenaries now spawn in the tavern alongside adventurers

---

code/modules/client/customizer/customizers/organ/horns.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halforc.dm

Half-orcs can customize tusks

---

code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm

WE NEED TATTOOS IN THIS BITCH RAHHH
This hasn't been done in months let us not delay it more

Update | Halfkin Tiger Markings

---

_maps/map_files/dun_manor/azure_coast.dmm
_maps/map_files/dun_manor/dun_manor.dmm

- Adds back the beds in the beach cove.
- Unlocked the doors to the bath in the crazed duke manor.
I forgor

Mapping Oversights Fix

---

code/modules/admin/admin_verbs.dm

Adds Assume Direct Control to right click admin verb list
Adds Assume Direct Control to right click admin verb list

Adds Assume Direct Control to right click admin verb list

---

code/modules/jobs/job_types/roguetown/church/monk.dm

gets rid of the description bit saying only a few divines are supported
as they're all supported!! silly us, never scrolling over to that line like five updates down the road...
witness, player.

smol acolyte "fix"

---

modular_azurepeak/virtues/utility.dm

Now they can only spawn on the ground floor buckled to a chair

Fix for resident adv/merc spawn

---

code/datums/status_effects/rogue/debuff.dm

Title. I forgor to set a timer, just got bug reported yesterday.
Uhh it perma effects your skills otherwise.

Fixes Graggar Debuff Lasting Forever

---

code/modules/admin/admin_verbs.dm

New verbs coming out at the same time as a verb category renaming is HNNNGGGGG
Only one admin tab plz

[Hotfix] Updates Verb Cat for Remove Bounty verb

---

code/game/objects/items/rogueitems/natural/feather.dm

Increases the quill's change desc limit to 250 (from 100)
4 and some lines instead of 2 lines is likely a good basis on description limit without letting people post a literal paragraph or two about how the helmet saved their lives or w/e

(More than) doubles desc limit

---

_maps/map_files/dun_manor/dun_manor.dmm

I noticed a LOT of space used for a kitchen in the new quarters, when the marshal still has that dingy old room. So I blew it up, made the old marshal quarters a second guest room, and took over that kitchen.
Marshals are the leaders of both the Sergeants and the Knight Captains yet they get a dingy ol' closet room. This changes that.

Map Update | Marshal Quarters

---

code/modules/roguetown/roguecrafting/items.dm

Dice are now craftable, using a knife and bone. Now we can slowly wittle away those floods of bones.
Requested. Also going to confuse tf out of people who don't realize die is the singular for dice and it will be funny hee hee

Nice Bone Dice [Small Recipe Addition]

---

modular_hearthstone/code/modules/spells/roguetown/buffs.dm

Forgot to call parent on haste
Haste shouldn't stack permanently

Stop haste from stacking

---

modular_azurepeak/virtues/combat.dm

so they can do their t2 miracles

Devotee virtue now gives psydon and inhumen worshippers psicrosses

---

code/game/objects/items/dice.dm
modular_azurepeak/code/datums/loadout.dm

Adds a deck of cards and a bag of six dice to the loadout, also a bag of six dice (enough to play everyone's favorite dice game featured in KCD2!!)
Fun fact: 90% of gamblers quit right before they hit it big!

Gambling Update (real edition)

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
modular_hearthstone/code/modules/spells/roguetown/flagellant.dm
roguetown.dme

The Flagellant is a pacifist that does not attack, nor do they flinch in the face of devastation. Instead, they act as a conduit for pain, pulling suffering from others onto themselves. Their resilience is near-supernatural, capable of enduring wounds that would fell lesser beings.
Custom Spells
Damage Transfer – A sacred bond is formed between the Flagellant and their chosen target. So long as the link remains, every wound, every cut, every strike meant for their ward is redirected onto the Flagellant instead. This is the ultimate shield—one that feels the blade but does not break.
Affliction Transfer – The Flagellant may take the injuries of another as their own. Cracked ribs, bleeding wounds, even the absence of a vital organ—whatever ails their target is transposed onto them. The …

***READY FOR MERGE*** The Flagellant: A Living Martyr

---

modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Raises mindlink charge from 2 to 5 minutes

---

code/datums/mind.dm
code/datums/skills/_skill.dm
code/datums/skills/combat.dm
code/datums/skills/craft.dm
code/datums/skills/labor.dm
code/datums/skills/magic.dm
code/datums/skills/misc.dm
code/game/objects/items.dm

- Adds a "?" after every skill in the skills button. 
- Not all-inclusive and only includes the most important points. 
- Deletes some unused code I found
Makes the game more transparent.

In game skill description

---

code/modules/jobs/job_types/roguetown/adventurer/wretch.dm

Made an oopsie that removed outlaw for berserker. A big my bad for that.
OUTLAWS SHOULD EXIST!!!

Readds Outlaws Whoops !

---

modular_azurepeak/virtues/utility.dm

Puts in logic to handle resident virtue stuff for dun world. Fun!
the snowflake grows more complex

Adds case for resident virtue for dun world

---

config/maps.txt

Since we're worlding it up, might as well let the repo know it.
keep the boat afloat

Dun World now set as default map in repo config/maps.txt

---

code/game/objects/items/rogueitems/coins.dm

user.put_in_active_hand(new type(user.loc, 1)) was suggested as being too risky, so, going back to the clunky oldfashioned way of spawning the roguecoin.
Chasing the mammon duplication bug.

Changes coin right_click to oldfashioned way of spawning

---

code/modules/mob/living/carbon/human/examine.dm

Fix wound examine doubling up
Fix wound examine doubling up

Fix wound examine doubling up

---

code/modules/food_and_drinks/food/snacks.dm
code/modules/roguetown/roguestock/_roguestock.dm
modular/Neu_Food/code/raw/NeuFood_processed.dm

- Fixes `TRAIT_NASTY_EATER` not working for noble pickiness (only `TRAIT_ORGAN_EATER` worked).
- Fixes getting a 'no water to soak in' message when you make cheese.
- Fixes being able to stockpile partly-sliced sticks of butter (and other non-batch-sliced foods).
Fixes some bugs.

Fix various food-related issues

---

_maps/map_files/dun_world/dun_world.dmm

I forgot the MEISTER, and to add tunics and tights to the closet. 
I forgor

Map Update | Bathhouse Fixes

---

code/datums/browser.dm
code/modules/client/preferences.dm
code/modules/mob/living/simple_animal/rogue/game/saiga.dm
code/modules/roguetown/roguecrafting/alchemy/reagents.dm
modular/code/game/objects/pillory.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

- Fixes the saigabuck typepath
- Fixes stamina potions not increasing stamina (currently they're scaled identically to the mana potions, which also restore stamina)
- Makes blinking out of the pillory/guillotine unbuckle you. **If you have issues with mages blinking out of captivity, gag them so they can't cast spells.**
- Fixes constructs being able to become nobility via the Virtuous statpack.
- Fixes the UI title not having the intended custom font.

Fix a handful of issues

---

_maps/map_files/dun_world/dun_world.dmm

Fixes stuff being improperly stacked.

Fix improperly doubled-up objects and turfs

---

code/__DEFINES/traits.dm
code/modules/mob/mob_movement.dm
modular_azurepeak/virtues/combat.dm

Had this idea a bit ago, and upon realising it's like 3 minutes of work decided to give it a shot.
It removes the fixed-eye slowdown.
No, you still can't sprint with it.
No virtue:
Virtue:
Both instances were with a 14 SPD Royal Champion.
My vibe ball told me it was cool enough to try

Adds a new Virtue -- Sure Footed

---

code/modules/client/preferences.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/_anvil_recipe.dm
modular_hearthstone/code/game/objects/effects/track.dm

see title. completely untested btw

Replace unnecessary new-then-qdel pattern with initial()

---

_maps/map_files/dun_world/dun_world.dmm

New tavern kitchen.
More counterspace, better sightlines, the door that was always kept open is just gone now so there's more floor space. There's even space to drag the barrels from downstairs up.

Remaps the tavern kitchen

---

code/_globalvars/special_traits.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm

-You now get 3 loadout slots rather than 1
It's Drip. No more grinding sewing for a extra piece of fluff-clothing.

3 Loadout slots

---

code/_onclick/other_mobs.dm

fixes standard jumps immobilizing you

---

code/modules/mob/living/carbon/human/voicepacks/other/moth.dm

copies the fix from the female moth voicepack

Fix male moth voicepack

---

code/game/objects/items/rogueweapons/melee/knives.dm
code/game/objects/items/rogueweapons/ranged/ammo.dm
code/modules/clothing/rogueclothes/storage.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm

They were really weak compared to projectiles before due to doing stab armor damage. They do piercing now like arrows which puts them on an equal playingfield.
Also gave them better armor pens to stand up to arrows, some are better than arrows but of course they still do less damage and only % chance to embed.
Muh balancejak but they were legit worthless before (besides the silver variant) but now actually can do OK. Still.. outclassed by arrows but this is so they're at least decent. Can always play with values later more.

Javelin + Tossblades Now Peirce 

---

code/modules/jobs/job_types/roguetown/adventurer/wretch.dm

Listened to some people, namely remembering that this class needs a tune-up to be 'better' than traditional barb and other classes given their wretch status.
Changes include: 
- A new sword option, for those wanting to use blades instead. This will give you a falx to start off with. Journeyman swords starting off, Expert if sword option is chosen.
- Medicine skill of 1, given they wear light armor + it takes them a million years to suture a wound. A barbarian, I imagine, knows how to do the most minimal, but if I see them trying to do surgery, welp, bye-bye!
If you want to be able to fix leathers or armor, just pick a virtue or farm it yourself.
EDIT: Gives them swords as an option as well as a single level in medicine! Stat changes removed for the timebeing.

GRAGGING ON MY GAR (Berserker Buffs)

---

.github/PULL_REQUEST_TEMPLATE.md
.github/labeler.yml

* Tweaks PR template.
* Adds couple of labels for gitbot to automatically apply.
good for me

labels & PR template tweaks

---

code/modules/jobs/job_types/roguetown/yeomen/archivist.dm

The Archivist can tutor new things!
Allows an Archivist to tutor in alchemy, brewing alchemy, fishing, lumberjacking, mining, smelting, and various languages. If the language tutoring seems balanced, I may make it its own tutoring thing later.
It keeps things in line with the archivist being the teacher for crafts and some athletic stuff. It also fits a discord poll done earlier. I did NOT include athletics because that can impact stamina and in turn, combat.

Archivist Tutoring Expansion

---

code/modules/client/preferences.dm

-Fixes donators, if they had their own item in the first loadout slot, getting access to all others.
(only showing the one properly assigned)
yea

fixes 3 item donator thing

---

code/game/objects/items/rogueweapons/melee/blunt.dm
code/game/objects/items/rogueweapons/melee/polearms.dm
code/game/objects/items/rogueweapons/melee/swords.dm
code/game/objects/items/rogueweapons/shields.dm

- Restores parry sounds for swords, medium sized swords and greatswords(and their derivatives) now have their sounds turned back on.
- Also restores some shield sounds.
https://github.com/user-attachments/assets/8ba8f389-1e70-419d-bcdb-bc436a8ef94f
Clang!

The Clangening - Restoring sword parry sounds

---

code/modules/jobs/job_types/roguetown/garrison/manorguard.dm

Makes it so men-at-arms still have their classes but stops locking you into weapon-specialization choices. You'll still get to choose your starting weapon options and class, but you'll have the same skill regardless of weapon choice you make.
- Men at Arms regains their weapon skills, keeps choice in starter-weapons
- Skirmisher lost its 1 shield skill, got back its 1 sword. (A buckler + knife is really strong, would prefer encouraging non-projectile deflecting defense options)
- Cavalrymen get an extra whip skill point and mildly better tracking; these guys are good scouts + makes them have a unique weapon skill (compared to other maas) to stand out given how good whips and flails can be. 
Also - two small changes to weapons, as requested:
- Footman no longer gets a steel mace, gets a …

MAA Re-adjustment

---

modular_azurepeak/code/datums/loadout.dm

We had nun habit but no nun veil. And additional anklets for bare feet characters.
Tested on local server, all works fine.
More fun loadout items - less dripcrafting in-game - more RP.

Adding 3 more clothing items to the loadout menu

---

code/modules/clothing/rogueclothes/armor.dm

Don't worry about it. Ha Ha.
Tested it ingame. Pressed right click on the gambeson. Didn't explode.
Bugs!!! Bugs!!!

Little tiny otavan gambeson fix

---

code/modules/roguetown/roguecrafting/structure.dm

Players couldn't be trusted with this after all. Thought that would be the case; stop being bad-taste and edgy.
nothing to show it just doesn't craft anymore.
People asked "Hey, make it craftable!" a bunch - did so, even though I thought this might happen - boom. Happened. No more...

Removes Craftable Noose

---

code/modules/clothing/rogueclothes/armor.dm
code/modules/clothing/rogueclothes/pants.dm
code/modules/roguetown/roguecrafting/leather.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm

"Bikini" Armor is renamed to "Corslet", a 1500's English term for lightened plate armor in military issue with Old French linguistic roots.
"Half-Plate Corslet" has armor values equal to "Steel Cuirass", only covering chest and groin rather than chest and vitals. Medium Armor.
"Full-Plate Corslet" has armor values equal to "Full Plate", only not covering vitals. Heavy Armor.
"Chain Skirt" now cover legs but not groin. Light Armor.
"Plated Mini-Skirt" is now "Plate Tassets", cover legs but not groin. Changed from Light to Medium Armor.
"Brayette" given a description text.
All crafting recipes have names updated.
No changes to object names, iconstates, etc.
No changes to costs.
Plans exist to form corslet sprites for male bodytype and touch up the spritework more generally. Its hack right …

Bikini Armor Retheme; Corslets, Tassets and Skirts

---

code/game/objects/items/rogueitems/inquisitionrelics.dm

The box erroneously applies the negative effects to the inquisition as well, which was a testing feature.

forgot to remove testing code from the inquisition box

---

code/modules/roguetown/roguecrafting/alchemy/ingredients.dm

I had forgotten to change the icon name when making the new ingredients. I made the icon for it but forgor to use it.
This is what it is supposed to be. I changed it to this.
Fixes a bug.

Massive Salt PR - Bugfixes the Purified Salt's icon

---

code/datums/gods/faiths/inhumen_pantheon.dm
code/datums/gods/patrons/inhumen_pantheon.dm

Fixes the lore blurbs and followers for Ascendants.
I ran it once.
Make consistency

Whoopsie, lore pr.

---

code/game/objects/structures/roguetown/rogueflora.dm

- Returns SOVL to Roguetown
- Uncomments SOVLful code
- Examining a Wise Tree will now play Ambience
https://github.com/user-attachments/assets/ccc084ec-216e-47f4-8b16-e910233b44f9
No lollygaggin

returns sovl to roguetown

---

modular_hearthstone/code/modules/spells/roguetown/flagellant.dm

-1 range on flagellant's teleport thing did NOT give it unlimited range. This bugfix, in practice, should
bug: fix

[BUGFIX] fixes flagellant's teleport spell

---

code/modules/events/rogue/skellysiege.dm

Mysterious skeletons happening around the Peak? It's more likely than you think!
lol
Admin request

Should prevent skellysiege.dm from randomly firing

---

_maps/map_files/dun_world/dun_world.dmm

I forgot to add the Hermes and realized when it came up in gameplay.
Loaded in-game, fully functional where it got placed.
Oversight my beloathed

Yet Another Fix | Merchant shop

---

modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/minotaur.dm

Had a small oversight. Fixed it. 
Fixes my mistake.

Greataxe fix merge ASAP

---

_maps/map_files/dun_world/dun_world.dmm

Fixed this from happening:
Simple fix so I didn't check in-game.
SEE BUG SQUASH BUG RAHHH

Fix | Random torch in the merchant shop

---

code/modules/client/customizer/customizers/organ/ears.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
code/modules/surgery/organs/ears.dm

Makes it so you can choose the types of ears your tiefling have. 
More choices of customization.

Update | Tiefling ears

---

modular_azurepeak/code/modules/spells/pantheon/inhumen/zizo.dm

Mage Overhaul 1 had one uncaught bug. I forgot to give Arcyne T3 as part of Rituos which kinda screwed up Zeretic in that they don't get to use their 6 spell points.
Not tested. I ran it in my mind. It should works.
I think Zeretic is an Issue but gimping them unintentionally is BAD and set BAD precedents. So I fix this bug.

Zizo Zizo. Dame of Progress. Give me T3 magic

---

code/modules/clothing/rogueclothes/mask.dm
code/modules/roguetown/roguecrafting/sewing.dm
modular_azurepeak/code/datums/loadout.dm
modular_azurepeak/statpacks/mental.dm

Adds the ability to craft cloth blindfolds. Currently only the concubines get them. You can also loadout spawn them.
They also no longer hide your face.
The only runtimes that started up when I spawned in was completely unrelated to my code. Works fine.
Beyond freaky stuff this is peak fashion for blind people/seer types.

Blindfolds can be crafted or put in loadouts, and they no longer hide your face.

---

modular/Neu_Food/code/NeuFood.dm

The generic of https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/1788 bypassed the idea in the code, that putting something on a plate increases its faretype value by 1. This readds it.
Helps nobles eat things off of plates.

Putting food on a platter increases its fare.

---

_maps/map_files/dun_world/dun_world.dmm

https://i.imgur.com/bVUGfZb.png
https://i.imgur.com/B4vZCMP.png
https://i.imgur.com/Q3PXw5u.png
Bug. Hopefully.

fixes drow town door wall

---

_maps/map_files/dun_world/dun_world.dmm

Fix, for the new mage tower:
- The stairs having a wall underneath them.
- The kitchen's roof, being climbable.
- The coastline, allowing you to climb back up.
Bugs are bad.

Mapping hotfix - Mage tower

---

_maps/map_files/dun_world/dun_world.dmm

Moved the keep's gallows a few tiles to the north.
Switched the merchant's top floor windows for iron bars.
Added a lantern post in front of the mercenaries guild.
Added a vomitorium to the keep's alchemy laboratory.
Added HERMESes to:
- The keep's meeting room
- Mage tower
- Garrison's building
- Shanty town
- Mercenaries guild
- Wardens tower
- Hamlet's inn
- Forest's inn.
Added spare HOUNDSTONE/CROWNSTONE to the captain and marshall bedrooms.
Added a dye station on the road north of town.
Switched one of the candles at the witch's house for a standing fire.
Tested by roaming on the map in a local server. Too many small changes to post screens.
Quality of life is amazing! And letters, MAIL?! EVEN BETTER!

Small town changes, and the HERMES revolution

---

code/modules/farming/fermenting_barrel.dm

The snowflake roguebag onto fermenting barrel interaction never played nice with tetris inventory, which meant the storage datum had ghosts still clogging it after the bag was emptied. This updates the movement of the fermentables via the Storage datum removal, fixing that bug.
1. Got the bag full of wheat and an empty barrel
2. Clicking bag onto barrel puts all the stuff in there.
3. Since the storage datum plays nice now, we can use the bag for another batch.

Updates bag and fermenting barrel interaction to fix broken bag bug

---

modular_azurepeak/code/modules/spells/pantheon/inhumen/baotha.dm

Title
One-line change
OCD-Fix, it was missing any kind of cost.

[FIX]: Adds missing devotion cost to Baotha's Enrapturing Powder

---

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/hunter.dm

Title, very good, it's supposed to spawn in hands but always drops on the floor and it's easy to forget it
Just switching slots.
Quality of life.

[QOL]: Stops Hunter's recurve bow from spawning on the floor

---

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/hunter.dm

This gives the towner hunter class a hunting sword and increases their sword skill by 1 to better accommodate it.
It adds a little more flavor to the class, and gives them a better chance at defending themselves from wildlife.

Gives the Hunter class a hunting sword (Wow!)

---

code/modules/mob/living/grabbing.dm
code/modules/mob/living/living.dm

Ports https://github.com/Rotwood-Vale/Ratwood-Keep/pull/2751
Please note 10 seconds passed between one and the other so in reality the bleed went from 0.8 to 0.4 after the grab
Gubfix

[RATWOOD-PORT]: Fixed grabs not reducing blood loss on grabbed body parts 

---

modular_azurepeak/code/datums/loadout.dm
modular_azurepeak/code/game/objects/items/donator_fluff_items.dm

Essentially just moves the outfits pathing from Leather Vest to robes. Leather Vests have armor and TECHNICALLY speaking the donator items shouldn't have armor. THAT however was just one of the issues, also it spawned brown because base vests have their color set to brown. I went ahead and added a Color = null to fix that.
Booted test server, added it to my loadout, pulled it out, basked in its glory.
Fixes stuff and things, solves world hunger, brings about world peace.

Fixes my Donator Item - Grenzelhoftian Mages Vest

---

code/game/objects/items/rogueweapons/melee/swords.dm

PR does three main things:
- **Makes the executioner sword combat-viable**; to be specific the _executioner_ sword, not the dungeoneer one. These cost 2 steel and 1 iron vs longswords 2 steel. So, now it's a SLIGHTLY better longsword in that it has axe chop while longsword has swordchop, but its thrust has a swing delay. In exchange it has some extra penetration though. 
- **Sabre received some buffs due to its cost & to compete with rapier and falx**; this is because I learned swords normally have 1.1 damage on cut, so it explained why sabres felt ass still compared to other swords. Now standardizes it to make it slightly better by giving it a PROPER 15% bonus, gave it same defense as rapier (it's a dueling sword), plus gave it 10 pen (base is 0 on cut) so it's a bit more usable as well. …

Executioner Sword Improvement + Sabre Adjustment (Also OCD Fix)

---

code/datums/particle_weathers/datum_types/rain.dm

Reverts GeneralPantsuIsBadAtCoding/Azure-Peak#2234

Revert "[IMMERSION]: Rain now takes a few seconds to soak you"

---

code/modules/spells/spell_types/wizard/buffs_debuffs/giants_strength.dm
code/modules/spells/spell_types/wizard/buffs_debuffs/hawks_eyes.dm
code/modules/spells/spell_types/wizard/buffs_debuffs/stoneskin.dm
code/modules/spells/spell_types/wizard/utility/mending.dm

Spell-checks new status effects from the Magic Overhaul 2 + makes mending more immersive
Very simple change but tested in game anyway.
Muh immersion

Spell-check of a few new status effects + makes the mending spell play an immersive sound

---

_maps/map_files/dun_manor/azure_coast.dmm
_maps/map_files/dun_manor/azure_forest.dmm
_maps/map_files/dun_manor/dun_manor.dmm
_maps/map_files/dun_manor/smalldecap.dmm
_maps/map_files/dun_world/dun_world.dmm
_maps/map_files/generic/CentCom.dmm
_maps/map_files/rockhill/rockhill.dmm
_maps/map_files/roguetest/roguetest.dmm
_maps/map_files/templates/sewers/sewers_bottomleft_2.dmm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lcarp.dm

That should be all of them, hopefully.

Fixes hammers in dmm files

---

code/modules/mapping/space_management/traits.dm

A couple more that were non-functional. Fortunately, the procs weren't used anywhere in place of the defines that do it correctly.

Fixes multi-z checks

---

code/game/objects/items/rogueweapons/melee/swords.dm
code/modules/surgery/bodyparts/bodypart_wounds.dm

and deals even less damage
It's not meant to be usable in that way, though the bandaids are growing thick.

Peel can no longer crit

---

code/game/objects/items/rogueitems/natural/wood.dm
code/modules/roguetown/roguecrafting/items.dm

Made it so you can craft wooden mallets.
And also fixed the issue regarding full logs fitting in bags.
Fixes bugs.

Wooden Mallet Crafting + Log Fix

---

code/modules/mob/living/carbon/human/life.dm

Big AI human number, big runtime.

Fixes AI processing their charflaws

---

code/datums/skills/misc.dm

I LOVE FLAVOR SO FUCKING MUCH!!!!
As it say in the tin: Tracking never gets any messages when you sleep, so I uh. You know. Added some.
Admittedly I did not test it but I simply added a dreams list. If it SOMEHOW breaks shit, I'll be astonished.
Joy Flavor Joy Joy .

Add Tracking Skill dream messages

---

code/game/objects/items/rogueitems/ropechainbola.dm
code/modules/food_and_drinks/food/snacks.dm
code/modules/mob/living/carbon/human/human_topic.dm
code/modules/reagents/reagent_containers/glass.dm

A couple bug fixes and one port.
- **Chaining, giving drinks, and feeding another person requires that they also stay still during the process.** There's probably other specific interactions I could have missed but, увы.
- **Unbandaging someone requires you to be adjacent to them.** Somehow this is not already the case and you can take bandages off people with your mind, evidently. From https://github.com/Rotwood-Vale/Ratwood-Keep/pull/2709.
Uhhhhh
Can't record a video right now but, basically just move away from someone who's trying to chain you/forcefeed you and it cancels. This is the same way Assessing works.
Wireless chaining bad.

Misc. Bug Fixes and Sanity Checks

---

code/game/objects/items/rogueweapons/melee/blunt.dm
code/game/objects/items/rogueweapons/melee/polearms.dm

as in big
before
after
This also changes its wielded intents to have 2 range.
People liked it when it was bugged

makes the naledi warstaff great again

---

code/modules/antagonists/roguetown/villain/lich.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/roguemage.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
code/modules/jobs/job_types/roguetown/courtier/magician.dm
code/modules/roguetown/roguecrafting/items.dm
code/modules/spells/spell.dm
modular_azurepeak/code/game/objects/items/magic_staffs.dm

- blows up the prepared staff crafting because its pointless. you can just slap gems on normal staffs now.
- allows nonarcyne ppl to slap gems onto wooden staffs if they really want to
- gives the wretch necromancer a ruby staff because they're like one step down from bandit right? right.
- gives the advmage a single amethyst, which they can spend to immediately upgrade their staff or slap on their book.
it works i checked 👍 
removes some tedious speedbumps that dont need to exist

cleans up mage staffs :3c

---

_maps/map_files/dun_world/dun_world.dmm

Mapping bugs fixes and patches:
- Added a missing block on the chimney of one of south street houses.
- Switched the hunter's house top floor windows with new ones.
- Moved the mercenaries guild front SCOM inside the building and switched it for an HERMES.
N/A.
Bugs are bad.

Small town patches pack

---

code/modules/roguetown/roguejobs/fisher/fish.dm

Fix clam sprite
Fix clam sprite

Fix clam sprite

---

code/game/objects/items/rogueitems/needle.dm
code/game/objects/obj_defense.dm
code/modules/spells/spell_types/wizard/utility/mending.dm

Fix mending destroying armor, fix insta needle repair
Tested locally w/ mending spell
Fix mending destroying armor, fix insta needle repair

Fix mending destroying armor, fix insta needle repair

---

code/game/objects/structures/well.dm

Well transfer 200 units
Well transfer 200 units
Well transfer 200 units
Cook power creep (fill pot in one click!!!)

Well transfer 200 units

---

code/modules/reagents/reagent_containers/glass.dm
code/modules/roguetown/roguejobs/fisher/fish.dm

Fix crab not being butcherable
Fix crab not being butcherable
Fix crab not being butcherable

Fix crab not being butcherable

---

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/carpenter.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm

Carpenter get a handsaw
Carpenter get a handsaw
Carpenter get a handsaw

Carpenter get a handsaw

---

code/game/objects/items/rogueweapons/melee/blunt.dm

I don't think there's a way to make the hugely damaging intent be usable one-handed. Strike is still going to be dealing more damage to unarmored opponents and to integrity, if you're aiming for it, it's just going to be slight.

Removes smash from warhammer

---

code/__DEFINES/combat.dm
code/_onclick/item_attack.dm
code/game/objects/items/rogueweapons/rogueweapon.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/spells/spell_types/wizard/conjure/conjure_weapon.dm

- It is not swappable (Just like Grand)
- It takes 1.2x damage from everything.
No more shaft farming.

Adds a conjured shaft to conjured weapons

---

SpacemanDMM.toml

To enable visible floors in mapdiffbot!

Disables icon smoothing 2016 for spacemandmm

---

code/modules/mob/living/carbon/rogfatstam.dm

Fixes reagents runtime

---

_maps/map_files/dun_world/dun_world.dmm
code/modules/mob/living/carbon/human/npc/dwarfskeleton.dm
code/modules/mob/living/carbon/human/npc/zizoconstruct.dm
strings/rt/dskeletonaggrolines.txt
strings/rt/zconstructaggrolines.txt

Mapping, code, and string fixes/changes.
Fixes some issues with the Gundu'Zirak dungeon. A near complete list as follows:
1. Fixes a missing turf under a door near one of the primary entrances into the dungeon.
2. Adds some reeds to alleviate the aggro issue between the less than amiable neighboring dragon and a dorf.
3. Fixes the baroness restroom area so she'll be more difficult to pen down in the space. The intent was to allow her to be dogpiled, but it shouldn't have been quite so easy in that space in particular.
4. Fixes zizoconstruct and dwarfskeleton say spam. While not pretty, it's far better than them spamming their lines every time they get hit and switch targets.
5. Changes say strings for zizoconstruct and dwarfskeleton to reflect the changes of their say behavior.
6. Adds …

Gundu'Zirak fixes and changes

---

code/game/objects/items.dm

Only show wielded force on weapon that can be wielded, oops.
See above

Proper 2hand check for force

---

code/modules/roguetown/roguestock/stockpile_rawmat.dm

Add silk to stockpile
Add silk to stockpile

Add silk to stockpile

---

code/modules/roguetown/roguejobs/fisher/fish.dm
modular/Neu_Food/code/cooked/NeuFood_pies.dm

Crab cake made by butterdough slice. Crab now give crab meat.
Crab cake made by butterdough slice. Crab now give crab meat.

Crab cake made by butterdough slice. Crab now give crab meat.

---

modular/Neu_Food/code/drinks/tea_coffee_drinks.dm

Let coffee beans get cracked for seed.
Let coffee beans get cracked for seed.

Let coffee beans get cracked for seed.

---

code/modules/spells/spell_types/wizard/projectiles_single/acid_splash.dm

Atomized this change off of #2309 
Makes acid splash more viable

Acid Splash Speed Change (non-lbolt PR edition)

---

code/modules/mob/living/carbon/carbon.dm

Weird fringe runtime where a mob tries to fall while not being on a turf (like when it is ashed in lava). Safe navigation operator ? should fix it.
compiles
One more runtime.

Safe access to loc for fall runtime

---

code/modules/farming/crafting_recipes.dm

Fixes westleach zig recipe

---

code/modules/admin/admin.dm
code/modules/admin/create_object.dm
code/modules/admin/topic.dm
html/create_object.html

- Ports https://github.com/Rotwood-Vale/Ratwood-Keep/pull/2754 (and fixed the WIP tab)
- Ports https://github.com/Rotwood-Vale/Ratwood-Keep/pull/2770
New admin panel:
Ability to search by type or by name:
Admins get cooler stuff. Unfortunately the "role ban panel" button is defunct atm and will probably(?) be stripped out.

Admin tools improvements (with fixed stats panel) [Ratwood]

---

code/modules/library/lib_items.dm
code/modules/library/random_books.dm

fixes a bookcase related runtime
destroyed various bookcases with & without books in them, no issue & drops books and log as intended
increased cap of books that can appear in a randomized bookshelf so books actually appear

fix bookcase runtime

---

code/modules/roguetown/roguemachine/vendor.dm

Fixes a peddler bug

---

code/modules/spells/roguetown/acolyte/astrata.dm

Add DNR for dead people being anastasised
Tested
DNR good.
Alternatively I've had *one* report of a person ghosting during the time of being a corpse which doesn't seem normally achievable (correct me if i'm wrong). Nothing to be done about that unless it's regularly possible

Astrata respects the dead's wishes

---

code/modules/admin/admin.dm

Fixes the player panel not working on non-living mobs

---

code/modules/roguetown/roguecrafting/structure.dm

Same PR as #2368 but just less bars instead of recycling a pot

Alchemy cauldron only requires one bar of iron to make

---

code/controllers/subsystem/rogue/devotion.dm
code/datums/gods/patrons/divine_pantheon.dm
code/datums/gods/patrons/inhumen_pantheon.dm
code/datums/gods/patrons/old_god.dm
modular_azurepeak/virtues/combat.dm

- Combat classes w/ Devotee will now get the Cleric tab
- The devotion code will no longer try to perpetually add new spells every time devotion is updated.
- Orision is now on its own tier `CLERIC_ORI`. Everyone still gets it, it's just easier to manage for Devotee.
Got on as combat class and did in fact now have Cleric tab.
Everything should be working as intended.

Devotion fixes

---

code/game/objects/items/rogueweapons/melee/knives.dm
code/modules/jobs/job_types/roguetown/church/priest.dm

Gives the unique Holy See knife to the priest as requested by Witty with a new description.
Requested, lore-accurate, something unique to the priest.

Priest Unique Knife (Requested Addition)

---

code/modules/clothing/rogueclothes/neck.dm

Inquisition gets psycrosses again - they appear over gloves
Tested
Bugfix good.

Fix psycross

---

code/modules/roguetown/roguecrafting/alchemy/reagents.dm

Accidentally deleted the parent call on my last commit, leading to them never metabolizing and lasting forever. Oops.
Oops

Fix alchemy buff lasting forever

---

code/modules/crafting/recipe_books/recipe_book.dm

Make recipe books actually flammable
Let people dispose of it ez

Make recipe books actually flammable

---

code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm

I fucked up some indentation on my previous PR and it's driving my OCD crazy.
I pressed the tab button an extra time.
Gotta make our code look nice.

SUPER MASSIVE MAGE ASSOCIATE BUFF (Not Clickbait) 

---

code/game/area/roguetownareas.dm

Adds highwaymen from #2359 to ambush lists so they appear ingame instead of just living in code. Does not place them anywhere on the map. 
I'm not sure how to manually trigger ambushes but the mobs are functional when spawned in. 
Actually uses my content that's been merged in game. Yay!

Adds highwaymen to the ambush list of several areas. 

---

code/game/objects/items/rogueitems/needle.dm

old PR i had laying around, makes this code less opaque by filling it with constants. want to balancejak about it? don't touch the actual code! just edit the constants! it's beautiful!!

Separate out constants in sewing repair code

---

_maps/map_files/dun_world/dun_world.dmm

Add 3 tea seeds to soilson
Add 3 tea seeds to soilson
it compiles
Add 3 tea seeds to soilson

Add 3 tea seeds to soilson

---

code/modules/mob/living/carbon/life.dm

It tries to skeletonize a limb when there should be no limbs left. I /think/ it was meant to skeletonize the head, there.
Kicked a guy in lava, kicked a guy in acid.

fixes a cremation runtime

---

strings/rt/timechangetips.txt

like why not right most of the stuff in there has been read 100,000,000 times
some of it's false some of it's just random shit some of it's taken from the wiki and some of it's just descriptions of countries players don't know a lot about and some of it's shit i randomly made up and some of it is stuff in books like the astrata vampire creation myth
ig i could throw it in books or whatever also this is just something i did on my phone waiting at cvs 
i mean it's just tips its a text file
lore you don't have to shift through discord for

significantly expands the tips list to include random pieces of lore i found on the wiki and discord

---

code/game/objects/items/rogueweapons/melee/swords.dm

vol said the sabre was ass and asked for the ap to go up and then ansari said it would be better if it had 8 clickcd bc despite being the opposite of rapier it was worse on its cut and the rapier thrust was just better
ok so now the sabre has a better cut
also the cutlass sucked so i made it slightly better on vol's request because now it has chop or something idk literally only one person has the saber
i hate coding on my phone my thumbs hurt 
it's just numbers
genuinely don't think it matters people never pick these anyway

single line balance pr that i did on my phone

---

code/modules/spells/spell_types/wizard/buffs_debuffs/guidance.dm

Correct Guidance Status Effect Text
Correct Guidance Status Effect Text
Correct Guidance Status Effect Text

Correct Guidance Status Effect Text

---

_maps/map_files/dun_manor/dun_manor.dmm
code/game/objects/items/rogueitems/bait.dm
code/game/objects/items/rogueitems/instruments.dm
code/game/objects/items/rogueitems/magic.dm
code/game/objects/items/rogueitems/needle.dm
code/game/objects/structures/bearpelt.dm
code/game/objects/structures/deer_trophy.dm
code/game/objects/structures/fence.dm
code/game/objects/structures/fireaxe.dm
code/game/objects/structures/fluff.dm
code/game/objects/structures/kitchen_spike.dm
code/game/objects/structures/maneater.dm
code/game/objects/structures/mannequin.dm
code/game/objects/structures/mirror.dm
code/game/objects/structures/roguetent.dm
code/game/objects/structures/roguetown/gate.dm
code/game/objects/structures/roguetown/meathook.dm
code/game/objects/structures/roguetown/portal.dm
code/game/objects/structures/roguetown/rogueflora.dm
code/game/objects/structures/well.dm
code/game/turfs/closed/wall/roguewalls.dm
code/modules/clothing/rogueclothes/feet.dm
code/modules/clothing/rogueclothes/pants.dm
code/modules/clothing/rogueclothes/storage.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm

A PR that attempts to fix a number of in-game text that bugged me the most. As this is my first PR, this is by no means an exhaustive list.
- Fixed typos
- Fixed grammar errors
- Added the Oxford Comma, the only comma.
- Added descriptions to some items that were without. Especially common items everyone uses.
- Added some helpful tips to guide newer players.
- A bunch of miscellaneous changes.
1. Better readability and more flavor text lends to a more immersive experience.
2. It makes me less annoyed at the in-game writing quality.
3. Apothacary

Proofreading and Description Pass #1

---

_maps/map_files/dun_world/dun_world.dmm
code/modules/cargo/packsrogue/bathmatron/bath_perfume.dm
code/modules/roguetown/roguemachine/bathmaster.dm
roguetown.dme

- Adds perfumes to bathhouse with base cost of 15 for the cheap one and 30 for the expensive one (Sandalwood, Frankincense and Myrrh)
- Add a pair of starting Frankincense and Myrrh Perfume to the church's table on the second floor, moving the scroll / feather to one spot to clear space. It is thematic + raises awareness perfume exist + create demands for more perfumes
Now you can actually buy perfumes + thematic starting perfume and induced demand from church

Perfumes Followup

---

code/modules/roguetown/roguemachine/mail.dm

Add explanation for Hermes. You can insert a coin - just 1 bronze, to send a letter without a piece of paper.
I didn't know that existed.
Hermes is underused and a lot of people are under the impression they have to hunt down a piece of paper but nope, you can just get one for $1. What the hell.

Add Hermes explanation.

---

code/modules/spells/roguetown/acolyte/abyssor.dm

Fixes a faulty sanity check for abyssal infusion

---

code/modules/roguetown/roguemachine/headeater.dm

Add examine text for mass selling
Add mass selling heads.
Makes it less tedious to sell heads

Headeater improvements - mass selling heads and examine text.

---

code/datums/keybinding/human.dm

Add in AltQ AltE Hotkey for belt slot.

Add in AltQ AltE Hotkey for belt slot.

---

code/modules/spells/roguetown/acolyte/noc.dm

Change Blindness incantation to shout.
I got no esc'ed blindnessed yesterday so I am PRing this. Making this a whisper was in fact, a mistake.

Change Blindness incantation to shout.

---

code/modules/roguetown/roguemachine/headeater.dm

Round topay before paying on headeater.
Tested
Avoid a display error of spitting out 8.4 mammons or something, even though 8 is actually spitted out anyway.

Round topay before paying on headeater.

---

code/modules/mob/living/carbon/human/npc/deadite.dm

Compiled
Ambush mobs shouldn't trigger ambushes.

Deadites no longer trigger ambushes

---

code/datums/keybinding/human.dm

Swap Left and Right equip on the UI what the fuck.
Swap Left and Right equip on the UI what the fuck.
Yeah. 
It is swapped just like Q and E on the UI what the shit.

Swap Left and Right equip on the UI what the fuck.

---

code/modules/jobs/job_types/roguetown/peasants/soilson.dm

Mistakes were infact made
1 line change
After playing it with couple rounds yeah there is a reason this stayed at 3

Removes expert polearms for Soilson

---

code/modules/jobs/job_types/roguetown/youngfolk/apothecary.dm

Kill rous with style now. Apothecary was unfairly left out without pathologic vibes that other two doctor roles have.

Pathologic music for apothecary cmode

---

code/modules/client/preferences.dm

probably should've seen this coming
maybe stops people from clicking classic mode without knowing what it is
maybe
hopefully
if they dont read they're on their own

adds a warning to my last pr

---

code/modules/jobs/job_types/roguetown/garrison/dungeoneer.dm

Fixes dungeoneer runtime
How it used to be
Fixes dungeoneer runtime

Fixes dungeoneer runtime

---

code/modules/roguetown/roguecrafting/alchemy/alch_items.dm

You can rename vials and change descripition.
Asked for I guess?

Vial renaming

---

code/modules/farming/fermenting_barrel.dm

Adds exception to the barrel for containers
Works this time
me when bugs

Fermenting barrel water container

---

code/datums/keybinding/human.dm

Swap the belt equip default.
not tested
Swap the belt equip default.
oops

Swap the belt equip default.

---

_maps/map_files/dun_world/dun_world.dmm

Fix a little bug, making the vineyard stairs unusable.
Bugs are bad.

Hotfix - Vineyard stairs

---

code/modules/roguetown/roguemachine/merchant/goldface.dm

Add Perfume to Merchant inventory.
- Add Perfume to Merchant inventory.
- Perfume is not meant to be inaccessible, this give one more source for them. A little bit of goods overlap is good.

Add Perfume to Merchant inventory.

---

code/modules/clothing/rogueclothes/hats.dm
modular_azurepeak/code/game/objects/items/donator_fluff_items.dm

visored sallet now covers hair

---

code/modules/spells/spell_types/wizard/buffs_debuffs/enlarge.dm
code/modules/spells/spell_types/wizard/buffs_debuffs/featherfall.dm
code/modules/spells/spell_types/wizard/buffs_debuffs/leap.dm

Brings a few spells into line with other buff spells of the same style.
I did this on my phone :^( (its not much of a change SHOULD BE FINE)
Have you ever tried to cast featherfall, TEN WHOLE SECONDS with server lag ontop of that, its miserable for a short buff.

Normalizes some Buff Spells cast times - Featherfall is no longer complete ass

---

code/modules/farming/fermenting_barrel.dm

Me when I fail basic maths yet again.
THIS time surely it will work
It's a bug

Actually allows brewing at lvl 3

---

code/game/objects/items/rogueweapons/melee/swords.dm

people keep picking these roles for the swords and it encourages bad behavior
perhaps not having snowflake weaponry that is stronger than other weaponry will encourage people to stop gearing up and fragging out
single file pr
it'll mean knight captains and marshals stop behaving like shitters and dukes stop thinking they're kings of the world
long overdue- these weapons were meant to fight vl, anyway, and it's not here and never will be
don't reply to this pr i won't read it

single file ragebait balance pr

---

code/modules/cargo/packsrogue/merchant/alcohols.dm

read
i don't want to test it
fuck you

one file pr i made on my phone that makes alcohols say what they are

---

_maps/map_files/dun_world/dun_world.dmm
code/game/area/roguetownareas.dm

Adds a little Eoran hot spring shrine out in the woods just south of the city. It's hidden away above the forest and requires some climbing to get to.
https://github.com/user-attachments/assets/598c5c61-c0f3-423e-a710-8f839ec7ed4b
Cute new area. Maybe Eora-worshippers will gather there, I don't know. 
I added a necran-themed labyrinth area to mount decap a while back, wanted to do little shrine areas in the wilderness dedicated to each of the ten but never got around to it.

 Eoran hotspring/shrine area

---

modular_azurepeak/virtues/utility.dm

I am informed by sources they need these tools, so slap a statue or tree and receive them, go forth and craft.
Your Local shadowy necran sefra has proviced them.
Tools good?

Adds Hammer, Chisel and Hand Saw to Artificers Apprentice virture Stash.

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm

Reduce Adv. Mage spellpoint by 3.
Compiled
Number mistake made in my earlier PR that made them equal to Mage Associate in points. Oops!

Reduce Adv. Mage spellpoint by 3.

---

code/modules/mob/living/carbon/life.dm

was missing a line actually handling pain modifier
yea
yeah

Fixes Pain Mod

---

code/game/objects/effects/decals/cleanable/food.dm
modular/Neu_Food/code/cooked/cooked_baked.dm
modular/Neu_Food/code/cooked/cooked_cakes.dm
modular/Neu_Food/code/cooked/cooked_egg.dm
modular/Neu_Food/code/cooked/cooked_meat_meal.dm
modular/Neu_Food/code/cooked/cooked_pastry.dm

Makes a pass at fixing and adding new descriptions of some foods, mostly baked stuff.
More flavor to your flavor!

Proofreading and Description Pass: Baked Foods

---

code/modules/spells/spell_types/wizard/buffs_debuffs/giants_strength.dm
code/modules/spells/spell_types/wizard/buffs_debuffs/hawks_eyes.dm
code/modules/spells/spell_types/wizard/buffs_debuffs/stoneskin.dm
code/modules/spells/spell_types/wizard/conjure/conjure_armor.dm
code/modules/spells/spell_types/wizard/conjure/conjure_weapon.dm
code/modules/spells/spell_types/wizard/invoked_aoe/thunderstrike.dm
code/modules/spells/spell_types/wizard/misc/arcyne_prison.dm
code/modules/spells/spell_types/wizard/misc/enchant_weapon.dm
code/modules/spells/spell_types/wizard/misc/greater_forcewall.dm
code/modules/spells/spell_types/wizard/utility/create_campfire.dm
code/modules/spells/spell_types/wizard/utility/light.dm
modular_hearthstone/code/modules/spells/roguetown/flagellant.dm

I requested Lynx's friend Puma to help translate some of the stand in phrases I put in for several spells, and to fix up the horrid pig latin with the flagellant's spells and they got back to me.
- Update Latin Phrases for a dozen spells to new translation by Puma.
Compiled
More accurate Latin phrases.

Update Latin Phrases for a dozen spells to new translation by Puma.

---

_maps/map_files/dun_world/dun_world.dmm

Added the following to the kitchen:
- A set of a single cabbage, potato, and onion.
- A flint inside the closet to light the kitchen appliances since there are no torches anywhere in the bathhouse.
- Four wooden cups.
QOL. Plus it is strange there's only four cups in the bathhouse in total.

Update | Bathhouse Kitchen Adds

---

code/_globalvars/special_traits.dm
code/_onclick/other_mobs.dm
code/controllers/subsystem/adjacent_air.dm
code/datums/mind.dm
code/modules/client/preferences_descriptors.dm
code/modules/reagents/reagent_containers/glass.dm
code/modules/surgery/organs/organ_internal.dm

at least one of them will work, of that I'm sure

runtime bundle for TM

---

code/modules/surgery/surgeries_hearth/revival.dm

graggar requires you to destroy some guys heart with the culling but this would just lead to people being revived and instantly dying due to heart loss (requiring u to infuse lux in2 someone's heart which is gone)
this checks for that and stops you from doing it if there is no heart which should help provide an escape from churchbay hell
works
xP guess

fixes an oversight with lux revival

---

modular_azurepeak/code/game/objects/items/donator_fluff_items.dm

Code broke repairing the helm.
This fixed it.
fixes my item

Fixes Donator Helmet

---

code/game/objects/lighting/_base_roguelight.dm
code/game/objects/lighting/rogue_fires.dm
code/modules/roguetown/roguejobs/cook/tools/oven.dm

Fix lantern crafting runtime + lantern doesnt flip away anymore on craft

---

_maps/map_files/dun_world/dun_world.dmm
code/game/area/roguetownareas.dm

Fixes a few mapping bug reports related to the bath-house.
<details>
( https://www.youtube.com/watch?v=CK62s_TXL5k )
</details>
Bath-house related map oversights/fixes.

Some small bath-house related map fixes.

---

code/datums/mind.dm
modular_azurepeak/code/game/objects/items/spellbooks.dm

https://github.com/user-attachments/assets/65ebd0ab-fb72-43a8-b9be-a83db3886fb8

Fixes spellbook refund infinite duplication

---

code/game/objects/items/rogueitems/needle.dm

Success actually gives some XP now from repairing not just failure - squires can repair 1 whole second faster (or attempt to whoowie)
You probably should get rewarded for success not failure like with smithing.

Sewing success / time

---

code/datums/sexcon/sexcon.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lpeasant.dm
code/modules/roguetown/roguecrafting/crafting/ammo_and_ranged.dm

Fixes #2694 and #2634 (does that guy even show up still?) and also another thing that has been bugging me for awhile now.
Tested local forgot to take a screenshot though please trust
Argue for the merits of your changes and how they benefit the game, especially if they are controversial. If you can't, then it probably isn't good for the game in the first place.

Fixes #2694 and #2634

---

code/modules/client/customizer/customizers/organ/snout.dm

Enables the Hyena snout for Wild-Kin.
(From request.)
Enables a customization option. 
(It was already pre-coded and sprited, just needed to be added to a list.)

Enables Hyenas.

---

strings/rt/timechangetips.txt

There was some hidden mechanical knowledge regarding skeletons that would probably be better if it was in the tips file, so this helps that.
It's a text file, I hope it works.
IMO it's good to have this documented somewhere.

Timechange useful tip about skeletons

---

code/game/atoms_movable.dm
code/modules/client/client_procs.dm

Port two fixes from Ratwood Zun told us about
- Adding Find function to browser window at 516 client version or above - https://github.com/Rotwood-Vale/Ratwood-Keep/pull/3006
- Force update intents on human when item is forcemoved - https://github.com/Rotwood-Vale/Ratwood-Keep/pull/3010
it's good

Zun Fix Ports from Ratwood

---

code/modules/clothing/rogueclothes/armor.dm

Fixes broken light brigandine overlay
It's bugged also let's be real looks kinda ass if it's stuck on black.

Light brig colour

---

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/witch.dm
code/modules/roguetown/roguemachine/merchant/goldface.dm

Just two fixes I felt like doing tonight. Trying to figure out how to balance the new brewing recipes still.
- Round up silverface price correctly (?) - so hopefully there isn't an off by one error
- Gave Witch 1 Arcane Skill which was missing after Mage Overhaul 
Compiled.
Witch having spellpoints but no Arcane was weird. Round up silverface price.

Two small fixes

---

code/modules/roguetown/roguejobs/blacksmith/smelter.dm

- Fix an issue with right click smelting getting neutral quality
- Revert Steel Recipe to 1 coal, 3 iron for 3 bars
- Great Furnace size reverted back to 4.
Tested
Feedbacks from smith indicate I've hit the steel eco too hard from the smith side especially when we haven't implemented enough iron gears yet. This will be revisited at a later point. 
Also fix a bug with my implementation of right click quick smelt.

Fix smelter mind / quality issue (probably) + Revert Steel Recipe

---

code/modules/roguetown/roguecrafting/sewing.dm

Does title, there may be a couple more I am missing.
Things that were added were:
> The old Ravox tabard (it was changed from templar/ravox to cleric/ravox in the recent change)
> the Ravox gorget (It's actually just a hood, it has no armor it's only for drip)
> the NEW Xylian tabard as well.
I accidentally destroyed my tabard as a Xylixan and cried inside for the rest of the round.

Adds some missing Tabards to the sewing list

---

code/game/turfs/closed/minerals.dm

Allows auto mining of mineral walls. One click is all you need to start the process.
https://github.com/user-attachments/assets/7fdae478-1ed8-4a30-bbdb-d5fc87c8117a
Clicking rocks is fun but it hurts.

Allows for auto mining mineral walls

---

code/modules/reagents/chemistry/reagents/rt_alcohol_reagents.dm

An update to the tastes and colors of some of the alcohols that were missing it.
>Brandy of the new fruits
>Ciders of the new fruits
>Adjusted wine descriptions to have less overlap
Spawned the drinks with game mastery tab, drank them, and saw the changed flavor texts
https://github.com/user-attachments/assets/e330a6f6-d6ad-4fc3-8a2d-7869b4d83c0f
This is good because it makes it more enjoyable to drink! And more rewarding to brew the new alcohols. It is also more immersive if different fruits create different flavors.

More flavorful Alcohols

---

_maps/map_files/dun_world/dun_world.dmm
code/modules/roguetown/mapgen/beach.dm
modular_azurepeak/code/game/objects/items/spellbooks.dm

CITIZENS OF AZURE,
Today, the Grand Duchy of Azuria call for all adventurers. _**The hamlet, who just got renovated and integrated a small church**_, has once more fallen to the tide of skeletal servants of the inhumens. Furthermore, it seems that _**the graggarite orcs rebuilt their fortress**_, making it stronger to assault, but with new loots from their pillages! Abyssor, who _**expanded our sandy coasts**_ with his grand powers, bless us in the task of reclaiming this land for the Grand Duke!
Also, the mapping auto-generator has been modified a bit.
FOR AZURIA!!
<details> 
</details>
Gives more personality to the coast.

A coastal glow-up - Abyssor reconquest

---

code/modules/cargo/packsrogue/_pack.dm
code/modules/cargo/packsrogue/merchant/armor/merch_armor_iron.dm
code/modules/cargo/packsrogue/merchant/armor/merch_armor_light.dm
code/modules/cargo/packsrogue/merchant/armor/merch_armor_steel.dm
code/modules/cargo/packsrogue/merchant/merchant_gems.dm
code/modules/cargo/packsrogue/merchant/merchant_potions.dm
code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_foreign.dm
code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_melee_iron.dm
code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_melee_steel.dm
code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_ranged.dm
code/modules/roguetown/roguemachine/merchant/goldface.dm

Addressing feedbacks on silverface and such. 
- Implement Mandated Public Profit variable on supply pack. Pursuant to the anti-dumping labor agreement between the Azurean Guild of Crafts and the Merchant's Gulid, the Silverface must charge a margin of 100% on all weaponries of steel and 50% on potion on top of the ordinary margin.
- The merchant can withdraw the mandated profit from the supply pack. So they do benefit if a plate creechur skip the line.
- Recalculated the prices of iron and steel ingot item, raising the base to 20 per ingot for iron, 35 per ingot for steel (from 25). 
- Applied a 1.25x multiplier on all steel armor, on top.
- Adjusted potions to be sold in package of 1, and pricing upward.
- Clearly Silverface was a bit too convenient but I am against hamstringing it with …

Merchantry Price Adjustment

---

code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfs.dm

ports:
https://github.com/BlackmoorHold/Blackmoor-hold/pull/112
https://github.com/BlackmoorHold/Blackmoor-hold/pull/108
i didnt test it
removes unnecessary character creator limits

quick character creator improvements

---

code/modules/cargo/packsrogue/merchant/alcohols.dm
code/modules/reagents/chemistry/reagents/rt_alcohol_reagents.dm
code/modules/roguetown/roguejobs/alchemist/container.dm

This makes three simple changes to alcohols.dm, rt_alcohol_reagents.dm, and container.dm that fixes an inconsistency with the description of Voddena and what it has been used for (Vodka).
I asked y'all if it looked good and you said 'yeah'
It fixes a description and taste inconsistency while maintaining the flavor of the incorrect description by producing one more fancy of bottle you can purchase and drink.

Voddena is Vodka and Saz Distal is something else

---

modular_azurepeak/code/datums/loadout.dm

I'm an idiot.
yes
I put the crafting recipe instead of the result like a dummy.

Fixes Loadout Tarot decks

---

code/modules/roguetown/roguecrafting/structure.dm

Adds the:
- nice bed
- wool bed
- double bed
- wool double bed
Changed also the bed name to straw bed, to not be misleading.
More Beds!!

New | Double Bed Crafting + Single Beds

---

code/modules/roguetown/roguemachine/noticeboard.dm

Give noticeboard a new UI that minimize the amount of input menu. Hopefully this make people use them more.
Yes

New Noticeboard UI.

---

code/datums/brewing_recipes/wine.dm
code/modules/crafting/recipe_books/book_entries/cooking/book_entry_brewing.dm
code/modules/farming/big_liquid_containers.dm
code/modules/farming/fermentation_keg.dm

Small fixes for brewing
- Non-jackberry wine should age properly 
- Added an entry to the brewing book that you can use sack to dump valid ingredients into the barrel
- Fix fermentation barrel having a mix of ethanol / beer
Tested
Good

Brewing fixes

---

code/modules/mob/living/carbon/human/species_types/furry/anthromorph.dm

Forgot it in the previous PR.
Tested, infact.
My fault, this time.

Also gives the markings(bun/bangs) to wildkins

---

code/modules/mob/living/carbon/life.dm

ports https://github.com/BlackmoorHold/Blackmoor-hold/pull/102
copypasted code from blackmoor. simple. probably works, don't see why it wouldn't.
because leaning against a wall to not be tired is kinda awesome. it's not like it'll beat resting w/o sleep since it's half the value.

wall-lean fatigue recovery port

---

strings/rt/timechangetips.txt

- just adds a few messages, edits the bleeding one to specify changes we've made (harder grip = less bleed).
- adds like one or two liens abt astrata or some shit too idk i thought it was cool if u want me to remove it just lmk
- fixed eye dodge secret now revealed oooo
- it compiles and if something breaks idk man i added line to a string file
- more messages
- - i stole two lines from the 2000 game sacrifice 4 this those who know will go "Hehe"

adds a few more daily messages (helpful, hopefully)

---

code/datums/brewing_recipes/_brewing_recipe_base.dm
code/datums/brewing_recipes/aqua_vitae.dm
code/datums/brewing_recipes/brandy.dm
code/datums/brewing_recipes/cabbage.dm
code/datums/brewing_recipes/cider.dm
code/datums/brewing_recipes/grain.dm
code/datums/brewing_recipes/limoncello.dm
code/datums/brewing_recipes/liquor.dm
code/datums/brewing_recipes/mead.dm
code/datums/brewing_recipes/onion_beer.dm
code/datums/brewing_recipes/sugar.dm
code/datums/brewing_recipes/tea.dm
code/datums/brewing_recipes/vodden.dm
code/datums/brewing_recipes/wine.dm
code/modules/farming/fermentation_keg.dm
code/modules/reagents/chemistry/reagents/rt_alcohol_reagents.dm
modular/Neu_Food/code/drinks/drinks_reagents.dm

When I arranged the recipes it felt a bit soulless and the soulless name were also applied to the bottle instead of generic bottle. Oops! This fix that and 3 bugs / issues I noticed
- Brewing recipe now have a bottle name and a description. I wrote in description of the alcohol's taste etc. and it now have a lowercase name of the alcohol instead of Wine, Jacksberry (Don't ask why the S came from, I corrected it).
- Ale boozepower was **65** instead of **25** like beer, making them stronger than brandy (!?!?!?) - reduced to 25
- Gin's boozepower was 12, raised to 65 because it is a two step recipe and it is a distilled alcohol not something half as weak as water.
- Strawberry cider's recipe required apple due to a copypaste mistake. Corrected.
- Tweaks some tastes
Sovl (Adds flavor and …

Brewing PR Followup (Again)

---

code/modules/roguetown/roguejobs/engineer/anvil_recipes/mechanical.dm

Fix folding table recipe.
Fix folding table recipe.

Fix folding table recipe.

---

code/modules/mob/living/grabbing.dm

ports over headbutting from vanderlin.
combat mode aggrograb head grab, smash on self makes you headbutt them. 
this does extra unarmed punch damage to them, and does a little bit less damage to you.
this also immobilizes them for a second, makes them go offbalance for a second, and immobilizes you for half a second.
i wanna bash my head against someone else's until one of us breaks.

ports headbutt from vanderlin

---

code/modules/mob/living/carbon/stress.dm
strings/rt/stress_messages.txt

**DO YOU LIKE KNOWING WHEN YOU'RE REALLY, _REALLY_ FREAKING OUT?**
LO AND BEHOLD.
WE GETTIN' FREAKY IN HERE. 15 NEW STRESS MESSAGES FOR WHEN YOUR CHARACTER IS **NOT** HAVING A GOOD TIME.
I'VE ALSO LOWERED THE MESSAGE POPUP THRESHOLD DOWN TO 13. IF YOU SUCK AT CARING ABT YOURSELF, THE GAME WILL REMIND YOU.
More Sovl. They've got some really good stuff and are rarely seen!

Let's Stress It Out A Little: More Stress MSGs, lower Stress messagethreshold

---

code/datums/ai/controllers/abyssal.dm
code/datums/ai/controllers/deepone.dm
code/datums/ai/controllers/direbear.dm
code/datums/ai/controllers/dragger.dm
code/datums/ai/controllers/dragon.dm
code/datums/ai/controllers/haunt.dm
code/datums/ai/controllers/headless.dm
code/datums/ai/controllers/mimic.dm
code/datums/ai/controllers/minotaur.dm
code/datums/ai/controllers/mirespider.dm
code/datums/ai/controllers/mole.dm
code/datums/ai/controllers/mossback.dm
code/datums/ai/controllers/orc.dm
code/datums/ai/controllers/skeleton.dm
code/datums/ai/controllers/spider.dm
code/datums/ai/controllers/troll.dm
code/datums/ai/controllers/volf.dm
code/datums/ai/controllers/wolf_undead.dm

Basically a port of https://github.com/NovaSector/Solaris/pull/237
- Most simple mobs, except rats, now attack obstacles in their way
Less cheese.

Simple mobs now attack obstacles in the way.

---

code/modules/paperwork/rogue.dm

Fix compilation issue.
Fix compilation issue.
Fix compilation issue.

Fix compilation issue.

---

code/game/objects/items/rogueitems/natural/stones.dm

lets you hit things with rocks again!!
see why its good for the gmae
**SOUND ON, SIRE.**
https://github.com/user-attachments/assets/bb1f3d03-77db-4d7e-8c1d-46e6fa4a3ad9

fixes rocks

---

code/modules/antagonists/roguetown/villain/werewolf/werewolf.dm

- changes how the werewolf on_gain proc works a bit to give you a greeting, with announce_objectives removed. translation: when you become a normal werewolf, you get told you're a normal werewolf, but the objectives there don't flashbang you until you transform.
- this does not apply to lesser werewolves as u get u own msgs already 4 dat.
- adds a cool little greeting i wrote... (if its bad i'll replace it lmao, the original was so much worse.)
- **thank you for sutures for telling me what an override is.**
okay. so my testing for this is _limited._ i'm having to mostly _assume_ how stuff works and improvise based off that, since i don't know how to force a roundstart ww. as you can see in the videos below, gaining the lesser werewolf datum (as you do via bite) does **_not_** immediately …

werewolf now tells you you're a werewolf!

---

code/modules/spells/roguetown/acolyte/astrata.dm
code/modules/spells/roguetown/acolyte/necra.dm

Fixes my fuck ups with Death's Door. Mostly a battle of ERGONOMICS than proper bugs. It's now at a CD of 30 seconds and not 180 seconds. Instructions when the portal is examined.
Makes Sacred Flame 80 devotion. Does not L-Bolt people but does light people on fire. Skeletons get extra.
Tested and actually works. Any edgecases should be reported.
PR wasn't supposed to be merged technically. But fixed now. Sorry for the delay.

actually fixes death's door + sacred flame fix

---

code/__DEFINES/traits.dm
code/modules/mob/living/carbon/energystamina.dm

Makes the astrata passive work throught the entire day
Clearly nothing should go wrong with this.
It is by a longshot worst passive out of all the Ten and the numbers speak for themelves it's not an insane buff but suuurely.

Astrata passive

---

modular_azurepeak/code/game/objects/items/ritualcircles.dm

when i was testing shit to make sure the music and all worked i was curious 2 see wt the graggar summon ritual voicelines were. for some reason they were not capitalized. this felt very weird because youre still yelling but it looked like this!! which was weird!!! why is it not capitalized!!!!!! so i fixed it
- compiles
- if this somehow breaks shit i have idsohnored my ancerstors
- looks better
- im autistic

makes graggar rites more screamy-looking (capslock is on)

---

code/modules/clothing/rogueclothes/neck.dm
modular_azurepeak/code/datums/loadout.dm

Add the forlorn collar (but actually a collar - and not a gorget) to loadout for forlorn characters.
Tested.
Was a request to let people who used to be slaves but aren't mercenaries now have the collar still.

Add loadout forlorn collar

---

code/modules/cargo/packsrogue/merchant/armor/merch_armor_iron.dm
code/modules/roguetown/roguemachine/merchant/goldface.dm

Also add the iron hauberk to the merchant
Yeah there was a rounding / price error that took me half an hour to figure out. Fixed
It works
Forgot to include the Hauberk in the merchant.

Add Iron Hauberk to Goldface. Fix rounding error

---

code/game/turfs/open/water.dm

And also make the Abyssor Swim work as before. This was a regression when swimming was refactored to RW code during the AI port.
The other two major codebase does not provide a way to level up swimming like we do, as far as I know.
yes

Make swimming give you XP again.

---

_maps/map_files/dun_world/dun_world.dmm
code/datums/brewing_recipes/wine.dm
code/modules/cargo/packsrogue/bathmatron/drugs.dm
code/modules/reagents/chemistry/reagents/rt_alcohol_reagents.dm
code/modules/roguetown/roguejobs/alchemist/container.dm

- by request of ansari, adds lux wine to the game!! also adds the divine whip wine (mistranslation) and the other divine whip wine
- recipes are (fairly) unique. i wanted to try seeing if you could make anything a brewing recipe ingredient. you can.
<details>
- made with sugar, lux, and a calendula
- works as a poor health potion, doesn't restore blood or wounds, just fixes damage.
- cool kinda weird color
- mostly for status, u might be able 2 replace the "taste a lux" baothan objective w/ tasting this wine tho. 
- only makes 2 bottles (32oz) of the stuff cause it IS A healing potion made w/o alchemy. w/ the requirements and that it shouldn't be very gamer friendly
- should also be heretical to make probably as i noted in the comments but uhg...... idk thats up 2 players to actually GAF. …

adds lux wine, whip wine, and the Trve Whip Wine.

---

_maps/map_files/dun_world/dun_world.dmm

fixes a name on a door
ignore the weirdl ike black space i aghosted before hte round startd to see it fast and dun world loads like dun world lol
it not a clerk door

fixes shophand bedroom name

---

modular_azurepeak/code/datums/loadout.dm

Brought to you by Scarlet-Reach/Scarlet-Reach#221, you can have this too. less than 3
Compiled
I look so fucking cool with this I guess

Add fur hat to loadout options

---

code/_onclick/hud/screen_objects.dm
code/datums/keybinding/human.dm
code/modules/mob/living/carbon/human/npc/_npc.dm
modular_azurepeak/code/game/objects/structures/fartravel.dm

fugbixes.
they are put in seperate commits with descs.
Tested each.
why not

Miniscule batch of runtime fixes (only 4)

---

code/datums/keybinding/human.dm

I thought I tested this (I did, just not in the way it'd be used). Bug introduced in #3076 
I did test it now.
:/

Fix Belt Equip Hotkeys

---

_maps/map_files/dun_world/dun_world.dmm

Delete one quest mark in artificer room.
Delete one quest mark in artificer room.
Delete one quest mark in artificer room.

Delete one quest mark in artificer room.

---

.gitignore
.vscode/tasks.json
code/modules/roguetown/roguejobs/tailor/dyer.dm

All UIs have to have `<html>` tags or they get parsed as text.
The dyebin should work.

Fix dyebins for 516

---

modular/Neu_Food/code/drinks/drinks_reagents.dm
modular/Neu_Food/code/drinks/stew.dm
modular/Neu_Food/code/recipes/stew_recipes.dm

This PR introduces some uses for all of the plants that were added a while ago, as well as a use for POPPY! (It's drugs)
_The Drinks_
----------------
>**Poppy Milk**
A milk that instantly numbs the mouth and mind, has an OD threshold of ONE CUP, anything more than that in a short time will OD you similar to Ozium. Drinking this gives you the same effect of Ozium and sates your addiction! Druggies rejoice!
_The Soups/Stews/Marmalades_
----------------
>**Garlick Soup**
a simple soup made with a overwhelming amount of garlick, vampires beware. (Doesn't actually do anything to vampires YET)
>**Cucumber Soup**
a nice and tangy cucumber soup! Nothing special, it's just cucumber.
>**Eggplant Soup**
A simple eggplant soup that tastes more like plant than it does egg!
>**Carrot Stew**
a hearty …

8 new soups, 1 new drink - Part one of the FOOD-EN-ING.

---

code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_foreign.dm

fixes compile error on main

---

code/modules/jobs/job_types/roguetown/church/martyr.dm

- Gives the martyr sword the silver trait
- Thats It
(its one line)
https://github.com/user-attachments/assets/668a86bc-763e-43ce-be18-a9c3fe92a54a
I Cannot Frag the Vampire on Ultimate Mode If It Can Aheal

Silver trait Martyr sword

---

code/modules/events/spacevine.dm
code/modules/spells/roguetown/acolyte/eora.dm

what it says on the tin
tested
balance/sanity/consistency's sake.
also prevents spacevines on rooftops

Eora and Evil tree can only grow on dirt/grass

---

code/modules/clothing/rogueclothes/armor/plate.dm

I do not even want to know what is happening in this plate.dm Diff says it all. Psydon help me.
It. Works.
It haunts me. Bugs related to psydonian armor haunt me. I shall endure.

Fixes psydonic armor. Once and for all, hopefully.

---

code/modules/mob/living/carbon/human/npc/deranged_knight.dm

Give Steel Gorget to all deranged knight miniboss.
It compiled
Now instead of 3 / 4 hits to peel and cut them off you have to hit them like, 6 - 8 times (It doesn't make that much of a difference)

Give Steel Gorget to all deranged knight miniboss.

---

_maps/map_files/dun_world/dun_world.dmm

It unlock two doors. That's it.
I'm too lazy to test two doors, but trust me, it'll work.
Bugs bad.

Small bug fix for two doors.

---

code/modules/spells/components/enchanted_weapon.dm

Fix text for enchant weapon.
Tested
Fix text for enchant weapon.

Fix text for enchant weapon.

---

code/game/objects/items/devices/flashlight.dm
code/modules/spells/roguetown/acolyte/astrata.dm

This PR fixes astratan's spell ignition. 

Ignition spell bugfix

---

code/modules/jobs/job_types/roguetown/church/monk.dm
code/modules/jobs/job_types/roguetown/church/templar.dm

Give abyssor templar/acolytes swimming

---

code/modules/client/preferences.dm
code/modules/mob/dead/new_player/preferences_setup.dm

Changing your race no longer nuke your FT or OOC Notes or OOC Extra etc.
Tested
Friend lost bunch of shit over this. This is absymal. This shouldn't be a thing. They can clean it out on their own.

Changing your race no longer nuke your FT or OOC Notes or OOC Extra etc.

---

code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm

Daring Twit Prince, Adjudicator, Desert Rider, Barbarian/Monster Hunter gets them now.
Yup.
As intended.

Gives more people scabbards that should've gotten it

---

code/game/area/roguetownareas.dm

Ceiling protection to lich arena.
I did not.
Ceiling protection to lich arena. Can closes #3200 which uses mapped in variable which is bad. I spun this out from my massive area redefine due to conflicts

Ceiling protection to lich arena.

---

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/witch.dm

i was offered 600 rupee for pr giving witch 'any spell for defense'. so, here you go - plus seems reasonable.
yeah it worked
basically gives witch a single combat-spell since they have no combat skills so gave them a weak-er one of the list so they have something for self-defense.
also - pay up.

[Commission] Gives Witch Arcane Bolt

---

code/modules/spells/spell_types/wizard/projectiles_single/blood_lightning.dm
code/modules/spells/spell_types/wizard/projectiles_single/lightning_bolt.dm
code/modules/spells/spell_types/wizard/projectiles_single/spitfire.dm
code/modules/spells/spell_types/wizard/spells_status_effects.dm

Tries to rebalance two of the most annoying spells in a Mage's arsenal, that I have ideas for
- Cost reduced from 6 to 3
- Cooldown reduced from 25 SECONDS to 15 SECONDS
- Now, on hit, it inflicts 40 instead of 15 damage. 2x NPC Damage Multiplier.
- On hit, it set clickCD of the hit opponent up by 6 seconds and also slow them down like frostbolt / snap freeze but also for 6 seconds. 
- See Above. Damage is 80 though, making it some insane armor piercing lightning on par with palpaitine. It IS an antag spell.
- ClickCD / Slowdown is 8 seconds.
- Spitfire no longer flashbang and blind you
- It gives 1 firestack (!!!) and ignite you (!!!!) on hit now
Tested
Hardstuns are very unhealthy for the game and so is literally flashbanging your opponent's eyes and giving them epilepsy and this tone …

LBolt Rebalance + Spitfire Rebalance

---

code/modules/roguetown/roguecrafting/leather/leather_container_recipes.dm

The recipe for short satchels was crafting regular satchels instead :]
Yaay

Fixes short satchel crafting

---

modular/Neu_Food/code/raw/raw_dough.dm

Hardtack should be really cheap; this makes it less annoying to make. Less tedium = people having more fun, and less time waiting for stuff. Might also encourage people to buy hardtack at the Inn.
Compiled. Also it's a simple 2nd line change.
See About.

Hardtack Making: The Twoening

---

code/game/objects/examine.dm
code/modules/cargo/exports.dm

- replaced my shitty for loop on examine with a for loop in a DIFFERENT location nyehehehehe
- i think it still runs over everything because it Always gets real price even if they dont have the seeprices or shitty so this was all pointless and i spent 2 hours debugging vsc and my repo to get it to work for no reason broabyl ubut didi t :)))
i did. a lot. pelase trst me. it unfortunately just kinda supplants the value of the bag if there isa value but 1. no one is selling satchels and if they are they arent selling them full adn 2. i tried adding the value of the item to the thing and it fucking runtiemd so i not dong so that
=- help

for loop 2: better written boogaloo

---

code/modules/spells/roguetown/acolyte/ravox.dm

- Range 7 -> Range 5
- No cross z-level casts.
- requested changes + I meant to do the z-level thing before and forgot about it.
yea

ravox arena adjustment

---

code/modules/client/customizer/customizers/organ/tail.dm

... Are not real, they cannot hurt you...
- Enables the option to disable tail for Tiefling species in preferences. That's all
Its one line
More customization = good
Perhaps they got their tail cut off for being a demonspawn, perhaps they lost it in a fight, or perhaps they were born like this. Many ways to RP around this.

Tailless Tieflings

---

code/modules/mob/living/carbon/human/npc/orc/orc_outfits.dm

Fix traits on orcs.
Fix traits on orcs.
Fix traits on orcs.

Fix traits on orcs.

---

code/modules/mob/dead/observer/observer.dm

Who could've guessed that /mob/dead/Initialize() is not calling its parent!
Trust me bro
I think I need them hearing

Fixes ghosts not becoming hearing_sensitive

---

code/__DEFINES/role_preferences.dm
code/modules/antagonists/roguetown/villain/chosen.dm
roguetown.dme

- gamemaster request!!! 
- adds the "chosen" antag to the traitor panel. when it's given to someone, it tells them they must survive to be given further objectives, which should be done by a gamemaster.
https://github.com/user-attachments/assets/239de910-ce68-471d-871c-b4e59542447e
- request
- please ONLY tm this. i'm fairly certain it doesn't runtime or anything but idk how it interacts w/ end of round or whatever so i'd like to ask during TM the game-mins use it on a few people to make sure nothing explodes
- DOUBLY so as i had to enable it in the .dme and in the global preferences i thijnk??? Honestly I dont know but it's scary.

condenses 1 hour of attempts into a new antag that does nothing

---

code/modules/clothing/rogueclothes/cloaks.dm

Makes the stole sprite again visible on character
Tested on local machine, can provide screenshot if needed
fixes the stole

Fixes stole sprite

---

code/modules/mob/living/carbon/human/npc/orc/orc.dm

Carbon orc mobs have green skin and red eyes now. Their hair is also a bit less vibrant.
bug fix good orc mobs r supposed 2 be green

Orc mobs fixes

---

code/_onclick/click.dm

I managed to bypass both reason and attack chain.
Now it works.
I think I need those bugs fixed.

Fixes spec attack

---

code/_onclick/other_mobs.dm

This PR fixes this issue https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/issues/3298

Grab free-jump-resist exploit fix

---

code/modules/spells/spell_types/wizard/utility/mending.dm

Mending cannot repair item not meant to be repaired.
Accompanies https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/3311 - now that we are setting some items to be unrepairable on purpose.

Mending cannot repair item not meant to be repaired.

---

code/modules/spells/spell_types/divine/projectiles_single/divine_blast.dm

-Just changes the check in divine blast from Priest to Bishop
one line
huaghhn remember to check back on 1 month old prs kids

bishopification divine blast

---

code/modules/mob/living/carbon/carbon.dm

Throwing now respect clickCD.
Ports https://github.com/Scarlet-Reach/Scarlet-Reach/pull/475
Pre-empt cheese with tossing 10,000 objects at someone in rapid succession

Throwing now respect clickCD.

---

code/game/objects/items/rogueweapons/melee/swords.dm
code/modules/clothing/rogueclothes/armor/plate.dm
code/modules/clothing/rogueclothes/feet.dm
code/modules/clothing/rogueclothes/gloves/plate.dm
code/modules/clothing/rogueclothes/headwear/helmet/heavy_helmet.dm
code/modules/clothing/rogueclothes/pants/plate.dm

- Darksteel - > Avantyne
strings
requested by witty

darksteel retitle

---

code/__HELPERS/text.dm

You can use the characters in: https://docs.oracle.com/cd/E29584_01/webhelp/mdex_basicDev/src/rbdv_chars_mapping.html
In names. It will show up and display correctly in game.
It's the 1500s everyone had one of these badboys or so they tell me.
Inform the DB admin of this PR. I've talked with them but still - just in case.

Adds diacritical characters for naming

---

code/datums/skill_holder.dm
code/modules/mob/mob.dm

Another attempt to fix more lingering references based on ref-tracking
Yae
Possibly lag fix? Hard Deletes make up 2/3 of our overtime at 32 cpu time to 1021 cpu time (After last night's forced mob hard delete fix went in). Still not good. If we cut out spatial content and some sources that'll leave wounds and such in.

Tries to reduce mob harddels

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

This update our Readme.MD to be based on that of Vanderlin, which clearly line out what licenses our code and assets are under. This should be considered legal and unproblematic because Roguecode was based on an illegal closed source fork of TGstation beforehand and thus any attempt to retroactively license assets / code under another license should be void. 
This also put in a section under the pull request:
```
```
To clarify that there is in fact, no takesies backsies on any contribution you make here and the only reasons we have considered entertaining them is because we are nice and it is all about the optics
None.
Regardless of your stance on the Lore team and their work or not we've opened the Pandora's Box recently by remotely thinking of entertaining request from any developers …

Updating README.MD to clarify the license we are under and new pull request template

---

code/datums/ai/_ai_controller.dm

Remove unused pawn_turf variable.
Remove unused pawn_turf variable.
Remove unused pawn_turf variable.

Remove unused pawn_turf variable.

---

code/__DEFINES/movement_info.dm
code/game/atoms_movable.dm
roguetown.dme

Port Canonical Movement from TGStation[#82085](https://github.com/tgstation/tgstation/pull/82085)
Might or might not help with resolving spatial grid cells problem.
Walked around on local
TM for at least one round.

Port Canonical Movement from TGStation #82085

---

code/modules/jobs/job_types/roguetown/nobility/captain.dm

Captains now get Master (5) only in their chosen weapon.
Infantry Captains now get Expert (4) in flails.
They can select their armor the same way Knights can.
Their Knives skill is now Journeyman (3) the same as Knights have.
this is a completely self-indulgent pr to let me aurafarm with a big axe.
the flail option was also a complete noob trap since Captain was stuck on 2 lolol

Captains get Master in their chosen weapon + get armor choice and 3 knives.

---

modular_hearthstone/code/game/objects/items/clothes/stockings.dm

* fixes stockings harddel
this one too
doesn't show up failing on qdel log

stockings harddel fix

---

code/modules/mob/living/carbon/human/npc/highwayman.dm
code/modules/mob/living/carbon/human/npc/orc/orc.dm
code/modules/mob/living/carbon/human/npc/skeleton/skeleton.dm

This has been a point of frustration for PVE-er and I discovered it is because they are on dodge intent and never had special dodgetime of 30 like highwaymen so instead, I make them parry by default
Less PVE frustration. Gives blunt weapon thingie.

Default Orc and Skeleton and Highwaymen to Parry.

---

code/game/objects/effects/spawners/equipment_spawners.dm
code/game/objects/effects/spawners/loot_spawners.dm
code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_melee_steel.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/routier.dm
code/modules/mob/living/carbon/human/npc/orc/orc_outfits.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm

Falchion exists again, oops.
The militia falchion existing means it didn't detect that sword/falchion isn't valid. Falchion classes are spawning with an arming sword because of me. Oops.
No.
May thy losses be heavy, and thy wenches be few.

Falchion Fix

---

_maps/map_files/dun_world/dun_world.dmm

Fixes the ship keys (they didn't work) and removes some walls in windows. Fuck my stupid mapper life.

MAPPING HOTFIXES

---

code/modules/jobs/job_types/roguetown/Inquisition/absolutionist.dm

Adds holy skill to the Absolver
One-line change, it compiled
Even Brutes get holy skill. Let me conjure water without it taking 84 years, PLEASE

Absolvers Are Holy Now

---

code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm

It gives Concubines money.
It gives Concubines money.
It gives Concubines money.
It gives Concubines money.

Give Concubines Money

---

code/modules/antagonists/roguetown/villain/werewolf/werewolf_spells.dm

- Druids should hear werewolfes howl, BUT coder, who coding his howl, didn't take into account that there are no constantly used languages in the build
-Now everything will be as the coder intended.

[FIX] Now druid can hear werewolfes howl

---

code/_onclick/click.dm
code/game/objects/structures/traveltile.dm
code/modules/mob/living/ambush.dm
code/modules/mob/mob_defines.dm
code/modules/mob/mob_movement.dm

Port of this PR, with all of the code relevant to leashes cut out in the cherrypick:
- https://github.com/Scarlet-Reach/Scarlet-Reach/pull/529
Compiled. Also passed dreamchecker linting. I tested this on Scarletcode, and our code for this is the same on both.
No merge conflicts aside from leash.dm not being here. 'Twas piss-easy to cut all of that stuff out thanks to modularity.
See original PR. Ignore the kinky shit I guess.

PORT - Traveltile refactor/rework, blindfolds work, anti-abuse/anti-metagaming checks, no AFK ambushes

---

code/datums/status_effects/status_effect.dm
code/modules/surgery/bodyparts/helpers.dm

Some low hanging fruit from Tracy.
Reducing cost of procs helps with lag.

Optimizations

---

code/modules/paperwork/paper.dm

I did a return in the worst possible place for one.
Read the changed files.
GRAHHHHHH

HOTTEST HOTFIX

---

code/game/objects/items/rogueweapons/melee/polearms.dm

Decapitalize Naginata.
I did not compile this one.
It is consistent with other weapons.

Decapitalize Naginata.

---

code/__HELPERS/game.dm
code/controllers/subsystem/rogue/treasury.dm
code/datums/looping_sounds/_looping_sound.dm
code/game/objects/items/rogueweapons/intents.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/living.dm
code/modules/mob/mob.dm
code/modules/mob/mob_helpers.dm

Over 8+ hours spent and yet to find the source of 8 lingering unarmed intents that have Mastermob yet cannot be deleted. Fuck.
Fix a bunch of hard deletes. This might be the one that finally end most simple mobs harddelete. Human's a pain in the ass, do you know that like over 350+ unarmed intents get created on creation of a character? Yeah. 
Looping Sound changes is ported from Vanderlin's Create & Destroy PR
yeah
yeah

Some harddelete fixes?

---

code/__HELPERS/_lists.dm
code/controllers/configuration/entries/general.dm
code/modules/admin/admin_verbs.dm
code/modules/client/border_control.dm
code/modules/client/client_procs.dm
config/example/config.txt
roguetown.dme

Uses old Ckey whitelisting system from prior servers I've had code downloaded for; mild repurposing to get it working.
Tee hee
Lets staff add whitelists in game via admin command rather than handling it via direct webhook access to update the .txt

Ckey Database Hookup (Whitelisting)

---

code/modules/spells/components/enchanted_weapon.dm
code/modules/spells/spell_types/wizard/misc/enchant_weapon.dm

- Remove the Searing Blade Enchant
- Enchant Weapon now override existing enchant if you wanna swap. Yippee
Dude I've told everyone for 2+ months as the CREATOR this shit is broken and I don't have time why won't you let me remove it sobs.
Also enchant weapon override a pre existing enchant now.

Remove the searing blade enchant. Enchant Weapon override Enchant Weapon.

---

code/modules/spells/spell_types/wildshape.dm

-Previously when u used "Beast form" - there were a couple of seconds to grab the backpack (or somehting else) and it remained in the main character's hand and was not in the beast form. When u turned back, the backpack or other thing appeared in the hand again. Allowed you to store an item in an invisible slot. Now fixed. 
-everyone is equal and logic is not violated

[FIX] Wildshape now dont have extra-slot

---

code/__HELPERS/filters.dm
code/_onclick/hud/plane_master.dm
code/datums/status_effects/rogue/roguebuff.dm
code/game/atoms.dm

Ported from:
https://github.com/Scarlet-Reach/Scarlet-Reach/pull/568
Bug fix.

Baotha druqks fix

---

code/_onclick/hud/screen_objects.dm
code/_onclick/item_attack.dm
code/modules/mob/living/carbon/carbon_defense.dm
code/modules/mob/living/carbon/human/species.dm

Ports https://github.com/Scarlet-Reach/Scarlet-Reach/pull/570 by EvenInDeathIStillServe
Tested
It's good

Port Scarlet Reach #570 - Better Attack Targeting Feedback.

---

code/modules/spells/roguetown/acolyte/pestra.dm

- the title
- its one line
yea

Undivided fix - Infestation actually works without a pestran amulet now.

---

code/modules/spells/spell.dm

- Spell should no longer freak out if more than one item of X type is present like Convergence or most miracles. 
- Spell should indicate missing items properly when in hand or in required item list. It uses their actual name and doesn't account for subtype but that is OK.
2c-af116f6ba9f8" />
- If you had more than one psicross or something like that you could fail to cast any spells and that was annoying and unintuitive.
- Ever wondered what you're missing? Now you know.

Proper fix for item requirements on spell.

---

code/modules/spells/components/enchanted_weapon.dm

- Enchant Weapon should actually delete itself when on a mob but they do not have the skills needed to indefinitely maintain it (lol)
- No more durability stacking when enchant weapon expire.
Yae
Yae

Fix Enchant Weapon Issues

---

code/modules/jobs/job_types/roguetown/adventurer/types/wretch/heretic.dm

Apostasy PR caused a bunch of conflicts with mine, which ended up erasing a significant chunk of the commits I actually made for my last PR. This properly removes the church tabards and distinct helmet from Abyssorites, and brings back the skill + armor un-neutering that I originally planned. 
It's a jak sire
Because I dont like my code being left sloppy.

TENNITE HERETIC HOTFIXJAK

---

code/game/objects/items/rogueweapons/melee/knives.dm

Should work. Compiles.
Makes sense.

Flipped Navajas don't have delay

---

code/modules/roguetown/roguejobs/artificer/handsaw_chisel.dm
code/modules/roguetown/roguejobs/gravedigger/tools.dm
code/modules/surgery/bodyparts/bodypart_wounds.dm

thanks to scarlet / Dorodomki for reporting this

fixes omniwounds preventing werewolf infections

---

code/modules/roguetown/roguejobs/mages/arcana_crafting.dm

Tried to make T4 summon shackles a few days ago but found they didn't work, causing a whole slew of effort from myself and 5 mage associates to be lost. Turns out, the recipes for t4 and t5 shackles had t1 shackles as the output. This PR fixes that, and also corrects some description discrepancies.
I don't think its intended, because the recipes say one thing, but had an error in output.

Fixes Broken Item Path For Binding Shackles

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm

I missed a tab
Divine Blast is not meant for Paladin or Cantor

Divine Blast ONLY for missionary class.

---

code/modules/client/client_procs.dm
code/modules/client/customizer/customizers/organ/ears.dm
code/modules/client/customizer/customizers/organ/horns.dm
code/modules/client/customizer/customizers/organ/tail.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/carbon/human/species_types/furry/anthromorphsmall.dm
code/modules/mob/living/carbon/human/species_types/furry/lizardfolk.dm
code/modules/surgery/organs/eyes.dm
code/modules/surgery/organs/feature_organs/snout.dm
code/modules/surgery/organs/feature_organs/tails.dm
strings/rt/timechangetips.txt

Reverts GeneralPantsuIsBadAtCoding/Azure-Peak#3607
slots are exploding and I frankly haven't a clue why now aaaAaaaaAaaaAAAa

Revert "Saurian"

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/forlorn.dm

Hey remember when Mercs weren't so bloated.
Yeah anyway.
- **Forlorn Mercenaries** now start with Brigandine Chausses and Brigandine Bracers, effectively gaining Semi Full Body Coverage ~~as every single fucking merc class tends to have. God fucking damnit.~~
- They also get a +1 to Shields, leveling it to **Expert**.  Only other merc class w/this is Varangian (who only has axes as a reliable weapon, + cleric spells), whereas other merc classes with jman shields are those such as a Steppensmen subclass (Steppensmen get lvl 3 riding as well as a handful of utility skills i.e. skincrafting) and Routier (Heavy armor nobles. Die.)
Its 3 lines of code.
@MrSaxyMan and a few other forlorn players (myself included) do think that Forlornians are a bit weaker as-is currently due to the fact that …

Forlorn Merc Buff: Brigandine bracers + chausses + 1 shield skill

---

code/modules/admin/admin_verbs.dm
code/modules/client/border_control.dm
code/modules/client/client_defines.dm
code/modules/client/client_procs.dm
code/modules/client/manual_donator.dm
roguetown.dme

Copypaste Rebel's code to add in a manual listing system for Donators under Admin.Border Control. https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/3384
- Also fixed two instances in admin log / whitelist log where it doesn't actually log the ckey of whomever did it.
- Admin can access those verbs under Admin.BorderControl. On reconnection / new client, is_donator verb is set to TRUE on the client if they are a donator in the list.
- There's no perks attached to it yet. This is a future framework for donator stuffs so we can afford a box upgrade and switch that will hopefully solve our cursed box issue (And spawn 300 more goblins)
Ryzen 9950X isn't free.

Copypasted Donator List System

---

code/modules/admin/verbs/adminhelp.dm

Port Multiline initial ahelp from tgstation.
https://github.com/tgstation/tgstation/pull/49276 
https://github.com/Scarlet-Reach/Scarlet-Reach/pull/708
yes

Port Multiline initial ahelp from tgstation.

---

code/controllers/subsystem/vote.dm

Small Pr is today I barely work.
Yes

Make the storyteller vote panel 800 height

---

code/modules/mob/living/carbon/carbon.dm

Port https://github.com/NovaSector/Solaris/pull/330
yes

Do an attack animation when throwing.

---

code/modules/client/preferences.dm

- Virtues, Races and Statpacks are now alphabetically sorted in the character setup screen
Yeah

Sort virtues, races and statpacks.

---

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
code/modules/roguetown/roguecrafting/leather/leather.dm

- Just makes plague masks craftable(1 leather, 1 bone) via skincrafting.
- Also gives the plague coat to town doctors.
- Commission by squidqueen
https://github.com/user-attachments/assets/1a9469fc-cfcd-4c47-b59a-1d14d6e2d951
probably good 2 have these acquirable through some means. fashionjak.

craftable plague masks + plague coat on town docs

---

_maps/templates/smalldungeons.dm
code/game/objects/items/granters.dm
code/game/objects/structures/roguetown/loot.dm

Remove blindness scroll from granter.
Remove blindness scroll from granter.
It's a miracle now.

Remove blindness scroll from granter.

---

code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_foreign.dm
code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_melee_iron.dm
code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_melee_steel.dm

Add warhammer and etruscan longsword to merchant inventory.
Add warhammer and etruscan longsword to merchant inventory.

Add warhammer and etruscan longsword to merchant inventory.

---

code/game/objects/items/rogueitems/coins.dm

Restablish Capitalism and the Monetary Economy

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/foreigner.dm

fixes a transposition error w/ ninja stats
the stats are correct now 👍

freak nasty ninja style what up

---

code/game/objects/lighting/_base_roguestreet.dm

ghnghfhnm
it works
they used to be invisible

fvck - fixes lightbars

---

code/controllers/subsystem/storyteller.dm
code/datums/storytellers/_base.dm
code/datums/storytellers/gods.dm

Adds href to a popup window with storyteller description to rectify currently cluttered vote window
https://github.com/user-attachments/assets/09834ed8-c2c2-4ced-9155-77d4aa61404e
Its all over my screen sire! Or, in this case, *was*. Visual clutter no more.

Removes clutter from storyteller vote panel

---

code/modules/jobs/job_types/roguetown/adventurer/types/antag/Iconoclast.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/hedgeknight.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/roguemage.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/sawbones.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/sellsword.dm

Gives every CTAG_BANDIT swimming apprentice.
Knaves get jman because they are, well, knaves!
Trust me pookie...
Most wretches have roundstart swimming skills. Bandits, on the other hand, do not.
We need to stop powercreeping wretches and make our dedicated antags less abrasive to play as.
And, at the end of the day, everyone and their moma has swimming these days.

[Cl*ss edit] Blatant bandit powercreep or bandits know how to swim now

---

code/modules/clothing/rogueclothes/cloaks.dm
code/modules/clothing/suits/toggles.dm

This PR fixes cloak hoods staying visible on the HUD.
This is a port of a fix done here https://github.com/Scarlet-Reach/Scarlet-Reach/pull/847
Fixes a bug.

Fix cloak hoods

---

code/world.dm

Port https://github.com/tgstation/tgstation/pull/83316
Did not.
Trust me bro

Set cache lifespan to 0 - TG 83316

---

code/datums/character_flaw/_character_flaw.dm
code/datums/character_flaw/addiction.dm
code/datums/stress/negative_events.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/life.dm
code/modules/mob/living/emote.dm

tl;dr, masochist has had it's weird bleed-needing pain-code fucked w/. i didn't bother reducing the amount of pain they can tolerate or w/e cause i'm not a balancejak but i can remove it onr equest. it's lit. 1 extra point of con and u have to still injur eurself bad it think its fine.
it now functions like sadist. what does this actually Mean? painscream.
on the backend? it's now an /addiction flaw like sadist, which also means that it a ffects player prefs. according to my local testing, this did not brick saves, but u do have 2 turn the vice back 2 masochist from alcoholic. woohoo!! a roguetown save thing that HAS BUILT IN PRECAUTIONs!!!!! htank u vice coder
ignore my commit history i  had a tough round b4 this.
lux forces painscream so i tested it w/ that
<details>
<summary>masochist …

masochist now functions like sadist!

---

code/modules/mob/living/carbon/human/npc/deranged_knight.dm

- what it says on the tin
- i have no clue if this needs 2 be a non-generic trait request an edit if so if not jusjt merge
- i spawned a matthios guy and killed them and all their oomfs while dyting myself but no one  was set on fire
- 
help
- bugfix

gives the npc bandit radiant guys their heretic traits

---

code/modules/jobs/job_types/roguetown/adventurer/types/wretch/deserter.dm

-Tweak:
Charge: 2 LCK now 2 PER
Bolster: Now give 2 CON and 3 WIL (bcs PR on wil do some changes in CON -> https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/3634)
QoL:
-Now you cast command immediately
-Add description of command
Some changes, which may reflect a little in fights. Deserter now more usefull in fights, bcs commands get instantly cast amd stats are actually

Deserter tweaks and QoL

---

code/modules/roguetown/roguemachine/bounty.dm

fixes this bug report
i have no idea what i'm doing this shit is confusing but i tested it and it works i think probably
bug fix

Fixes player-set bounties

---

code/modules/jobs/job_types/roguetown/yeomen/guildmaster.dm

fixes guildmaster spawn

---

code/modules/roguetown/roguemachine/mail.dm

- Ports this https://github.com/Scarlet-Reach/Scarlet-Reach/pull/830
- Also fixes yougotmail not working when hand-letters were sent. 
https://github.com/user-attachments/assets/41edf5a2-2c7a-4fb5-92f8-2da8f34be401
- Get paper
- Get Quill
- Get Bitches.
- (You can write letters away from a HERMES + a source of paper/quills for other purposes)

HERMES quill/paper buy port

---

code/__HELPERS/AStar.dm
code/__HELPERS/game.dm
code/modules/mob/living/carbon/human/npc/_npc.dm

A non-negligible amount of runtime unfortunately.
Reverts GeneralPantsuIsBadAtCoding/Azure-Peak#3174

Revert "NPC AI leaping fixes and tweaks"

---

code/modules/mob/living/carbon/human/voicepacks/genfemale.dm
code/modules/mob/living/carbon/human/voicepacks/genmale.dm
code/modules/mob/living/emote.dm

* Adds new sound, Stomp. 
Uses an existing sound that's pretty convincing.

adds stomp sound

---

code/modules/mob/living/carbon/human/examine.dm

fugbix
yes
nobody reports bugs these days i stg

Fix DNR description

---

code/game/objects/items/rogueweapons/melee/special.dm

WRONG NUMBER

---

code/modules/mob/living/carbon/human/npc/_npc.dm

https://github.com/Scarlet-Reach/Scarlet-Reach/pull/996
Order of operation
Nae
I'd win

Port of SR 996

---

code/_globalvars/special_traits.dm
code/datums/character_flaw/_character_flaw.dm
code/datums/components/rotting.dm
code/modules/client/preferences.dm

Tested.
Bugfix + no more zombification for DNR'd people.
First of two (three?) PRs i promised to do before i left. Cleaning up my recent PRs and finishing them up for good.

Fixes vice with DNR + DNR prevents rotting

---

code/__HELPERS/reagents.dm

Lib n dink
Rolls off the tongue smoother. Also reference.

Ligula / Ligulae -> Dram / Drams

---

code/modules/jobs/job_types/roguetown/youngfolk/prince.dm

fixes nettlesome scamp not getting declare champion
fixes nettlesome scamp not getting declare champion

fixes nettlesome scamp not getting declare champion

---

code/modules/spells/roguetown/acolyte/resurrect.dm
code/modules/spells/spell.dm
code/modules/spells/spell_types/mime.dm

ok so tl;dr the way invocations are done as much as i wanted to just add an [src] to the check doing so wouldve needed me to define a click thing and do a bunch of if/elses. this is a much simpler, much shittier solution until a real programmer can rework how emote invocations are done in a much, much better way.
tl;dr:
emote invocations are now constructed on cast from the [usr] and [chosen_invocation]. these can be formatted on a case by case basis as i did not want to turn All of it into red text at the start. if u want my honest opinion if we ever rework it we should make them produce blue or even purple text to emphasize magic shit but this is fine for now.
i also had to change how the mime spells work, but it works.
**...and my spellcheck is back in this pr, too. i don't know why. …

changes how emote invocations work (very shittily) and turns abyssor revive into an emote

---

code/modules/client/preferences.dm

Title explains everything!
Booted up my local. New slots appeared, old ones worked. Everything as expected.
We have players who need more slots because they cant stop making chars/have been playing for a long time now
After all, not all of us are ready to part with old characters in favor of new ones, preferring to keep slots as a memento.
And players saves weight like ~10KB which is negligible.

Increases max number of slots from 40 to 60

---

code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm

wtf was this for lmao. removes the language half elves gained through this esoteric proc if they were naledi
compiles and i ran a check u still get elven as a language
- removes sovl
- no seriously  this is so random what the fuck was this a reference to

removes celestial from naledi half elves

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm
code/modules/jobs/job_types/roguetown/mercenaries/mercenary.dm

- Oversight from the job refactor. They no longer get the 15 spellpoints meant for Hiero.
- Also Grenzmage is now in the subclass creen
Yeah

Vizier and Pontifex no longer get spellpoints.

---

code/modules/roguetown/roguemachine/bathmaster.dm

Ports https://github.com/Scarlet-Reach/Scarlet-Reach/pull/833 which make BMTreasury check around itself instead of in world. Will make a little dent in overtime / performance
Yah

Port Scarlet Reach #833

---

code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm

Ratwood 101 port claw hammer steel exploit.
Ratwood 101 port claw hammer steel exploit.
Ratwood 101 port claw hammer steel exploit.

Ratwood 101 port claw hammer steel exploit.

---

code/_onclick/click.dm
code/datums/components/crafting/crafting.dm

Addresses bug stated in  #4007, yeah reagent_containers was too general. Adjusts the check to reagent_containers/glass, should be ok now?
Also fixes that dual wield string to make sense to 3rd parties.
Swamp weeds drying now.

Bugfix bottle crafting exclusion + string fix

---

code/modules/clothing/rogueclothes/feet.dm

Remove shoes mat exploit.
Remove shoes mat exploit.
Remove shoes mat exploit.

Remove shoes mat exploit.

---

code/modules/admin/agevetting.dm

- Rename command to BC - Add Age Vetted
- Move it to Server Tab
Yep

Rename Add Age vetted and move tab.

---

code/modules/farming/fermentation_keg.dm

Lower skill gate for brewing to apprentice.
Lower skill gate for brewing to apprentice.
Lower skill gate for brewing to apprentice.

Lower skill gate for brewing to apprentice.

---

code/datums/stress/positive_events.dm
code/modules/food_and_drinks/food/snacks.dm

See title.
It's a mood buff of -1 for 5 minutes. Not too good but it's present. Fruits like jackberries or strawberries and such all work.
It works when I test it
SERVANT FEED ME MORE GRAPES I MUST WATCH THIS GLADIATOR FIGHT

Hand-feeding someone fruit now gives a minor mood buff.

---

code/datums/sleep_adv/sleep_adv.dm

Fix a bug where you can bank one more level than your cap allows.
Yes
Yes

Actually fix level up logic this time.

---

code/modules/admin/admin_verbs.dm
code/modules/admin/holder2.dm
code/modules/client/client_procs.dm
code/modules/client/verbs/who.dm

Adminwho actually shows up for non admin
Adminwho actually shows up for non admin
Adminwho actually shows up for non admin

Adminwho actually shows up for non admin

---

code/modules/roguetown/roguemachine/merchant/goldface.dm

We love copypaste
One line change
Fixes the bug

Fixes silverface bug

---

code/game/turfs/open/water.dm

* New town square. Moved Stewardry 1 tile east to accomodate this
* Adds back stall IV
* Small edits. Removed some town herb locations, unneeded wash bins and one dye bin.
the 1 stall that actually got used was mapped over with 2 fountains that exist to annoy your WASD travel as much as possible

changes the town square

---

code/datums/skills/labor.dm

Survival Expert actually ungate Fishing. Lumberjacking actually gated.
Survival Expert actually ungate Fishing. Lumberjacking actually gated.
Survival Expert actually ungate Fishing. Lumberjacking actually gated.

Survival Expert actually ungate Fishing. Lumberjacking actually gated.

---

code/modules/mob/living/simple_animal/rogue/game/drider.dm

Drider mount spiders are 1.5x scaled for no reason and it's kinda ugly. No reason for them to be. Also fixed up some possible typoes in the code - the proc that gave them sound was called goat, now it's properly labeled.
doesnt breaks hiut
its good

Fixes some drider weirdness

---

code/game/objects/structures/maneater.dm

Yes.
Fixes being chucked into a tree, back into a maneater to be ate again. No more pingpong.

Lets maneaters spitout on spot now

---

code/modules/clothing/rogueclothes/npc/goblin.dm

- makes goblin loincloths cover groin instead ofwhole body. i can now cut out hteir hearts.
- compiles and i punchjeda goblin and nothign b lew up
- why it do that.

makes goblin loincloths cover groin

---

code/datums/character_flaw/_character_flaw.dm
code/modules/jobs/job_types/roguetown/yeomen/archivist.dm

Adds a new vice, unintelligible.
It removes your ability to speak or understand imperial/the common tongue and by extension makes you unable to read as well.
If for some ungodly reason you decide to spawn with this trait and have no other languages selected, you just can't speak at all.
Archivist is the only job banned from taking this vice, since it sorta directly conflicts with a large part of their job.
Spawned into a local server, it works Goodly I Think Probably I Don't Know Maybe Test Merge It Or Something.
It's kind of like the mute vice, but more interesting. Instead of whole ass making you unable to speak, you just can't communicate in the common language.
Cool for playing foreign characters, I guess.

Adds new vice - Unintelligible

---

code/modules/jobs/job_types/roguetown/youngfolk/apothecary.dm

Apothecary can be any ages, instead of being locked to adult
This just make sense with the newest rewrite of the factor and the fact that AP's environment treats Apothecary as any town doctor instead of a leper that is always a youngling apprenticed underneath the head physician.

Apothecary can be all ages.

---

code/game/objects/lighting/_base_roguestreet.dm

adds a few changes to gethesmane to make it a bit easier/smoother to run. lots of tiny things but in short:
first off- changes the inn, adds a little backdoor patio that leads smoother into gethesmane (it still has medium quest marker spawns, i didn't add/remove any, just moved them so they arent spawning in trees)
adds a second entrance (doesn't actually bypass anything, u need to go back)
gives a little hint as to how to get to this area via the lil window and removes the door since it legitimately confused the fuck out of ppl, i don't think ANYONE figured this out without being shown/strongdmm
adds a backup entrance in case u Legit Can't Figure it Out
replaces some of the streetlights with the ancient lightbars (figured out why they gave opff the wrong color light lol)
rat pic …

more prettification/remapping of gethesmane, and lightbar bugfix!!
