_maps/map_files/dun_manor/dun_manor.dmm

The door on the NE side of town still was tagged with the mason keyid, which has been removed. To make the door useful, I assigned it to the smith ID so the artificer has an entrance and the smith - and the doors are named, for player facing help. A bit hacky, but we currently can't multi-key a door and there were two there anyway.
fix bug, also gives smiths a reason to even use their north facing doors. escape the line, quietly...

Fixes smith/artificer door

---

code/modules/food_and_drinks/food/snacks.dm

Adds a fork type check to ```/obj/item/reagent_containers/food/snacks/attackby()```
with a 0.5 second do_after to eat with a fork.
https://github.com/user-attachments/assets/f70bf58e-cf86-40d0-80af-4146a6af4293
Forks are currently non functional (I believe) this will allow you to keep food on the table and use a fork to eat it. I think it's neat.

Makes forks functional.

---

code/modules/roguetown/roguejobs/tailor/dyer.dm

Ever sewn a royal shirt, just to stare at the ugly purple color the Duke picked at the start of the round and that you are unable to now change? Ever regretted your pick of tabard colors and had to toss it away to find a new one?
Let me present to you: The Humble Dye Station.
Dye Stations will now show up an option for secondary color on applicable items. They will only display a primary color selection for clothes that lack this feature. I've changed the dialog a little so it's more condensed.
Customization is good. Being stuck with the duchy's colors as a foreign noble is bad, for example.

Dye Station can now change detail colors

---

code/game/objects/items/rogueweapons/melee/axes.dm
code/modules/jobs/job_types/roguetown/courtier/magician.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/steppesman.dm

Does three small fixes pointed out to me today.
- The battle axe was a short weapon, despite.. being a big fucking two-handed axe. It's now long. Should actually help it be viable for combat too now instead of a shittier longsword type.
- Steppesman had a regular undershirt while its speed-class counterparts had gambeson, or even heavy gambeson. This was likely forgotten about because Steppesman used to have crit resistence. (I guess it's balance-jak but - it's.. basic as shit.)
- Court magician had **no shirt** on round start for some reason. Gives this wizard a shirt so they stop flashing their associates. Our court does not need a registry......
Small collection of oversights, overall just QOL or seemingly forgotten/unintended/missing stuff fixes.

Small Collection of Oversight Fixes

---

code/__DEFINES/roguetown.dm
code/modules/jobs/job_types/roguetown/church/monk.dm
code/modules/jobs/job_types/roguetown/church/templar.dm

We have Ravox miracles now, so it's time for Acolytes... and we actually had Xylix ones, although they need sprites for the spell scrolls but it'll do for now.
Ideally all of the Ten get bespoke robes, but this'll do for now. With this, Acolytes are now completely covered. Hooray, hooray.
Update: This also adds Xylix templars. However, I have made the choice to rip the bandaid off; **Psydonian Templars were removed.** To the Inquisition with you, heretic.
release the fight and trick nuns

Ravox and Xylix acolytes edit: and templars

---

code/modules/jobs/job_types/roguetown/nobility/lord.dm

The Duke's 'Grant Nobility' spell now will:
- Give a text message saying you cannot remove nobility from foreigners instead of fail-casting spectacularly.
- Allow you to remove nobility from towners who take the noble virtue.
- Granting nobility will now REMOVE the outlander trait from those you grant it too, effectively making them no longer foreign.
Shores up the functionality.

Grant Nobility Bugfix/tweak

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/trader.dm

Adds the Harlequin, a new adventurer trader subclass. It's essentially a travelling jester.
They spawn with jester's clothing, an instrument of their choosing, a bag of dice, some playing cards, an iron dagger, and 3 smoke bombs.
None of the crazy z-jumper traits or unique spells that actual jesters get, sorry. The actual court jester should still retain some unique content - he's Xylix's top guy.
Variety. A new adventurer class with some unique flavor. Debated making this a towner class, but decided it might better fit the trader adventurer class. If people would prefer it as a towner class instead let me know in the comments, I guess.
i'm just a silly little guy

Harlequin [New Adventurer Trader subclass]

---

code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm

A few people requests half-elves to have dark elf skin tones, so people could roll half-drow. Luckily for them the skintone defines is just a repeat, huh?
The names of the identities are a little lazy, admittedly, but they work and I don't really want to play various References underneath Otava or whatever.
now people can be half racists

adds dales lazily

---

modular_azurepeak/code/modules/spells/pantheon/inhumen/zizo.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

got asked to do so because exactly what i thought would happen happened apparently. 
im kinda annoyed about this not because the spell or even that it got merged but players felt negatively about it but didn't voice it despite - talking about it in the discord, getting buried, for ages. but w/e, that's the literal norm for ss13 servers.
can search the word 'recall' and see how many complaints it got so fast.
recall isn't great for the game. it has no counterplay, allows across-the-map teleport, the suggestions and requests given on the pr such as casting time, etc weren't taken into account, etc.
if someone plans to fix it instead of revert, go for it - im just not really wanting to fix this rn, i kept the code in, just commented it out so maybe could get future use as something else (or …

Reverts Recall Spell

---

_maps/map_files/dun_manor/dun_manor.dmm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Blink clean-up and fixes.
- Prevents blink from being used through bars, passageways, and shutters. The last PR that tried to do this used the wrong path for bars.
- Prevents blink from allowing you to teleport onto the same tile as doors/bars/windows, which wasn't really much different from just teleporting through them.
- Changes the keep gatehouse to use stone windows rather than adding a separate check for the grilles - grilles aren't even supposed to have density and this is the only place where grilles are even used like this across the entire map.
- Raises cost to 2 points, as Blink is essentially a straight upgrade to the Leap spell since it can be used to teleport across Z levels.
- Charge up time is slightly longer to give other players a chance to react to the spell channeling. …

Blink fixes

---

modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Bugfix. I missed the 3 tile wide gates (like the ones used in the throne room and several dungeons) in the last blink patch. This is hopefully the last PR I have to make related to the blink spell.
Consistent behavior. Blink isn't meant to allow you to phase through dense structures such as walls, windows, bars, shutters, gates, etc.

Blink can't go through gates anymore

---

code/modules/roguetown/roguejobs/miner/rogueores.dm

Prevents tongs from interacting with things inside bags.
to prevent this: 
(you can pick out ingots from inside bags with tongs and it pulls out the entire grid making it uninteractable)

Tongs no longer take things from bags

---

code/datums/status_effects/rogue/roguebuff.dm
code/modules/antagonists/roguetown/villain/vampire.dm
code/modules/mob/living/roguetownprocs.dm
modular_hearthstone/code/modules/spells/roguetown/buffs.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm
roguetown.dme

- Guidance: Adjust Guidance cost to 1. Guidance now applies +15% and -15% (About equal to one skill level) to both dodge / parry bypass, instead of only parry and only 10%. Cooldown reduced to 2 minutes.
- Haste: Cooldown standardized to 2 minutes instead of 1.5 minute (It is the strongest of the 3 main combat buff spells). 
- Fortitude: Fixed it applying the vampire Armor of Darkness effect giving player 20 END & CON for 30 seconds. It applies the original, intended buff of * 0.5x stamina cost. Cooldown standardized to 2 minutes.
- All three of the above abilities has a duration of 1 minute when cast on self, 2 minutes when cast on others now to encourage support
- The buffs and spell now indicate what it does
- The spell list for wizard is now sorted
Sorted spell list good. 
Right now …

Buff support spells. Add overlay & fix Fortitude.

---

code/modules/clothing/rogueclothes/armor.dm

This PR standardizes the Brigandines to be pegged off the coat of plates standard. In the brigandine's case, it's slightly beefier due to the extra layers of fabric.
Brigandine is the worst heavy armor due to being powercrept out by the coat of plates, but not standardized up to it's level. This fixes that, and should make the gamefeel of using the brigandines better.

Brigandine Standardization Passover

---

code/datums/status_effects/rogue/roguebuff.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/emote.dm
code/modules/spells/roguetown/jester.dm
modular_azurepeak/code/game/objects/effects/temporary_visuals/music.dm

Those who worship Xylix receive a +1 Fortune buff for 5 minutes whenever they hear another person laugh or play music, as these are Xylix’s gifts to mortals. However, this effect does not trigger if they themselves are the one laughing or playing music.

Xylix passive - Trickster's joy

---

code/modules/clothing/rogueclothes/feet.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/routier.dm

Seems like Otavan Boots have no way to be repaired! No anvil nor needle will fix it. This, of course, fixes it!
Also - Otavan Routiers are meant to be a sort of noble knight mercenary company, and yet they can't ride for shit whilst Forlorn (for example) gets 1! They can get 2. Lower than Riders (3), more than Forlorn (1). It's nice.
I think the leathery thing that is made out of leather like the other leathery things should be able to be repaired.
And a knight who doesn't even have an IDEA how to ride, sucks ass. Give them a bone.

Give Otavan Routiers Apprentice Ride + Fix Otavan Boots

---

code/modules/jobs/job_types/roguetown/nobility/knight.dm

Bugfix. Heavy knight no longer applies shared knight class traits twice.
Shared traits are supposed to be applied on the base knight class rather than on each subclass. I missed heavy knight's traits, somehow.
This doesn't really have any effect on gameplay because traits don't stack anyways, it's just code clean-up.

Heavy knight no longer applies duplicate traits

---

code/modules/roguetown/roguemachine/bathmaster.dm

Applies a nerf to the Bmaster vault, which was apparently rather readily becoming richer than the court. Should still be a powerful tool, just maybe not -as- strong. Done by request of original commissioner
BMaster probably shouldnt be **that** rich.

Bathmaster vault income from 30% ->20%

---

code/modules/mob/living/roguetownprocs.dm

Move guidance check on dodge before mobility check
Someone pointed out I put the guidance check on dodge after the mobility check instead of before on parry. This fixes it.

Move guidance check on dodge before mobility check

---

code/modules/roguetown/roguejobs/engineer/prostheticarm.dm

- Bronze left leg and left arm had 20 max_damage instead of 110 that right arm / right leg had, same as wooden. Clearly not intended. Changed to 110
Ends bigotry against left leg and arm.
Chopped myself left and right arm before and after code changes

Fix bronze left leg and arm max damage

---

code/modules/mob/living/carbon/update_icons.dm
code/modules/mob/living/living.dm

Fixes your pixel shift being reset to the middle of the tile while you are debuffed
<details>
<summary>Before/After</summary>
**Before:**
https://github.com/user-attachments/assets/a2d144e1-6455-4423-bec1-8423d5fc8347
**After:**
https://github.com/user-attachments/assets/63e01cd2-a54f-4e78-9fb1-75902c3ca8a0
</details>
its a bugfix

Pixel Shift Bugfix

---

code/game/objects/items/rogueweapons/ranged/crossbows.dm

Crossbows used to have damfactor = 2, but it was lost in https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/commit/471d6bac4d3240ec4eae0bf6e8c3b3da1d61c355#diff-6aca19292fd895d88e8bbd1876a467d1e45af87c2c19075de9ce0b1957b50356
This readds it.
Longbows are pretty superior to crossbows without this. The old balance world used to have knights carrying crossbows with one bolt for toe-poppers, let's hope that doesn't crop up again. More snowflake nerfs on the horizon to deal with it.

Readds crossbow damfactor = 2 that was lost in debloat

---

code/modules/mob/living/grabbing.dm

1. Graggarites can now drink blood, they no longer get sick from player blood.
2. They also actually get hydration from it, both from players and carbon mobs.
3. Also makes blood drink *slightly* more lethal. Draining 15 blood rather than 5. This isn't like, hyper lethal. But now you can actually suck someone dry if you drink them alot, rather than it draining so little that it had no effect. Still nothing compared to the VLORD 45 blood drain, but usable for dramatics.
Commissioned by mashimashers
Blood for the blood god.

Graggar blood drink

---

code/datums/status_effects/rogue/roguebuff.dm

- Deletes the redundant definition of guidance & fortitude that was causing a warning. This was merged in with the Vizier Rework, oops.
Warning is bad, and redundant definition is bad.

Delete redundant definition of guidance & fortitude

---

code/game/objects/items.dm
code/modules/roguetown/roguejobs/cook/tools/pan.dm

- Add an associated skill to frying pan: Mace
- Allows people to inspect frying pan as a weapon
- Add the associated skills to all weapon inspection.
- Change frying pan w defense from 5 to 1 to match the lowest tier club (Wooden)
Let people actually see what skills is used to use a weapon and stop spreading misinformation (Frying pan was NOT associated with any skills and it keep spreading on the discord)
Frying pan is a weapon and giving it inspect helps reinforce that.
Also, this is funny.

Mace skill, inspect for frypan. Add skill to weapon inspect. Wdefense to 1

---

code/game/objects/items/rogueitems/needle.dm

The Sewing repair action is set to repeat itself in the same fashion as the blacksmith's hammer repair action.
Tested: Attacked a shirt with an axe then repaired it from broke to full with a single click on a low sewing skilled character. 
Sewing repair is tedious, especially on lower skill levels due to needing to manually initiate it every single time, it just means dozens of extra clicks on something that's random chance anyway. This will atleast automate most of the tedium.

Sewing Repairs will automatically retry if the item is not fully repaired.

---

code/modules/clothing/rogueclothes/feet.dm

- You can now slot tossblades into boots, and remove them by right clicking. 
Commissioned by dongwaiver
Boot knife! Boot knife! It's Neat. Kinda just gives a little use-case for people to carry *a* tossblade if they aren't necessarily wanting to carry an entire belt, a little Thing:tm:.

Tossblades in Boots

---

code/modules/clothing/rogueclothes/quiver.dm

- Add an examine text to a quiver saying you can pick up ammo from the floor
Originally wanted to add this feature only to realize it actually exists and no one knew about it. What the fuck.
Document an important feature.

Add instructions to pick up ammo on the floor

---

code/game/objects/items/rogueitems/needle.dm

- Squire repair trait applies to sewing / repairing armor
- Squire can't fail to repair light armor (I think)
- Same effect as having 3 levels in skincrafting + sewing combined, just for repair
Light armor are used by the Keep a lot and it seems odd that squires can repair weapons + armor but not clothes.

Squire repair applies to sewing too

---

code/modules/mob/living/carbon/human/examine.dm

it was indented inside a block that only runs if someone's face isn't covered. see:
```dm
if(obscure_name)
. = list(span_info("ø ------------ ø\nThis is <EM>Unknown</EM>."))
else
// it was in this block
```
the fix is to move it later.

Fix Eyes of Matthios not working for mobs with obscured faces

---

code/modules/clothing/rogueclothes/hats.dm
modular_azurepeak/code/game/objects/items/ritualcircles.dm

Buffs priests by letting them use the Astrata ritual without bursting into flames. Other Astratans using the ritual still burst into flames, as Astrata intends.
I believe this ritual was pitched with the idea of a % risk of bursting into flames, but the Priest/notPriest risk seems fair now. 
Throws the Priest a gimme that they can light up the area without having to jump into the water or have a bucket on standby.
Fun fact, this is the 2nd use of the Chosen trait. The 1st was the Priest's vestments. The Solar Visage was using a job check, so, moved that to check Chosen too. Now there's 3 checks for Chosen, yippee

Adds check for Astrata ritual that doesn't burn priests

---

code/modules/mob/living/carbon/human/species_types/furry/vulpkanin.dm

Small one line tweak for Vulpkian. Description says they get +1 int and +1 per and now they actually do instead of getting +2 int.

Vulp race stat bugfix

---

code/game/atoms.dm
code/game/atoms_movable.dm
code/game/objects/buckling.dm
code/game/objects/items.dm
code/game/objects/obj_defense.dm
code/game/turfs/open/lava.dm
code/game/turfs/open/water.dm
code/modules/mob/living/carbon/carbon_defense.dm
code/modules/mob/living/carbon/human/damage_procs.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/human/update_icons.dm
code/modules/mob/living/carbon/monkey/combat.dm
code/modules/mob/living/carbon/update_icons.dm
code/modules/mob/living/living_defense.dm
code/modules/mob/living/simple_animal/rogue/game/saiga.dm
code/modules/mob/mob_helpers.dm

Fixes throwing not dealing damage. Long story but basically Vanderlin fucked it so it'd only create wounds and not deal damage bc it expected `BRUTE` but got `blunt`.
Small optimisation to `generate_icon_render_key`, not a huge deal but will be kind of helpful I hope. Avoids unnecessary string concatenation operations that can be slow due to string tree rebalancing taking for-fucking-ever.
Fixes saigabucks not taking damage from projectiles/thrown weapons. Also cleans up saiga and saiga buck code. I made sure to test the dismount thing.
Fixes and improvements. This will let Rebel make throwing weapons that pierce only when thrown and not used as melee weapons I hope.

Fix issues with saiga bucks and throwing damage

---

code/datums/migrants/migrant_waves/heartfelt roles.dm
code/datums/special_traits/traits/traits.dm
code/modules/cargo/packsrogue/wardrobe.dm
code/modules/clothing/rogueclothes/feet.dm
code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelt.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelthand.dm
code/modules/jobs/job_types/roguetown/adventurer/types/special/whitecheesemaker.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/routier.dm
code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
code/modules/roguetown/roguecrafting/leather.dm
modular_azurepeak/code/datums/loadout.dm

For some reason, otavan routier boots(and Inquisition boots) were never actually pathed as boots. Making them not work with the tossblade change.
EDIT: Also fixed noble boots
Proper Pathing

makes inquisition boots a boot subtype

---

_maps/map_files/dun_world/dun_world.dmm
code/game/objects/items/rogueitems/keyrings.dm

Repost of #1985 with request changes from maintainers because I accidentally fucked up my branch.
Removes armory and garrison keys from the wardens key ring. They probably shouldn't be hanging around in the keep or taking equipment from the keep. They still get keys to the city walls and their own watchtower.
Mapping changes are just changing the doors on the city walls to actually use the 'walls' key - which wasn't used anywhere previously.
There's no real reason for wardens to have access to the garrison building and the armory. They already have their own barracks and their own mini-armory filled with spare equipment in their watchtower anyways.
They don't currently even have access to the keep gatehouse to reach the armory (they don't get manor keys) which means they already either …

Warden keyring adjustments

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/atgervi.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm
html/browser/slop_menustyle2.css

Fixes subclass preview hover-over text. The black background should appear properly now even on newer byond versions.
Also adds subclass preview descriptions for most of the mercenary classes.
🐛 Bugfixes 🐛
Launched local host, spawned as several different roles with subclass previews. Hover-over text backgrounds seem to be working correctly.
https://github.com/user-attachments/assets/6684d217-f05d-41c9-b67c-7d40dab6bc74

Fixes subclass description previews

---

code/modules/jobs/job_types/roguetown/adventurer/wretch.dm

Gives Wretch deserters a saiga on spawn and more diverse weapon skills.
Currently, the heretic wretch subclass is just kind of a straight upgrade to the deserter subclass - with the same heavy armor and the same weapon skills, but with miracles thrown on top.
This was an oversight on my part when designing the classes and this PR gives deserters a small buff so that heretic is no longer directly better in every way. 
To lean into them being former knights, they now spawn with a mount. Similar to knights, they also now get multiple expert weapon skills, meaning they can swap between different weapon types in-round regardless of what they choose to spawn with. A former knight having training in a variety of weapon types makes sense.
This probably doesn't make them /that/ much stronger than …

Small wretch deserter buffs

---

code/modules/jobs/job_types/roguetown/yeomen/tailor.dm

Gives tailor job selection text as it was the only one without it.
Feels like an oversight so getting rid of it is good.

Tailor Selection

---

code/game/objects/items/rogueweapons/melee/polearms.dm

Remove the swing delay on halberd's cut intent
Halberd is the archetypical guard weapon and a mainstay of this time period. It should be versatile. 
Also the chop intent on halberd is 100% superior with 1.0 damfactor, 8 swingdelay instead of 10, and 30 pen. This is inconsistent with most weapons where cut is the fast, no delay option and chop is the stronger, delayed option.
But it is just completely out of the meta because of a 10 swingdelay which no other cutting polearm has - it already has lower cutting damage so this is just plain unfair. This removes the swingdelay so halberd is a viable weapon.

Remove swingdelay on halberd

---

code/modules/clothing/rogueclothes/storage.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

- Tossblade belts can now be reloaded with iron tossblades, fixing a type bug.
- Repulse and Mind Link no longer require LoS to use, making repulse feel a lot better in a tight situation.
Tested.
Fixes bug and restores spell use/feel.

Two simple fixes to tossblade/spellLOS

---

code/datums/status_effects/rogue/roguebuff.dm
code/game/objects/items/rogueitems/natural/stones.dm
code/modules/mob/living/carbon/human/species_types/roguetown/construct/constructm.dm

Allows constructs to munch down on magical rocks for wound/break/crippling healing. Wondrous.
Also makes them TRULY bloodless, and fixes them having insomnia because they lost it when the sleep changes got added. 
_I'm so fucking hungry...._
Constructs are rather unplayable due to lack of healing from miracles (and wont be able to fix breaks without sleep, which is getting taken from them once more.)

ROCK MUNCHING AND CONSTRUCT FIXES

---

code/modules/jobs/job_types/roguetown/nobility/knight.dm

Allows Royal Champion to select the other knight helmets. These helmets are not actually classified as heavy armor mechanically, so they would be wearable by anyone. Squires will often go to the smith to get one made in a round. They aren't particularly better than the current selection of helmets either:
`armor = list("blunt" = 90, "slash" = 100, "stab" = 80, "piercing" = 50, "fire" = 0, "acid" = 0)` for /heavy/ helmets (Armet).
`armor = list("blunt" = 90, "slash" = 100, "stab" = 80, "piercing" = 40, "fire" = 0, "acid" = 0)` for the visored sallet RC already can choose.
.
May as well just give them the same helmets as knights all get. It's more or less just a personalization choice.
(True Psydonians wear the Armet)

Royal Champion Knight helmets

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm

Gives a KNIFE to the only _warrior_ class that doesn't starts with one, and it should. (DUELIST)
Particularly the parrying steel dagger, doesn't really adds much to the class but at least gives them a secondary weapon that fits them and makes sense.
Just that :)

Dagger for the Duelist

---

code/modules/spells/roguetown/_roguetown.dm
code/modules/spells/roguetown/necromancer.dm
code/modules/spells/roguetown/wizard.dm
code/modules/spells/spell.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

I AM NOT CALLING IT SOMATIC. 
A redo of #1555 with a more limited selection of spells. Now, all projectile spells, and a few selected offensive / mobility spells requires your hands to be free to cast. 
The follow spells requires gesture (hands free):
- All projectile spells (fireball, bolt of lightning, arcyne bolt, frost bolt, repel, profane etc. etc. etc.)
- Necromancer's: Bone Chill, Eyebite, Raise Greater & Lesser Undead (Summon spells are pretty offensive)
- Some Mobility Spells: Blink & Leap
- Some Offensive non-projectile spells: Blade Burst, Snap Freeze
This should cover the ground of most spells that directly harm people = can't be cast while chained. You can still send out a message or mindlink to call for help or turn your invisible or buff someone if you want. 
I also noticed …

Make some spells requires uncuffed hands

---

_maps/map_files/dun_world/dun_world.dmm

Reworked the merchant shop so that everything is more cohesive in the spots they're in, and there's not 300 keys spread all over the place. Plus: no more ladders.
Map in StrongDMM:
<details>
</details>
In-game testing:
<details>
</details>
Begone, ladders from hell. Rejoice, shophands, for now you have a bed.

Map Update | Merchant Shop Rework

---

code/modules/mob/living/carbon/carbon.dm

- You can no longer stun someone by throwing them into a wall unless they're already off-balance.
- You can no longer throw someone up(who's in cmode) if they're not laying down
Basically just adds back in some stuff from https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/344 that I suspect was removed during debloat on mistake.
https://github.com/user-attachments/assets/f033bad2-1f6a-475e-8aea-1a15e8387e3d
https://github.com/user-attachments/assets/5013cc2a-8b79-4ce4-9425-0a362fb668c5
https://github.com/user-attachments/assets/8bfe62fa-a07e-4a90-94da-ba5b524dc6a8
I tire greatly of seeing people infinitely chain-stunned on a wall or instantly having their legs broken.
Permastuns are insanely bad and were already removed once: …

No more wallbangs/combat uppies

---

code/modules/mob/living/living_defense.dm
code/modules/mob/living/simple_animal/animal_defense.dm

Currently, whenever you shoot a simple mob, your arrows / bolts / slingstones get devoured because shitcode.
This is because of a snowflake override on bullet act and embed. The simple embedded system is untested and unused (disabled for melee). This PR:
- Remove the snowflake bullet_act (Arrows no longer disappear)
- Disable projectile embed on simples (a lot of simples weren't designed with them in mind anyway)
Tested vs volf, saiga (no embed), tested vs goblin - embeds worked correctly due to override.
Arrows disappearing on half of the mob type isn't fun

Disable projectile embed on simple, 2.0

---

code/__DEFINES/roguetown.dm
code/modules/jobs/job_types/roguetown/nobility/lord.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm

Was asked by lore team to do this PR. Simply makes the Duke and princes/princesses not be able to be Psydonites.
Makes sense from a lore point of view, given this is an Astratan duchy where the monarch is given the right to rule through Astrata. Plus inhumen believers are little cretin liars unlike Psydonians.
(Psydon is dead........ And lore killed him......)
Greys out selection from class selection, doesn't appear on late-join as Psydonite. Works for Ascendants/Divine
Lore stuff; I can see why given people want a stress-point between the Inquisition and the Monarchy rather than being chummy. Plus, a Psydonite rejects the divinity - and thus right-to-rule - blessed by Astrata reasonably.

(Lore Request) No More Psydon Monarchy

---

code/game/objects/items/rogueweapons/melee/polearms.dm

This pull request reverts the changes done to polearms in pr #1762 as the proposed changes to bring swords up to the same kind of durability in #1885 were denied. As is, polearm durability is the result of a PR that was meant to go through with others as to not upend balance, and should be reverted until a proper larger PR that can implement these changes properly can be done, rather than a half approved piecemeal update.
Code compiles localy, changes are direct reverts
Polearms are high defense dual wielded weapons that are meant to parry attacks. The previous PR that increased their durability acted like an important buff to polearms, which was supposed to be counteracted by increasing the durability of other weapons in return.
These changes did not go through, and as it stands, …

Revert polearm durability changes

---

code/modules/jobs/job_types/roguetown/garrison/veteran.dm

An expert lockpicker without their tools? A former spy, described as having been an assassin and neutralizing enemies, not being able to tell the difference between ale and Instant Death Poison?
This fixes that.
Launched the game. Looked at my roundstart killersice bottle. Jingled my lockpicks.
Small oversight? It makes sense for them to start with these, and they don't really get much else gear-wise.

Tiny Ex-Spy Veteran Addition - Gives them a lockpick ring, Cicerone trait

---

_maps/map_files/dun_world/dun_world.dmm

Removed the floating door next to the stewardry third floor. Also added more lights in the merchant place.
Before:
After:
I almost had a heart attack when I noticed this bug.

Fix | Floating Door 

---

code/game/objects/items/rogueweapons/melee/polearms.dm

so uh. turns out the zweihander was just the greatsword with 100 less integ and 1 less defense
also the steel and iron zweihander were identical
what this does is give the zweihander a whole 5 (up to 35!) more force in exchange for having 1 less defense compared to the sword. (10% parry chance)
this also gives the steel zweihander 100 more integ, to be equal to the greatsword
<details open>
<summary>how I'm going to convince luto to merge this</summary>
<be>
PLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASE
i put more time into this drawing then the actual pr.
</details>

SHAMELESS ZWEIHANDER BUFFS (im sorry)

---

code/modules/jobs/job_types/roguetown/yeomen/merchant.dm

Merchant loss alchemy, which means it lost the ability to see reagents inside bottles. For the sake of wines and whatnot, good to give it back to him.
I hope this trait works, I coded it
Merchant shouldn't be sweat grinding alchemy, but knowing what is in bottles is good business.

Gives merchant Cicerone trait

---

code/game/objects/items/rogueweapons/melee/swords.dm

Turns the 5 swing delay on 'pommel strike' to 0. This makes the strike instant like stab or cut. Damage multiplier from 0.8 to 0.6. AP from 20 to 50.
Tested by beating several bums to death. Works as intended. Common helmets have blunt crit resistance so you're not going to get randomly knocked out if you're smart (even bandanas? wtf?). #EpicWin
Pommel strike would normally be a blunt equivalent to stab, but it has a 0.8 damage multiplier on top of swing delay. Having used it in duels and fights, you're better off using any other intent. I'd like to see it used more. I'm happy with the damage multiplier staying (and I have made it more severe), but swing delay combined with the current power of the intent gives people very little reason to use it.

Removes pommel strike swing delay, lowers damage, increases AP

---

code/game/gamemodes/roguetown/roguetown.dm

Minimum amount of bandits that can roll at 20 readies is now 3, increasing by 1 for every 5 players readied past 20, with a max of 5 bandits
Needs a TM in ensure proper working order, since I don't have 30 pop on my local server

lowers bandit slots that can roll.

---

modular_azurepeak/code/datums/loadout.dm

Byond apperantly doesn't like spaces in the name. (?)
Can't test it really beyond knowing adding 'Rebel0' lets me choose it on loadout but player this was intended for says on live-server he couldn't get it. Forgor to push this till now.
Yeah.

Fixes Donator Item

---

code/modules/roguetown/roguemachine/scomm.dm

Messages from crownstones in the garrison-line are now larger than those from regular SCOMs.
Makes for good differentiation between `head roles` and `non-head` when it comes to the garrison. Relieves a lot of the text mash, good to lead during busy incidents.
Since the text is tied to the crownstone. This won't give away people who've stolen one (and may even legitimise stolen crownstones in a way). Automatically is only for head roles since thats all who get the crownstone.

Crownstones speak louder

---

code/modules/clothing/rogueclothes/hats.dm

Shit was bromken, figured out why. Added a little tag for future use if people need to hide EVERYTHING on an adjust, unlike most hoods that now allow for snouts to show through.
https://github.com/user-attachments/assets/53cbf19f-616a-4882-b417-98a25b1ea842
onmob fixup
Don't ask me what black hole their snouts get sucked into. Someone needs to sprite some snout-alts for a lot of masks, but hell if it'll be me.

Fixes the Keffiyeh to Adjust Properly

---

code/modules/mob/living/carbon/human/human.dm

Title. The one being climbed on needs their cmode off to be piggybacked onto.
I didn't test this but this should work (famous last words)
Prevents piggyback cheese during grapplefights

Prevents piggybacking when the piggybackee has combat mode on

---

code/game/objects/items/rogueitems/needle.dm

Fixed up the code where if you have more than 30 skills it get turned into 30 (like if you took hunter's apprentice as squire), sutures pointed this out. 
also removed the sewing time boost, suffer if you're not skilled.
(this is with to chat code added)
Taking hunter's apprentice is worth it on squire.
debuff repair speed of squire a tiny bit (it doesn't matter) if they don't have the skills

Tweak + fix for squire needle repair

---

code/_onclick/item_attack.dm
code/modules/mob/living/roguetownprocs.dm

- Fixes unarmed parries(They actually work now). Removed a unused part of item_attack.dm which seemed to be the sole thing breaking them. 
- Unarmed parries now scale at 30% per point of unarmed, compared to 20% with every weapon skill. Statistically, this means, you basically have 1df per point of unarmed. So, a expert unarmed fighter will have a total 120% parry chance, brought down to 40% by any other expert weapon user. Making them have worse than having an actual weapon, but still better defense than before.
- You only get 30% per point if you have bracers on, otherwise, you only get 10% per point, meaning a measly 40% at expert, easily negated by any weapon user.
- You will use unarmed parries if its df calculations somehow beat out whats in your hands. So, you can fight with chairs …

Fixing unarmed parries[Pls TM first]

---

strings/laws_of_the_land.json

Basically just redid the Humen Supremacy law into a religious supremacy one; instead of encouraging racial genocide as it was previously worded. (Maybe should just disable it entirely, but I feel the new wording is better.)
Disabled the US constitution lawset from rolling. Doesn't make sense even given time period or setting, plus people felt it was too out of place and requested it be removed in a decent number. Thus the reason for this PR in the first place.
Generic lawsets are pretty eh anyway, it feels weird to have meme lawsets roll and expecting people to follow them. This tries to fix the racial genocide lawset and the US constitution lawset. Should be a bit more 'immersive' and less stupid now.

Generic Lawset Changes

---

code/modules/roguetown/roguecrafting/alchemy.dm

Remove stone mortar and pestle from alchemy lab recipes
It was always weird that you have to separately make mortar and pestle. Let's just assume the lab's fully equipped already.

Remove stone mortar and pestle from alchemy lab recipes

---

code/modules/roguetown/roguejobs/gravedigger/tools.dm
code/modules/roguetown/roguejobs/miner/tools.dm
code/modules/surgery/bodyparts/bodypart_wounds.dm

Bugfix that makes ghetto surgery tools actually work and removes !FUN! exploitable smelting for the stone pickaxe.
- Adds flags for improvised hemostat and retractor to their embed states, enabling additional steps of surgery.
- Adds the TOOL_SHOVEL to the shovel as was intended, it is now the saw replacement for surgery.
- Makes the stone pickaxe not equivalent to the iron pickaxe, updates the force to not be inherited.
- Removes an age-old bug to smelt the stone pickaxe into steel bars.
- Makes iron pickaxe wield able so it's not the odd one out.
Now tongs properly works as a clamping tool, a stake works as a retractor and a shovel works as a saw for all your foul mending in the wilds without boring miracles.
Stone pickaxes are no longer the solution to the riddle of steel.
Tested that …

Ghetto surgery and stone pickaxe double bugfix power hour.

---

modular_azurepeak/code/game/objects/items/gwstrap.dm

Due to the gw straps not working with the axes from my other PR I looked at the code and sighed.
TL;DR of what this does: 
-Great weapon straps can hold a greater variety of options and the repeated OR checks they had was cleaned up.
-Great weapon straps will also show the name of the weapon they're carrying in parenthesis.
Longer read:
I noticed that the code for how they handled things was a list of repeated OR checks for several weapons.
This PR refactors it to now contain any object which is a subtype of rogueweapon AND has the weight class of WEIGHT_CLASS_BULKY.
To summarize what WEIGHT_CLASS_BULKY does, is it disallows the weapon from being able to fit into containers. Essentially, any weapon which will **not** fit into your bag will now fit onto a great weapon strap.
This means …

Great Weapon Strap Refactor [Ready]

---

code/modules/mob/living/carbon/human/npc/skeleton.dm

Round start bog guard skeletons throw runtimes trying to touch a null mind. This adds the H.mind check, as per usual.
These need to be offloaded to some sort of spawner, maybe.

if h mind sanity for runtimes in skele bogguard pre_equip

---

code/game/objects/items/rogueitems/natural/feather.dm

Uses the initial name of a weapon instead of the renamed renamed renamed name when feather rename..
It is a bug and prevent cursed weapon with extremely long name

Fix feather renaming

---

_maps/map_files/dun_world/dun_world.dmm
code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm

Adds a SCOM to the bathhouse to remove a dead zone in the main bathing area, at the request of a veteran bathmatron player. Doesn't impact any of the private rooms at all.
As a bonus, also fixes a typo I noticed while making a debug character. 
SCOMs encourage town players to interact with each other by providing updates on the events in town. The bathhouse can be isolating as it's underground and a bit out of the way, this will alleviate that a bit. Players who do not wish to hear the SCOM in the bath can simply mute it.

Adds a SCOM to the bathhouse. Fixes a typo.

---

code/game/objects/lighting/_base_roguelight.dm
code/game/objects/lighting/lantern_post.dm
code/game/objects/lighting/rogue_fires.dm
code/modules/roguetown/roguejobs/blacksmith/smelter.dm

- Port Ratwood #2698 Infinite Fuel Fix.
- Also changes the alert text to "Yes" or "No" instead of Fuel / Smelt, because Smelt gives you the idea that you will smelt it instead of fueling it when it is a cancel. This is applicable to items without smeltresult.
- Item are also dropped and fed to the furnace when smelted. This prevents a 4x coal exploit doable by spam clicking the Great Furnace.
- Add a check to prevent fueling torch holders etc. that cannot be fueled.
bug & exploits bad

Port Ratwood #2698 Infinite Fuel Fix + Great Furnace Exploit fix + No refuel check

---

code/game/objects/items/rogueitems/natural/clothfibersthorn.dm

Add a value of 2 to fiber, 4 to cloth.
- After 10,000 debate about stockpile this keep getting brought up that cloth / fiber has no value and is not exportable. Turns out it exportable by steward but it does in fact, have no value.
Value based on the normal export value (2.4 each for fibers and 4 for cloth before supply  / demand reduce)

Add sellprice to fiber and cloth

---

_maps/map_files/dun_world/dun_world.dmm

Removed a floating manor key from the wall. Also gave both a greatweapon strap.
Uhh Bug Uhh Squash Uhhh
Re: the greatweapon strap, it saves the headache of getting one if they decide to ask for a larger blade down the week.

Map Fix + Other additions | Marshal + GC Room

---

_maps/map_files/dun_world/dun_world.dmm

- Discovered an extra dark wood window hidden beneath one of the reinforced windows and removed it. 
- Also noticed that the corner of the basement was showing from the outside.
- Made the basement one tile wider and looped the unpickable rock around it.
No visual mistakes now that the map around the witch hut is bigger than it was in Dun_Manor. :]

Teeny Witch Hut fixes

---

code/controllers/subsystem/migrants.dm

Court agent appears in the actors tab as "Name as Adventurer".
Seems like an oversight that this isn't already the case. Either way it makes it easier to tell when a character you want to RP with is on.

Court agent appears in the Actors tab (as Adventurer)

---

_maps/map_files/dun_world/dun_world.dmm

Adds shutters to the smithy back windows. That's it. That's the PR.
Simple change done in strongDMM, I ensured each shutter corresponds to each side levers.
Privacy gud. Also a request from a smith player.

Map Update | Smithy Privacy Shutters

---

code/modules/surgery/surgeries_hearth/revival.dm

When someone uses lux to revive you, you get a prompt.
Logged out people can't be revived.
Some people just want to stay dead.

Adds a DoNotRevive prompt for dead being revived + ZZ'd people can't be revived

---

code/modules/clothing/rogueclothes/cloaks.dm
code/modules/clothing/rogueclothes/feet.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
modular_azurepeak/code/datums/loadout.dm

The tailors within azure peak have learned how to sew pockets onto tabards and other such clothing! 
-Tabards/surcoats/stabards now have pockets.
Means that you do not have to compromise your drip for that extra smidge of storage.
-Added psicrosses to loadout!
Represent your faith without having to be a templar or an acolyte.
-Some minor fixes (removal of a defunct anvil recipe and making some footwraps inline with each other)
Less need to compromise style and storage. Anyone who decided to give up a cloak for their colors would lose out on that tiny bit of pocket space for storing their hardtack and flask of red. I believe they should have some
Otherwise, loadout psicrosses are there for people who wish to represent their faith without needing to find or be given one. For those who carry …

Pocket Additions to Tabards (And some minor stuff)

---

code/controllers/subsystem/rogue/role_class_handler/class_select_handler/class_select_handler.dm

This one was a doozie that we hunted for a week, shameful I know. The "last option" on advjob menus was getting cut off mysteriously. After tracking it down, it turns out the KEY, iteration loop to populate that menu, could be lowered by class restrictions; but there was no mechanism to raise it up again. So if Adventurer has nominally 7 slots. And Construct joins, which removes Noble, which brings it to 6. The KEY would be stuck at 6 forevermore for all other joining as that jobslot, which meant the last of the 7 (warrior) would be cut off.
This enforces the KEY to be the same length as the valid classes list, which should resolve that collision. The whole class_cat_alloc_attempts system was back when you only had slim pickings of random choices in RT, and we short-circuit it by raising …

Fixes disappearing advanced class options (hopefully)

---

code/datums/status_effects/neutral.dm
code/modules/projectiles/projectile/magic.dm
code/modules/spells/spell.dm
code/modules/spells/spell_types/touch_attacks.dm

Admins reported a bug that happened with Mage Overhaul 1 where spells would red out permanently. It turns out this is because of an edge case with charge_max being set *above* the current charge counter, on a fully charged spell, where recharging = false.
This removes the recharging variable and also moves the int scaling bloc outside of process to start_recharge() instead
(Funnily enough, you can just fix this by clicking on the spell anyway which start a recharge)
I replicated the issue once locally with Baotha's Blessings - when itr expired my Baotha's Blessings redded out. Haven't been able to replicate it with this fix.
Fix this shitass code so I can add more bloats.

Fix int scaling breaking recharging by removing recharging variable

---

code/modules/jobs/job_types/roguetown/church/druid.dm

I got a bug report that says beast lost their beast language from extra language. But when I looked in the druid file they never got it in the first place so idk what happened. Maybe some weird interactions with transformation.
Let people get beast without having to click a language first

Actually add beast language to druid

---

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/thug.dm

抓取垃圾郵件 GRABSPAM 銅指節圓起點 ROUNDSTART BRONZE KNUCKLES 平衡手淫 BALANCEJAK
In all seriousness, all this does is add some candy to Thug to encourage people to play it over, you know, the straight upgrade to Thug that is mercenary. They still don't get any expert proficiencies, because I feel like it would take a miracle to avoid getting gutted alive for giving a towner role better than journeyman wrestling, but they do get;
- Some labor skills
- Better climbing and constitution
- A little bit of stealth because who doesn't like sneaky assholes with blunt weapons
- The choice between knuckles and the ol' cudgel.

Thug Candy

---

_maps/map_files/dun_world/dun_world.dmm

Fixes a mild oversight with the overhand over the moat near the keep. Rock wall no longer shows in the open space.
Plus added one unmerged commit here where I just linked the flowing waters. Nothing major besides you can now get washed to sea by the whole north moat instead of just half of it. (Still able to swim to the lip)
Fixed the overhang
Linked moat
Fix.

Map Moat Fix

---

code/modules/spells/roguetown/acolyte/malum.dm

Delete range override on vigorous exchange
Did not test
Yurke pointed out on discord it has a range of 1 and since LOS check was added that was respected and now you cannot stam max with the spell. 
this removes the override consistent with the LOS tweaks that removed most unnecesasry range override

Delete range override on vigorous exchange

---

code/modules/roguetown/roguecrafting/items.dm

So after seeing what it takes to actually get the peasantry weapons from scratch, I realised that farm tools require iron anvil recipes and blacksmithing. So unless you're a soilson who spawns with one of them, you'd need a whole smithy setup 
(at which point why aren't you making steel for yourself -- you already mined / procured coal and iron AND can smith well enough!)
This PR adds a bunch of extra recipes for hoes, threshers, pitchforks and shovels:
Every farm tool can now be made on a table w/ a hammer, using Carpentry and:
- 1 Iron Ingot, 2 Sticks
OR
- 3/4 Whetstones, 1 Rope, 2 Logs
In addition: 
- Carpentry is no longer only grindable using wooden bins.
- Every farm tool added above has craftdiff of 0.
- Wooden buckets, swords and staves also have a craftdiff of 0.
Overall, this …

Adds more recipes for farm tools, carpentry recipe adjustments

---

code/game/objects/obj_defense.dm
code/modules/projectiles/projectile/reusable/_reusable.dm

Thanks to https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/2176 an interesting bug came to surface: when arrows failed the CheckExit() check of objects such as chairs, benches (or anything that stops any atom from exiting the object from a specific direction), said arrows would jitter in place until they reached their max distance of movement, triggering their own on_range() which then called handle_drop(). But since they also called Bump(), the code that I added recently was triggered. Effectively this duplicated the arrows.
Instead of fixing the arrows not being able to exit chairs (as it might be an intended feature) I decided to fix the origin of the issue directly by making sure handle_drop() sets a flag to true for a single projectile, stopping it from dropping multiple …

[FIX]: Fixes any potential duplication bug with reusable projectiles

---

code/modules/roguetown/roguemachine/lottery.dm

Fixes a bug introduced in #339
Currently this exploit exists and can be tested by doing the following steps.
1) Insert gold
2) Right click the machine to open the withdraw dialog
3) Keep it open and middle click to gamble
4) Withdraw money on when fail sound effect triggers
This adds an additional check before coins withdraw to see if gambling is currently underway.
Closes an exploit for infinite coins.

Fix exploit in lottery machine

---

code/__DEFINES/roguetown.dm
code/modules/jobs/job_types/roguetown/garrison/sergeant.dm

PR adds new loadouts for Sergeant so they don't just get a billhook and cudgel anymore. They now get a weapon choice akin to how knights and regular MAA do.
New loadouts:
- **Romphaia** - Armor piecing sword subtype of a bastard sword. Has lower durability, only 125, but has some bonus armor pen. (Comes with cudgel for backup-weapon.)
- **Steel Flail + Towershield** - Steel flail is an attempt at making use of the whips and flail training sergeant gets while trying to avoid giving out steel maces or the like. Comes with tower-shield for parrying/defense.
- **Halberd** - Halberd acts as a 'better' billhook albeit with worse stab damage. Present on regular MAAs already. (Comes with cudgel for backup-weapon.)
- **Sabre + Crossbow** - The 'versatile' ranged option hybrid. Sabre since it has …

Sergeant Loadouts

---

code/modules/clothing/rogueclothes/storage.dm

Adds preexisting storage component meant for cloth belts to cloth and rope belts, nerfing their storage
It's already there bro
Returns old consistency pre-grid storage where shitty belts had shitty storage
I didn't actually consider who has or hasn't a cool belt (except bandits) , I just think a couple pieces of twine shouldn't hold 2 swords and 3 knives

Simple Belt nerf

---

code/modules/mob/living/roguetownprocs.dm

Wo-balance-salt-jak upon ye
Really simple PR. People kept saying "Well, if you wear armor you aren't trained for you fall over" - which wasn't true EXCEPT if you tried to dodge. So, parrying in armor you didn't have training for? No difference.
This makes it instead you have a capped parry % of 75, and you use extra stamina when parrying in the armor. Basically acting as a penalty but one you can honestly live with to a minor extent. You'll be less efficient than a trained person but still able to fight at least.
I'll post some soon when I test this, getting this up first.
Basically does what most people seemed to THINK was the case anyway where you got penalized for wearing armor you aren't trained for. Does it in a less 'bullshit' way instead of just knocking you over to die.

Small Non-Armor Training Penalty

---

code/_onclick/other_mobs.dm
code/modules/mob/living/carbon/human/species.dm

You can now kick while on the floor. Works as normal.
All kicks now break passive grabs. Though aggressive grabs only result in the grabber keeping their grab and both being pushed by one tile. (Use this strategically to kick aggrograbbers off cliffs/onto tables/into walls if you can)
Kicking out of grab immobilises you for 1s, preventing *instant* escapes.
Tested in local with two mobs. Remains to be seen how annoying it is in game.
Another counter to being constantly grappled. Might make grapplers more mindful of where and how they're grappling (or, if they can). Plus floor-kicks are right out of action movies, pretty cool.

Add floorkick + kick breaks passive grabs

---

code/modules/roguetown/roguejobs/gravedigger/hole.dm

_"Desperately claw your way out of any bad situation!"_
> Have you just found yourself 6 feet under for literally no reason because of a jackass with a shovel? Are you a deadite, ready to claw your way out of rest and begin your hunt for brains? Buried yourself accidentally and dropped your shovel? Well, say no more to round-removal via gravestone and burst right out of that grave Return Of The Living Dead style with all new lessons such as "How to Fake Your Death", "Ways to Escape When Buried Alive", and "How To Stop Drowning In Dirt; Romero Style!"
This PR is very simple, pressing the Resist button while buried alive without a coffin makes you start clawing and crawling your way to the surface. Best to start escaping quick after burial, though, starting too late will have you falling …

Grave Bursting: Part 1

---

code/modules/jobs/job_types/roguetown/nobility/knight.dm

In the https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/2168 PR
Royal champions receive a greataxe + slings option.
However, they have no axe skills and are not given any from the selection.
This resolves that issue.
I didn't. It should be fine though!
Now they won't suck with axes despite supposed to be very good at it?

Small skill oversight fix

---

code/modules/roguetown/roguejobs/blacksmith/items.dm

Fixes polishing tools occupying 4 inventory grids and also fixes an exploit that allowed polished tools to be infinitely applied +50 integrity. Now the code appropriately applies the temporary max integrity then removes it once the object is damaged.
Gubfix

[FIX]: Fixes polishing tools being massive and infinite integrity exploit

---

code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/disciple.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
code/modules/jobs/job_types/roguetown/church/templar.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm

Hello!
This is the third _(and final_) part of a recent rework to the _"pugilism"_ playstyle, spearheaded by Onutiso and myself. Her previous contributions include [overhauling the _"Civilized Barbarian"_ trait, adding unarmed damage multipliers to gloves](https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/2017), and [fixing the long-broken unarmed parrying mechanics](https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/2011). Seeing as these changes have been successfully merged for a couple weeks without any serious issues or bugs cropping up, we _should_ be in the clear to cap off this rework with one last pull request.
As the title mentions, this pull request will be adding the _"Expert Pugilist"_ trait - which gives you a higher critical hit chance _(and no …

Power in Faith (And Pugilism) - Addition of the "Expert Pugilist" trait, alongside some minor rebalancing, to most "Monk" classes.

---

modular_azurepeak/virtues/utility.dm

**Gets up to apprentice level in**
- Cooking
- Lumberjacking
- Athletics
- Farming
- Fishing
Mage associate with the new skills. Cooking mastery to test if it works with personal granary. 
There's no apprentice style trait for these skills. This should let more people pick a food producing focus without making it their entire job or having to hinge solely on the Innkeep. But it's mainly interesting for.
- Adventurers (Ability to be self sufficient)
- Hermits (Witches, druids and whatnot)
- Servants (Being very poor, servants often have to farm if they wish to run the kitchen specifically, but they start with no farming skill)
- Followers of Abyssor & Dendor.
- Mercenaries who want to cook for their guild.

Add the forester virtue

---

_maps/map_files/dun_world/dun_world.dmm
_maps/map_files/generic/CentCom.dmm

* Increases the reward yield for conquering and fighting the Lich boss, as it requires a large group of players to fight this unique mob, with a very high risk for a good quantity of players to get turned into lynch mob victims, nuggets, and BBQ'd by the Lich and his goons.
* Because I'm sinister and evil, a small handful lamia were placed around the terrorbog. Enjoy. Note, they are distant from one another.
* Adjustments made to the staff only area.
* Removed and replaced a few armor pieces in the lord's closet, they're not a frontliner but should still have access to something in case.
* Added a few pieces of clothes and other items to the marshal's and Hand's rooms. 
*Added a few houndstones to the sergeant's key closet, to hand out to an additionally hired members of the garrison, …

Minor Dungeon and Other Map Updates

---

code/_onclick/hud/screen_objects.dm
code/modules/client/preferences.dm

The extra language default feature populates to "None" if not set on a new character, which breaks the language / trait display loop. This puts in a check to continue if it hits that "None", which solves the runtime.
My breakpoint enjoyed seeing a string come out of a datum expectation. Hey, it's a scripting language
One less runtime

Touches Preferences population to handle unset extra language runtime

---

code/datums/ai/behaviors/hostile/melee_attack.dm
code/modules/mob/living/living.dm
code/modules/mob/living/simple_animal/hostile/simple_skeleton.dm
code/modules/mob/living/simple_animal/rogue/creacher/bigrat.dm
code/modules/mob/living/simple_animal/rogue/creacher/honeyspider.dm
code/modules/mob/living/simple_animal/rogue/creacher/mossback.dm
code/modules/mob/living/simple_animal/rogue/creacher/troll.dm
code/modules/mob/living/simple_animal/rogue/creacher/trollbog.dm
code/modules/mob/living/simple_animal/rogue/creacher/volf.dm
code/modules/mob/living/simple_animal/rogue/rogueanimals.dm

tweaks basicmob controllers to hopefully probably enforce a proper cooldown on their melee attacks as previously they were attacking approximately five times a second. whew.
this is a bit of a band aid fix to a more extensive rework and refactor of mobs because i dont want to take time away from my current projects but it should fix the functionality well enough until i or someone else can do proper basicmob refactors 👍 
live:
test enviro:
fixes broken shit

probably fixes simplemob's busted ass melee cooldowns

---

code/modules/jobs/job_types/roguetown/garrison/manorguard.dm

Gives Cavalryman loadout for Man-At-Arms a mount (Saiga Doe).
It has no real benefit over playing a footman and doesn't even live up to a fantasy of being mounted watchman, so now it might even be picked.

Cavalryman Saiga

---

code/modules/mob/living/roguetownprocs.dm

Reverts GeneralPantsuIsBadAtCoding/Azure-Peak#2241
this turned every weapon into a polearm fragility wise, which seems to have been overall a negative for combat
(which means the people talking about polearms feeling awful were very, very, right and should feel vindicated)
I'm not quite done with tweaking parry damage, but this is a stopgap for now that makes swords / axes etc immune to pve parry damage again

Revert "Removes blade dulling from parry damage"

---

modular_azurepeak/virtues/utility.dm

Court agents weren't being caught by the resident apply_to_human or chain. Now they do.
Now I cannot meta that your resident adventurer is actually a court agent because you spawned outside of the tavern. Whatever good that would do me!

Fixes resident spawn to catch court agents too

---

_maps/map_files/dun_manor/azure_forest.dmm
_maps/map_files/dun_manor/dun_manor.dmm
_maps/map_files/dun_manor/smalldecap.dmm
_maps/map_files/dun_world/dun_world.dmm
_maps/map_files/rockhill/rockhill.dmm
_maps/map_files/roguetest/roguetest.dmm
code/modules/farming/crafting_recipes.dm
code/modules/roguetown/roguecrafting/structure.dm
code/modules/roguetown/roguejobs/cook/tools/grinding.dm

- Turns millstone into an item and make it placeable and craftable on table, like how it is done everywhere on map
- Nukes the unused wheat + oat recipe for crafting from Ratwood, no one used them anyway and it is not sovlful (tm)
Mapper put millstone on tables all of the time but when I am in game I cannot do it and have to take up space on the floor. Why???

Repath millstone, makes it placeable on table and an item

---

code/modules/surgery/surgeries_hearth/cure_rot.dm

Reported issue where de-rot surgery was giving anyone, living or dead, the rot paralysis debuff. This makes it so it checks that the mob is dead OR is already a zombie, plus has 5 minutes worth of rot-time (7 min will zombify you) and then apply the debuff.
This way doing self-surgery or removing rot from non-dead people will no longer give the rot paralysis debuff.
Didn't take a screenshot but tested on local. When doing self-surgery it did not apply the debuff to me.
When doing the surgery on a rotted corpse, it gave them rot paralysis as intended. Can't test this fully but was able to ensure it is at least looking to work as intended.
Unintended 'feature' of mine because I didn't think to include a check to avoid punishing living people who were being de-rotted.
I think players are …

Fixes De-Rot Surgery Debuffs

---

code/modules/roguetown/roguejobs/blacksmith/items.dm
modular_azurepeak/virtues/utility.dm

Tweaks Polishing in a few ways, please see the "Why it's good for the game" section for all the bullet points
To show how often the glint appears on worn armor
https://github.com/user-attachments/assets/57427372-5615-49f2-99f8-f9a3d381eed6
- Brush has been made 2 inventory grids tall: I originally made the size too small for a reusable tool, even the sprite went over the 1x1 inventory grid
- Polishing now lasts until the object has taken damage and its integrity 25% or less: This makes polishing more durable and not a 1-hit disappearing thing
- Polishing max integrity has been changed from a static +50 max integrity, to a +10% max integrity depending on the object's max integrity. This stops low max_integrity weapons like stone knives from obtaining a massive boost in their durability.
- …

A few tweaks to the Polishing system, including shiny armor

---

code/_onclick/hud/action_button.dm
code/datums/keybinding/carbon.dm

Hotkeys changes from https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/2267, atomized. 
- You get Alt1 to Alt6 as default hotkeys for action 1 to 6 on your hotkey bar - mainly for mage but also sergeant and knight etc. 
- I unlocked Ctrl key clicking to rearrange them which WILL affect the order you swap it at. It is a bit janky atm and it isn't documented, I blame it on SS13 interfaces. Documentation, soon. 
Makes using these abilities easier.
Stuck to Alt 6 I think most reasonable poeple stick to alt 1 to alt 4 and alt 6 is farthest I can reach with a finger.

Actions 1 - 6 Hotkeys. Atomized edition

---

_maps/map_files/dun_world/dun_world.dmm
code/modules/jobs/job_types/roguetown/nobility/knight.dm

- Foot Knight, Mounted Knight now get sabre options
- RC gets a Fluted Cuirass, KC gets a fluted half-plate in their cabinet
- Knights get plated gauntlets.
- Heavy Knight gets +3 INT (instead of +1), with -1 SPD
Tested. 
- A sabre is a shittier rapier. Good for the sovl, while still keeping the need to upgrade
- I didn't add the fluted cuirass/fluted half-plate (even though, balance-wise, they'd fit alongside other options for the respective roles) particularly because I didn't want to touch too much at the time of adding them. Think it's good now, though
- Knights get plate anyways, and it'd fit for a `knight`. Chausses has been kept as is since legs are usually more of a factor in fights than gloves (nobody aims for hands, they aim for arms. Easier to hit.)
- Heavy Knight (and Royal …

Assorted Knight/KC changes

---

code/datums/migrants/migrant_waves/heartfelt roles.dm
code/datums/migrants/migrant_waves/heartfelt wave.dm

I was picking away at making a new migrant wave and decided to take a look at the Heartfelt and why they never get played. Before, the fewest Heartfelt that could spawn was 3, and they HAD to be the Lord, Knight and Hand; now, the game will attempt to spawn another combination failing that (lord/LADY/hand), then attempt to spawn pairs: Lord and Hand, Lord and Knight, Lord and Lady - eventually allowing a singular Lord to spawn. This might be controversial, but I think having a lone survivor is compelling and they make an excellent antagonism target. As well, more people will likely begin to play Heartfelt in greater numbers if you allow fewer; I believe the barrier to entry has a stifling effect, and enabling more Lord and Lady spawns together may be more appealing to many.
This also …

a very HEARTFELT PR

---

code/modules/roguetown/roguecrafting/leather.dm
code/modules/roguetown/roguecrafting/sewing.dm
code/modules/roguetown/roguecrafting/weaving.dm

Realized what the issue was and amended it. Leather and recipes had a sub_type checker set to false, it's set to true - should work fine given how everything is pathed.
Tl;dr - does this now:
- if you list the required leather as, say, cured - it NEEDS to be cured leather to craft.
- if you list the required leather as regular hide, you can use cured leather OR regular hide to make it.
Same way furs work now too. If it's listed as just fur, no specific? Any fur will be able to make it. If it's listed as fur but specifies direbear? Will need direbear to make. Etc.
Hard to really prove via screenshots but did boot my test server up a few times. Tried making fur-lined boots and wolf helms to make sure this works without issue.
Also made sure to test things like, fur-lined boots (requires fur …

Fixes Fur Crafting Issue

---

_maps/map_files/dun_manor/azure_coast.dmm
_maps/map_files/dun_manor/dun_manor.dmm
_maps/map_files/dun_manor/smalldecap.dmm
_maps/map_files/dun_world/dun_world.dmm
_maps/map_files/roguetest/roguetest.dmm
code/game/objects/effects/spawners/roguemapgen.dm
code/modules/cargo/packsrogue/tools.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
code/modules/roguetown/roguecrafting/alchemy.dm
code/modules/roguetown/roguecrafting/alchemy/alch_items.dm
code/modules/roguetown/roguejobs/alchemist/container.dm
modular_azurepeak/code/modules/alchemy/alchemy_recipes.dm
modular_azurepeak/code/modules/reagents/reagent_containers/spider_venom.dm

Alchemical vial is now 1x1.
Repathed it and deleted most unnecessary copy pasted code from bottle. Might conflict with map. 
Alchemical Vial - except for the fact they cannot be thrown, are strictly inferior to the 16 ounces glass bottles. They are neat for selling things from cauldrons because cauldron brew in 9 / 27 ounces, but every gamer rebottle them instead. This give them a niche as they hold 9 ounces each and stop triggering my inner optimizer.

Makes alchemical vial small, repath to reduce repeated code

---

_maps/map_files/dun_world/dun_world.dmm
code/modules/jobs/job_types/roguetown/nobility/lady.dm
code/modules/jobs/job_types/roguetown/nobility/lord.dm

- Removes the extra mapped in crownstones from the duke's bedroom, the knight captain's quarters, the marshal's quarters, and the sergeant's quarters.
- The duke and the consort now both spawn with crownstones.
- The anti-magic ring the duke previously spawned with can now be found in the duke's bedroom.
Cuts down on crownstone bloat. The dev who made the houndstones/crownstones, @Onutsio, has mentioned several times that they are intended to be in short supply and supposed to be limited to strictly garrison leadership roles.
Others have since come through and mapped in several spares and it's led to there being a total of 5 spare mapped in crown-stones to be freely handed out to whomever - which is pretty excessive. Half the garrison shouldn't be running around with instant access to …

Cuts out excess crownstones, roles that should get crownstones now simply spawn with them

---

modular_azurepeak/code/game/objects/items/magic_staffs.dm

Use drop location for staff and fix it disappearing in hand (inside mob)
Sutures pointed out that the staff might be inside mob content and it turn out because it is calling for (loc) that means if you add a gem to your staff in your hand it get moved inside you.
there is no longer an amethyst staff inside you

Use drop location for staff and fix it disappearing in hand (inside mob)

---

_maps/map_files/dun_world/dun_world.dmm

Added the correct ID check for the court magicians quarters doors.
Also adds two manor keys so the magician associates they hire can also get into the keep itself.
The damn key isn't being used anywhere, not even in their private room. This changes that.

Fix | Court Mage doors

---

code/game/objects/items/rogueweapons/melee/polearms.dm

Reverts GeneralPantsuIsBadAtCoding/Azure-Peak#2046
As the original author of the polearms integrity changes, I did not "intend for the buff to be counteracted by swords going up in durability", the PR author who opened the revert, read subtext that was not present.
My original intent was to bring the polearms up to the standard of the eagles beak, which, at the time was 500 integrity (easily the highest polearm, as all others were (and are) at 200 across the board.
I'm willing to adjust the values down from the original PR's values, but it's still very clear, with all the love given to swords lately (with innate armor values) that the polearms are quite lacking even in mock fights, when it comes to their overall durability, compared to how the weapons SHOULD work, based on real life …

Revert "Revert polearm durability changes"

---

code/modules/roguetown/roguemachine/scomm.dm

Admin request. This solution allows fellow Matthiosites out in the world have and cherish their bandit coin if they are given one. But prevents (in one way) the coin from falling into the hands of a town-aligned Matthiosite.
https://github.com/user-attachments/assets/92157508-fd7c-47f0-a567-05d6bb3e6de4
hmm

Adds dostrip overload for bandit coins, ashes them on non-bandit strip

---

code/modules/reagents/reagent_containers/powderspice.dm
modular/Neu_Farming/code/eggs.dm
modular/Neu_Food/code/NeuFood.dm
modular/Neu_Food/code/cooked/NeuFood_snacks.dm
modular/Neu_Food/code/raw/NeuFood_dough.dm

Rename cackleberry to egg, "powder" to flour, "powder" to "ozium"
Cackleberry is a late 19th century obscure word we've been calling them eggs since before and after what the fuck. 
Also "powder" should be flour.
Also "powder" should be ozium we have no reservation about naming moondust moondust so why ozium get a pass?

Rename cackleberry to egg, "powder" to flour, "powder" to "ozium"

---

code/game/objects/items/rogueitems/bags.dm
modular_azurepeak/virtues/utility.dm

- Grants 1 bread instead of hardtack & copiette.
- Fishing rod
- 9 bait items
- frying pan
- 2 fishing levels up to legendary
Shifts the focus of the virtue towards food gathering and cooking. You can make cheesebread pretty easily with the supplies. Pots are easy to make, but pans are not. So now you can get set up with a little kitchen more easily out in the woods.
Main goal is to make it so that adventurers take this actually sit down somewhere to cook up some butchered meats or gathered fish instead of just living a whole round off their own granary bag.

Rebalances personal granary

---

code/modules/jobs/job_types/roguetown/nobility/hand.dm

hover hand fr fr
Somewhat selfish; I wanted to make a swashbuckling hand but the sword one is knight-coded, gross.
This evens out the sword abilities between Hand (Generic) and Spymaster, as well as giving all three the decorated rapier (normal rapier, different sprite) as well as detace, Hand's iconic spicy dagger.
This also balancejaks while I am here, as advisor could roll higher intelligence then court mage/archivist and spymaster had the single highest speed in the game. The advisor... probably _could_ be powered up slightly to the mercenary Almah spellsword and the Hand (Generic) get the captain's expert sword to make it _mechanically_ worthwhile in comparison, but master sword is not something I'm willing to do off the cuff.
I did actually spawn in with all three to make sure …

Hand creep, dtace/rapier for all

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm

Adds a few options to the battlemaster class. Traditionally, fighter archetypes in DnD type settings are boring but offset this by being highly customizable. Our battlemaster is just some dork in chainmaille, so this aims to remedy this. Also does terrible powercreep to the subclass by giving it the 1 shield it used to have before the great adventurer resorting.
Adds:
1. Three options for armor instead of just one: players now can choose from the classic chain set, an iron breastplate set (**iron** breastplate, heavy leather gloves, normal leather pants) or a gambeson & kettle set perfect for the aspiring bog guard hopeful (kettle hat, gambeson, heavy leather gloves)
2. A sword & board weapon option for weapon choice - Short Sword & Heater Shield. Gives the player an (iron!) short sword …

Battlemaster Customization Options

---

code/game/objects/items.dm
code/game/objects/items/soap.dm

Add word descriptor to show a weapon's force in game
Also cleaned up unused old force string code
Add word descriptor to show a weapon's force in game. Better transparency so people know roughly how good a weapon is without needing to code dive. Obscure it slightly behind words for immersion.

Add word descriptor to show a weapon's force in game

---

code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm

Double efficiency of iron and steel javelin recipe
Double efficiency of iron and steel javelin recipe. 
Since they're meant to be throwable projectile having them as expensive as a singular melee weapon is wild, five ingots to fill up a bag of five? Doubling the efficiency should make them see more use on classes that don't start with them.

Double efficiency of iron and steel javelin recipe

---

code/__DEFINES/combat.dm
code/game/objects/items/rogueweapons/intents.dm
code/game/objects/items/rogueweapons/melee/axes.dm
code/game/objects/items/rogueweapons/melee/blunt.dm
code/game/objects/items/rogueweapons/melee/flail.dm
code/game/objects/items/rogueweapons/melee/knives.dm
code/game/objects/items/rogueweapons/melee/polearms.dm
code/game/objects/items/rogueweapons/melee/special.dm
code/game/objects/items/rogueweapons/melee/swords.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/mob/living/living_defense.dm

Also changes examine on intents with negative penfactor:
This should ensure that every instance of blunt damage will not go through armor if it's there.
Set a penfactor to 85 
and hit meself
Unintended!

Fixes a missing blunt override, adds blunt define

---

code/modules/projectiles/projectile.dm
code/modules/spells/roguetown/_roguetown.dm
code/modules/spells/spell_types/wizard/projectiles_single/arcyne_bolt.dm
code/modules/spells/spell_types/wizard/projectiles_single/guided_bolt.dm

- Fix a mathematical error resulting in all magical projectiles hitting chest
- Fix Arcyne and Guided Bolt knocking people out. Turns out setting armor flag = "blunt" result in people going asleep...across armor, what the fuck.
Bugfix and no more knocking people out what the fuck

I hate this codebase (Arcyne Bolt + Guided Bolt + Spells Accuracy Fix)

---

code/game/objects/items/rogueweapons/shields.dm

Runtime was throwing when passed atom/movable that hit a shield wasn't an item. Like hitting someone with a thrown goblin. This tightens up the var access to prevent that runtime.
It compiles. Theoretically it works!
Since this is addressing a runtime, passing hits down to null/false shouldn't be any worse than the current alternative.

Fixes shield hit runtime by mob or non-item

---

code/game/objects/items/rogueweapons/melee/polearms.dm
code/modules/roguetown/roguecrafting/items.dm

- Gives iron and steel quarterstaff reinforced shaft
- Fix their recipes not consuming the quarterstaff
Gives iron and steel quarterstaff reinforced shaft. It just make sense. It is literally reinforced. It is a better PVE (and maybe all around option) but most importantly it makes sense.
Fix their recipes not consuming the quarterstaff

Gives iron and steel quarterstaff reinforced shaft + fix recipe

---

code/game/objects/items/rogueweapons/melee/polearms.dm

Raises steel zweihander damage so that it's no longer objectively weaker than its iron counterpart.
The steel zwei does less damage than the iron one for some reason, this PR makes them do the same amount of force damage. Steel weapons are supposed to be an upgrade to iron - this feels like an oversight. 
It's two lines.

Insane zweihander buff

---

code/game/objects/items/rogueweapons/melee/polearms.dm

Gives greatswords (and the estoc) metal shafts, like other swords.
eeeeeeeeee
Greatswords didn't have a blade_dulling variable assigned, so they were just defaulting to wooden shafts. It seems like most other swords use metal shafts, so I would assume this is unintentional.

Gives greatswords metal shafts

---

code/game/objects/items/rogueitems/natural/clothfibersthorn.dm

One liner to stop the experimental onhip draw for cloths onhip.
Wish I knew a better way to fix these offsets other than just turning them off.

stops floating cloth sprite onhip

---

modular_azurepeak/virtues/combat.dm

2nd skill assignment in the combat virtues was overwriting edge cases of skill gains for 1st condition. This constructs the list with += instead of =, fixing that bug.
Hunter spawns with swords 2 and knives 2, and both skills are bumped to 3.
There might be an exploit here I can't see, might have to do this differently.

combat virtue added_skill levelup to fix override bug

---

_maps/map_files/dun_world/dun_world.dmm

Lowers fishing village hermes by 1 z-level so it is generally accessible.
Adds a small barred window for the cheesemaker to do business out of.
Cheesemaker window was a request I saw, it helps them to do business out of their house a little easier.

Map: Hermes and cheesemaker window

---

_maps/map_files/dun_world/dun_world.dmm

rontzes are no longer the base gemtype to help prevent funky behavior when calling them up. this ensures that all rontz on dun world are the new, proper typepath
it just works
they shouldn't have been the base gem item in the first place arguably, now they're properly childed alongside their siblings, gay sex, etc

mapper wrongs activist

---

code/modules/jobs/job_types/roguetown/adventurer/wretch.dm

This pull request do four things: 
- Add in a new, popularly requested Wretch Subclass for non-zizo flavored wretch. They have the same stat spread as the Necromancer. 8 spell points, and deliberately has nearly the same fit as a Mage who just cast Conjure Armor (no Iron Gorget). They loses out on Zombie Immunity, Zhurch Key and Gravedigger for obvious reasons. Oh they have an eyepatch and an edgelord tutorial.
- Assert my design dominance by saying that wretch is a 9 points soft antagonist class and adjust the stats to match it from now on
- Deserter gets +2 Endurance for more Stamina without lopsiding their stats. Now they can somewhat match a knight.
- Heretic get nothing. They are stacked as fuck with heavy armor and rituals and shit. 
- Poacher gets +1 Endurance and +1 Constitution, …

Wretch Subclass: Hedge Mage + 9 Points Stat Adjustment + More Customizable Bounty

---

code/modules/spells/roguetown/_roguetown.dm
code/modules/spells/spell.dm
code/modules/spells/spell_types/wizard/invoked_aoe/aerosolize.dm
code/modules/spells/spell_types/wizard/invoked_aoe/ensnare.dm
code/modules/spells/spell_types/wizard/invoked_aoe/repulse.dm
code/modules/spells/spell_types/wizard/invoked_single_target/frostbite.dm
code/modules/spells/spell_types/wizard/invoked_single_target/gravity.dm
code/modules/spells/spell_types/wizard/misc/magicians_brick.dm
code/modules/spells/spell_types/wizard/misc/shadowstep.dm

When I added the gesture required call it was added to all projectiles. However, I didn't do the check properly which means you can select the projectile, charging just fizzled out. But there were way around. Chains just prevented you from charging the spell reliably but you can get around it. 
This should prevent all of such edge cases:
- Added gesture required to the invoked spells that should have it: Aerosolize, Ensnare, Magicians Brick, Gravity, Frostbite, Repulse, Shadowstep. Following the rules of if it has direct offensive / mobiltiy potential it cannot be cast while cuffed. 
- Readded the check to all projectile spells. Some no-delay projectiles can still be fired and from what I heard, with spamming inputs you can still bypass it on projectiles requiring charge time
- Redid the …

Refactor & Redo gesture required. Readd to projectile / offensive spells, prevent selection

---

code/game/objects/items/rogueweapons/melee/polearms.dm
code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm

Adds combat music to Deserter > proof in #2352 
Fixes typo in halberd description
Fixes typo in halberdiers description
Gives Halberdier for Grenzelhoft Mercenary instead of Mace the Axe skill that is advertised in the description.
Typos are annoying, deserter should have had this since beginning probably and the description was misleading.

Typos and Cmusic

---

code/game/objects/items/rogueweapons/melee/polearms.dm

- Quarterstaff intent no longer have penfactor.
- Spear bash no longer have penfactor 
- Quarterstaff still have two intents. Bash remain the same. Stab now have a chargedelay of 6, but a damage multiplier of 1.3 - hopefully it has a niche as a playstyle?
- Both iron and steel quarterstaff has 1.2 integrity damage modifier.
Compile and checked intents
Just some tweaking to quarterstaff to make them a competitive viable alternatives to other polearms. (To be tested)

Redo quarterstaff intents, give int damage to metal quarterstaff

---

code/controllers/subsystem/rogue/devotion.dm
code/datums/gods/_patron.dm
code/datums/gods/patrons/divine_pantheon.dm
code/datums/gods/patrons/inhumen_pantheon.dm
code/datums/gods/patrons/old_god.dm
code/datums/migrants/migrant_waves/heartfelt roles.dm
code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/disciple.dm
code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/psydoniantemplar.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/Iconoclast.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
code/modules/jobs/job_types/roguetown/church/druid.dm
code/modules/jobs/job_types/roguetown/church/monk.dm
code/modules/jobs/job_types/roguetown/church/priest.dm
code/modules/jobs/job_types/roguetown/church/templar.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm
code/modules/jobs/job_types/roguetown/youngfolk/churchling.dm
modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/excommunicado.dm
modular_azurepeak/virtues/combat.dm

For players:
- You shouldn't notice any changes! Except:
- Matthiosans now get Lesser Miracle where applicable (same as every other Patron).
For coders:
- Miracles are now an all-inclusive assoc list tied to the expected cleric tier as a value rather than hardcoded T0/T1 etc.
- Positives: Tiers can have any amount of miracles now.
- Negatives: Orision and lesser miracle are now included in every miracles list.
- Added defines for passive devotion gain values.
- Everything is now tied to a single `grant_miracles` proc that has everything we may need (hopefully) in the parameters.
- When adding a miracle-user class you only need to init the devotion and call that proc. No need to start processing or add the verbs or anything else. grant_miracles handles all of that now.
Tested:
- Priests / …

Refactors devotion

---

code/_onclick/hud/mouseover.dm

This PR fixes #2306
I have debugged the original issue by tracing what is attempted to be drawn over the screen when hovering the cursor over an object, and found that even after it has been collected, it'll attempt to render the position of a QDEL'd item.
I've recorded a video of this bug in action, and the fix being shown working by logging in chat.
```dm
/atom/proc/handle_mouseover(location, control, params)
var/mob/p = usr
if(QDELETED(src))
to_chat(p, span_notice("attempted to render deleted object [name]"))
return FALSE
...
```
https://github.com/user-attachments/assets/3d8d5900-76bd-4d68-b884-a34053b95874
By using the same checks when collecting items as for hovering, it'll avoid rendering hover over items that'll be invalid as the object no longer exists on the server, but still …

Don't attempt to show hover over text for qdel'd turf/mob/atoms

---

code/game/atoms.dm
code/modules/mob/living/living.dm

Fixes runtime where was we were trying to write attacklog onto NULL when someone yields.
Fixes clumsy hands that happen when standing up between the 30 second and 60 second yield debuffs by just calling update_mobility() after the 60 seconds' ends.
https://github.com/user-attachments/assets/d7743f3c-b450-4f1f-828c-4b7882e4d170
I YIELD!

Fixes yield runtime and calls update_mobility to fix clumsy hands

---

code/modules/mob/living/carbon/human/npc/zizoconstruct.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/roguetownprocs.dm
code/modules/mob/living/simple_animal/hostile/deepone.dm
code/modules/mob/living/simple_animal/hostile/roguetown/haunt.dm
code/modules/mob/living/simple_animal/hostile/simple_skeleton.dm
code/modules/mob/living/simple_animal/rogue/creacher/bigrat.dm
code/modules/mob/living/simple_animal/rogue/creacher/cat.dm
code/modules/mob/living/simple_animal/rogue/creacher/demon.dm
code/modules/mob/living/simple_animal/rogue/creacher/direbear.dm
code/modules/mob/living/simple_animal/rogue/creacher/dragger.dm
code/modules/mob/living/simple_animal/rogue/creacher/fox.dm
code/modules/mob/living/simple_animal/rogue/creacher/headless.dm
code/modules/mob/living/simple_animal/rogue/creacher/honeyspider.dm
code/modules/mob/living/simple_animal/rogue/creacher/lamia.dm
code/modules/mob/living/simple_animal/rogue/creacher/mole.dm
code/modules/mob/living/simple_animal/rogue/creacher/mossback.dm
code/modules/mob/living/simple_animal/rogue/creacher/troll.dm
code/modules/mob/living/simple_animal/rogue/creacher/trollbog.dm
code/modules/mob/living/simple_animal/rogue/creacher/volf.dm
modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/dragon.dm
modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/minotaur.dm
modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/mirespiders.dm
modular_hearthstone/code/modules/mob/living/simple_animal/rogue/orc.dm

- Remove the defdrain variable, which is defined on living mobs and defined how much stamina is drained on parry.
- This variable was set to FUCKING 20 ON SIMPLEMOBS ORC AND SKELETONS, harder than trolls
- Combined with previously bugged attack rate, it means a single mob can stunklock you and drain stam in seconds from parry, nevermind two.
- Now all parry drain 5, consistent for both PVP and PVE
There's far better leverage for making mobs harder to fight like giving them harder hitting weapons. 
Stunlocking them with a non transparent stamina drain mechanics, especially with skeletons (a trash mob) having 20 drain (!!!), is unfair.

Nuke defdrain and set base parry stamina drain to 5

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm

Expands barbarian weapon selection to allow them access to a wider array of weapons to better facilitate roleplaying more types of half-naked dude who beats stuff to death. Gives barbarians two points in polearms, up to three if they elect to start with a spear. Gives the barbarian starting weapons a refit, making them both more in-line with the class identity as well as gently depowering them - notably, the battle axe is now a stone axe. 
Spawned as each of the weapon subtypes and verified that they started with the correct skills and loadout.
More customization is always good as it facilitates better roleplay when mechanics and character identity line up. 
The general design direction by the maintainers seems to be 'make adventurers weaker' so this aims to help in that direction, …

Advanced Lessons in Unga - Barbarian Loadout Expansion

---

code/controllers/subsystem/rogue/roguemachine.dm
code/modules/clothing/rogueclothes/hats.dm
code/modules/roguetown/roguemachine/scomm.dm
modular_azurepeak/code/modules/clothing/rogueclothes/crown.dm
roguetown.dme

This PR modularizes the crown of azure peak, setting it in its own new file. And then we slap all of the snowflake SCOM guts into it (Claude helped me do this). Effectively turning the crown into its own crownstone.
We do a safe navigation check off of SSRoguemachine to see if the crown exists on each access, which plays nice with the titan crown recovery logic that could lead to the crown being repeatedly deleted and initialized.
Generally it behaves as everything else does. Inhand use switches from main scom to garriscom. Middle click mute. Right click while wearing to speak into it.
Here we are speaking on the crown. The garrison line comes through large and golden, but is normal on the main line.
Other SCOMs seemed ok after far travel deleted the crown.
Regent RP, particularly the …

Adds crownstone functionality into the crown

---

code/game/objects/items/rogueitems/keyrings.dm
code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm

Turns out my map pr did jack shit because they for some reason spawned with the COURT MAGOS special key. This fixes that.
The court magician room remains exclusive to them.

Oversight Fix | Mage associate keyring

---

code/datums/status_effects/status_effect.dm
code/modules/cargo/packsrogue/food.dm
code/modules/cargo/packsrogue/merchant/merchant_potions.dm
code/modules/reagents/chemistry/reagents/other_reagents.dm
code/modules/reagents/chemistry/reagents/toxin_reagents.dm
code/modules/roguetown/roguecrafting/alchemy/cauldron_recipes.dm
code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
code/modules/roguetown/roguecrafting/alchemy/potionbuffs.dm
code/modules/roguetown/roguecrafting/alchemy/reagents.dm
code/modules/roguetown/roguejobs/alchemist/container.dm
code/modules/roguetown/roguemachine/merchant.dm
roguetown.dme

A series of tweaks to make some underused potions more used, make alchemy better for the end users, make normal gaming more worth it and powergaming less effective:
- Removed redundant define of killer's ice. Now it display properly as killer's ice instead of killersice. 
- Poison Antidote and Disease Cure now have 0.1 metabolization rate, instead of disease cure having 3x the metabolization rate and 4x the healing. Disease cure is now 3x as effective and *efficient* per volume, purging another asymmetrical cases of the stronger potion being faster acting but also arguably less effective. It is now a strict upgrade in every sense.
- Poison Antidote / Disease Cure has the dylovene effects common to charcoal / antitoxin on other server. It purges harmful reagents at the rate of 1 / 3 per …

Alchemy Tweaks

---

code/modules/surgery/surgery_tools_rogue.dm

Small change to setting forceps, bone setter, and speculum to blunt so they wont be used to amputate, speeding up surgery on limbs, and making accidental decaps much less likely 
- No more accidental decaps/amputation when setting bones. 
- Speeds up surgery with no more pop ups asking to amputate for the bone setting and forcep steps.
- (Maybe a negative would like feedback) Scalpel will be needed in surgery rather then just using forcep to cut
Tested in a local host and Amputation still works along with bone fix and lux.

Small Surgery Tweak

---

modular_azurepeak/code/modules/spells/pantheon/divine/necra.dm

In the refactor the free (and frankly strange) Abrogation miracle has been removed from all templars. Only Necrans (Templars with Devotee & Acolyte) now get it. Considering its meant to counter the undead, it now hardstuns deadites and knocks them down.
The Undermaiden rebukes!

Abrogation now stuns deadites

---

code/modules/jobs/job_types/roguetown/church/monk.dm

Gives Eoran Acolytes Beautiful instead of Good Lover, she's goddess of Beauty not hedonism like Baotha.
Makes Eora just tad bit less of a meme.

Looksmaxxing [Good Lover trait replaced with Beautiful for Eoran Acolytes]

---

code/modules/mob/inventory.dm
code/modules/roguetown/roguecrafting/alchemy/mortarpestle.dm
code/modules/surgery/surgery_helpers.dm

Having a helmet on hip blocks your mouth, you can't drink. Overloads the call to treat beltslots more or less as pockets, defaults the condition to TRUE for cooperation with other function calls.
Alchemy mortars were not nulling their obj ref when emptying with full hands, causing remote fetches. Fixes that.
Two for one deal

Two Bugs, Helmets on Hips stopping drinking and Alchemy Mortar Drop

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm

The Biome Wanderer.
Additional ranger class, focused on combat more than passive skills or stealth.
More akin to a Battlemaster (but able to fire a bow early on) or a weaker Warden.
The supposed "theme" of the class is a ranger capable of traveling long distances, or someone who has—fitting for a clustered setting—and dense, untamed wilderness.
Similar to Squire, it lets you pick what armor you wish to wear.
Light giving you dodge expert, or Medium (which will give you medium armor training).
You **CANNOT** have both.
See the screenshots!
Additional class that's modular for certain skills. Allowing people to "pick" their playstyle.
Basically a tinkered with Battlemaster/Sentinel in one class. using Battlemaster, Warden, and Sentinel as a reference for balancing.
Has the Adventurer's stat …

Additional Ranger Class.

---

code/modules/clothing/rogueclothes/quiver.dm
code/modules/jobs/job_types/roguetown/garrison/manorguard.dm

What it says on the tin. Use quiver in hand to dump out arrows.
MAA gets their recurve because I accidentally gave them selfbows instead when pulling their longbows.
Tested.
issue fix + easy way to dump out arrows is good when you're replacing your quiver stash

quiver dump + MAA recurve

---

code/modules/clothing/rogueclothes/hats.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm

Horned Helmets (made famous by the sea raider mobs we all know and loathe) are functionally identical to skullcaps (and nearly every other helmet but that's a different convo) except for the fact that they smelt into steel instead of iron. Several PRs have been made recently trying to address the very real 'steel is too common' issue, many of which remove the viking's horned helmets which damages their visual identity. My solution to this is making the helmets iron instead of steel, solving the steel availability issue while helping vikings maintain their visual identity. 
Too much steel bad. Enemies maintaining visual identity good. Grrr.....

Makes Horned Helmets Smelt & Require Iron Instead Of Steel

---

code/game/objects/items/rogueitems/books.dm
code/modules/crafting/recipe_books/recipe_book.dm
code/modules/crafting/recipe_books/recipe_books_list.dm

Keep seeing people ditch their starter survival's handbook recipe book. Understandable. 
- Books now burn for 5 minutes (standard with fiber) instead of 2.
- Recipe books can also burn
compile, i tested it
Burn books. raaaa

Make books + recipe books burn for 5 minutes

---

code/game/objects/items/rogueitems/ceramics.dm

The glazed clay statue was invisible. This fixes that! 
Wow! Such glaze! 
It did make a funny invisible party trick, but it's probably best to let the room décor piece be room décor.

Invisible Glazed Clay Statue Fix

---

code/modules/antagonists/roguetown/villain/lich.dm

- Cut down Lich to only having 2 lives instead of 4 (by reducing the amount of phylactery they get from 3 to 1)
- Give Lich much better combat stats - 3 strength instead of -1, +1 speed instead of -1, +3 perception. Get +1 Endurance (barely matter) instead of -1.
- Polearms go to Expert now. They had a lot of time to practice with their poles.
- Arcane is always 6. I mean, they're a Lich. (It barely affect anything)
- Gave them 8 spellpoints base
Tested
People complain about Lich round because you have to kill them **four** times which dominate an entire round. This allow them to keep their sovlful phylactery but now you only have to chase them once. It may make Lich much more bearable as an antag in regular rotation in the future. 
In exchange, they get significant stat buff to not get …

Small Lich Tweak - 2 lives, better combat stats, 8 spellpoints

---

code/modules/spells/spell_types/wizard/invoked_aoe/blade_burst.dm
code/modules/spells/spell_types/wizard/invoked_single_target/gravity.dm

1 year ago I. dente. Unleashed the biggest evil azure peak has ever seen. gravity.
I'm tired of people (rightfully) bitching about it, it was fun. this pr gives gravity a small delay, about half as long as blade burst.
will ppl still typebait you with this? maybe. idk. but it's now way harder to hit moving ppl.  (also doubling the damage up to 60 as it's now harder 2 hit.)
this also speeds up bladeburst slightly as the speed it was at was pre-debloat and pre-awesome serverbox. shit runs way better now. still very slow.

gravity delay

---

code/modules/antagonists/roguetown/villain/bandit.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/Iconoclast.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/brigand.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/hedgeknight.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/roguemage.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/sawbones.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/sellsword.dm

Talked about it a bit, biting the bullet and doing the PR because seems others agree at least with the premise that bandits should be worshiping at least the Ascendants. Won't rant much, here's simple reasons:
- They get the 'commie' trait, letting them identify Matthiosans, and lets them operate the Matthiosan idol regardless of faith. (..Which has led to them outing Matthiosans for no reason)
- Bandits use Matthiosan idol and the dragon hoard, which checks if the user is a Matthiosan (has the commie trait) to use it, it is also related to Matthios and his worshipers.
- On spawn the text even says: "Long ago I did a crime worthy of my bounty being hung on the wall outside of the local inn. I live now with fellow free men in reverence to MATTHIOS whose idol grants us boons and wishes when …

Bandits Now Worship Ascendants

---

code/game/objects/items/rogueitems/ceramics.dm

Fixes clay cup so it isn't invisible and swaps its cooked version to use the right sprite.
- The raw clay cup was invisible on craft. It is now visible.
- The glazed clay cup used the wrong sprite. It now uses the correct sprite.
[Forgot to get a screenshot so just pretend this is it and take my word for it]
More fucky stuff has been made unfucky. Bugfixes ahoy!

Ceramic Tweaks

---

code/game/objects/items/rogueweapons/melee/polearms.dm

Rebel gave the Cavalryman class Bardiche instead of Glaive (good) but Bardiche always felt awkward to use because of its poor thrust that is not competitive vs the BIS Billhook / Halberd that stab through armor. 
It also has 1 charge time on its cut making it much harder to use in practice compared to say, Zweihander.
This remove the charge time on the cut and give it 1.2 dam factor for 36 damage per cut, compared to Zwei's base 35 damage and 38.5 damage per cut at 1.1 dam factor. Both have no penetration and zwei is probably still the better weapon but at least Bardiche should be good for the thing it is thematically good at now.
It compiles
Give Bardiche a bit of a niche amongst polearm with no delay 2 range cut.

Bardiche no chargetime on cut 1.2 damfactor

---

code/modules/jobs/job_types/roguetown/garrison/manorguard.dm

MAA can now select helmets on spawn, similar to knights.
Most of these helmets are near-identical in terms of protection and already available in the armory anyways. With the armory size reduction, this means MAA who latejoin won't risk of losing out on their favorite-looking helm.

MAA Helmet Selection

---

code/modules/clothing/rogueclothes/mask.dm
code/modules/mob/living/carbon/human/npc/highwayman.dm
code/modules/mob/living/carbon/human/npc/militia.dm
roguetown.dme
strings/rt/highwaymanaggrolines.txt

Adds two new types of NPC types - highwaymen and peasant militia. One is friendlier than the other. Doesn't place any ingame yet, but they can be spawned by admins running events or placed by mappers at a later date.
Hark! Bandits! I wanted to create a new enemy type that had a power level between "goblin or skeleton you can stomp" and "medium armor axe man who removes thine limbs". Enter the bandit: an (easier) human enemy that wields mostly improvised weapons and clubs and wears leather armor. Intended to be a medium-low powered enemy that also provides a source of decent leather armor, something that in this world of the viking steel mill and 0 tailor players is hilariously harder to find than plate. They also come with fun little red masks! Who doesn't love that. Sometimes they'll …

Cops and Robbers: two new NPC types for mappers and event runners to play around with

---

_maps/map_files/dun_world/dun_world.dmm

Some small mapping changes to the smithy/tailor shops. Adds queue space areas in front of the service desks.
<details>
<summary>Screenshots:</summary>
Ground Floor:
Basement: 
</details>
There's lines now, which should mean less people clogging the roads in front of the smithy. Doesn't change the overall layout of either building **too** heavily.

Small smith/tailor map edits

---

code/modules/roguetown/roguecrafting/sewing.dm

Add spellsinger hats and robes as Level 6 recipe to sewing
Add spellsinger hats and robes as Level 6 recipe to sewing
Felinid said that is OK and Level 6 should gate it from being easily craftable. Plus it is whimsical and good and practical mage drip.

Add spellsinger hats and robes as Level 6 recipe to sewing

---

code/game/objects/items/rogueweapons/intents.dm
code/game/objects/items/rogueweapons/shields.dm

Stricter typecasting for atom/movable throwing to obj/item, apparently if it's a mob it will still go in the square hole.
Something about a door trying to mouse up, I don't know. Everything else in that proc is safe navigation. What did the ancestors know that we don't.
Compiles.
Thought I fixed em

safer access for two little runtimes

---

code/modules/roguetown/roguemachine/steward/steward.dm
code/modules/roguetown/roguemachine/stockpile/stockpile.dm
code/modules/roguetown/roguestock/_roguestock.dm
code/modules/roguetown/roguestock/stockpile_food.dm
code/modules/roguetown/roguestock/stockpile_rawmat.dm

- Adds stockpile limit to all stockpile items. Any additional item sold beyond the limit will NOT give you ANY money.
- You can check the stockpile limit in the feeding the stockpile tabs
- Steward can set the stockpile limit as they see fit.
- Default limit are very generous on purpose, so it mostly punishes people who flood the market with a single item. They are so generous they might as well not exist. 
Not really up for balancejakking. Might in the future add in an auto-export feature.
A baby step solution to stop people from flooding the market with a single item completely.

Azurian Disinflation Act - Stockpile Limit

---

code/modules/clothing/rogueclothes/quiver.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/underdweller.dm

was only going to do LOOC change but this was a simple fast pr and i got cum in my mailbox about the steppesman issue so fuck it fixed it
- javelin bags can now fit on hip, which they didn't originally because fear of 4 bags of them, but honestly on testing it was such a non-issue just let them have it. fixes steppesman not spawning with it cus not fitting on hip.
- underdweller lost it's 4 wrestling (accidently gave it 4 instead of 3), as reported as being a bit 'too overtuned' by an underdweller main, instead tossed them an extra climbing skill since they'll be using it to get tf out of cave areas semi-often. it's equal to garrison skill level anyway on some of their roles so it's plenty fair.
yeah it works
1. i made javelins not fit on belt cus they were originally really strong then …

Mercenary Fixes

---

code/__DEFINES/admin.dm
code/modules/admin/admin.dm
code/modules/admin/sql_ban_system.dm
code/modules/admin/verbs/randomverbs.dm
modular_hearthstone/code/interface/LOOC.dm

was taking a time away prs but staff wanted a way to mute and ban players from looc which apparently had broke prior. this adds the ability back to mute LOOC, which is just a round-long thing or until unmuted, or ban LOOC akin to how they can ban OOC usage.
staff want to police the dogshit looc abuse, so here - ported some of vanderlin's tweaks from https://github.com/Monkestation/Vanderlin/pull/393 + mild changes to get it working here properly since we use a mildly different ban system.
i did leave out the part where admins anywhere can see looc just to avoid flashbanging them with vile shit + left out the 'dead and unconcious players can't looc' only because i've seen it used properly to ask to rr or requesting rr or going  'sorry wasn't in my body' - so it stays cus i see use and hope …

(Staff Tool) LOOC Muting & Banning

---

code/datums/status_effects/rogue/roguebuff.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/living.dm
code/modules/surgery/surgeries/healing.dm

Some float logic in complex damage pain hud overlay meant that the flash wasn't properly going away when at full health. This helps the logic, and throws around some more places where that pain can go away.
https://github.com/user-attachments/assets/e817542c-d514-4b92-8ba4-e5b5967396de
Red flashbangs

Tightens up painflash logic

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/noble.dm

Replaces knight errant's belt with a steel tasset belt instead of a gold belt.
It's a single line change.
- Matches their armor a lot better and just looks nicer overall.
- Can't be immediately traded to the merchant roundstart for a ton of extra mammon for free.
- More in line with gear that actual knights have access to. Why does knight errant spawn with a special belt that is normally reserved for the duke and the marshal?

Replaces knight errant's belt

---

code/modules/clothing/rogueclothes/armor.dm

Coat of plates now properly inherits the stats of regular brigandine not making it objectively worse choice
It's basic inheritence.
This was already supposed to be the case pretty sure.

Coat of Plates

---

code/datums/wounds/types/punctures.dm
code/datums/wounds/types/slashes.dm
code/datums/wounds/types/special.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/human/npc/_npc.dm
code/modules/mob/living/carbon/life.dm
code/modules/mob/living/emote.dm
code/modules/mob/living/life.dm
code/modules/surgery/bodyparts/_bodyparts.dm
code/modules/surgery/bodyparts/head.dm

This was done as part of my NPC AI improvements PR before it was moved from here to Ratwood. Basically:
- Makes special wounds more painful, because they're special.
- Makes pain checks use CON instead of END, because a lot of NPCs have insane amounts of END so it's not super easy to just make them OOS in combat.
- Increases the maximum pain level on the chest/head, so targeting chest/head on NPCs can more reliably put them in painstun/painflee.
This is part of bringing over/finishing/etc the NPC AI stuff I had planned for here and PR'd on Ratwood.

Tweak pain thresholds and make them use CON instead of END

---

code/modules/spells/spell.dm

Mages can't cast with both arms non-functional
Mages can't cast with both arms non-functional. 
Someone pointed out nugget mage can cast lol

Mages can't cast with both arms non-functional

---

code/modules/jobs/job_types/roguetown/youngfolk/apothecary.dm

Since we already have named clothes in the game for this specific role, why don't make them wear it on the roundstart? Also, no more open ankles under robes, not the best idea to collect herbs from forest/garden when they are thorny and having your bare flesh open to them. Hood is a nice finishing move, along with plague mask in the bag to seal the drip, making apothecary a worthy apprentice to the physician by looks and skills.
Drip = good.  Flashing out clothes that were only craftable before.

Drip or Drown - updated apothecary starting clothes

---

code/game/objects/items/rogueweapons/shields.dm

- Added Smash Intents to all shields. No integrity damage modifier.
- Applied unused metal shield intents to Buckler & Metal Shield, so you hear the metallic clonk when you bash / smash.
- Changed the Associated_Skill of buckler from 0 to shields by default, this MIGHT fix the get_skill_level(0) runtime. 
- Added examine text to buckler to explain its obscure mechanics of using mainhand parry skill.
- Applied no AP to bash and smash for consistency with blunt rework
Sovlful. 
Better player transparency.

Shields Stuffs

---

_maps/map_files/dun_world/dun_world.dmm

Removes a few valuables from the keep, there's absolutely no reason for these to be around in both a gameplay and realistic sense.
Moves the scomstones from the sergeant's drawer and into the locked cabinet, instead gave them beer for their chronic alcoholism due to managing the garrison.
Gives bathhouse their lil crate of freeby drugs back.
Replaces the Drow in the baroness' room with instead a dwarven knight.
Slightly buffs the loot for fighting with the drake gang.

Minor Map updates

---

code/__HELPERS/text.dm
code/modules/client/preferences.dm
code/modules/paperwork/paper.dm

Does what it says on the tin.
`-=FFFFFFtext=-` to do so. `FFFFFF` is of course where your colour code of choice goes. Works with all other formattings, does work on paper.
Example shows using this with nesting as well as other formatting option and multi-line.
More customisation in paper and FTs are good. These colours are not restricted - and *can* be a bit painfully if asked to.
Sanitised, and does not have a decent chance in malicious HTML/XML code injection.

Add custom colour to FT/Paperwork

---

code/modules/clothing/rogueclothes/hats.dm
code/modules/clothing/rogueclothes/neck.dm

Helmets (base) hide ears and hair. Children helms that override flags_inv and aren't already meant to hide hair won't be affected.
Full-face coif hides snout.
Not extensively tested. But will work.
Helmet not hiding hair/ears made them look silly.  Same for the full-face coif.

Make base helmet hide hair/ears + Fullcoif hides snout

---

code/modules/roguetown/roguestock/stockpile_rawmat.dm

Follow up on my other economic PR to make stockpile actually used for WITHDRAWING MATERIALS.
- Remaining materials's withdraw price is lowered to match payout price, to cement stockpile's role as a way to exchange goods. The crown **do not** need to make more arbitrage profits. By default the price should favor stockpile as a way to feed materials the town need and withdraw materials producer need. 
- Stone's stockpile limit raised to 30 so there's a little bit of incentives to sell some stones instead of none to supply some building materials.
Compiles
Because it is.

Raw Materials Withdraw reduction + Stone 30 limit

---

code/modules/clothing/rogueclothes/hats.dm

Very simple change/buff/revert(?). All it does is up the armor on the wolf helm from ARMOR_HEAD_CLOTHING to ARMOR_HEAD_HELMET_BAD.
I changed a single line of code.
Before the standardisation, the Volf Helm had the same stats as the Leather Helmet. Its description is: "A leather helmet fashioned from a volf's head." It's a leather helmet with a volf helm stitched on it. Further, codewise, it's a child of the leather helm and mechanics wise and its crafting recipe is found in leather_armor_recipes.dm, the filepath for **leather armor**. Not to mention, it takes more to craft than the leather helm.
It should have the same armor as the leather helm and the saiga head, thus the change. I can only imagine this was an oversight during the armor standardisation.

Volf Helm adjustment

---

code/datums/skills/craft.dm
code/modules/farming/fermenting_barrel.dm
code/modules/farming/plough.dm
code/modules/farming/tools.dm

Adds descriptions to farm tools in the ways on how to actually use them (some were very obscure like plough).
Fermenting barrels now require lvl 3 cooking (Journeyman) to ferment anything in.
Updated cooking and trapmaking descriptions.
The tools are obscure in some of their uses so some clarifications for new players is probably a good idea since it's not all too intuitive.
With how much I buffed fermentation in barrels it did lead to tapsters being out of the job pretty much since even little amounts of produce could fully satisfy the demand of alcoholics. This way you have to either grind it out or take a virtue to be able to do it.

Farm Tools & Brew

---

code/modules/clothing/rogueclothes/hats.dm

Was supposed to be done so in the previous PR.
Tested.
Reverts to the status quo of no-hair/ear hiding on helms since MMB hides them, now.

Lets helmet not hide hair/ears by default

---

code/modules/spells/roguetown/acolyte/astrata.dm

Anastasis has some painful failures for casting on inactive minds, unlike lux which rejects and then allows you to go ahead with the next lux revive attempt. This fixes that.
It compiles. All of the lines are before a return false, so that checks out.
Helps the church in dealing with the after-effect of slaughters, not have their resurrect eaten by an inactive mind. This was never the case before the ask to check if someone wants to respawn. But now, and especially with some of the other bugs spoken about in anastasis, this will help a little.

QOL refunds for Anastasis on cast failures

---

code/modules/spells/spell_types/wizard/invoked_aoe/thunderstrike.dm

Updates thunderstrike to hopefully become useful
* Reworks Thunderstrike into a high-damage ranged AOE without CC
* Damage occurs in three concentric rings spreading out from a central point
* Damage falls off sharply as it spreads out; high single-target damage, lower AOE damage
* There is no (intended) associated Crowd Control mechanisms; this is the Blade Burst of lightning spells, as it were
* It now costs 6 spell points, up from three
* Cast time has been increased to 3.5 seconds
* Specific numbers are: 80 damage in the center, 40 in the middle ring, 20 in the outer ring
* Short central delay of 0.4 seconds, with an additional 0.4 seconds for each ring: 0.8 and 1.2, respectively.
* Damage was tested at all applicable ranges and works fine
* Delays and warning icon placement were …

Thunderstrike Revamp

---

code/game/objects/structures/flora.dm
code/game/objects/structures/fluff.dm
code/game/objects/structures/roguetown/rogueflora.dm
code/modules/spells/roguetown/create_wise_tree.dm

Fixed the issue of the wise tree and inverted psy-cross (zizo) being missing. Was a minor bug. Also should fix the spawning on wise trees by the dendorite spell given via personal objective. 
shrimple fix
unintended bug due to bad pathing on both.

Fixes Wise-Tree Sprite & Inverted Cross Sprite

---

code/datums/actions/mobs/stone_throw.dm
code/datums/ai/controllers/troll.dm
code/modules/mob/living/simple_animal/rogue/creacher/trolls/trollcave.dm
roguetown.dme

Gives the big scary cave troll their ability to throw rocks per the original port from Vanderlin. I'm not a coder so if this is bad feel free to close. Can be evaded by moving or by breaking vision with the troll before it throws it.
Adds stone_throw.dm and includes it in the .dme file.
Modifies trolls/cavetroll to grant them the ability.
Modifies controller/trolls to make cavetrolls have their own controller instead of inheriting the regular trolls. I wish I could explain why this was causing issues with granting the cavetroll abilities but I cannot, it just works™. Also changes the targeted_mob_ability to the appropriate "continue_planning" type path.
Does not map in any cave trolls.
This is good to go but I plan to modify their behavior in the future so they don't simply open with the …

Cave Troll, Stone Throw Fix

---

code/game/objects/items/rogueitems/magic/magic_resources.dm

I forgot to set base size on the magical resources I ported from Vanderlin which was ported from RW yada so they were humongous.
Properly sized things for future summoning use

Tweak Base Magic Resource Size to 1x1.

---

code/_globalvars/customization/organ_customization.dm
code/game/objects/items/rogueitems/hair_dye.dm
code/game/objects/structures/mirror.dm
code/modules/client/customizer/customizer_choice.dm
code/modules/client/customizer/customizers/bodypart_feature/hair.dm
code/modules/client/preferences.dm
code/modules/client/preferences_body_markings.dm
code/modules/roguetown/roguejobs/tailor/dyer.dm

Makes colour have a lower Luminescence limit, but an upper Saturation limit (thank u so much pooch for the help)
This disallows vantablack and neon while keeping the entire range of colours. Cyan and the like that do not look too reasonable on people will still exist, but they won't be as egregious
Also lets dye bin and brush work fully.
Tested, works.
REMEMBER - IF TM'd, ENSURE PEOPLE CHECK THEIR EXISTING CHARACTERS' HAIR/FUR/EYES.
May need further tweaking to be perfect. Plsplspls ping @reen062 on discord if its not good.
Lets people use colour without being restricted. Still prevents vantablackism/neonism

Colour Sanitization Changes

---

modular_azurepeak/code/modules/mob/living/ambushes/mirespiders_ambush.dm

Reduces by roughly half the quantity of mirespiders spawned by ambushes within the Bog. The maximum becomes four instead of seven. This does not touch the rarer special mirespider spawns.
Untested - minor code changes (single digit swaps).
While ambushes provide an interesting challenge, too many mobs at a time. Being dead in the bog does not exactly provide any roleplay value, either. I personally believe a game is more fun if the match-ups are fairer. 
"You should team up to go in the Bog!" What about wretches? What about explorers, or anyone who wants to, y'know, interact with the round? 
"You should have moved around using stealth." is not a fix-all issue for when you do summon the ambushes. Mistakes happen.

Reduces bog ambush mob quantity

---

_maps/map_files/dun_world/dun_world.dmm
code/game/objects/items/rogueitems/bags.dm
code/game/objects/items/rogueitems/ceramics.dm
code/modules/roguetown/roguejobs/alchemist/container.dm

The Potter's house and craft needed some attention. 
This PR makes a minor fix to a specific bottle in ceramics, adds more starting material to get the Potter off the ground, and remaps their home slightly. This also adds some spawnable, though not complete list, of ceramic bottles with liquid.
The map change consists of prespawned ceramic, wine bottle. A glass statue, and changes their furnace to an oven, which is the structure that is used with their craft.
Booted up local, tested. No issues.
The Potter role needed a bit of attention in a few minor ways. While they need MUCH more content, this is at least, in my opinion, a step in the right direction.
Puts them in line with other trades by giving them a slight boost to their starting materials.

Potter-Changes

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm

Changes the spawn gear back to a steel zwei. That's all.
Assumedly changed to iron by mistake, noteably the path on these suck so I get it.

fixes grenzlehoft zweihander

---

modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/beggar.dm

wrong beggar had it
Gives Beggars Thieves' Cant. There were supposed to have it but it was put in the wrong beggar.dm. Requested by funky. 
i thieves cant think of a reason

[Fix] Gives Beggars Thieves' Cant Back

---

_maps/map_files/dun_world/dun_world.dmm

Title (evil ass dirt block can be found at Z4: 157 344
[https://i.imgur.com/Cyg33xO.png](https://i.imgur.com/Cyg33xO.png)
[https://i.imgur.com/sl9Iqjx.png](https://i.imgur.com/sl9Iqjx.png)
Prevents some poor soiler from dying when the Minecraft dirtblock falls on his head

Removes evil-ass floating minecraft dirtblock on the Azure Coast

---

code/modules/roguetown/roguecrafting/alchemy.dm
modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/mirespiders.dm

These were never meant to be rare drops.
Undoes these being rare drops from when butchery was reworked.
- Also adds an alternative recipe for revival potions that just takes more glands since the arils themselves are already pretty hard to get, and hunting mire spiders is dangerous enough as is. Trolls are a little bit too finite and hard to get from ambushes.
Reuses working code.

Fixes inert glands being -too- hard to get

---

code/datums/gods/patrons/divine_pantheon.dm
code/modules/spells/roguetown/acolyte/noc.dm
code/modules/spells/spell_types/wizard/spell_list.dm

- Remove Blindness from the Mage Spelllist 
- Refactor it so that Miracle is the base spell so to avoid someone else adding it in as a spell later
Spaned in as CM and Noc Acolyte
Blindness is one of the few spells with zero telegraph besides an icon, and don't need a projectile to hit. In a 1v1, the fact you can see an incantation makes it less OP than before (thanksfully), but in a group fight slapping this spell just completely shutdown someone and get them killed. 
I've always disliked Blindness spells and any spell that I see as very hard to telegraph / counter so this remove it from the list of spells Mage can take. Noc Acolyte / Templar (?) can keep it for now so I don't take away their exclusive toy without giving them something back. 
I also leave Eyebite untouched due to it being …

Remove Blindness from Spell Mage List.

---

code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm

Adds bun n bangs to a few forgotten species.
Yep.
Dwarves are the only species with sprite requirements. The rest (Volk included) can take in buns and bangs fine

Add bun-bangs to halfelfs-tieflings

---

code/_onclick/item_attack.dm
code/modules/mob/living/carbon/human/human_movement.dm

If you lack the strength you will no longer randomly drop your weapons for moving.
Mostly a QoL update
Weapons already get a 70% damage penalty if you do not meet the requirements. We don't need something that annoys people by making them drop their items when they get slightly hungry and don't have a strap, or being forced to arbitrarily drop it mid combat because they got hungry.

Removes strength statcheck causing weapons to drop.

---

code/game/objects/items/cigs_lighters.dm
code/game/objects/items/devices/flashlight.dm

torches have their light range bumped to 7 instead of 5 and are now impervious to the rain. they are still extinguished by standing or falling in water and still have to be held to be used. this change gives them a purpose beyond a lamptern placeholder without displacing lamptern as a clear upgrade for most people.
zigs and pipes emit a small amount of light when lit and no longer lose parts of their name when extinguished.
brightens up the game without sweeping balance changes and adds a little more verisimilitude

itty bitty light tweak

---

modular_azurepeak/code/game/objects/items/ritualcircles.dm

- This just reworks the way armor rituals work on the backend
-  Now you get a selection menu of everyone with the appropriate trait in range 1.
- Maybe fixes the mysterious 'Very rarely sometimes the ritual randomly fails to select a target' bug which has illuded me for months?
- Either way, better for both user understanding and maybe fixes that bug hopefully.
This doesnt change basically anything from the user-side other than making a neat selection menu instead of randomly picking someone on the rune.

updates armor rituals a bit

---

code/modules/spells/spell_types/touch_attacks.dm
code/modules/spells/spell_types/wizard/conjure/conjure_weapon.dm

Changes Conjure Weapon to now be only capable of sustaining one weapon at a time and requiring the spell be known to sustain the weapon's existence. On summoning a new weapon, the former vanishes. On losing or forgetting the spell, the weapon vanishes. Furthermore, removes the timer altogether and lowers the cast time, as my changes leave no reason for the timer to continue existing and the lowered cast time will make the spell more useful should you find a break in combat (2-4 seconds, casting plus navigating menus) and need a weapon.
I went around conjuring the weapon in different circumstances and despawning it in said different circumstances to see if it would break.
Currently both conjure weapon and conjure armor are odd spells. They're more useful to regular mages than they are to …

Conjure Weapon - No More Infinite Bladeworks

---

code/modules/cargo/packsrogue/Sawbones.dm
code/modules/cargo/packsrogue/Things.dm

- Fixes Speed potions being incorrectly labelled as Strength potions in Sawbones Hoardmaster shop.
- Adds smoke bombs as an escape tool in the 'general' Hoardmaster shop. I meant to do this in the last hoardmaster PR but it slipped my mind, sorry.
It's like 4 lines, man. It compiles.
Stupid typo fix. Also adds smoke bombs 4 bandits in their shop, which are a decent escape tool for getting away from 1v5 situations.

Hoardmaster fixes

---

modular_azurepeak/virtues/utility.dm

One line change that gives artificer's apprentice +2 ceramics! Round two of my first PR lol
Lobby Text:
Added for a friend who wanted round-start ceramics! Really doubt this'll affect much since the potter subclass gets +5 ceramics, which means you'd have to grind to get close to that even with this change.

Give Ceramics to Artificer's Apprentice!

---

code/modules/roguetown/roguejobs/engineer/prostheticarm.dm
code/modules/surgery/bodyparts/_bodyparts.dm
code/modules/surgery/bodyparts/bodypart_wounds.dm

This PR tries to addresses that armor full coverage is 1000% necessary on AP to survive because you will get critted within 1 - 2 hits if you are unarmored.
- Instead of crit threshold applying at half max limb damage, you now need to hit 90% damage before you can crit a place
- Chest max health increased to 300 from 200. Limb base health increased from 100 to 200.
- Prosthetic limbs health doubled to match above
People are far too fragile and full armor coverage is 200% necessary to survive in this game. Longer, less insta delimb / crit fight are more enjoyable than  2 hits into delimb / crit, despite what all the armorjakking / hema / realism / lifeweb jakking people on discord tell you otherwise (they like to play armored roles too). 
This should make it more palatable to reduce armor …

Crit Threshold & Limb Health Changes

---

code/game/turfs/open/lava.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/spells/spell_types/wizard/invoked_aoe/snap_freeze.dm
code/modules/spells/spell_types/wizard/projectiles_aoe/fireball.dm
code/modules/spells/spell_types/wizard/projectiles_aoe/greater_fireball.dm

- Firestack no longer deal a flat 20 damage, and then 200 damage if above 5 stacks. Instead, it has a "curve" of dealing minimum 5 damage regardless of stack, and 2 per stack after. Up to 20 stacks.
- Fireball's damage is now frontloaded. Getting hit by one should hurt a lot - 60 damage on base fireball, 90 on GFB. They also have 2x NPC Damage Multiplier. They will demolish NPC in PVE now. Maybe people will run them?
- Snap Freeze's delay raised from 6 to 10 ticks and damage reduced to 40 from 50.
- Lava no longer round remove you. Torch you for 40 burn damage still and still set you on firestacks.
- Acid no longer RR you by skeletonizing you. Torch you for 100 burn damage per tick, and damage your items by 10% per tick so if you get yeeted into it your gears get melted if you don't leap …

Firestack, Some Spells Adjustment, Turf RR Removal

---

code/modules/clothing/rogueclothes/shirts.dm

Fancy Coat always had details but whoever made it forgot to put the detail tag in the code.
Now it can be recolored.

Fix Fancy coat details

---

code/modules/clothing/rogueclothes/hats.dm
code/modules/roguetown/roguecrafting/sewing.dm
modular_azurepeak/code/datums/loadout.dm

Does as the title says. Adds a few neat little things.
- Jester outfit can now be sewn, The tunic is a difficulty 3 and requires 3 cloth and 1 fiber. The Hat and Shoes can be made with 2 cloth, 1 fiber, and the Jingle Bells.
- Jester outfits have been added to the loadout as well for peak Xylix fashion. Z-level jumping and comedy sold separately.
- You can now MMB the Jester hat to show and hide your ears instead of them automatically being hidden.
- A little side addition to the loadout while I was at it, the TAROT CARDS. They're fun.
Compiles and works on my machine :^)
Allows for replacement outfits should the jester accidentally lose their clothing, lets people be goofy, adds soul.
Also adds more use for jingle bells because they currently are used for one whole thing.

QOL changes for Xylix-adjacent folk - Adds Jester outfit to Sewing, allows Jester hat to be MMB'd to show ears, adds Loadout Jester outfit

---

code/modules/cargo/packsrogue/merchant/luxury.dm
code/modules/cargo/packsrogue/merchant/merchant_gems.dm
code/modules/clothing/rogueclothes/neck.dm

Adds back the blortz gem, the silver psycross to luxury tab, and reduced the talkstone base price to 70 so it can be sold at the merchant for a 100.
Also moves the riddle of steel to the gems tab.
<details>
</details>
I Hate Missing Things. Also hopefully incentivizes people to buy the talkstone now.

Bugfix | Merchantry Fix

---

code/modules/jobs/job_types/roguetown/church/templar.dm

I promise I'm working on things that are actually good too! I promise!
Single line balance change (flay me)
(Okay but, really, this is just a very popular role that is very low slotted despite not being incredibly strong. Now that Orthos are still stronger than Templars, and that the garrison has 12+ combat roles, I dont think 1 more templar slot will really be that big of a deal. I guess this is TECHNICALLY a balance pr since +1 church combat role)

Self Service:tm:, +1 Templar Slots

---

code/modules/mob/living/carbon/human/npc/mad_touched_treasure_hunters.dm

fixes the cursed mask that mad-touched treasure hunters drop to only curse upon equipping in the mask slot
expanded mechanics for this and refinement of the treasure hunters themselves comes in another pr but i wanted this out so admins dont have to wrench it from ppls hands
bugfix

quick fix 4 da spooky mask

---

code/game/objects/items/rogueweapons/melee/swords.dm

The executioner's sword now has its unique thrust intent while gripped. Does 30AP instead of the usual 20AP but has a delay. This already existed but for some reason was removed from the sword at some point. Also has axe chop again while wielded.
Mordhau also just inherits from the longsword again.
The sword is now a little more functionally different from the longsword instead of being longsword that requires 12 STR to use. While gripped, the sword has a slower thrust/chop but does more AP.
Also fixes a bit of a bug where the alt-grip/mordhau was using cut/thrust despite visually being held by the blade. Other swords don't do that.

Gives the Executioner's Sword its own intents.

---

code/modules/clothing/rogueclothes/armor.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm

I put the new armor underneath heavy/coat but for some reason made it a child of just heavy. Supposed to be a coat as per the name "megarmach scale coat"
As above. Forgive my smooth brain for having two PR two hotfixes for such a simple thing.

hotfixes megarmach coat to be an actual codewise coat

---

code/game/turfs/open/lava.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/spells/spell_types/wizard/projectiles_aoe/fireball.dm
code/modules/spells/spell_types/wizard/projectiles_aoe/greater_fireball.dm

Felt like I overcorrected.
- Fire damage is now a minimum of 10 instead of 5. Each additional stack apply 3 instead of 2. Up to a maximum of 70 instead of maximum of 40.
- Lava now deals 100 instead of 40 on burn. You **can** still dramatically cross lava, but is much less likely to survive the act
- Fireball CD, which was raised to 20 seconds by Molly during April as Firestack were kinda cracked (but also unreliable back then), is lowered to 15. This applies to both Fireball and GFB.
Burned myself
I felt like I overcorrected on fire so I am now increasing its lethality back up again.

Raise fire and lava damage, again, lower fireball CD to 15.

---

code/modules/roguetown/roguecrafting/structure.dm

Adds wicker baskets as a basic crafting recipe, requiring 4 sticks and 3 fibers to make. These are pretty much everywhere on the map as-is and have been requested before (https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/issues/2090) so I figured I might as well.
If these becoming craftable somehow turns into an issue I could tie them to a specific crafting skill and skill requirement and/or alter the recipe but they really shouldn't.
Compiled, ran and functioned as intended.
Easy storage access for any class that doesn't have a dedicated home, feature has been requested before.

Gives wicker baskets a crafting recipe

---

code/game/objects/structures/roguetown/rogueflora.dm
code/game/objects/structures/well.dm
code/game/turfs/open/water.dm
code/modules/reagents/chemistry/reagents/alcohol_reagents.dm

Small stuffs
- Searching bush now autosearches until you find something. Taken from a Solaris PR.
- Drinking from a water turf / fountain will also automatically repeat drinking. Try to not drink from sewage automatically. Amount drank raised from 2 to 5 per bite.
- I made most non-beer alcohol dehydrating by accident. I have moved hydration factor up to the ethanol level as 10 - so ethanol is around 83% as hydrating as water per unit. No more thirsty at bar.
Tested
Yeah

Bush + Drinking from River / Fountain QOL, Alcohol Hydration

---

code/modules/clothing/rogueclothes/cloaks.dm

Allows Fur Cloak, Dierbear Cloaks, and Rapscallion's shawl to be worn in back slot.
Launched locally, spawned as Noble Adventurer with items in loadout, tested them all over tabard and armor. Looked fine.
Allows for further combination of outfits. For example, allows you to wear armor, jupon, and fur cloak.

Allow more cloaks to be worn in back slots.

---

code/modules/mob/living/carbon/human/human_defense.dm
code/modules/surgery/bodyparts/bodypart_dismemberment.dm

Werewolf one taps your leg. A tale as old as time. What if your armor let you have at least one bop?
/datum/species/proc/spec_attacked_by() rolls for dismemberment on each hit where there is NOT "no damage", meaning that werewolf claw overpenetration memetically one-taps your leg. This PR puts in a little check so that if the armor on that limb is better than 80%, the dismemberment is prevented IF, ONLY IF, the damage type is prevented by the crit protection on that armor. This represents your armor being in good enough integrity to withstand a severing blow.
Expensive loop fishes for the armor piece on the limb with the most integrity, so maybe your scale will save you from one and then your chausses will save you from the next. Nifty …

Snowflake Dismember Prevention for very strong weapons

---

code/modules/jobs/job_types/roguetown/other/lich_skeleton.dm

Acts on some of the supposed sore points of skeletons. Lets see if this works.
- Removes Crossbows from Ballistaires.
- Removes Grand Mace in favour of Regular Mace + Shield (and dumbs down to 12 STR instead of 14) for Bulwarks
- Removes master skills from Legionnaires.
Needs a lich test whenever.
Now that the first iteration was overcompensated. We can begin shaving off bits that make them unbearable.

Balance iteration for Lich Skeletons

---

code/modules/farming/produce.dm

Adds (returns?) splatters to grown fruits. They will squash on impact.
Fruits thrown by chars with STR 8 or below will sometimes not squash, just for the pun of it.
This PR contains _a catch_ - I had to add `var/splat_color` to all squishable fruits & set their color. Not the best decision, I think?
At the same time I can't really get primary color from an icon in runtime, as BYOND's icon operations are quite slow. 
<details>
<summary>The clip</summary>
https://github.com/user-attachments/assets/44bec128-1a52-4d5d-b773-691fdc951723
</details>
Sovl intensifies. A logical continuation of my previous pillory PR. 
It is time to pelt annoying characters with tomatoes.

Splatterification of grown fruits

---

code/datums/status_effects/rogue/debuff.dm
code/modules/spells/roguetown/acolyte/ravox.dm
modular_azurepeak/code/modules/spells/pantheon/inhumen/graggar.dm

Continuing my trend of buffing and reworking a role and then maining it 4 PRs and 1 month later.
- Ravox Spells **actually** have an incantation - they were returning parent which didn't return TRUE leading to them not using their incantation. That's why Ravoxian templars / monk are so damn silent.
- Call to Arms now actually debuff the inhumen instead of having no stat attached to the debuff. Mirror of Gagger
- Graggar's Call to Slaughter and Revel in Slaughter will now have functional incantation.
Bugfix for a templar I seldomly see played. (I see one monk)

Fix Ravox & Graggar Incantations. Give CTA an actual debuff.

---

code/controllers/subsystem/migrants.dm
code/modules/jobs/job_types/roguetown/yeomen/guildmaster.dm

Fixes #2931 - for reasons unknown to me guildmaster had advclass cat rolls set up. Despite the fact that there are no advclasses for them.
Fixes lack of postequipment for heartfelt migrants. Actually, it fixes lack of postequipment for *any* migrants without advclasses.
<details>
<summary>Heartfelt migrants, as well as any advclass-less migrants, now get their post equipment </summary>
</details>
<details>
<summary>Guildmaster gets it too after removal of faux advclass rolls </summary>
</details>
Remove all bugs.

Fixes lack of post equipment for migrants and guildmaster

---

code/datums/status_effects/rogue/roguebuff.dm
code/modules/clothing/rogueclothes/armor.dm

Fixes #2930 
Psydonian plate will no longer remove heavy armor training.
On top of that, it will no longer blatantly deprive mobs of their stats. Apparently, ``dropped()`` is called any time mob drops an item. Consequently, psydonian plate was removing endurance and constitution even when dropped from hands.
I decided to transfer stat and trait addition/removal to buff. First of all, looks better code-wise. Secondly, it is more informative for user - players will now clearly see what buffs their stats.
Also it now removes trait from source, so it should not break in case we add other items/buffs that grant TRAIT_HEAVYARMOR.
~~I can't believe I wasted thirty minutes of my life staring at trait removal code~~
</details>
Something like this.
Psydon Endures, and so do I.

Fixes psydonian plate 

---

code/game/objects/structures/well.dm
code/game/turfs/open/water.dm

Patch being contributed back upstream after I was requested to port PR #2905 to Scarlet (Scarlet-Reach/Scarlet-Reach#81). I made implementation changes because the game definitely shouldn't need to constantly recheck for mouth coverings or spam the chat when you drink.
I tested this in-game on Scarlet and it works just fine. This got a compile test because both the before code and the after code are the same.
Nice things are good. I like people.

Minimizes fountain and water-turf drinking spam (port)

---

code/modules/jobs/job_types/roguetown/garrison/bogguard.dm

* Gives wardens Cooking 1 and Butchering 1.
Just adds two skills to the subtypes. Works fine.
Gives the survivalists a slightly easier time when having to scrounge for an improvised meal. 
Remember when the Wardens used to be able to cook, farm, and make little camps for lost adventurers?
_(Probably not.)_
Wardens got nerfed a while back, which removes some of their little passive skills from being survivalists.
(I mean heck, they don't even get LUMBERJACKING.)
This just adds cooking and butchering 1 to both Warden archetypes (is that the right word?) so they can at very least, have a higher chance to skin animals better, and fry meat of cooking sources with less of a struggle.

Gives Wardens Cooking/Butchery 1.

---

code/modules/roguetown/roguecrafting/sewing.dm
code/modules/roguetown/roguecrafting/structure.dm

- changes the name of bed crafting recipes to be bed, [subtype] instead of [subtype] bed or similar
- fixes a () error w/ the recipe listings
- compiles
- easier time crafting beds and bedsheets sou  cna hug ur friends :) i love my frenz

better categorizes bed crafting & fixes 1 parenthesis from my bedsheet pr

---

code/modules/mob/living/ambush.dm

As per title.
It compiled
Was always kinda weird you can just get no ambush despite deliberately triggering it because someone else somewhere in the world triggered an ambush in the last 3 minutes. 
Now this make ambush slightly more farmable if you are hungry for a fight and also no longer dependent on a weird global CD.

Remove global ambush CD. Make ambush CD per mob every 5 minutes.

---

code/controllers/subsystem/storyteller.dm
code/datums/storytellers/_base.dm
code/datums/storytellers/gods.dm
code/modules/events/god_intervention/schism.dm

Ports [schism and influence changes from Vanderlin by Arkatos1](https://github.com/Monkestation/Vanderlin/pull/2261)
- Lowers event weight very considerably, should happen much less often now
- Challenger is now decided by influence, not number of followers
- Challenger must have atleast 1 clergy of their faith present
- No triumph rewards for those who a choose side after the half point announcement
- Loser deity also loses a bit of their influence
- **_Unlike in original PR, Astrata's followers will not get cursed. We lack god-themed curses._**
- If Challenger wins, Astrata will throw a tantrum and hides the Sun for a while
- Vice Priest can now only be chosen from the clergy and also gets a passive devotion gain
- Eora will now not trigger the schism
Influences
- Penalty from a …

Ports schism and influence changes from Vanderlin

---

code/modules/surgery/bodyparts/bodypart_dismemberment.dm

Suggested tweak to the armor dismemberment catch to take it from 80% to 30% threshold of working.
There may be some edge case where the werewolf is hitting enough damage to put someone's new armor under 80% in one hit, I don't know, I didn't see the dismember but it's possible. Anything is possible

Tweaks armor dismember catch from 1 hit to 2, or 80% to 30%

---

code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
code/modules/jobs/job_types/roguetown/nobility/steward.dm

Just gives the two warden classes +1 riding.
Also smacks a duplicate steward riding skill I saw while double checking riding values.
listen u know im good 4 it but this is a two line change...
wardens are on the exceptionally short list of people woh might **actually** want to use a saiga given their domain is outside, and they get one for free besides. Might as well have a serviceable skill in it, the same as various passive court roles. In the future they could probably get a dedicated class, but wardens are kind of due for minor QoL with weapon selection and stuff like their sisters. Right now, though, that'd mean a +5 perception mach speed horse archer and fuck that

Minor warden riding buff

---

code/game/objects/items/rogueweapons/melee/swords.dm
code/game/objects/items/rogueweapons/ranged/ammo.dm
code/game/objects/structures/fluff.dm
code/modules/clothing/rogueclothes/headwear/hats.dm
code/modules/clothing/rogueclothes/headwear/helmet/heavy_helmet.dm
code/modules/clothing/rogueclothes/headwear/helmet/light_helmet.dm
code/modules/clothing/rogueclothes/headwear/helmet/medium_helmet.dm
code/modules/clothing/rogueclothes/headwear/masks.dm
code/modules/farming/produce.dm
code/modules/mob/living/carbon/human/species_types/furry/anthromorph.dm
code/modules/mob/living/stats.dm
code/modules/roguetown/roguejobs/gravedigger/gravemarker.dm

- Stonearrow now show properly (Fix found on Solaris)
- Port https://github.com/Scarlet-Reach/Scarlet-Reach/pull/156
- Port https://github.com/Scarlet-Reach/Scarlet-Reach/pull/160
- Port https://github.com/Scarlet-Reach/Scarlet-Reach/pull/158
- Remove body_marking/bangs and body_marking/bun from body_marking_sets on anthromorph (wildkin), which was wasting me 15 seconds of development time everytime I boot up (It really adds up with the runtime)
- Gladius no longer smelt into iron
Tested
Bugfix, sovl

Bugfix Packs

---

code/modules/jobs/job_types/roguetown/church/monk.dm

Bumps up Pestran acolyte starting medicine from Journeyman to Expert. Puts them on level with the apothecary, as far as medicine and surgery is concerned. They've still got to find surgery tools, good luck
Oftentimes the Pestran has to doodle with his needle on a corpse and then go to sleep before he can start doing the lux harvest and resurrect dance. It's not really necessary for him to doodle, since this is the thing he's signed up to do.
The ultimate church powercreep balancejak PR. pls no gitban

Bumps Pestran Acolytes to Expert medicine

---

code/game/objects/structures/maneater.dm

Dismember returns true/false, made that respect whether the limb gets qdel'd. Maneater list is now shuffled, maybe it will eat a leg first this time instead of your left arm, ooh. And it will keep chewing until it eats a limb or you escape. Armor will save you pretty good from these, especially with the random eating order. So maybe they could be spun up a little faster, who knows. Something to think about.
https://github.com/user-attachments/assets/c1f1a321-d202-42f5-bb6e-4315756ddbc9
Watch out boy, she'll chew you up

Fixes maneater.dm limb eating with new dismember armor catch

---

code/modules/jobs/job_types/roguetown/church/martyr.dm

Allows martyrcloak to be worn on backslots.
Hosted, spawned it, wore it. Works.
Allows for a bit more customization.

Allows martyrcloak to be worn on backslots.

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
code/modules/jobs/job_types/roguetown/church/monk.dm
code/modules/jobs/job_types/roguetown/church/templar.dm

Cantors have been in a weird spot for a while. They get Dodge Apprentice, like Monks do, but they lack the Monk's extremely offensive abilities with Expert Unarmed. They get journeyman knives, a small debuff spell (which is meaningless if you happen to pick Xylix as your patron), and... that's it?
They could make up these deficiencies by having some miracles, before that too was nerfed. This undoes their miracle nerf and puts Cantor as a middle-point between Monk and Missionary. Not as good at fighting as a monk or templar, and not as good at miracles as the missionary with their whopping two (2) holy skill. They get music though.
This also makes a few tiny changes for flavor, mostly:
- Xylix adventurers get the Xylix **tabard** (not the cool cloak that churchies get!) and the lucky charm …

Cantors get T2 miracles, small music changes (Did Not Whiff A Merge Conflict Fix I Swear)

---

modular_hearthstone/code/game/objects/effects/track.dm

Title.
True
It's annoying to invest into a skill where it's completely useless in an area of a map that is commonly traversed.

Allows tracks on sand

---

code/modules/mob/living/carbon/carbon_defense.dm

Increases grab message readability. Currently, "I'm grabbed" message has smaller font than regular combat msgs. Despite the fact, that knowing which limb is being grabbed is paramount to effectively counter it.
Now grab messages will use span_danger(), that is currently used in send_item_attack_message() for regular combat information.
Grabbed mob will get span_userdanger() text, that is bigger and has different color - to actually see who is grabbing your limb.
How it was:
How it will be:
Chat readability == good

Tweaks grab messages to increase readability

---

code/modules/roguetown/roguemachine/questing/questing_landmarks.dm

Forgot to add kill mobs in the tracked atoms list, therefore compass was tripping and not showing direction to anything.
Also removes levitating skeletons from Radiant.
Tested, works, trust me. 
I think I need those bugs fixed.

Fixes tracking bug in Radiant

---

_maps/map_files/dun_world/dun_world.dmm
code/__DEFINES/dcs/signals/signals_global.dm
code/controllers/subsystem/ticker.dm
code/game/objects/structures/crates_lockers/roguetown.dm
code/modules/jobs/job_types/roguetown/church/priest.dm
code/modules/jobs/job_types/roguetown/nobility/lord.dm
roguetown.dme

I couldn't help but notice *obnoxious* behavior when nobles assume regency and bunnyhop to loot blacksteel drip.
While Duke's blacksteel armor is *awesome* and lets them lead their soldiers in appropriate drip... This whole "guaranteed lootdrop for regents" situation is kinda bleak. Either you roll duke and drip, or you do not get duke's drip.
A solution: subtype of closet that subscribes to ``COMSIG_TICKER_RULERMOB_SET`` and spawns blacksteel on demand. This demand being Duke's spawn - be it roundstart or latejoin.
Also, I added a wrapper to set ``rulermob`` and ``rulertype`` directly in ticker. Both those variables were directly assigned from duke job code and priest coronation. Less duplicate code is better. 
Works, here are breakpoints so you will believe me.
Players are already …

Balance: removes duke's blacksteel lootdrop for regents. Blacksteel armor set now spawns only on duke's spawn.

---

code/game/objects/items.dm
code/modules/clothing/rogueclothes/shirts.dm
code/modules/surgery/surgery_helpers.dm

Ruma clan lenticular tattoos have a couple collisions with not drawing breast layer and preventing surgery on arms. This PR handles both of those issues.
New surgery_cover var on obj/item, very expensive, very decadent. Puts check in /proc/get_location_accessible, which from my cursory inspection is only otherwise used for naughty verbs, so no surprises there.
https://github.com/user-attachments/assets/9b0ad1b8-7283-4ea1-bf38-a955d731ee23
It makes sense?

Fixes for Ruma Clan lenticular tattoos

---

code/modules/jobs/job_types/roguetown/youngfolk/prince.dm

Simply nixes the Psydon lock that was added a hot minute ago for Lords and Princes, but only removed for Lords back in #2547.
i actually did test it but i forgot to take the screenie uwaaaaaaaah
i actually fucking hate psydonites in the keep but it's an oversight

Allows Psydonite heirs

---

code/modules/jobs/job_types/roguetown/nobility/hand.dm

Hand weapons in the parent loadout were double-applying on the subsequent child loadout execution, meaning copies of the weapons were dropped at feet. Puts the weapons in the advloadout child lines, only one spawn now.
https://github.com/user-attachments/assets/a9a71877-3953-4e5f-972f-c31b982a059e
Gee Hand why does your Duke let you have TWO de taces?

Touches hand loadouts to prevent double unique weapon spawn

---

code/__DEFINES/roguetown.dm
code/__DEFINES/role_preferences.dm
code/__DEFINES/say.dm
code/_globalvars/lists/poll_ignore.dm
code/modules/admin/sql_ban_system.dm
code/modules/antagonists/roguetown/villain/unbound_deathknight.dm
code/modules/events/antagonist/migrant_waves/exiled_adventurer.dm
code/rt.dm
goon/browserassets/css/browserOutput.css
roguetown.dme

Adds yet another midround injection antag (those who appear in migrant waves).
This is basically masterless death knight that gets one objective.
With priority, we are trying to assign objective to protect/kill (prob(50) to chose between them) one player who opted in - all conscious players are polled when new deathknight is spawned.
In case no one opts in, we resort to "freeform" protection of the Northern Hamlet. I'm not sure if some mechanical incentives to keep the deathknight there are needed. Probably not!
Otherwise, it is pretty much the same deathknight but without VL to command. Same skills, same gear, 9 spellpoints and bonechill spell. They can choose from longsword & shield, steel warhammer & shield, halberd. Also I gave them knight-like helmet choice because it is cool. …

Midround injection antag: refurbished death knight

---

_maps/map_files/dun_world/dun_world.dmm
code/modules/cargo/packsrogue/_pack.dm
code/modules/cargo/packsrogue/merchant/armor/merch_armor_iron.dm
code/modules/cargo/packsrogue/merchant/armor/merch_armor_steel.dm
code/modules/cargo/packsrogue/merchant/merchant_gems.dm
code/modules/cargo/packsrogue/merchant/merchant_potions.dm
code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_foreign.dm
code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_melee_steel.dm
code/modules/roguetown/roguemachine/merchant/goldface.dm

-  Splitting up Tailor's Silverface (Apparel, Wardrobe and Light Armor). Now they can lock it to protect their own job if they wish.
- Splitting up most Metallic gears (excluding foreign weapons) away from the Merchant's Silverface to Smithy's Silverface. Lockable by Crafter's Guild key.
- Mandated Public Profit was a mechanic implemented to deal with some **very** strong wording certain very vocal players had for me as a compromise to avoid removing steel gears entirely from the Silverface. It was concurrent w/ a massive raise in the base price I used for steel armor ingot to 40 + 1.25x which made them pretty damn hard to afford for anyone but Roguetown Georg who speedrun a dungeon
- I removed the MPP variable and any effects it had. Steel Armor and Gears still remain quite expensive due …

Splitting the Silverface + Death of MPP

---

code/__HELPERS/customization.dm
code/_onclick/hud/screen_objects.dm

"Makes the eye on the hud display the characters eye colour
Credit to useroth for basically carrying this entire bugfix" - wow50000
Ported from https://github.com/Rotwood-Vale/Ratwood-Keep/pull/3076
Ignore missing HUD (it's local build issue)

[Port] Fixes HUD eye displaying incorrectly

---

code/modules/roguetown/roguemachine/steward/steward.dm

Have you ever been confused by Slampig the Squreplougher (footman) in the nerve master interface, trying to understand who that is - a knight, a man-at-arms or a random hobo?
No more! This makes nerve master output characters' jobs only in compact mode. Regular mode will display jobs like knight (royal champion), because I think that paying royal champions less than other knights is a good practice.
It worked and was not borked!
Compact:
Not-so-compact:
I have no idea why nerve master was outputting adjobs - that is likely a design oversight. Steward mains complained about it in the past. QoL is good and so on and so on.

Showing steward some love or nerve master now shows jobs, not advjobs

---

code/modules/roguetown/roguemachine/scomm.dm
code/modules/roguetown/roguemachine/titan.dm
modular_azurepeak/code/modules/clothing/rogueclothes/crown.dm

Gives Throat announcements 5 minute cooldown like the rest.
You get a message if someone starts speaking into their crownstone (not for matthiosans) and the actual crown
Every other announcement now has 5 minute cooldown so it's not so annoyingly spammable.
It is mechanics to call for help this just makes it obvious.

Throat and Crownstone

---

code/datums/emotes.dm

Mute characters can now use audible emotes. This also fixes up some kind of unused code so that it properly understands if you've been muzzled by cloth/other items that mute you.
I launch as a mute tailor on the test map, try to speak. I still can't speak. I can however roar, giggle, etc.
My evil Graggie berserker should b able to roar. She still cant speak doe.

Mute characters can now use audible emotes.

---

code/game/objects/shapeshift_holder.dm

Back when shift code was refactored, or scrunched, the aheal found its way back in. Removing it, now shape shifting isn't a free omni heal. Unless we set one to be so! Which could be interesting.
https://github.com/user-attachments/assets/59edd7be-21e0-4f40-8e61-d7fdfd1179a5
This was removed before the refactor, but got put back in during the scrunching, so good to remove it now that we found it again.

Removes the free aheal in un-shifting

---

code/modules/mob/living/carbon/human/life.dm
code/modules/mob/living/carbon/human/npc/_npc.dm
code/modules/mob/living/carbon/human/npc/deadite.dm
code/modules/mob/living/combat/dodge.dm

- Fix NPC stamcritting themselves by making NPC actually call update stamina and update energy (Their stamina never regenerated)
- Fixes existing Juking and then port the new, improved multi-step juke from Ratwood by Sutures.
All credits to Sutures for the original code. Main PR is: https://github.com/Rotwood-Vale/Ratwood-Keep/pull/2972/files for Juking
No more NPC stamcritting themselves easily and improved difficulty - but in a fair manner. 
Radiant Quest adjustment will be coming next :tm:

NPC Improvements - Port Juking from Ratwood & Fix NPC Stamcrit

---

code/__DEFINES/atom_hud.dm
code/datums/hud.dm
code/modules/antagonists/roguetown/villain/vampire.dm
code/modules/antagonists/roguetown/villain/vampirelord.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/surgery/organs/eyes.dm

Partial port of
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/2298
- Ports over the set_eye_color proc which this relies on as well
- Fixes Vampire eyes, disguise, and VAMPIRE HUDs to actually work properly.
- Disguise now actually makes your eyes your normal color, so you arent creamy-eyed the obvious.
- You get sick ass evil red-eyes now instead of the uggo dead eyes.
- Changes the 'MONSTER' text on thralls to 'LICKER', so anyone can tell the difference between the big boss and the little shits.
- ALSO fixes up death knight stuff + gives them working HUD/etc
Balance thing:
- Re added critical weakness to vampire lords/thralls. I thought they already had this, as it was the main thing that balanced them out in the past. Without heart crits, it is currently impossible to kill a …

Vampire lord + spawn adjustments/fixes

---

code/modules/events/antagonist/solo/lich.dm

Someone forgot to rename Knight Captain in Lich.dm role restriction therefore captain was able be Lich all the time
It's literally just one word fix in one file...

Bugfix role restriction for Lich

---

code/modules/clothing/rogueclothes/gloves/chain.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm

Unify all chain gauntlets recipe to 2x efficiency. Make them unsmeltable
Material exploit bad. Inconsistency bad.

Chain Gauntlets recipe to 2x. Chain Gauntlets cannot be smelted.

---

code/game/objects/items/rogueweapons/melee/flail.dm

- Repairing the matthios flail now takes weaponsmithing.
- That's it
- one line
aaahhghngfhnghfnghngfgnfgnfhd I LOVE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TOYS!

BUGFIX - Matthios flail repair

---

code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
code/modules/jobs/job_types/roguetown/garrison/sergeant.dm

- MAA footman and cavalryman now get the choice between three chest armors: Scalemail, Lightweight Brigandine, and Iron Hauberk. 
- MAA Skirmisher gets the pick between 'medium' or 'light' armors, which will dictate their chest and leg armor to either hardened leather or LW Brig for chest and chain chausses for legs.
- All MAAs now receive a gambeson instead of an arming jacket.
- All MAAs get to pick between jack chains, brigandine rerebraces and steel bracers for arms coverage.
- Cavalryman and Footman have also been given a choice of legwear, between chain chausses and brigandine chausses.
- Skull Cap has been added to MAA helmet selection.
- MAA Footman was given iron-plated gloves to reflect the close-quarters. MAA Cavalryman was given iron chain gloves.
- MAA Skirmisher was given …

Man-at-arms and Sergeant changes

---

code/datums/components/rotting.dm
code/modules/antagonists/roguetown/villain/zombie/remove_rot.dm
code/modules/antagonists/roguetown/villain/zombie/zombie.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/human/npc/deadite.dm
code/modules/mob/living/living_defines.dm
code/modules/surgery/surgeries_hearth/cure_rot.dm
modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/undead_animal_helpers.dm

Clicking on your heart or using diagnosis now shows if someone is slowly turning into a deadite.
Fixes cure rot surgery causing people who weren't yet deadites dying, and then reviving when the timer finished
I used "[m1] slowly rotting away" as the examine text, but if there's something more fitting I can change it
The only way I found to test infection wasn't great, so it's possible I might have missed something.
Tested being infected gave the Infected var properly
checked that having infected var made examining self and using diagnose on self not give double message
used diagnose on another carbon with infected var to check the message showed up on diagnose and hammer showed the message
Spawned deadite NPC, possessed it, bit a carbon until they got an infection. Then cured the …

Health examine shows rotting and cure rot fix

---

code/game/turfs/open/water.dm
code/modules/spells/roguetown/acolyte/abyssor.dm
modular/Neu_Food/code/raw/raw_fish.dm

What it says in the title.
- added var/sinkable to fish, set to TRUE by default
- flag sinkable is set to TRUE after the fish is finished being thrown
- /turf/open/water/Entered now checks if fish is sinkable
- aquatic compulsion sets sinkable flag to FALSE before throwing the fish
Summoned some fish from further away, got hit by some, released some, had fun times all around.
Code compiles, releasing mechanic still works, and summoning fish with aquatic compulsion works from further water tiles.
Aquatic compulsion is now more intuitive to use as you no longer have to summon fish from the water tile bordering land. You can still release them afterwards as the sinkable will be changed to TRUE at the end of aquatic compulsion "throw".
Initially wanted to include this change in my other …

[Bugfix] Fish summoned by aquatic compulsion are no longer instantly released when summoned from further water tiles

---

_maps/map_files/dun_world/dun_world.dmm
code/game/objects/items/rogueitems/keys.dm
code/game/turfs/closed/wall/roguewalls.dm
code/game/turfs/open/floor/roguefloor.dm

This PR dramatically changes the silhouette and internal layout of the merc-house, as well as adding 8 new keys
-You will now enter into an [airlock-style](https://i.imgur.com/7nwBqmV.png) lobby/waiting room
-[A larger, more central dining room with enough bowls, spoons and mugs for 8 mercs](https://i.imgur.com/JL7s7pb.png)
-[A basement jail-level which is largely unchanged from the mostly unused second floor jail](https://i.imgur.com/hwsJXMf.png)
-Larger [2nd Floor](https://i.imgur.com/4aNzmT0.png) and [3rd Floor](https://i.imgur.com/mwhwE9h.png) to accommodate the new 8 private rooms with keys, allowing a merc to store items without worry of being nicked. Or like..you know
-A lot of the windows now have curtains behind them for privacy.
-Added salt to the kitchen chest along with 3 …

Merchouse+ (drastic remodeling of the merc-house and minor changes to the surrounding grassy area to support)

---

code/game/objects/lighting/rogue_fires.dm

Tiny in-line pronoun string fix.
Fun fact, aside from the base macro, these were the last three versions of byond's \his in the repo.

fixes fire hand warming string to respect pronouns

---

code/game/objects/items/rogueitems/undies.dm

This PR fixes grid size of underwear and gives weight of it
Before: 
Now: 

Underwear size bugfix

---

_maps/map_files/dun_world/dun_world.dmm

This PR makes large changes to dun_world.dmm by replacing tiles which have instanced iconstates with preexisting subtypes of that particular iconstate, for example, 995 instances of wooden tiles with the spiral iconstate being replaced with ruinedwood/spiral 
It should be noted I only replaced instances with already existing coded subtypes; this PR doesn't fix every instance (there are a lot). I'd be more than happy to trim out as many as possible if this PR is something that's wanted.
https://i.imgur.com/fUBy4qY.png
https://i.imgur.com/0cNDr4f.png
https://i.imgur.com/GI9R0N0.png
Compiled, 
Flew around, didn't notice anything weird
This should assist with load times (slightly) and potential merge conflicts by reducing the number of[ lines in the DMM file.](https://i.imgur.com/giUEcrj.png) …

Replaces instanced turf icon_states to pre-existing subtypes

---

code/datums/components/crafting/crafting.dm

This PR fixes crafting causing natural bundles to disappear if they reduce to 1 item in-hand 
"Have a bundle of natural materials (fiber, cloth, stone block, leather, etc).
Hold the bundle in your hand.
Craft something that costs 1 more than the stack contains (eg. craft a cloth with 3 fiber in hand):
The single natural item that remains disappears into the mob's contents, never accessible again, instead of being placed into their hand or dropped.
I imagine you can gib the player to get the contents back but that's certainly not intended behavior.
This PR simply places the single remaining item back into the person's hand or drops it via mob.put_in_hands()." - Tastyfish
Ported from https://github.com/Rotwood-Vale/Ratwood-Keep/pull/2654
Check where it was ported ^
Bugfixes are always good, …

Crafting natural bundles dissapearance bugfix

---

code/modules/cargo/packsrogue/merchant/adventure_supplies.dm
code/modules/cargo/packsrogue/merchant/armor/merch_armor_iron.dm
code/modules/cargo/packsrogue/merchant/armor/merch_armor_light.dm
code/modules/cargo/packsrogue/merchant/armor/merch_armor_steel.dm
code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_melee_steel.dm

Light brigandine was changed to steel in a PR last week and it hadn't been reflected on the SILVERFACE and GOLDFACE yet. This fixes that, adds the new splinted gear to iron armors, adds chain kilts, adds heavy padded coifs and short satchels to the 'faces, and fixes a tiny typo on the kriegsmesser.
Bought Everything. It Just Works.
Fixes steel being cheaply buyable. New armor types hadn't been added to the merchant yet.

Silver/Goldface armor fixes & misc additions

---

code/__HELPERS/AStar.dm
code/__HELPERS/game.dm
code/modules/mob/living/carbon/human/npc/_npc.dm

i made these commits ages ago and never pushed/PR'd them until ansari reminded me. i also had a fix for the stam regen thing but ansari beat me to that too
- inLineOfTravel (proc used to check if leaping is blocked) now uses the exact same checks as throwing, so NPCs won't leap into walls or solid objects as much
- A* won't get stuck as much on objects in the mover's turf
- **EXPERIMENTAL:** carbon NPCs will retreat (similar to fleeing but they go back to combat at the end, plus they walk instead of sprinting
- attempts some fixes for npc leaps getting overwritten by the NPC walking, which teleported them back to the start of their leap. unfortunately it seems to still happen sometimes
i tested these like 20 days ago so i don't have any screenshots :)

NPC AI leaping fixes and tweaks

---

code/modules/spells/roguetown/acolyte/necra.dm

I had these in there before so i readded some PRETTY MUCH spitout mob has to have it as user not trapped (I made that mistake one time), as the spitout mob timer calls USER so it can trip it up.
TWO: The safety for DISPELLING was removed cause it was spitting people out inside the caster again..
SO spitout now checks for dispelled, this is set to false on inital creation and recast. if the portal was dispelled we yeet it at the casters location...
compiled
oh lawd plase no more bugs with this thing please necra pls undermaiden haven mercy

Deaths Doors safety checks...again

---

modular_azurepeak/code/modules/spells/pantheon/inhumen/matthios.dm

- Equalize no longer insane on the backend to do jumbo math.
- Now its just a stat steal, -2/+2 CON/STR/SPD from a target for a minute. Basically the same effect as last time but not so niche it was barely applicable unless you built wretched around the miracle.
-  Commission by Mashi
https://github.com/user-attachments/assets/2f61c80c-14a7-4853-8b4e-bddeebb37e64
- Equalize has been mostly unusable for the longest time, I was far too careful with it at first.

EQUALIZE rework

---

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/witch.dm
code/modules/spells/roguetown/vampire.dm
code/modules/spells/spell_types/wizard/projectiles_single/arcyne_bolt.dm

Witch anymore cant cast "Zad form" when she in chains/roped. It will be possible to tie her up properly and not kill her/hope for a rag. More balance. Let her just not get caught. She is now CATCHABLE for further RP and talks. Also change arcyne bolt to able use only when u a witch, NOT a crow.
https://github.com/user-attachments/assets/762eaa21-abda-4271-896f-5515c15eb423
More RP moment, NO Drone-crow with arcyne bolt and leave from RP with turning into a crow in chains

FIX Witches. More balanced Zad-form of witch

---

code/_onclick/click.dm
code/_onclick/other_mobs.dm
code/game/objects/items/rogueweapons/rmb_intents.dm

Guard rmb intent was intended to bypass click cd. Unfortunately, this was not the case.
Solution: snowflake try_special_attack() chain that fires before next_move check happens (Opposed to a mob listening to their own signals).
- Special attacks can be fired in a 'non-targeted' fashion, by just clicking a turf. Special intent will hit a random mob on it, prioritizing standing mobs and giving lower priority to unconscious, resting and surrendering mobs.
- Guard can be raised bypassing click cd
Non-targeted feint, targeted aimed and guard through click cd. WORKS!
https://github.com/user-attachments/assets/f645c4bc-7d4d-41f1-bc6a-e5b2e2b0ee7f
Guard special attack was intended to bypass click cd, so this is, basically, a bufgix.

"Refactors" rmb_intent attack chain, allowing guard to be used during click cd

---

code/game/objects/items/rogueitems/natural/stones.dm

- Stone and Rock now scale off unarmed skills
- Force of Rock has been increased to 20 from 18, force wielded from 15 (??) to 22.
- Integrity of Rock is now 90 -> 100
- Minstr is now 11
I saw someone throwing rock at someone and it was the funniest shit ever.

Stones and Rock now scale to unarmed skills + slight rock buff

---

_maps/map_files/roguetest/roguetest.dmm
code/game/area/actualcoast.dm
code/game/area/areas.dm
code/game/area/mountdecap.dm
code/game/area/northcoast.dm
code/game/area/roguetownareas.dm
code/game/area/terrorbog.dm
code/game/area/underdark.dm
code/game/area/undergrove.dm
code/game/area/woods.dm
code/modules/mob/living/ambush.dm

- Add some grass and bushes to Roguetest for testing purposes
- Ambush_type no longer exist in areas, instead pulling from a globally defined list of turfs that could trigger ambush if you walk on grass. **This means more reliable ambush triggering instead of ambush not triggering on dirt/road (???)**
- Ambush now spawn mobs adjacent to instead of on top of a potentially dense tile
- Eoran shrine ambush list of two fae types (not used) removed
Tested
Should fix issues with mobs getting stuck due to pathfinding.

Ambush fixes & stuffs

---

code/modules/events/antagonist/migrant_waves/bandits.dm
code/modules/events/antagonist/solo/bandits.dm
code/modules/jobs/job_types/roguetown/adventurer/bandit.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/brigand.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/hedgeknight.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/roguemage.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/sawbones.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/sellsword.dm

~~Yes, this opens bandit roundstart.
4 guaranteed bandit slots.~~
Instead of using inconvenient migrant wave system - ST now simply opens 3 slots per bandit injection (up to 6 bandits in total). Previously, if no one signed up for migration - slots were lost. Now they wil be opened with to_chat() output to lobby players.
Also increases bandit roll weight. I have no fucking idea how that works and what that means, presumably - this should roll bandits more often.
ALSO removes swords 5 from sawbones. Swords 4. Sorry, my fellow physicians, you will no longer wield swords like knight captain!
ALSO ports [this](https://github.com/Scarlet-Reach/Scarlet-Reach/pull/191)
ALSO removes forced patron change from all bandit subtypes except for iconoclast. Now players will get a choice whether they …

Makes bandit injection open bandit slots instead of rolling antag wave

---

modular_azurepeak/virtues/combat.dm

Instead of an iron axe, dungeoneer apprentice users get a basic leather whip.
Something, something, "makes more sense, dungeoneers of azuria are associated with their whip usage"-
whatever, you already know

Dungeoneer's Apprentice Virtue gives Whip instead of Axe

---

code/game/objects/items/rogueitems/natural/animals.dm

Saddles now deal 1 damage.
Saddles now rely on the riding skill.
Riding can be trained by hitting a training dummy with your saddle.
There is LITERALLY NO WAY to obtain any riding skill outside of random dream rolls. This is bad.

Adds an objectively funny way (and the only way right now) to level up your riding skill

---

modular_azurepeak/code/datums/loadout.dm

What it says on the tin: the striped tunic is a simple garment (that is a child of /armor for some reason) that I think should be readily available to access.
To my knowledge it doesn't provide any meaningful protections, or at least not any more than normal clothes.
~~I would test it myself but every single time I've tried to fork and clone AP it's never made it past the lobby and DD lobotomizes itself. This is before I even change anything with my copy. The change is simple enough anyways.~~
Running the DMB directly out of VSC worked. Sort of. It blew itself up trying to equip literally anything in the armor slot though. I'm cursed!
more options more agency etc

Add striped tunic to the loadout

---

code/game/objects/items/rogueweapons/intents.dm
code/modules/clothing/rogueclothes/feet.dm
code/modules/clothing/rogueclothes/robes.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm

In order..
* Restores the option for Adventure!Monks to pick either a _katar_ or some _knuckledusters_. Following the precedence set by Felinid, these will be _bronze_ instead of _steel_. I don't actually have a sprite for the _bronze katar_ yet, but we'll get that added within the week.
* Reduces the cost of punching to _one_ unit of stamina, compared to _two_. This doesn't affect _any_ other unarmed intent: the stamina costs for _grabbing_ and _wrestling_ remain the same. 
* Removes the dyes that're automatically applied to Monkvestments _(and, as I've just discovered, Heavy Leather Boots)_. Slightly tweaks the description of Monkvestments to better reflect the hidden armor values they have.
_(Addendum: upon looking at the code, I realized that monks actually had cruddier armor than …

Dusters & Denim - Rearms the Adventure!Monks, reduces the stamina cost of punching, and undyes (+strengthens) the Monkvestments.

---

code/__HELPERS/cmp.dm
code/datums/skill_holder.dm
code/datums/skills/_skill.dm
code/datums/skills/combat.dm
code/datums/skills/craft.dm
code/datums/skills/labor.dm
code/datums/skills/magic.dm

Port from Twilight
Changes: 
- The character's skills are sorted by category and arranged alphabetically. Abilities (Labor, Craft, Magic etc) are highlighted in colors depending on the color.
- Level up ! and !! has been updated into ☆ - one level; ★ - two levels.
Better shown character's skills

Sorted and ordered skills with highlight

---

code/game/objects/items/rogueweapons/shields.dm

Forgot to add descriptors to the decrepit-and-ancient shields.
Five-line change. Should be safe.
Consistency is wonderful. I am a damn idiot for forgetting this-- like, I _felt_ something was missing, but I didn't actually know what it was until someone mentioned _"skeletons with shields"_ in #dev-general. My bad. This _should_ be it.

DECREPITY FLASH-UPDATE - FORGOT SOMETHING. AUUUUGH.

---

code/modules/clothing/rogueclothes/headwear/helmet/heavy_helmet.dm

Allows the face of the Decrepit Barbute to be attacked
Spawned in Decrepit Barbute, attacked all areas of head with knife; ears, top, and general head are protected.
The Decrepit barbute is an open faced helmet, this will also allow adventurers who don't use peel weapons (Dagger, unarmed, hammers, etc) a way to score (semi reliable, as skullcrush/skullpierce is still luck based) kills on armored skeletons. Did not touch the normal Barbute as that is used by players.

Allow face to be attacked on Decrepit Barbute

---

_maps/map_files/dun_world/dun_world.dmm
code/game/objects/effects/spawners/roguemapgen.dm
code/game/objects/items/rogueweapons/melee/swords.dm

- Fixes potion loot spawners.
- Unique mad duke's rapier is now worth slightly more than regular decorated rapiers instead of slightly less.
- This one's not exactly a bug-fix but I added regular steel sabres/rapiers in a few spots where decorated sabres/rapiers were previously prior to the dungeon pass. *Hopefully* shouldn't conflict with anything - I only edited like two whole tiles here.
Spawned in, tested potion spawners, seems to work fine.
Bug fixes good

Fixes potion loot spawners & a few other small dungeon pass oversights

---

code/game/atoms_movable.dm
code/modules/mob/living/simple_animal/rogue/farm/goat.dm

Apparently, movement to nullspace was not calling Moved(), in turn causing a harddel since atom was not leaving its spatial cell properly
Ideally, we need to port this - https://github.com/tgstation/tgstation/pull/82085
Also removes lack of goat's QDEL_HINT because it irks me

Fixes spatial harddel

---

code/modules/admin/verbs/playsound.dm

Remove the preload ambience button
On demand lag button on server shouldn't exist. This has been tested in game and causes a measurable stutter serverwide for between 5 - 15 seconds.

Remove preload ambience button.

---

code/game/objects/structures/maneater.dm

Port from https://github.com/Scarlet-Reach/Scarlet-Reach/pull/446
"Currently maneater will ALWAYS delete your limb even if it was protected or you cant be dismembered
This pr makes a proper check for dismember(), also taking in account that goblin npc cant be dismembered (we gib them right away)" - Heheniy
This PR fixes issue about goblin endless loop eating by maneater and makes limbs not deletable instantly from the world.
"You will no longer loose your limb to maneater even if your armor protected you or you have TRAIT_NODISMEMBER" - Heheniy

Maneater incorrect limbs delete fix

---

code/modules/farming/produce.dm

You can middleclick a fyritius inside mortar to grind it into nectar now
compiled, worked in local
There is a recipe for vitae decotion to cure the Lux taint rituals from heretics. But there is currently no way to actually get the nectar to create it

Makes fyritius grindable for nectar

---

code/game/objects/items/rogueweapons/melee/blunt.dm
code/game/objects/items/rogueweapons/melee/flail.dm
code/game/objects/items/rogueweapons/melee/knives.dm
code/game/objects/items/rogueweapons/melee/polearms.dm
code/game/objects/items/rogueweapons/melee/swords.dm

5 minutes PR to pretend I am being productive while I am crying and sobbing looking at hard deletes. This PR buffs the templar weapon that are equal to their normal counterpart or in one case worse (Ravox's Hammer):
- Ravox Hammer: 250 -> 350 Max_Integrity. Gain Daze Intent. No force increase (It is a Steel Goden do you want that). Before this it is literally just a steel goden without the ranged stab.
- Necra's Flail: 30 -> 33. Purely offensive weapon. Shouldn't be too bad
- Plaguebringer Sickle: 20 -> 22 Force. 
- Dendor's Scythe: 30 -> 33 Wielded Force. Durability 250 -> 300. (Picked a more balanced profile as it is a polearm)
- Malum Longsword: 25 -> 28 Force. 30 -> 33 Wielded Force.
- Eoran Rapier: 22 -> 25 Force. WDefense 7 -> 8. 1 to 1 to the Cup Hilted Rapier
Tested, compiled. …

Buff Some Templar Unique Weapons slightly.

---

code/__DEFINES/traits.dm
code/_onclick/other_mobs.dm
code/modules/antagonists/roguetown/villain/vampirelord.dm
code/modules/clothing/rogueclothes/headwear/helmet/heavy_helmet.dm

- Adds a TRAIT to two helmets, the Graggar heretic set + the Vampire lord's helmet. On equip, grants the user the ability to bite through their own bevor/helmet/anymouthcoverage.
- Commissioned by witty
https://github.com/user-attachments/assets/f36eb4a2-71ce-48b5-94f0-efc6f5e56aff
https://github.com/user-attachments/assets/8ba6f96a-f993-4756-946e-349fb441ab0a
- Vampire lords can do their thing without being decapped
- Graggin on my Graggar

Bite Through Helms - Graggar/Vampire Lord helmet

---

code/game/objects/items/rogueitems/ropechainbola.dm
code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_ranged.dm
code/modules/mob/living/carbon/carbon_defense.dm

Ports https://github.com/Scarlet-Reach/Scarlet-Reach/pull/192 by roarbark!
Throwing nets now take two seconds to break out of, instead of instant (or the supposed 3.5 seconds they originally were supposed to have). Buying a net at the merchant's now only gives you one instead of two.
Removed the exemption nets had from catching to allow counterplay.
<details><summary>Screenies</summary>
</details>
More fun and cool toys for you! Makes a situational tool relevant and desirable again. Not too crushing unless actively sprinting away was the only option left, and now a little less easy to hoard unless you have at least some crafting skill to make your own.
You also originally could not catch nets because of a special, net-specific exemption. Now you can, so it's a little less safer to use as …

Throwing Net fix port + nerfs

---

code/modules/admin/admin.dm

Make sure admin skill panel works on mindless mob.
Thanks to Cat and Spartan for reporting this bug. They have skill holder it just don't show up.

Make sure admin skill panel works on mindless mob.

---

code/modules/mob/living/combat/parry.dm

This was regressed as part of the roguetown procs split, leading to mob attacker not using skills on attack.
Bug

Mob attacker use skills on parry. Again.

---

code/game/objects/effects/gods/unassuming_fluff.dm
modular_azurepeak/code/game/objects/items/ritualcircles.dm

Obvious spoiler warning if you want to learn about this sort of secret fluff stuff organically.
- When appearing in their intended manner, volatile crystals can't be broken for a bit. This is to stop people from killing themselves with them whilst in the secret area.
- All items in the dream are returned with the last player to leave the area. This is a precaution to stop unique items like the master rod to end up trapped there as it's not easy to end up there.
Tested both, it would be silly of me not to test a fix...
As much as I'm a fan of consequences for throwing the evil crystals, you're not really intended to die there and it would make the secret area dangerous for anyone that visits later.

[God fluff] Foolproofs fluff area.

---

code/__DEFINES/traits.dm
code/datums/gods/_curses.dm
code/modules/jobs/job_types/roguetown/church/priest.dm

- Fixes an issue where bishop swap would get rid of innate spells, admin provided spells. This also made it so that if we ever add more innate bishop spells, we don't have to be careful about swap purging them deus vult style.
- Limits the swap with a 20 minute cooldown. This is in part to make combat swapping multiple times impossible (like dropping 4 different debuffs on the same person). And to prevent resetting cooldowns of spells.
- Swapping now makes you keep your T3-4 spells, swapping out your T0-T2 spells for those of other patrons. This process uses a whitelist that excludes certain low tier spells that have broad usefulness outside of combat or medical use. This should work seamlessly with undivided as well.
- You can however, still DEDICATE yourself to a single patron. This …

[Bishop role] - Fix miracle change bugs & functionality rebalance.

---

code/datums/sleep_adv/sleep_adv.dm

`/datum/sleep_adv/proc/adjust_sleep_xp` where homesteader xp multiplier is applied is also called with a negative `adjust` value in `/datum/sleep_adv/proc/buy_skill` causing incorrect xp calculation after buying first skill level making it impossible for homesteader to level up a skill twice in one night.
This PR adds simple value check to `adjust_sleep_xp` proc to ensure that the homesteader multiplier is only applied when the `adjust` value is positive.
Compiled, was able to level up a skill twice in one night as a homesteader.
Bugfix cause I heard somewhere that bugs are bad.

Fix homesteader not being able to level up a skill twice in one night.

---

_maps/map_files/dun_world/dun_world.dmm

I'll just list it here.
- Added light gambesons to squire armory; they had no gamby's prior and don't spawn with any.
- Added short swords, iron big mace, spears, and bardiches to squire armory
- Added 4 iron kettle helms to squire armory; they had no helms prior
- Added 4 fingerless gloves to squire armory; technically a buff, better than leather ones they spawn with
- Remove glaive from knight armory, placed partizaner in its place.
- Replaced Lucerne with Eaglebeak given it's just worse than the grand mace anyway so let them have it instead of the iron one.
- Added 2 iron warhammers to MAA armory since someone pointed out MAA can spawn with them but have no extras. It's not steel warhammers so - gave two. We get two backup knives anyway.
Also fixed the floating candle in knight armory …

Armory Fixes for New Keep/Gari Map

---

code/game/objects/structures/mineral_doors.dm

- Remove the gc_destroyed variable literally making them undeletable
- Gave them 150 obj integrity so they are not destroyed in one left click
- Set repairable to false to achieve the same ffect of making them unrepariable.
- Gave them a new desc.
Door that defeats admins are perhaps too strong for the balance of this server.

Makes broken dwarven fortress door actually destructible and deletable.

---

code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/valuables.dm

For some reason Terminus Est used Blacksmithing instead of Weaponsmithing
trust
bug fix

Bugfix - Makes Terminus Est require Weaponsmithing instead of Blacksmithing to craft

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm

Fixes saber loadout not giving you your expert swords and apprentice shields.
Renames the Naledi armour option to Raneshi since that's what that actually is.
Bugged for long time now, the other just misleading

Bmaster - Raneshen

---

code/game/objects/structures/fluff.dm
code/modules/roguetown/roguemachine/ATM.dm

Modified description of the covetous crown to mention that it can be used on people (I had no idea) since players get mechanical info from these descriptions. Added the silver and gold bowl candles to the idol's pool since it wasn't intended for these to not be offerable while the candlesticks are.
Description for the crown, courtesy of @radarseas 
compiles just fine.
Player facing mechanics should be explained in a player facing way. Also things gotta be consistent!

modified covetous crown desc, added candles to idol pool

---

code/modules/jobs/job_types/roguetown/church/priest.dm

Polytheist bishops now always get immolation & anastasis as t4s in addition to being able to swap between various t0-t2 spells from other patrons.
It's a couple line change in working code that compiles, chief.
Stopgap measure until undivided can be given a unique T4 spell.

[bishop] Gives them immolation when polytheist

---

code/game/objects/items/rogueweapons/shields.dm
code/modules/jobs/job_types/roguetown/church/martyr.dm
code/modules/jobs/job_types/roguetown/church/templar.dm

- Re-Tools the unused decashield sprites of the Holy See for Undivided.
- They're now just kite shields, statswise.
- Martyrs and Undivided templars spawn with this, instead of the regular kite.
- Swap between Noc and Astratan form with mmb!
Drip(which matches the Martyr set and ideally will match the See/Undivided sets of later.

Decashields for Undivided/Martyr

---

code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_foreign.dm
code/modules/mob/living/carbon/human/npc/drow.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm

- Removes glaives from anvi recipes
- Removes glaives from drow NPCs, replacing it with bardiche (which is iron, btw!)
Why? Because glaives are, frankly, best polearms in the game. 
It is a problem if they are easily accessible (Knight's armory, for example, but thanks to Rebel for rectifying this) - by smithing or looting drow NPCs. Not a problem if they are limited in supply.
After this change glaives will be obtainable:
- By spawning as a melee boak
- Through high tier general loot spawners (borderline acceptable since those spawners are rare and have other unique weapons)
- Buying it as a sellsword bandit (seems acceptable since hedge knights can get grenzel zweis)
- Importing via merchant (on par with other unique weapons)
Trust me brother!
Discussed above.

Removes glaive from anvil and drows

---

modular_azurepeak/code/game/objects/items/scabbard.dm

Bug-fix including:
- Not being able to repair scabbards.
- GWStrap eating a sheathed longarm.
Tested.
Zigbux

Fixes 2 bugs with scabbards/gwstrap

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
code/modules/spells/spell_types/divine/projectiles_single/divine_blast.dm

- Cleric with Divine patron now get access to Divine Blast (You won't have enough devotion to spam it, sry)
- Dendor Bolt now just applies Slowdown(2) instead of Immobilize + Offbalance for 1 second which is extremely strong if you know what you are doing.
Gives cleric a lil bit of offensive bite. It won't compare to mage, but at least they got heal. 
Also Dendor nerf is a request cuz it is absurdly stronk.

Give Adv. Missionary Divine Blast + Dendor Nerf

---

code/game/objects/items/beartraps.dm

I saw https://github.com/Scarlet-Reach/Scarlet-Reach/pull/603 but thought the code wasn't good so I did my own version.
- Armed Mantrap now have a height of 256 x 256 to make it impossible to fit inside sack or anywhere, hopefully pre-empting any armed mantrap cheese
- They resets back to w_class_normal and grid height / grid width (set manually instead of on compile, so that mapped trap is usable in theory?)
I load up my six shot revolver and mow down every powergamer who isn't me.

Force armed mantrap to be too big to fit anywhere.

---

code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_foreign.dm
modular_azurepeak/code/game/objects/items/scabbard.dm

Hi, so I was wondering where all the Ruma Clan mercenaries were, and now I see why. 
Their scabbards? Their main gimmick? Broken, absolutely-so, especially if you manage to break it in combat and repair it. Once it's repaired, you can't even slide a weapon into the scabbard nor parry with it after.
So this is a band-aid fix until someone can do this better than me, because honestly this is a shitty way to do it. 
Reduced the defense from 9 to 8, so it isn't as gross as before. I may lower it in the future.
Made the integrity to 0, so that it has FUNCTIONAL INFINITE DURABILITY as it did before. 
And I made the foreign goods for the normal scabbard a lot more expensive, though at this rate I may just remove it to encourage Kazengunites to not lose their unique scabbard. I haven't since I …

MAKING KAZENGUN SCABBARDS GREAT AGAIN (MAKING THEIR GIMMICK ACTUALLY FUNCTIONAL)

---

code/game/objects/structures/roguetown/meathook.dm
code/modules/mob/living/simple_animal/simple_animal.dm

- Port Continuous Butchery by EIDIS from https://github.com/Scarlet-Reach/Scarlet-Reach/pull/576
- Meathook now improves butchering speed by 25%. It still improves yield as per before. This is now shown on an examine text.
- Spreading out the butcher results is less abrupt and more immersive.
- Gives another reason to make a dedicated meathook to save time.

Continuous butchery Port + Meathook Buff

---

code/modules/food_and_drinks/food/snacks.dm
code/modules/roguetown/roguejobs/cook/tools/grinding.dm
modular/Neu_Food/code/NeuFood.dm

- Reduce base time for short cookstep to 2 seconds from 6 seconds
- Long cookstep 10 to 3 seconds
- Slicing base time 3 seconds to 1 second. Scale to cooking skill
This will massively inflate the food economy.
Serious Answer:
Food are but a mechanical set piece to roleplays that it creates and in AP's environment whatever makes the Innkeep prepare food faster and spend more time rping is better. RT food creation time is **far** longer than base SS13 and that is not conductive to good roleplay imo. 
This is a substitute (?) or part of a complement to more further food rework sometimes down the line.

Chopchop - Speed up cooking steps by 3x + Slicing scales to cooking skills

---

code/_onclick/hud/plane_master.dm

Port https://github.com/Scarlet-Reach/Scarlet-Reach/pull/580
Although I just outright remove the filter this time instead of commenting it out.
I cannot replicate the absence of a crash. TM this like on SR.
No crash.

Port SR Fix for Baotha's Blessing crash - by removing the animation.

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/routier.dm

Remember when Mercenaries weren't bloated? Me neither.
- ~~Routiers get +1 Riding skill, up to *Journeyman*. If this somehow makes Routiers 10x stronger than they already are, lemme know.~~ Nevermind. I tried it a bit more. The difference is day and night and Routiers are already strong.
- Halberdiers of the Grenzel variety get +1 Athletics, up to **Expert** to be on par with Zwei users. If this makes it suck 50% less, great!
- **NEW GRENZEL CLASS!** *Armbrustschutze!* Stands for *crossbowman*, literally.
- CROSSBOW ~~OR SLURBOW~~ AS PRIMARY! JOURNEYMAN AXE SO THEY CAN DEFEND THEMSELVES WITH A STEEL AXE! UTILITY SKILLS BECAUSE THEY'RE MEANT TO BE A SUPPORT SORT OF MERC!
- BUILD A FORT FOR YOU AND YOUR MERC BUDDIES! GO HUNT FOR FOOD! STITCH HOLES IN CLOTHES!
- **NO MEDIUM ARMOR, NO DODGE …

New Grenzel crossbow class, and halberdier's athletics!

---

code/modules/spells/spell_types/wizard/invoked_aoe/repulse.dm

Second attempt to nerf it to remove the hardstun. Now it just force you to rest instead of making you drop your weapons. CD reduced by 5 seconds to compensate. This should retain all utility as an escape tool and CC tool while making it less of an autowin button.
Death to hardstuns.

Repulse now set resting instead of paralyze. CD 30 to 25.

---

modular_azurepeak/code/game/objects/items/ritualcircles.dm

- Shrimply. The max amount of demons one spire for a heretic can have now is 7, down from 10.
- Abyssorite crystal spire markers can't be made before 30 minutes into the round.
There's been a lot of jassing about how there's a lot of these and it's kinda harsh on town and sometimes it murders everyone on lowpop. Which is fair. This small nerf should make the impact of an abyssorite saving up crystals for most of the round less... silly.
2:30 mark : 6 crystals => 5 crystals.
If more nerfs are needed I'll work on it. One step at a time.

[Abyssor nerf] - Makes heretic crystals slightly weaker. It takes a while before they can be made.

---

code/modules/jobs/job_types/_job.dm

Topic name. Basically, wretches and bandits are in GLOB.peasant_positions - and any joining job with a bank account will know them. Similar - with vampire (and lich, I believe?), because those antag roles never change their original assigned role, they just change their special role var.
And thus - antags in list(ROLE_VAMPIRE, ROLE_NBEAST, ROLE_BANDIT, ROLE_LICH, ROLE_WRETCH, ROLE_UNBOUND_DEATHKNIGHT) will now be skipped. They will not know anyone, no one will know them. Antags (everyone with set special_role var) will still know each other, that's intentional. I think it is a win.
Tested on local with two clients. Latejoining character was not learning about a pre-existing wretch, tis a success.
You all know why.

Bandits, wretches, vampires and other knaves should no longer be known to Azurians

---

code/modules/roguetown/roguemachine/mail.dm

This PR adds more additional feedback to the mailing logic.
* Ask the player if they still wish to send the letter if the recipient is not found
* Adds a mention of leaving the from name field blank to be able to send mail anonymously
* Adds a chat notice message hint if tried to collect their mail if their mail was stolen/burned/missing
* If the recipient tried to collect their mail and there was none to be found, silently readd the `ugotmail` status effect for the recipient if their mail is readded into the mastermail machine
I have tested this logically and confirm it does exactly as above describes.
More feedback helps players get less frustrated and cuts down on false bug reports.

Improve mail feedback

---

code/modules/spells/spell_types/wildshape.dm

Druids will no longer be able to cheat and turn into animals after they've given up.
From:
https://github.com/Scarlet-Reach/Scarlet-Reach/pull/691
It won't happen that the druid gave up, and then abruptly turned into a wolf and started running away.

Druid surrender button

---

code/game/objects/effects/gods/unassuming_fluff.dm
code/game/objects/items/rogueweapons/melee/polearms.dm
code/modules/mob/living/carbon/life.dm
code/modules/roguetown/roguejobs/fisher/rod.dm
code/modules/spells/roguetown/acolyte/abyssor.dm
modular/Neu_Food/code/raw/raw_fish.dm
modular_azurepeak/code/game/objects/items/ritualcircles.dm

I've no way to prove it, but I reckon something that's supposed to be a 1 to 5/10000 chance to occur, shouldn't be happening MULTIPLE times in the same round. Given byond fractions are known to be -messed up- due to being single point precision floats, I've made sure the math doesn't use these anymore.
As per the testing image I got 0.39% and 0.45% on an expected outcome of 0.5% (given this is an abyssorite the chance is 5x as high). This is within expected binomial distribution. (running 10000 test trails for a chance of 5/1000 or 0.5%, twice)

[God fluff] Fixes god fluff probability math.

---

code/game/objects/items/rogueweapons/shields.dm

Changes from https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/3643
- As per title
I have faith in the God-Emperor and my code. Do you?
- I added this intentionally to make it possible to attrition a shield down. Using quartered damage encourage people to use broadhead (pending rebalance :tm:) instead of spamming bodkin. With the best case scenario of a 300 durability shield vs broadhead fired by a 15 perception (60 damage -> 15 damage) - that's lasting through 20 arrows. 18 Perception - that's 16 arrows. Arcyne Bolts - 30.
- We should retain attritioning a shield down (at cost of most of your quiver) as an option

Shields take quartered damage from projectile now.

---

code/_onclick/click.dm

This PR fixes a exploit of being able to look outside of buildings.
1) Stand by any wall with an exterior that has open space tiles
2) Right click shift the obscured black area which leads to open space outside, and you'll get a view from below
I have tested this locally and confirm it has fixed the exploit.
Fixes an exploit.

Fix exploit of looking outside of buildings

---

code/modules/clothing/rogueclothes/neck.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
code/modules/spells/spell_types/divine/projectiles_single/unholy_blast.dm

- Implemented the arcing code for Divine Blast for Unholy Blast
- Made unholyblast a subtype of holy blast, removing repeated code. 
- Zcross now also have a arc intent, if you wanna out yourself.
Cleaner code and avoid diverging balance between the two abilities.

Refactor Unholy Blast - It can arc, is a subtype of divine blast now.

---

code/modules/jobs/job_types/roguetown/adventurer/types/wretch/heretic.dm

A speed/light armor subclass for Heretic. Pretty simple, they're a worse Cutpurse wretch with access to miracles. That's it.
Don't imagine it should ruffle any feathers since not having heavy armor is a straight and significant downgrade, so gamers won't be picking this.
In terms of how they're worse than cutpurses, they get less speed, (but a little int/per to make up for it) they get a -1 to all the cutpurse skills, they spawn with no helmet, and they don't get a crossbow/skills unless they specifically pick it, in which case, they lose out on having any other weapon skill above journeyman. I'm open to more suggested nerfs since we don't want to discourage people from picking cutpurse.
It compiled, I ran it locally, everything was were it was supposed to be.
I want to play a heretic …

Adds a Heretic subclass: Spy

---

code/datums/status_effects/rogue/debuff.dm

trust me pookie
Basically it was too punishing to the point that resisting until death and being revived/sent to lobby was more favorable than allowing your lux to be drained via evil ritual. Not the way it was intended.
Debuff is now statwise on par with revival debuff, duration is one hour. Because cope with it. (I feel like 15 minute revival debuff time needs to be increased but it is what it is)

Nerfs devitalized debuff caused by matthiosite and graggarite rituals

---

code/modules/cargo/packsrogue/merchant/apparel.dm
code/modules/clothing/rogueclothes/neck.dm
code/modules/clothing/rogueclothes/shirts.dm
modular_azurepeak/code/datums/loadout.dm

I was bored and looked at dev_suggestions and saw a few that were easy to code, not harmful to the game, and I decided to be productive with anything that isn't pertaining to my real life stuff and therefore more important.
- **FANCY COAT** can now be worn in the Cloak Slot. Drip.
- **AMULET OF THE TEN** and **ZCROSS (Zizo's Cross)** are now available in the Loadout menu. Yay.
- **AMULET OF THE TEN** can be purchased from the Tailor's Silverface. Yay.
- Gave Desert Rider's medal some fluff because HOLY SHIIIIIT STOP DROPPING IT YOU COWARDS FUCK FUCK FUCK FUCK. ENJOY YOUR DRIP!!!
- Also you can wear your DRider's medal on your *wrists, ring or hip* as well as being a bit more valuable.
Drip? QoL changes? 
Do you want me to go back to do adventurer/merc class changes? Huh? 
That's what I …

Dev_Suggestions that are actually Suggestions

---

code/datums/gods/patrons/divine_pantheon.dm

i'm sorry, frok.
does not comment out the spell itself, just comments it out on the patron screen. should prevent people from getting it for the moment. as the spell can still be fixed at a later date, i see no reason to remove it. entirely.
- compiles
- i bootedu p roguetest and i spawned in as an acolyte adn it was gone
death's door currently has issues w/ breaking people's clients, preventing them from seeing /me's, etc. i would really like to see it actually operational but atm it's just kinda borked and not in a way i can fix. i propose commenting it out until we get frok back 2 work on it or similar.

comments out death's door from being given

---

code/game/objects/items/rogueweapons/ranged/ammo.dm

As per title. Iron Javelin, Steel Javelin and Decrepit Javelin are no longer smeltable
It's an exploit

2x Javelins cannot be smelted anymore.

---

code/modules/mob/living/grabbing.dm
code/modules/mob/living/living.dm
modular/Neu_Food/code/others/fat.dm

Ports Oiling Up from Vanderlin. Original code by Dwasint.
Not visible on character yet.
- Fat can be used on splash intent to apply the oiled up status effect 
- Oiled Up gives you a 50% chance (from 35% chance originally) to just slip away from any grab if your bodypart is uncovered 
- Also gives you a 2% (from 3% originally) chance to slip, per movement and flop onto the floor.
- This ain't becoming meta. 
Yes.

Ports Oiling Up from Vanderlin.

---

code/datums/components/cursed_item.dm
code/game/objects/items/rogueweapons/melee/axes.dm
code/game/objects/items/rogueweapons/melee/flail.dm
code/game/objects/items/rogueweapons/melee/swords.dm
code/modules/clothing/rogueclothes/armor/plate.dm
code/modules/clothing/rogueclothes/cloaks.dm
code/modules/clothing/rogueclothes/feet.dm
code/modules/clothing/rogueclothes/gloves/plate.dm
code/modules/clothing/rogueclothes/headwear/helmet/heavy_helmet.dm
code/modules/clothing/rogueclothes/pants/plate.dm
roguetown.dme

Fixes an exploit where you could put ascendant-aligned items like the graggar axe into a sack and then pull it out safely with rclick as a non-Graggite. 
Did this by adding a component for properly handling curse triggering for items, with some customization added in for specific items.
Didn't touch the Priest garb bc honestly nobody cares and it's not an issue like the Gragaxe.
It triggers when you try the exploit.
ikts not

Adds component for handling cursed Ascendant items, fixes an exploit.

---

code/game/objects/items/beartraps.dm

This PR prevents armed beartraps from being placed over or next to travel tiles. It also automatically disarms a beartrap if it was kicked/thrown next to/over on a travel tile.
I've tested this and confirm it works.
Anti-abusive mechanic to stop players from attempting to spawn camp travelers.

Don't allow beartraps to be armed over/next to travel tiles

---

code/game/objects/items/rogueweapons/melee/polearms.dm
code/game/objects/items/rogueweapons/melee/swords.dm

I pulled out a chart and reviewed some numbers hoping to make Arming Sword and Longsword slightly better compared to the more meta choice of rapier / sabre and here are my conclusions:
- Greatsword (Base) gain +100 Blade Integrity so that it lasts longer than the zwei, which are stronger offensively with more force
- Steel Zweihander loses 1 WDefense as god intended cuz it was meant to be an offensive sidegrade to Greatsword and not a str8 upgrade.
- Arming Sword's Cut Intent is now 1.2x and 10 clickCD instead of 1.1x and 10 clickCD. This means it has slightly higher EDPS at 26.4 instead of 20, but is still handily beaten by the sabre at pure cutting (with 22 damage, 1.25x, and 8 clickCD)
- Arming Sword's Stab Intent now have 35 Penfactor instead of 20. No damfactor changes. This allow it …

Hyperspecific Sword Balance Pass.

---

code/controllers/subsystem/rogue/miscprocs.dm
code/datums/gods/patrons/old_god.dm

Courtesy of Yische and Vex, who were polite enough to help me diagnose the issue at hand.
This _should_ fix the ongoing issue of Psydonites _(with at least Novice-tier Holy skills)_ not receiving the _"Psydonite Devotion"_ trait, which would prevent them from being healed by Pantheonic miracles.
It's just a one letter change, so nothing _should_ go wrong.
Restores the intended balance of dedicated Psydonites _(like the Clerics, Adjudicator, Disciple, and Ordinator)_ being physically tougher, at the cost of losing access to the now-very-useful miracles that the worshippers of the Pantheon have.

Minor Bugfix #I - Readds the missing 'Psydonic Devotion' trait by fixing an argument in the old_god.dm file.

---

code/modules/roguetown/roguemachine/stockpile/stockpile.dm

Stockpile now sells on the tile in front of them again.
Makes egg and barrel selling possible again

Revert stockpile selling changes.

---

code/game/objects/items/rogueitems/coins.dm

- Coin cannot be scattered by being thrown anymore 
- Coin of the same type, when crossing a turf, now automerges with eachother
Tested.
Probably not a good idea to have a lag machine generatable by withdrawing a 1800 coinstacks, throwing it, and then alt clicking it right?

Remove Coin Scattering - Coin of same type now automerges.

---

code/modules/clothing/rogueclothes/headwear/masks.dm
code/modules/clothing/rogueclothes/robes.dm
code/modules/jobs/job_types/roguetown/church/martyr.dm

I added the cursed item component but was too lazy to make it work for bishop robes and mask. It works now. The martyr sword code that doesn't allow you to pick it up using the sack exploit (put sword in sack, rclick to remove it, you now have the cool sword as a non-martyr)
tried exploit n it didnt work
id say its not but onutsio aske dme to do this so who am i to say no

Fixes possible exploit with martyr sword and makes Bishop robes act like other cursed items.

---

code/datums/storytellers/gods.dm

As the name suggests, this adds a brief two-sentence-long descriptor to the names of each Storyteller: it explains their _theme_, the _events_ that're most likely to happen during their rounds, and _how_ to garner favor with them.
These descriptions are printed _directly_ in front of each Storyteller's name. It's a bit of a crude solution - at least until someone like Ansari can better refine this system, _but_ it will ensure everyone will know what the round might have in store.
_(There's also a new series of 'welcome_text' blurbs, which add a little bit of flavor to the start of each week.)_
Shouldn't be anything too severe, as it's just a couple line changes. The _absolute_ worst case scenario is that the descriptions don't print with the names, for whatever reason. I'd testmerge this …

Potential Feature #III - Adds summarized descriptors to the Storyteller options.

---

code/game/objects/buckling.dm
code/modules/mob/living/carbon/carbon.dm

- You can no longer buckle someone in combat mode, unless they are restrained(chained or roped), or unconscious.
- No longer get owned by pews
- Actual salt pr coming through after I got combat buckled for the 3rd time. This shit has always sucked though.

aborts combat buckling

---

code/modules/farming/composter.dm

Gives a line of text to tell peeps that they're using a pitchfork to flip compost.
It works!
Incase a new player doesn't realize that using a pitchfork makes flipping compost faster. 4 seconds compared to 7 doesn't visually seem massive; and you can easily not notice it.

Pitchfork Feedback

---

code/game/objects/items/rogueitems/natural/wood.dm

- gives sell value to wood planks. u get 1 more value that u would get selling a normal log at the stockpile
- request
- you still cant sell them at the stockpile its merchant only
- i booted it and sawed a log and a single one is worth 4 mammon. i don't think you can sell full stacks of them at the merchant but that's an entirely different beast and  last time i touched how merchant and stacks work and shit goblin heasd were no logner sellable and  i  Do Not Want 2 Touch That.
- also im not booting dun world and waiting 10 minutes 2 test it & i dont think dun test has a merchant zone???? i dont fucking know???? Please send mheplp  immediatelyt
- request
- if an advent somehow abuses this i aint even got shit to say.

CRASHES WOODWORKING ECONOMY WITH NO SURVIVORS

---

code/datums/sexcon/sex_actions/sex/anal_ride_sex.dm
code/datums/sexcon/sex_actions/sex/vaginal_ride_sex.dm

This PR addresses an oversight with the sex commands, `ride them` and `ride them anally`.
Both of these commands would not mechanically give pleasure to the ridden character - this PR fixes that.
I have tested this locally and confirm it works.
This fixes an oversight/bug.

Fix riding commands not applying pleasure to rider

---

code/game/objects/items/rogueitems/magic/magic_resources.dm
code/modules/roguetown/roguecrafting/alchemy/alch_grind_recipes.dm
code/modules/roguetown/roguecrafting/alchemy/ingredients.dm

Adds a "manabloom powder" alchemy item for brewing simple mana potions with (or big ones if you have enough other ingredients).
Adds a grind recipe in the mortar to turn manablooms into manabloom powder.
edit: THIS REMOVES THE MORTAR GRIND RECIPE FOR MANABLOOM SEEDS. YOU MUST NOW SMACK THEM WITH A BLUNT-INTENT OBJECT TO OBTAIN SEEDS. Blame mortars not allowing multiple different options for crafting.
(I forgot to take pictures of this part) Manabloom seeds can be extracted from manabloom produce with blunt-intent strikes. Manabloom seeds can be planted properly as herbs. Planted manabloom grows properly and can be properly harvested.
There are literally only two ingredients in the entire game that can provide basic mana potions. Now you don't have to go kill wolves for a simple potion, …

makes manabloom alchemical

---

code/modules/mob/living/carbon/human/human_defense.dm

Makes armor with a cursed_item component damageable again. Heretic armor is no longer invincible.
Tested it with a normal sword, silver sword, blessed silver sword, unblessed psydonian sword, and blessed psydonian sword. All apply damage to the armors that were invincible before.
Invincible Graggar armor bad.

Fixes silver blessed stuff

---

code/game/objects/effects/glowshroom.dm
code/game/objects/items/beartraps.dm

Kneestinger / Mantrap no longer trigger an ambush when triggered.
Compiled
As part of the warden ambush refactor, the ambush tile mechanics that prevented ambush from happening when kneestinger / mantrap were triggered were removed. This led to way more mantrap / kneestinger induced ambush which generally tends to be unfun.

No more mantrap / kneestinger ambush.

---

code/_compile_options.dm
code/controllers/subsystem/job.dm
code/modules/client/preferences.dm
code/modules/jobs/job_types/roguetown/adventurer/types/_advclass.dm
code/modules/mob/dead/new_player/new_player.dm

- Port USES_PQ define from https://github.com/Monkestation/Vanderlin/pull/3163 - Composter now allows bulk removal via a shovel by Dwasint
- Allows downstream / anyone to just comment out one compile option to disable the PQ system entirely
Yes

Port Vanderlin's USES_PQ define.

---

code/game/objects/items/rogueweapons/melee/special.dm

Kinda based on a discovery from: https://github.com/Rotwood-Vale/Ratwood-2.0/pull/29
- Katar is now 8 clickCD in line with dagger / sabre instead of 6 clickCD
It compiled
I was not even aware that Katar has an additional +25% multiplicative clickCD on top of better damage than dagger, which would explain why it feels so damn busted in PVE. Luckily nothing happens so it wasn't abused widely in PVP, yet.
This still make Katar pretty damn good as it has access to very high cut damage multiplier and a stab better than rapier. It just isn't ultra absurd anymore.

Make Katar 8 instead of 6 clickCD

---

code/modules/mob/typing_indicator.dm

Add shitty attack logging for typing indicator.
Help investigate log. Unfortunately it don't work on typing in the chatbar. Thankfully from anedoctal evidence I am the only psychopath on AP that do that on the regular

Add shitty attack logging for typing indicator.

---

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/miner.dm

Changes Miner's journeyman polearm skills to journeyman mace skills.
Just changing a skill value.
I think it's more fitting for Miners to be good at smashing things with big blunt objects than for them to be good at using spears. They're already good at using pickaxes and axes. When swinging a pickaxe, an axe, or a mace, it all generally uses the same motions and muscles. Maces are also a typical weapon used by conscripted footmen, right after spears, but we have farmers and spear-hunters for spear militia.

Miner Skill switching polearms to maces

---

code/__HELPERS/reagents.dm
code/datums/brewing_recipes/_brewing_recipe_base.dm
code/datums/components/crafting/recipes.dm
code/game/atoms.dm
code/game/objects/items/rogueitems/ceramics.dm
code/game/objects/items/rogueitems/waterskin.dm
code/game/objects/lighting/rogue_fires.dm
code/modules/reagents/reagent_containers/bottle.dm
code/modules/reagents/reagent_containers/glass.dm
code/modules/roguetown/roguecrafting/alchemy/alch_cauldron_recipe_base.dm
code/modules/roguetown/roguecrafting/alchemy/alch_cauldron_recipes.dm
code/modules/roguetown/roguecrafting/alchemy/alch_items.dm
code/modules/roguetown/roguecrafting/alchemy/reagents.dm
code/modules/roguetown/roguejobs/alchemist/container.dm
code/modules/roguetown/roguejobs/mages/rituals/_ritual.dm
modular/Neu_Food/code/cookware/bowl.dm
modular/Neu_Food/code/cookware/cup.dm
modular/Neu_Food/code/cookware/pot.dm

Port of https://github.com/Monkestation/Vanderlin/pull/3060
- Replaces mention of "Oz" with "Ligulae / Ligula", an old roman unit that is kinda close to 10 ml. No more desync between in code and out of code units.
- Normalized reagent container & transfer amount where noted. Bucket / Pot -> 100 / 200 from 99 to 200. Cups to 25 from 24. Bowl is now 30. Stew Recipe generates 30 instead of 32 units. Bottle is now 50 units, Alchemical Vial is now 30 units. Potion recipe is 90 / 30. Overdose threshold for potion buff is now 33 instead of 30. 
Finally no more fucking desync of OOC and code units

Port Vanderlin's "oz" to "ligulae / ligula" changes

---

code/__DEFINES/roguetown.dm
code/modules/clothing/rogueclothes/rings.dm

- Fate Weaver integrity -> 75 -> 50
- Armor is now 10 blunt, 100 across the board, meaning it'll block nearly all hit - at least once or twice.
People says Fate Weaver bad, because at 75 Integrity but with low value it don't really blocks (one) hit from the things that matter so now it does.

Make Fateweaver 50 integrity but block at least one hit that matters.

---

code/modules/roguetown/roguemachine/bathmaster.dm

apparently my for loop broke shit, again. this should fix it by not allowing any kind of storage item to count as stuff. if there's another kind of bag or some shit, i don't know. this is my best attempt rn i dont have time for any better checks and idk i could just remove the loop but it'd suck for qol.
if there r any better solutions to this lmk asap. i've been thinking about actually splitting the real_value proc and whatever else from the examine proc and using some sort of fake value system so that you have to still sell shit individually but, again, idfk.
- runs. i put stuff in the bath vault and it gave me a percentage of what Wasnt in bags or whatever so i assume it works. idk how to mnaually fire the subsystem to check so this is the best i can do.
- bugfix

fixes bathhhouse bug

---

code/modules/surgery/surgeries/organic_steps.dm

took ages figuring out how to bypass this shit until i realized there was an ignores_clothes flag i could've set if it was in the trait list. lmao. 
folk who have the expert medicine trait can now cauterize through armor. i considered adding a cmode check but i don't think it's worth it. if someone is doing this shit 2 powergame i aint even got shit 2 say. i can add it later idk i just felt like shit adding an if check and then it was anm or chec i i HAVE TO STOP ADDIGN CHECKS .PLEASE. OGHGHH MYG OD.
- it runs. i didnt tkae screenshots but on my test i stabbed myself w/ armor on/off, took the trait on/off. it works fine.
- i got paid 2 erp tokens by one person and a ksis on thge cheek by another

medicine experts can caut thru armor/clothes whateever

---

code/modules/mob/living/carbon/human/npc/orc/orc_outfits.dm

Revival of https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/3379 
I'm still of the belief post loot nerf that the Orc Mobs are far too cracked for the risk vs rewards ratio and until / unless loot is tweaked with a major PR from me they should be downtuned a bit. This is relatively mild and just cut down 3 - 6 statpoints on average, alongside removing Crit Res from Warlord (Which are already cracked)
Nae
Nerfing Omniwound bleed rate for orcs does not measurably improve the experience because kiting and bleeding out mobs is not a viable PVE tactic and more of a PVP tactic that take place over 3 minutes  - generally not feasible nor fun in close quarter. 
Orcs are utterly cracked but it was fine under the old balance where the dungeons were highly rewarding. Now it is a high …

Orc mob nerf 2.0

---

code/modules/client/preferences.dm
interface/skin.dmf

fixes this weird shit where the character preview is clipping with the text for anthro species & half-kin
my bad
also properly centers the window
and moves familiar preferences to the left-side since there's a lot of empty space there and the right-side menu was getting kinda crowded
oops i messed up when resizing the char setup window

Fixes fucky character preview for anthro species

---

code/_onclick/hud/screen_objects.dm

This PR makes an optimization to proc `/atom/movable/screen/zone_sel/update_overlays()`
By caching mob `get_missing_limbs()` results, it will reduce the number of times needed to check for missing limbs.
Before:
After:
Makes the server run slightly faster.

Cache `get_missing_limbs()` for HUD

---

modular_azurepeak/code/game/objects/items/donator_fluff_items.dm
modular_azurepeak/code/game/objects/items/donator_modkit.dm

changed the item path to only apply to the zwei, not all greatswords so i don't morph my knight zwei into greatsword stats
tested on local, didn't catch fire...yet
removes the ability to get something i'd have to buy from the smith

Donor sword fix

---

code/_onclick/hud/screen_objects.dm
code/datums/components/crafting/crafting.dm

Miacraft menu and 'repeat last recipe' right click function both now respect can_craft_here area proc.
This means you can't craft in areas that are supposed to prevent crafting.
Tested locally, worked fine.
It's a bugfix. You aren't really supposed to be able to craft around spawn zones/travel tiles or in certain dungeons. The new TGUI crafting menu doesn't currently check for can_craft_here.

Bug-fix - Miacrafting now respects can_craft_here area proc

---

code/modules/clothing/rogueclothes/armor/brigandine.dm
code/modules/clothing/rogueclothes/cloaks.dm
code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
code/modules/jobs/job_types/roguetown/garrison/sergeant.dm
code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
code/modules/jobs/job_types/roguetown/nobility/captain.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm

Cuts down on the amount of clutter MAAs have to go through on spawn by slamming their selections into 2 options - Brigandine Set (what skirmisher already has on spawn) and Maille set (scale / haubergeon / bracers). Sergeant gets full brigandine.
Brigandines (light and medium) now copy the heraldry colours on spawn for easier identification.
Removed the black belt and satchel for garrison - it's a leftover from when the default heraldry colours were red and black.
Repathed knight tabards and put them back on knights - should help seperate them from garrison.
Having to click through 6 windows just to play guard gets annoying after the 50th time even if it does limit customization.
Easier identification is nice besides it's in the code might as well use it.

Just one more retinue PR to save the Peaks trust

---

code/game/objects/items/rogueitems/necro_relics.dm

Necromancers now set a task for their Skeletons, before summoning. This is to give the potential Skeleton player a hint as to what their round might be like.
Unfortunately, not every Skeleton wants to be turned into a Mining Machine for an hour and a half.
skeletons won't be hot-dropping into an unknown battlefield. They'll at least get a sense of who they're working for, and what they'll be doing. This helps them invested, and might intrigue other players who might never play a skeleton.

Task-based Necromancy (small necromancer QOL change)

---

code/modules/roguetown/roguejobs/gravedigger/hole.dm

Look, it's ass. It's always been ass.
This removes the check that see's if a stone is on the tile when you're digging before spawning another one. Essentially you would have to stop, switch hands, pick up the stone and drop it just to get a second stone to spawn. It was tedium for the sake of tedium. 
`
"BUT WHAT IF SOMEONE ABUSES IT TO MAKE A RIDDLE OF STEEL BY JUST DIGGING UP STONES"`, if someone wants to dig up 8,205 (give or take, fast maths) stones to make one riddle of steel when they could buy it for about 600 mammons (or like a dungeon and a half worth of work) then they deserve the riddle of steel. It's still a 23% chance to spawn on dig.
dug hole 6 times, 1 rock appeared, dug hole 4 more times again with rock on tile, second rock appeared.
Tedium for the sake of tedium is bad. …

The PR to save Azure Peak - Removed the check for a stone being on the tile already when digging for stones.

---

code/datums/mind.dm
code/modules/jobs/job_types/roguetown/garrison/veteran.dm

Fixes: Retired Mercenary loadout being broken
Fixes: Refunding one spell of the same type refund other of the same type without giving you point back (I.e. Artillery fireball + fireball)
y

Bugfix Pack

---

code/modules/clothing/rogueclothes/robes.dm
code/modules/jobs/job_types/roguetown/church/templar.dm
code/modules/roguetown/roguecrafting/leather/leather_unique_recipes.dm

Removes the vestments that give the stamina regen perk from clerics. Lets them keep the vestments in a red color though without it; basically letting them keep it as unique good armor but without the perk attached.
Works!!!!
I added monk vestments to cleric-monk when punches took more stamina, this was reversed so the entire point of giving monk adventurers this has been pretty - annoying given the increased stamina cost, the entire point of the vestments, is gone.
This technically is a nerf to monk-cleric but brings them back in-line with other adventurer types instead of whole-sale overshadowing them now.
Left the perk-vestments on Templar since I guess they can still use it since they're literally surrendering heavy armor for it so it's more justified at least.

De-Vestments Cleric-Monk

---

code/__HELPERS/priority_announce.dm
code/controllers/subsystem/rogue/treasury.dm
code/datums/taxsetter.dm
code/modules/jobs/job_types/roguetown/nobility/steward.dm
code/modules/roguetown/roguemachine/steward/steward.dm
code/modules/roguetown/roguemachine/titan.dm
roguetown.dme
tgui/packages/tgui/interfaces/TaxSetter.tsx

- Adds new pookie TGUI for setting taxes. Accessible via the titan itself or via steward's verbs.
- Adds four new taxation and fine categories. This can be tweaked by the duke/regent/steward, of course.
Nobility: 0% taxes roundstart, exempt from fines
Church: 6% taxes roundstart, exempt from fines
Yeomen: everyone with TRAIT_RESIDENT or with job in GLOB.yeoman_list ("Merchant", "Innkeeper", "Archivist", "Scribe", "Town Crier", "Bathmaster", "Guildmaster", "Guildsman", "Tailor"). 12% taxes, not exempt from fines
Peasants: everyone else. 12% taxes, not exempt from fines
Adds boilerplate.
Something about dukes having more control over the economy.
Copilot write me a justification for this PR thanks

IRS: small upgrades to Azurian taxation

---

code/modules/spells/roguetown/acolyte/resurrect.dm
modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/undead_animal_helpers.dm

- pem sem time doubled (1 min -> 2)
- my spellcheck that was on another branch somehow got here but its fine probably
- compiles
- i do not have the energy to stare at a corpse for 2 minutes after figuring out how to manually trigger thre storyteller event
- constant complaints abt it
- actually valid now that butchery takes like 45 seconds to a minute to complete. u literally cant butcher animals in time rn. honestly it might be worth upping it to like 2 and 1/2 but this should be fine as a test value.

increases reanimation time for pet semetary

---

code/datums/character_flaw/addiction.dm
code/datums/gods/_curses.dm
code/game/objects/items/rogueweapons/rmb_intents.dm
code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm
code/modules/mob/living/carbon/human/human_defines.dm
code/modules/mob/living/grabbing.dm
code/modules/mob/vision_cone.dm

Currently working on a PR that adds stuff to the carbon human datum and I could not handle the fact it got redefined like seven times for menial variables so I consolidated them all back into the original datum declaration. Might help with compile time but it's mostly for organizational purposes.

Consolidates carbon human variables

---

code/_onclick/hud/mouseover.dm

Ok so when I forced mouseover maptext to be constrained by 1,1 bounds (the infamous pine tree problem), I forgot that our inventory is actually on the main window, not in a separate one
Thus minimal X screen_loc should be -3, not 1
bug

Updates screen_loc bounds for mouseover maptext

---

code/game/objects/structures/roguetown/bell.dm
code/modules/roguetown/roguemachine/scomm.dm

The garrison building has this neato front lobby and I've never really seen it used. This puts one of those nifty zone summon bells here for the garrison, Maa / Sergeant / Dungeoneer so they have some excuse to say "not it!" on the houndSCOM whenever it rings.
Also touches garrison scom to let "Watchmen" convert roles turn them on and off. Maybe this niche feature will be used once per year.
Who really talks to garrison characters, anyway?

Garrison Bell and Watchmen Garriscom

---

code/__HELPERS/files.dm
code/__HELPERS/text.dm
code/controllers/subsystem/sounds.dm
code/modules/client/client_procs.dm
code/modules/mob/login.dm

https://github.com/Monkestation/Vanderlin/pull/2838 - Load music into memory to remove client side music lag when transitioning areas or such. 
Also port a function ported by Flieeeppy / Chen Marisa
Logged in game, turned on music.
Yippee

Port Vanderlin 2838 - Load Client Music Lag.

---

code/modules/antagonists/roguetown/villain/werewolf/werewolf_spells.dm

This fixes werewolf claws. There is a slight modification to the behavior; if you have an empty hand, you will always attempt to extend a claw into that hand. You will only try to retract your claws if both hands are full. whether it's from holding something or that hand being unavailable.
https://github.com/user-attachments/assets/659de51b-6edf-48f2-b86a-d310e79642bb
BUG: fix
VALID: KILL

Fixes werewolf claws

---

.gitignore
.vscode/launch.json
.vscode/tasks.json
code/__DEFINES/preferences.dm
code/controllers/configuration/configuration.dm
config/config.txt

Ported from tg / vanderlin etc.
Some very very very very very long overdue improvements to our development workflow to bring us up to 2022 or 2025 standards:
- We now have a launch.json with five options for vscode (I don't think unit tests work yet), including a LOCALTEST mode (My version of low memory mode)
- Localtest mode currently just define minimum flavor text & ooc notes as 0 that's it. Now local run will actually run our build.sh with CBT etc.
- New mode may be added
- Five launch options: Dreamseeker w/ and w/o localtest, Dreamdaemon w/ and w/o local test, and unit tests. I don't think unit tests work but I CBA to continue today
- Added dev_overrides for local overrides
- Copied our example config.txt and put it in the actual folder, so that anyone who download the repo fresh …

Add Launch Options & Move Config.txt out of gitignore into the actual folder

---

code/modules/mob/living/carbon/human/npc/skeleton/skeleton.dm
code/modules/mob/living/carbon/human/npc/skeleton/skeleton_lich.dm
code/modules/mob/living/carbon/human/npc/skeleton/skeleton_outfits.dm
code/modules/mob/living/simple_animal/hostile/bosses/lich_boss.dm
roguetown.dme

- Lich should now be fire proof 
- Instead of spawning 10 simple mobs in a wave, it now spawn 6 complex mobs (medium spread) in a wave.
- Added spitfire to the list of projectiles it is allowed to shoot
Yes
Lich Boss became way too easy after the L Bolt nerf - the L bolt followed by being ganged on by simple mobs was the main threat. Its difficulty has been trivialized as an unintentional insult. 
Now it spawns less mobs but stronger complex that are more engaging to fight and also more dangerous to deal with and impossible (?) to ignore.

Lich Boss Buff

---

code/modules/spells/spell_types/wizard/invoked_single_target/counterspell.dm

Counterspell is often unpicked by most mages due to how situational it is. Something I've learned while playing Grenzelmage has shown that the charge time for it is often way too long for it to actually be useful.
In order to bring it in line to being a EFFICIENT mage on mage violence weapon, I have removed the charge time of it, allowing you to use it as a reaction as if it were D&D!
A note: A reminder for what exactly Counterspell does, It adds BOTH Spell-immunity as WELL as prevents the target from casting. It's a double edged sword for a mage. You can prevent them from casting a big fireball or anything for 20 seconds, however your spells will fizzle for the next 20 seconds as well.
It also still has an 80 second recharge time so you can't CHAIN it.
ANOTHER reminder, most HIGH LEVEL …

Counterspell Glow-up (literally c:)

---

code/modules/client/preferences.dm
code/modules/mob/living/carbon/human/human_topic.dm

This is an addendum to a preceding pull request, [linked here](https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/3986), which ported Scarlet Reach's verification system over to Azure Peak.
There's already been a bit of confusion from the community over _how_ this works, so I've decided to go in and manually edit the following..
- _'Agevet' is now _'VERIFIED'_, on the character creation menu.
- Changes _"No"_ and _"Yes"_ to _"NAE?"_ and _"YAE!"_, alongside their coloration.
- Alters the on-click description to explain the purely optional - and non-gamechanging - nature of this mechanic.
- Alters the blurb shown on the flavortexts of verified players.
- Ports the maintainer's change, [linked here](https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/4022), which fully …

Differing Systems - Reflavors 'AGEVET' into 'VERIFIED', clarifies how Azure's optional agevetting system works.
