GeneralPantsuIsBadAtCoding/Azure-Peak

code/datums/character_flaw/_character_flaw.dm
code/datums/character_flaw/addiction.dm
code/game/objects/structures/fluff.dm
code/modules/mob/living/emote.dm
code/modules/paperwork/rogue.dm

Reimplements a fan-favorite mild flaw and implements a new one, after discussions between staff. Colorblindness looks as follows, and shouldn't follow you between lives (at least, it didn't when tested.)
We don't want to be _quite_ as hardcore and 'immersive' as Ratwood - having Devout Follower was right about our right level of "immersion" for Azure Peak, it seems. Similar flavorful but not-so-debilitating flaws to follow!

Re-adds 'Devout Follower', adds 'Colorblind'

---

code/datums/sleep_adv/sleep_adv.dm
code/modules/jobs/job_types/roguetown/adventurer/types/_advclass.dm

Makes it so that leveling up skills up to Apprentice happens same as the old system, no need for sleeping.
And increases the dream points you get by 1.
Also fixes gock for adventurers.

The Skillening

---

_maps/map_files/rockhill/rockhill.dmm
code/game/objects/structures/tables_racks.dm

Why was it like this?! You can also now craft the rightward facing table part by simply facing east when making the stone table.
Tables that look like one cohesive object are better for ERPing me on top of - even altar tables in the middle of churches.

Fixes the FUCKING church table

---

code/modules/roguetown/roguecrafting/sewing.dm

The "padded dress" item has two recipes with the same path, one using purely cloth and the other a mix of cloth and hide and fibers, this removes the non-functional pure cloth recipe in favor of the leather recipe, given that the item's descriptions mentions leather.

removes duplicate padded dress recipe

---

code/modules/mob/living/carbon/life.dm

After conferring with our resident Arthurian knight, [coffeecoffeecoffee](https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/issues?q=is%3Apr+is%3Aopen+author%3Acoffeecoffeecoffee), I have elected to boost the maximum protection values for armours that allow sleep before it is blocked by being overburdened. Chainmail jammies are a thing now.
The dev team at Azure Peak do extend their heartfelt blessings to Ser Coffee. May his blade strike true and may fortune favour him in the forthcoming crusade.

Chainmail Pajamas

---

code/controllers/subsystem/rogue/treasury.dm
code/controllers/subsystem/vote.dm
code/game/gamemodes/objective_items.dm
code/game/gamemodes/roguetown/roguetown.dm
code/modules/antagonists/roguetown/villain/vampirelord.dm
code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
code/modules/mob/dead/dead.dm
code/modules/mob/living/carbon/human/death.dm
code/modules/roguetown/roguemachine/scomm.dm
code/modules/shuttle/supply.dm

Just a bunch of fixes for our Monarch change. Monarchs should now be getting updated about the gold income, and can no longer be vampire lord, cannot get the objective to steal the crown - a bunch of little edge cases I missed. Same for "Queen consort" references which are now just "Consort" since we have malewifes.
This machine squashes bugs

Monarchs cannot be vampire lord

---

code/game/objects/items/rogueitems/bags.dm
code/modules/farming/composter.dm
code/modules/farming/fermenting_barrel.dm

Allows using sack bags on barrels and composters so you don't have to process things one at a time.
Also lets you examine the sack to see how many things are inside, along with letting you mousedrop it on the floor to dump it out on a different tile.

Allows Using Sacks on Barrels and Composters

---

code/modules/farming/produce.dm
code/modules/farming/seeds.dm
code/modules/roguetown/roguejobs/cook/ingredients/meat.dm
code/modules/roguetown/roguejobs/cook/ingredients/misc.dm
code/modules/roguetown/roguejobs/cook/ingredients/vegetables.dm
code/modules/roguetown/roguejobs/cook/recipes/meat.dm
code/modules/roguetown/roguejobs/cook/recipes/plates.dm
code/modules/roguetown/roguejobs/cook/tools/cookingpot.dm

NEW CROPS -
*CABBAGE - OBSOLETE can only be eaten raw for now
*BEET - OBSOLETE can only be eaten raw for now
*LEEK - Fried in the pan/oven 
*POTATO - Roasted in pan/oven
*CARROT - Roasted in pan/oven
*RICE - Used in dishes, seeds sold by merchant
DISHES -
*Boiled rice - Combine 1 rice 1 bowl (Subject to change, cooking needs to be reintroduced)
*Schnitzel - Craft 1 steak - 1 egg - 1 flour (Grenzelholfter dish)
*Roasted potato and Schnitzel - Requires bowl, craft with roasted potatoes and fried schnitzel (Gives filling meal buff)
*Sweet Oat Porridge - Requires bowl, combine 1 oat and 1 apple (WIP)
*Spiced eggs now require a bowl
*Peppersteak now requires a bowl

adds crops and recipes

---

code/datums/keybinding/living.dm
code/modules/mob/living/living.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/living_movement.dm

Does what it says on the tin. By default layer shifting is bound to Ctrl + Shift + Pageup/Pagedown. You will need to set this, just like the pixel-shifting keybind, but you can do so easily by going into your keybinds and just "resetting to defaults", as this is now default. Also, now if you pixel shift 10 or more in most directions or 8 or more downwards, people will be able to move through you!
The ability to decide who's REALLY on top.

Adds functionality to moonwalking back and forth on tiles, ports pixel shifting

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
code/modules/jobs/job_types/roguetown/courtier/physician.dm

Adjusts the stats of the court physician, and barber surgeon to be similar to their mage analogs.
Also decreases the +4 intelligence adventurer mages get from being old. What the flip?

Puts Doctors In Line with Mages

---

code/game/objects/items/rogueweapons/rogueweapon.dm
code/modules/projectiles/gun.dm

Have you ever wanted to quickly notice what weapons someone is carrying on their person without having to squint like a bag of nails?
Well, I have just the thing for you! With our patented **GearGlance™** technology, weapon names now leap off the screen like never before. No more straining your eyes or missing that crucial piece of gear. Just one glance, and BAM! You know exactly what they’re packing. Whether it’s a crossbow, a Zweihänder, or a rusty old dagger, you'll spot it faster than ever before.
Say goodbye to guesswork, and say hello to clarity with **GearGlance™**! Grab this pull request now, and revolutionize your examinatory experience today!

Makes Weapon Names Bold in Examine

---

code/modules/client/preferences.dm
code/modules/client/preferences_toggles.dm
code/modules/mob/mob_movement.dm

so uhhhh you  can now open the game preferences window from the options tab
it works goodly. you can set your keybinds while you're there. they'll take effect immediately.
also if the lobby window stays open after the round starts, opening up the game preferences and clicking the DONE button should forcefully close it.
happy game preferencing

Ingame Game Preferences Option

---

code/game/objects/structures/fluff.dm
code/modules/roguetown/roguecrafting/structure.dm

Are you tired of unruly customers jumping over your counter? Sick of those pesky prisoners escaping from your makeshift cells? Well, do I have the solution for you! Introducing craftable _Shop Bars_ and _Jail Bars_! Need to keep those eager shoppers on the other side of the counter? Craft some _Shop Bars_ with just one iron ingot and slap it right on top of your table! Now they can’t jump over, but they can still slide items across for trade. It’s a win-win!
But wait, there’s more! Need to lock up those no-good troublemakers? Put together some _Jail Bars_ and build yourself a real cell! These bars aren’t just for show – they’re the real deal, perfect for keeping the riff-raff in check.
So what are you waiting for? Get your _Shop Bars_ and _Jail Bars_ today, lest you find your stockpile …

I Got Bars

---

code/modules/mob/dead/new_player/sprite_accessory/wings.dm

they were misaligned now they're not

displaces wing sprites by 1 (One) pixel

---

code/modules/roguetown/roguejobs/cook/ingredients/meat.dm

Removes a duplicate cooked_type var from raw sausages allowing them to be cooked in ovens

Lets sausages be cooked in ovens

---

code/modules/surgery/bodyparts/bodypart_dismemberment.dm

Seeing a skelington get its skull lopped off shouldn't tick you off anymore.
Also, women won't get even _more_ of a mood debuff for seeing someone get dismembered. You can use this thing called roleplay, I guess.

No Dismemberment Moodlet From NPCs

---

code/game/gamemodes/objectives_rogue.dm
code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm
code/modules/mob/living/simple_animal/animal_defense.dm

Improves werewolf lore. Gives werewolves more warning in advance as to when they're untransforming. Gives werewolves something to do other than tearing off people's limbs and eating them - they can ALSO eat LIVESTOCK to heal now!
Why does the transition take 25 seconds when sunrise begins, but players only get 15 seconds of warning out of it?
Players having more goals and alternative methods to achieve their goals other than pure ultraviolence good.

Tweaks to improve werewolf

---

strings/german_replacement.json

Look at the diffs.
Pending a new system, the Grenzelhoft accent has a lot of fucky replacements that bleed into each other and make certain words unintelligible due to how the Grenzelhoft accent was constructed. This should help with that in the meantime, and is better than outright deleting word changes like what I did before, sorry.
Hammerhold and the Half-Orc one probably have similar issues, but... nobody uses those, so...
If people want I will look through those ones too but it shouldn't be *too* long until a new system is devised.

Comments out Grenzelhoft's most egregious word-bleed replacements pending new system

---

_maps/map_files/dun_manor/dun_manor.dmm

I forgot to change the lock requirement on the peddler in the physician's house to respond to a physician key instead of a non-existent doctor key. whoopsie.
this is for dun manor btw

fix the physician's peddler

---

code/game/gamemodes/roguetown/roguetown.dm

This removes vampires and peasant rebels from the automatic antag spawning system, leaving us with Werewolves, Bandits and Aspirants (Maniac is already long gone.) Previously, it would roll for "major" antagonists and then add "minor" antagonists on top at a 40% chance each, potentially allowing for an insane amount of chaos - since we only have 3, I opted to make something a little more stable, and gave us a 1/3 chance of rolling any two antagonists, never all 3.
We can't be around to do manual antags and events all day long and people need drama, intrigue and action, as is plainly obvious by the way our player count looks throughout the day between event times and lowpop.

Adjusts antagonist rolls so we can roll certain ones

---

code/modules/mob/living/carbon/life.dm
code/modules/surgery/bodyparts/bodypart_dismemberment.dm

Makes it so that decapitations on PLAYERS only work if they're either downed or buckled to something.
Also HOPEFULLY allows sleeping when you're already and wearing armour, in case you're in crit and can't do anything about it.

Removes Random Decapitations

---

code/controllers/subsystem/vote.dm
code/game/gamemodes/roguetown/roguetown.dm

Removes the event that endlessly spawns goblin portals when there's no monarch, as a consideration for pop given we may be using the roguemode game mode more often from now on. Also changes the roundstart requirement for antags down to 10 to account for cowards who don't ready up - 10 people readied seems to roughly accompany about 20 people actually playing, which is what was intended.
goblussy is a kingdomwide health crisis

Removes the no monarch omen, changes the number of people required for antags

---

code/__HELPERS/game.dm
code/modules/mob/living/carbon/human/human_helpers.dm
code/modules/spells/roguetown/necromancer.dm

Makes Lich's name show up properly.
Also HOPEFULLY. HOPEFULLY. Makes it so that if you use the raise undead spell on an NPC skeleton, it'll poll ghosts AND lobby people to claim it. Hopefully.

Lich Additions

---

code/_globalvars/lists/poll_ignore.dm
code/modules/antagonists/roguetown/villain/lich/lich.dm
code/modules/mob/living/carbon/human/death.dm
code/modules/mob/living/carbon/human/npc/skeleton.dm
code/modules/spells/roguetown/necromancer.dm

Fixes the big lag from the lich dying after running out of phylacteries.
Gives the spawned skeletons random equipment + undead eyes.
Hopefully, HOPEFULLY fixes the secondary use of the raise undead spell in making skeletons sentient. It should give messages for success and failure.

Lich Fixes

---

code/modules/mob/living/carbon/human/species_types/roguetown/roguetown_species.dm

Elf, Dark Elf, Tiefling, and Dwarf Gibberish now do in-word syllable-ized changes.
The accents that don't work when in-word changes are turned off now work without breaking the other ones. +dwarf gibberish is more unintelligible as it should be
A new system is still needed to make this system perfect but this is good enough

Changes only some of the accents to do in-word changes

---

code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
code/modules/jobs/job_types/roguetown/garrison/sheriff.dm
code/modules/jobs/job_types/roguetown/garrison/townguard.dm
strings/accent_universal.json

This PR:
Disables bog guard and bog master.
Increases the amount of townwatch slots by 4.
Reflavors sheriff to explicitly be referred to as a sargent underneath the Guard Captain.
Adds sergeant -> sargent to the universal accent 'cause it's funny.
The Bog Guard, with the release of the new map, is exclusively bloat. They serve no purpose at all and are simply a slightly worse version of the town watch. Furthermore, people referring to the guards as the watch more often is !kino!, and I don't use the word kino lightly.
Sheriff and Guard Captain may be merged at some point, but for right now I don't think its that big of a deal for the Captain to have someone to delegate command to. Not that Guard Captain players ever actually pay attention to the guards, fucking... fuhhghghhhh...

Disables bog guard

---

code/game/objects/structures/traveltile.dm

Antag travel tiles now properly prevent people who do not have the trait associated with them from entering.
In order to get this trait, you need to either be the antag or see someone with the trait enter the travel tile.
Working mechanics yippie!

Fixes bandit/vampire travel tiles

---

code/game/objects/items/rogueweapons/ranged/ammo.dm

Buffs arrows and bolts with higher AP and damage.
Bolts
Damage 35->70
AP 35->50
Arrows
Damage 35->50
AP 10->40
Long ago, someone was neck-critted by a bow and dumpstered ranged weapons doing damage. No longer. Carry a shield, and for the rangers amongst you, you are now valuable. Restores ranged weapons into relevancy. This is pretty much just porting the same changes Hstone made about a month or two ago. Values can be adjusted

Buffs Arrows/Bolts

---

code/modules/jobs/job_types/roguetown/church/priest.dm

Adds cure rot to priest. They are often the only healer in the game. We do not yet have cleric spam with wild abandon. Last round proved that priest with cure rot is kind of a necessity.
Encourages people to play a leadership role, AND makes that leadership role actually capable. woweee

adds cure rot to priest

---

code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
code/modules/mob/living/carbon/human/species_types/roguetown/dwarf/dwarfm.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfs.dm
code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halforc.dm

Most races now have generic names for their skin colors.
The only ones not changed are Aasimar, Tiefling, and Lupian. Lupian because I don't know how to change the character menu to not refer to skin colors as your "clan", Aasimar and Tiefling because they are unique. This is how it was in old rogue, btw.
You don't need to be from a desert to have tanned skin.
The more Blackstone changes removed from the game, the better. I could say more, but GitHub would probably suspend my account if I did.

De-Chuddifies skin color selection

---

code/modules/mob/living/carbon/human/examine.dm

Ancestries no longer show up when you examine peeps. So it's purely your skin tone now.

Removes Ancestry From Examine

---

code/game/objects/items/rogueweapons/ranged/crossbows.dm

This makes it require two hands to fire a crossbow. Skill now plays a much greater role in your aim time. The unskilled will take MUCH longer to effectively use a crossbow now.
Crossbows are now a very valuable skill. The trained, elite ranged core of the garrison(and banditos ;3) will now feel like it. Rather than every goober who grabs a crossbow. Additionally. those specializing in melee will no longer ALSO be able to kneecap someone with a crossbow at 0 skill. Also, two handing requirements means you can't dual wield a crossbow/dagger/some other ridiculous combination.  
Before, everyone took about 4 seconds to aim, with skill/per having very little effect. To roughly approximate, the unskilled take about 10 seconds to aim, Journeymen will take about 4-5, and Masters will take cap out …

Crossbow changes

---

modular_hearthstone/code/modules/mob/living/simple_animal/rogue/simple_skeleton.dm

Skeletons are no longer part of the "orc" faction. Their health is now widely the same as bare, unarmored orcs, with the armored variant getting 200 (the heaviest-armored variant of simplemob orcs gets 500.)
Skeletons not attacking our lich is good. Skeletons not going down in a single hit is even better.

Simple fixes for simplemob skeletons

---

code/__HELPERS/roundend.dm
code/modules/antagonists/roguetown/roleobjs/purishep.dm
code/modules/antagonists/roguetown/villain/choosename.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/noble.dm
code/modules/jobs/job_types/roguetown/church/confessor.dm
code/modules/jobs/job_types/roguetown/church/mortician.dm
code/modules/jobs/job_types/roguetown/church/puritan.dm
code/modules/jobs/job_types/roguetown/garrison/dungeoneer.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
code/modules/jobs/job_types/roguetown/nobility/hand.dm
code/modules/jobs/job_types/roguetown/nobility/steward.dm
code/modules/jobs/job_types/roguetown/peasants/nightman.dm
code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
code/modules/mob/dead/new_player/new_player.dm
code/modules/mob/living/carbon/human/species_types/furry/akula.dm
code/modules/roguetown/roguecrafting/sewing.dm
code/modules/roguetown/roguejobs/tailor/dyer.dm

Enable confessor.
Gives a bunch of roles satchels.
Removes the awful stat maluses from prince. Their skills were changed to be more similar to squire. Noble pilgrims now have similar stat and skill distributions. They also got better outfits. Prince and noble pilgrim also got the same skill distribution regardless of gender.
Tights are now craftable. Tunics are now dyeable.
Replaces instances of Ratwood with Azure.
Removes bad eyesight from the steward.

Changes to Roles + Other Things

---

code/modules/mob/living/carbon/life.dm
code/modules/spells/roguetown/acolyte/astrata.dm
code/modules/surgery/surgeries_hearth/revival.dm

Revivals, both Astratan and surgically, didn't work for people who died from blood loss or had their heart cut out because their health was impossibly low from oxy damage. Revivals now cure all suffocation damage.
Also disables embed damage for corpses. Because you'd clamp bleeders with forceps in someones chest and it would _keep damaging them infinitely_.

Fixes Revivals

---

code/modules/antagonists/roguetown/villain/lich/lich.dm
code/modules/spells/roguetown/necromancer.dm

Firstly, liches spawn with some blacksteel. This gives them the skills to use it properly.
Liches now get a 'summon lesser undead' which spawns a random simplemob skeleton. Whether you get a good one is completely luck of the draw.
'summon undead' is now 'summon greater undead', which will AUTOMATICALLY poll people in the lobby to join as that skeleton without needing to be recast.
Liches are fun and now they work. Now just the subject of their resistances...

Fixes some Lich Spells, adds armor training to them

---

code/datums/migrants/migrant_waves/heartfelt roles.dm
code/datums/mind.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
code/modules/jobs/job_types/roguetown/courtier/magician.dm
code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Knock now also unlocks doors when forcing them open (oops!)
The Learning Spell now no longer needs to be invoked, just clicking the icon works (less confusing)
The Learning Spell now automatically removes itself once you have no points left
The Learning Spell now automatically re-adds itself if any more points become available
A mind's AddSpell() proc now no longer spawns duplicate spells unless the code asks for it

knock fix and learning spell tweak

---

code/game/objects/structures/fluff.dm
code/modules/roguetown/roguemachine/merchant.dm
code/modules/roguetown/roguemachine/submission.dm

You can right click the feeding hole to dump everything on your tile into it.
Merchant machine tells you how many items are in each pack.
Adds sounds to hitting fences.

Feeding Hole Mass Stockpiling

---

_maps/map_files/dun_manor/dun_manor.dmm

Changes a bunch of church stuff including
- Fixing the pool
- Fixing the cell lock so confessors can use it
- making better use of the upstairs space for storage, kitchen and dorms for churchies
- making the medical area bigger as it was always running out of beds, especially if people went afk after being revived
- changing the graveyard to a garden (the graveyard rarely got used and there's a crypt under the church which is bigger than the entire church
- added a scom to the druid tree (druid magic, i dunno, I wanted to make sure druids weren't completely disconnected from other players, good for interaction)

Church remapping + fixes

---

code/__DEFINES/traits.dm
code/controllers/subsystem/rogue/devotion.dm
code/datums/status_effects/rogue/roguebuff.dm
code/game/turfs/open/floor/roguefloor.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/living.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Message now gives you the option to be anonymous when sending, if you choose not to be anonymous AND the reciever knows who you are they'll recognize your voice, if you choose to be anonymous, they can still pass a Perception check just like the Scrying Orb. (this SHOULD work but I wasn't able to test it well enough on my own even with the dual client set-up, praying)
Forcewall now spawns infront of the caster
Featherfall now protects from ANY fall damage instead of just one z-level's worth.
Some span fixes to badly formatted strings
LONGSTRIDER:
Give the caster and all creatures in a 3x3 cube around them the LONGSTRIDER trait which means they get no slowdown from rough terrain (like the rough forest dirt floors) for 15 minutes, costs 1 point.

Message tweaks, span fixes, forcewall tweak, featherfall buff, new longstrider spell

---

code/datums/migrants/migrant_waves/heartfelt roles.dm
code/datums/mind.dm
code/datums/status_effects/rogue/roguebuff.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
code/modules/jobs/job_types/roguetown/courtier/magician.dm
code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Fixes weird interaction between learning Fireball when you already have Greater Fireball.
Removes manually adding Learnspell to jobs since they'll get it automatically
Reverts buggy tweak to AddSpell()
Buffs Darkvision.
Buffs Haste.
Forcewall now places the wall on your targeted turf.
Reduces Repulse cost.

darkvision, haste, forcewall, repulse & backend bugfixes

---

code/controllers/subsystem/ticker.dm
code/modules/jobs/job_types/roguetown/nobility/lord.dm

so apparently when the lord spawns in, it fucking loops through the ENTIRE WORLD to FIND the LORD and assign them as the LORD for the ROUND.
tahts stupid as fuck. it assigns the lord directly now

Fixes Severe Roundstart Delay

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm

Tweaks the Arcanist subclass for Bard slightly.
- -1 strength removed
- -1 crafting skill (now 1)
- +1 alchemy skill (now 1)
- Changed outfit (it's now black-and-white formalwear with a white coat befitting a stage-magician)
- Took away medium armour from Arcanist; Bard and Skald still have it.
The Arcanist is meant to be a well-read spin on the jack-of-all-trades Bard, giving up skill in combat for dabbling in the crafts here and there. Honestly, I forgot alchemy existed when I coded this originally. Given they already have _very_ lacking combat skills, I felt the -1 strength was overkill in hindsight. But they don't need medium armour, that's for sure - not as a spellcaster.

Tweaks to the Arcanist (Bard) subclass

---

code/modules/mob/dead/observer/observer.dm

Observers can pass through walls now, and have faster movement speed.

De-Gimps Observer Movement

---

code/game/objects/items/rogueweapons/melee/knives.dm

They were omitted by oversight, looks like.

Adds Pick Intent to Elvish Daggers

---

code/modules/jobs/job_types/roguetown/church/confessor.dm

Confessor got spells but no cleric tab. So now they get a max of 100 devotion, lesser heal, diagnose and their shepherd spell that lets them swap places with a target.

Confessor Devotion Fix

---

code/modules/clothing/rogueclothes/armor.dm
code/modules/mob/living/carbon/human/species.dm
modular/code/game/objects/items/items.dm
roguetown.dme

Ports https://github.com/Rotwood-Vale/Ratwood-Keep/pull/764
Armours have both an equip and unequip delay now.
Most are at 2.5 seconds.
Half-plate is at 4 seconds.
Cuirasses and scalemail at 4 seconds.
Full plate is at 12 seconds. 3 seconds to equip by others, 6 seconds to strip.
The issue with not being able to unequip storage items was fixed..

Armour Unequip Delay Fr Fr

---

code/datums/special_traits/traits/traits.dm
code/game/objects/items/rogueitems/magic.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

De-sanitizes the inputs for the Scrying Orb and Message Spell so they can target people with punctuation in their character name like 
Sir Lucian 'Monsterhugger' Vampyre-Kisser.
Also adds a new rare Be Special Trait that gives you one free arcane level on roundstart meaning jobs that already had spellpoints get one more, and any others get a single spellpoint to spend freely

Scrying Orb and Message spell input de-sanitization and New Be Special Trait

---

code/modules/spells/roguetown/wizard.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

When selecting a spell to buy it gives a little pop-up with the spell's name and description and a "Learn" or "Cancel" option so it isn't obscure and confusing to players exploring the system

Spellbuying preview

---

_maps/map_files/dun_manor/azure_coast.dmm
_maps/map_files/dun_manor/azure_forest.dmm

Adds some points of interest and two dungeons to the azure coast and bog, so adventures have more actual adventuring to do. Also adds a few braziers to the Azure Coast's roads, to make it a little easier to traverse. I've tried to use spawners whenever possible for loot, to prevent metaknowledge letting players have too much of an edge over those who don't. Below is a summary of all additions. If you wish to find them and experience them yourself, watch out for spoilers! 
On the azure coast, some orcs have set up a little spider farming operation in an abandoned temple. Contains some puzzles and combat encounters. Nothing too spicy. Has two entrances: players can enter through a cave on the coastside cliffs, or mine in through the spider pen. 
A port-homage of the sunken chapel from the …

Adventure Time: points of interest and dungeons for adventurers.

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/steppesman.dm
roguetown.dme

i realized i wanted to make a knight but also couldn't, not really.
Similar to Hearthstone, this adds the knight-errant adventurer role. The knight-errant has comparable stats to most of their adventurer kin, maxing out at journeyman. As a martial class they typically would get a bump up in an iconic combat skill, but they trade that with the armor they start with instead. Their statline is the same as warrior's. They unfortunately don't get any unique combat music, and we really need some ren faire ass trumpet bullshit, but I'll leave that to another soul.
The knight also comes with an archetype choice, letting them be a black knight given all the set up was already there. It's aesthetic only, someone just took a black spray can to you.
This also touches up the warrior and steppe merc; …

The knight-errants ride into the Azure Coast

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm

Host request! I maintain that I don't think it was that powerful, but nonetheless; the knight-errant role has their start armor dropped down to be directly in line with the royal guard's, the local knight. This takes the form of their gloves and pants going from plate to chain.
The black knight found more spray paint to get their new clothes dark, too.
ow the edge
:)

Knight-errant's limbs on the chain now

---

_maps/dun_manor.json

separates the z level trait entries into their own lines by map, so that hopefully the list is more readable to contributors than whatever it is now.
this should not affect gameplay in any way, it is only to improve the look of the file and hopefully disambiguate how map files and z levels are to be formatted.

Dun Manor JSON readability improvements

---

code/modules/jobs/job_types/roguetown/peasants/butcher.dm

When I turned the butcher doors into farm-coded ones I forgot about the Butcher's key apparently. As it's a townie/pilgrim role they won't get _inherent_ access to the place, but instead they get a cleaver.
working keys

Townie Butcher's key replaced with cleaver

---

code/game/objects/items/rogueweapons/ranged/ammo.dm
code/game/objects/items/rogueweapons/ranged/bows.dm
code/game/objects/items/rogueweapons/ranged/crossbows.dm
code/game/turfs/open/water.dm
code/modules/clothing/rogueclothes/quiver.dm

Ports https://github.com/Tree445/Hearthstone/pull/483 by @EtheoBoxxman
Bows and crossbows no longer levelable by hitting a dummy or hitting someone with it.
Hitting living things with bolts and arrows levels the respective skill now.
Can scoop up bolts and arrows with quivers by clicking the tile with them.
Swimming now trainable.

[PORT] Swimming, bows and crossbows leveling + Quiver Scooping

---

code/modules/jobs/job_types/roguetown/nobility/bailiff.dm

The recent Bailiff-Sheriff merge kept the brigandine of the Sheriff, but didn't give this class the heavy armour support required to actually wear it. Thus, the Sheriff can now wear heavy armour.
I considered making _this specifc_ brigandine medium armour, and I still could do that instead, if it's preferred.
A class being unable to wear the armour they're supposed to spawn wearing is obviously an oversight and should be remedied.

Gives the Sheriff heavy armour so they can wear their outfit.

---

code/__DEFINES/roguetown.dm
code/modules/jobs/job_types/roguetown/nobility/hand.dm
code/modules/jobs/jobs.dm

Gives the hand three new classes and makes them latejoinable. The hand has always felt kinda weird as they're described as a cunning spymaster but statwise they're a heavy armor blademaster: they very type of dude their description makes fun of. 
The three new classes are Hand, Spymaster, and Advisor. The 'Hand' class is your classical Hand class - same as before, nothing's changed. Spymaster gets sneaky skills, vaguely similar to the rogue adventurer class. However, they lose out on the heavy armor the standard Hand gets. The Advisor is the final class, made for people who want to play the Hand like a wizened old advisor instead of a spymaster or combat man. They lose most of their combat stats, but gain a lot more skills and intelligence, able to do alchemy and some medicine. They also …

Three new classes for the Hand: you could say things are getting out of h-*I am torn apart by wild vulfs*

---

code/game/objects/items/rogueitems/ropechainbola.dm
code/game/objects/items/rogueweapons/intents.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/grabbing.dm
code/modules/mob/living/living.dm
code/modules/mob/living/living_defense.dm

Ports https://github.com/Rotwood-Vale/Ratwood-Keep/pull/885 by @GuppyLaxx
> This PR changes the math on pretty much all grab related actions to properly use stats and skills.
> Pinning is no longer a roll, and instead an instant but lesser stunning action, meant to hold someone down while others help you, or to keep someone VERY down if you are much stronger than them.
> Grabbing can now be parried and actually uses stamina properly. The grabber uses more stamina than people resisting out of grabs.
> No more wall stuns, no more throwing up Z-levels unless they're laying down.
> A couple other changes overall!

[PORT] Grab Rework

---

code/modules/jobs/job_types/roguetown/church/monk.dm
code/modules/jobs/job_types/roguetown/church/templar.dm

Did you guys know Templar had the highest stat boon of the town other than Captain? Barely beating out the RG themselves. I learned this while wandering to myself "Wow, my acolyte stats sure feel dogwater!", and went looking.
Summary:
Acolyte-
Intelligence 1->3
Endurance 1->2
Speed 0->1
Removed per penalty
Acolytes, being the booky, educated types of the Church, now are actually smarter than their lumpheaded brethren. The endurance tick helps them cast more miracles, and the Speed bonus hastens them to their needed places, while not being so fast as to make them dodge gamers(The Dark hand of combat creep will NOT take me)
Templar
Str, Con, and End remain the same
Perception/Intelligent bonuses removed
Spd malus increased to -2.
This puts them roughly on par with MAA, being a bit stronger, …

Church stat shifts

---

_maps/map_files/generic/CentCom.dmm
code/__DEFINES/preferences.dm
code/game/objects/items/devices/flashlight.dm
code/game/objects/items/rogueitems/coins.dm
code/game/objects/structures/beds_chairs/chair.dm
code/game/objects/structures/tables_racks.dm
code/game/objects/structures/traveltile.dm
code/modules/admin/admin_verbs.dm
code/modules/client/verbs/ooc.dm
code/modules/client/verbs/who.dm
code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
code/modules/mob/dead/new_player/login.dm
code/modules/mob/dead/new_player/new_player.dm
code/modules/mob/living/carbon/human/inventory.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/power/roguelighting.dm
code/modules/roguetown/roguecrafting/leather.dm
code/modules/roguetown/roguejobs/alchemist/reagents.dm
code/modules/roguetown/roguejobs/blacksmith/items.dm
code/modules/roguetown/roguejobs/blacksmith/smelter.dm
code/modules/roguetown/roguejobs/miner/rogueores.dm
code/modules/roguetown/roguemachine/scomm.dm
modular/Neu_Food/code/raw/NeuFood_meat.dm
modular_azurepeak/code/datums/loadout.dm

You now require a minimum of 200 characters in your flavour text in order to join the game.
Grabbing a limb will grab any embedded item in it.
Adds spectacles, halfmasks, and rag masks to the loadout.
Talking too much on a SCOM will make your speech smaller. If you REALLY talk too much, the rats will have something to say in response.
You can fill up smelters with fuel up to 30 minutes. One coal is 10 minutes.
Health potion healing doubled for raw damage, increased by 50% for wound healing.
Default intent for torches is now use.
You can merge coins in bags. Merging coins will transfer coins from your hand to the target stack instead of the other way around.
Crafting wooden tables will always make the "nice" type.
Using a travel tile with a grabbed target will correctly teleport the both …

Flavor Text Now Required + More

---

code/_onclick/click.dm
code/game/objects/items/rogueweapons/intents.dm

Reach weapons will correctly swing even if you're not clicking on a mob. Port from Stonekeep by the excellent @maaacha
Added weapon reach listing to intent examine. Did you know you can examine item intents with shift-click to see their stats? Well, now you know.

Fixes Reach Swings

---

code/modules/jobs/job_types/roguetown/peasants/soilson.dm

Adds farm key to fem soiler loadout because I forgot loadouts are gendered.
Can't get inside the farm without it.

Farm key added to soilbride spawn

---

SpacemanDMM.toml
code/__HELPERS/_auxtools_api.dm
code/game/world.dm
modular/ze_genesis_call/genesis_call.dm
roguetown.dme

Ports https://github.com/Rotwood-Vale/Ratwood-Keep/pull/936 by @Cyprex
> This PR adds support for the auxtools debugger. All that a user needs to do is have the DM Langserver client extension installed(which comes with the recommended extensions) and run with debugging.
> 
> A reference I used a lot in making this: https://github.com/SpaceManiac/SpacemanDMM/wiki/Setting-up-Debugging
> 
> I've elected to add /world/Genesis() to enable debugging as soon as possible, which allows debugging early init. This is taken directly from tg.
> 
> A note on SpacemanDMM: I've only enabled the debugger here. We should enable the (local on the users PC, NOT on github!) linter part of it too, but that first requires dealing with a ton of linter issues, largely from old tgcode.
> Documentation for its …

[PORT] Add support for the Auxtools Debugger

---

code/modules/jobs/job_types/roguetown/nobility/captain.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm
code/modules/mob/living/carbon/human/species_types/roguetown/dwarf/dwarfm.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfs.dm
code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/aasimar.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halforc.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm

Adds racial stats to their descriptions for clarity
Changes knights back to actually being knights. I understand the original premise but this is a little silly. They are knights, everyone knows them as knights, people roleplay them as knights and they have squires. If there's a player issue, that should be seen to IMO rather than using an inaccurate word that may just confuse new players.

Wooo descriptions!

---

code/game/objects/structures/roguetent.dm
code/modules/surgery/surgeries/fracture.dm

Clarifies the text for setting bones that it isn't an immediate heal and the patient will need to rest/sleep for it to fully heal since it's not widely known among healers.
Also sets tent doors to be opaque when initializing since they start out closed and thus should block vision.

Clarifies bone setting text & tent door fix

---

_maps/map_files/dun_manor/dun_manor.dmm
code/game/objects/items/rogueitems/keyrings.dm
code/game/objects/items/rogueitems/keys.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm

Heir bedrooms were locked to the "manor" lockid, now they're locked to the "heir" lockid which corresponds to the new heir room key. Only heirs spawn with the key alongside their usual manor key, thus they get a keyring now.
Knights and courtiers should probably stop using the heir beds to sleep in because they're too lazy to find their own beds. Isn't that kind of weird? Anyways, heirs get up to weird highjinks all the time so enabling them [a layer of privacy](https://youtu.be/-mTZbuUMNwY) just fits imo.

Locks heir bedrooms behind new key

---

code/__DEFINES/roguetown.dm
code/modules/jobs/job_types/roguetown/church/templar.dm

Adds a slightly buffed version of the Monk adventurer class as a subclass for the Church's Templars. 
With Acolytes relegated to healing/support classes, the Church has less diversity in its roles. Since there's no Church role that effectively utilizes unarmed anymore, I wanted to re-fill that slot. Also, the Monk adventurer was the only class I could see that had no towner-analogue, making it harder for people who want to play monastic characters to interact with the town.

Adds Templar subclass - Monk

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/monk.dm

Extremely small balance patch - gives monks, a dodge based class, a point of END at the cost of their point of CON. Made at the request of our dear monk main, Saxobeet.
~~bloats my ROGUEDEV level so valx stops making fun of me~~ Monk's primary means of defense is dodging, which uses stamina, however they have no bonus to endurance so they can run out of stamina quite fast. Constitution, on the other hand, isn't incredibly useful or flavorful for them.

Tiny Monk Rebalance

---

code/controllers/subsystem/rogue/treasury.dm
code/game/objects/structures/stairs.dm
code/modules/power/lanternpost.dm
code/modules/roguetown/roguemachine/mail.dm

Removing lanterns from lanternposts has been removed
Changes all send_ooc_note messages' span to "biginfo" to make them more noticeable, this affects HERMES letter alerts and also treasury messages.
Removes the behavior where if you moved up and down a z-level while fireman carrying someone you would tighten your grip to an aggressive grab and slow down.

Lanternpost & send_ooc_note & fireman carry z-level moving

---

code/_onclick/item_attack.dm
code/_onclick/other_mobs.dm
code/datums/status_effects/rogue/debuff.dm
code/game/objects/inhands_rogue.dm
code/game/objects/items/rogueitems/cup.dm
code/game/objects/items/rogueweapons/melee/knives.dm
code/game/objects/items/rogueweapons/melee/swords.dm
code/modules/antagonists/roguetown/villain/werewolf/werewolf.dm
code/modules/assembly/flash.dm
code/modules/mob/living/grabbing.dm
code/modules/mob/living/simple_animal/animal_defense.dm
code/modules/surgery/bodyparts/_bodyparts.dm

Refactors the silver weapon code, assigning all silver weapons a var that calls on a proc to be used. The code is no longer assigned specifically to the silver dagger.
Or in Layman's terms, it makes it so we can now assign things as silver weapons, and they will work against werewolves and vampires. 
This means that the Elvish Saber, being made of silver, will now work against those two.
However, I also nerfed silver, removing the stun, knockdown, and fire effect on hit. It now purely locks regeneration of the werewolf/vampire it hits, since we all know that is all silver needs to do, and with silver soon becoming more available, this change is needed.
This code refactor also opens the path to creating new silver weapons in the future. If you are a spriter and have something in mind, now …

Silver Weapon Refactor

---

code/modules/farming/fermenting_barrel.dm

Alright, this one might be controversial, or it might not be. 
Basically, 1oz corresponds to 3u on the back end. Barrels that were supposed to be full or random either were filled to 300u or from 0 to 300u- meaning they were filled with 100oz and the range of 0-100oz respectfully. A "full" barrel was never full. This fixes that.
On the other hand, is a barrel half-full a good thing? I invite discussion. Personally, I hate filling water barrels. It's one of the most boring parts of the game in my mind.
Fixes an oversight, potentially good for QoL.

Proper barrel unit range.

---

code/modules/client/customizer/customizers/organ/snout.dm
code/modules/client/customizer/customizers/organ/wings.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/tbutcher.dm
code/modules/mob/living/carbon/human/species_types/furry/akula.dm
code/modules/mob/living/carbon/human/species_types/furry/anthromorph.dm
code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
code/modules/mob/living/carbon/human/species_types/furry/dracon.dm
code/modules/mob/living/carbon/human/species_types/furry/kobold.dm
code/modules/mob/living/carbon/human/species_types/furry/lizardfolk.dm
code/modules/mob/living/carbon/human/species_types/furry/lupian.dm
code/modules/mob/living/carbon/human/species_types/furry/moth.dm
code/modules/mob/living/carbon/human/species_types/furry/tabaxi.dm
code/modules/mob/living/carbon/human/species_types/furry/vulpkanin.dm
code/modules/mob/living/carbon/human/species_types/roguetown/dwarf/dwarfm.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfs.dm
code/modules/mob/living/carbon/human/species_types/roguetown/goblin/goblinp.dm
code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/aasimar.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halforc.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm
code/modules/surgery/organs/feature_organs/wings.dm

midnight, yesterday-ish; "gosh why can't half-kin get horsedongs" me, an intellectual; "huh that's probably an easy fix"
also me: ". . . I mean, I could give it to everyone. . ."
Bleh.
* All species has full access to junk options. This includes external or internal orbs, given people roleplay their horse donged "foota" humen babe already.
* Everyone gets the "anthro" dong, which just allows color customization. You can reset color back to your skintone, so it's no biggie for non-anthros.
* Verminkin no longer have a mandatory snout. They have become anthro but short.
* Half-kin have access to wings now, allowing traditional harpies to actually exist given half the wings are, in fact, harpy ones.
* Drakians have a selection on their wings now, including the _other_ half of the wings that …

dongs, wings, placeholder lore, and butcher butchering

---

modular_hearthstone/code/game/objects/items/signal_horn.dm

Makes horn more useful on a multiple levelled map. It now returns the area if you're in a notable landmark. So, the town, azure coast, basin, grove, church, keep, etc. It won't return places that don't make sense, like being underground, or in the Ultra Secret Dungeons. Horn-hearers will now be able to trust the final line of information, since being on a different z busts the direction/distance.
Later I will figure if that problem can be solved, but for now, the Hornening shall be a useful tool if you're in any area. Also, makes them a bit more accurate at shorter ranges and gives Wardens back the old bogguard horn sound.
Ex) "I hear the horn of the Wardens within 20 meters, somewhere to the northwest, in the Church!"
"I hear the horn of the Wardens very far, to the southwest, in the …

HORNS FUNCTIONAL FOR AZURE <3

---

code/game/objects/items/rogueweapons/melee/knives.dm
code/game/objects/items/rogueweapons/shields.dm

When Rebel was porting over their various shield adjustments they unfortunately missed a wild value on the wooden shield proper, giving it three times the intended defense _ontop_ of the parrying skill. Also missed adjusting the wooden tower shield.
I have my reservations about a wood _tower_ shield having that low of a defense, but I am bringing it inline with the intended changes as seen on other sibling servers.
While I am touching it, I also nerfed the parrying dagger. It still is an incredible tool for parry defense, if without the other perks of a shield so a buckler is still superior, but it isn't _also_ just a steel dagger and thus the best in show. You'll want to carry the parry dagger in your off hand and do your work with the main one. Given a dagger can fit comfortably in your …

Shield updates, parrying dagger nerf

---

code/game/objects/items/rogueitems/natural/clothfibersthorn.dm
code/modules/farming/soil.dm
code/modules/farming/tools.dm

If someone has Legendary farming skill:
Fiber collecting is reduced to .2 seconds from 1 second.
All hoe actions like clearing grass, making new soil and tilling the soil take .5 seconds.
Harvesting a non-perennial plant resets it to zero growth as if it had just been planted, health, water, and nutrition unaffected.

Legendary Farming Mini-Perks

---

code/modules/roguetown/roguecrafting/turfs.dm

Adds /wheat to requirement path because apparently this pink thing's called chaff.
Can actually craft hay now.

Fixes hay crafting

---

code/modules/jobs/job_types/roguetown/youngfolk/squire.dm

Adds a singular, additional squire slot.
Squire is a popular role and 3 is _just_ a bit short for the amount of people that want to play it during main hours.
There is almost IC justification for it in that there are 4 Knights, if you include the captain.
Balance-wise should be fine. Man-at-arms has 8 slots, even though it's overall a much stronger job.
I am slightly biased.

Squire Swarm. Hundreds of Squires.

---

code/datums/world_topic.dm
code/game/world.dm

Fix world/Topic being disabled, which causes issues with TGS.
Fixes the exploit that led to it being disabled in the first place, which is that a default commskey meant the password was just blank. Now if the commskey isn't set, secure topic commands will be disabled.
Fixes an exploit and re-enables world/Topic() so that TGS works properly.

Fix world/Topic

---

code/modules/projectiles/gun.dm

Removes a stub override that tripped up linters because it was relatively pathed.
Gets linters working again so that they're not failing on every PR that's been updated to main since the bow PR was merged a few hours ago. All currently open PRs should probably be updated to avoid something like this happening again, to be honest...

Fix linter failure due to relatively pathed stub

---

code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
code/modules/jobs/job_types/roguetown/youngfolk/apothecary.dm

A seperate, atomized PR as I know some people will dislike it, but;
This removes the full physician keychain from the court physician's underlings, instead just keeping their bespoke key. The keychain has access to the manor and garrison like any full court character, which is somewhat of a byproduct of when the physician lived in the keep. They don't, of course, on Dun Manor. The physician is still nominally a court position, but the apothecary is _not_.
get the FUCK OUT OF MY KEEP AND MY BEDS YOU FUCKING RATS YOU HAVE YOUR OWN HOME
I understand there's appeal of visiting the keep to get involved in the round events, but far too many help themselves in and snootily go "mm, yes, I'm a courtier you know" before sleeping in a heir's bed. (No longer possible, but.) They can be invited in or …

Removes full keyset from apothecaries

---

code/datums/status_effects/rogue/roguebuff.dm
code/modules/cargo/packsrogue/luxury.dm
code/modules/roguetown/roguecrafting/items.dm
code/modules/roguetown/roguemachine/drugmachine.dm

Largely inspired by https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1005. However, moondust was already balanced here. Touching the other two.
-Merchant now sells ozium. Price set to 5. In Purity, ranges from 6 to 15.
-Moondust price increased to 10.
-Spice price decreased to 30.
-Ozium no longer sets your speed to 0, rather it subtracts 5.  Time extended from 10 seconds to 30 seconds.
-Spice now has an added intelligence buff. There is reason to purchase it other than RP... for inspiration, of course. 
Misc change:
-Crafting names for platter and spoons have a (x2) suffix added to properly represent the crafted amount.
Adds a reason to purchase various drugs rather than moondust being the only one worth really getting. Ozium is a painkiller and a stress relief- actually affordable now. …

Drug minor rebalance (and very minor crafting name fixes.)

---

code/modules/farming/tools.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/miner.dm
code/modules/jobs/job_types/roguetown/church/druid.dm
code/modules/jobs/job_types/roguetown/peasants/soilson.dm

- Soilers spawn with Longstrider, No Stink and Seed Know trait, no slowdown from rough terrain and not affected by odour.
- Soilers have a new description from Stone Keep.
- Druids spawn with Longstrider trait.
- Miners spawn with Noc Sight trait.
- Thresh intent is set to 1st on two handed thresher.
- Skill adjustments:
**Miner**
1 Masonry -> 3 Masonry
-1 INT debuff removed.
**Soiler**
3 Knives -> 1 Knives
2 Polearms -> 4 Polearms
1 Wrestling -> 3 Wrestling
1 Unarmed -> 3 Unarmed
2 Archery -> 0
Miners should know quite a lot about the rocks they mine and how to use them. Strengthens their niche in the wake of masoner's removal. Being in dark tunnels adjusts their eyes' to be a bit better than others.
Soilers are Mud Wizards. They shouldn't have issues traversing the land they farm on. …

Evil Farmer Traps Innocent Verevolf In Mud: Adjusts skill changes and traits to soiler and miner

---

code/modules/farming/tools.dm
code/modules/jobs/job_types/roguetown/yeomen/artificer.dm
code/modules/roguetown/roguejobs/blacksmith/smelter.dm
code/modules/roguetown/roguejobs/engineer/prostheticarm.dm

Patches a few overlooked issues with recent updates:
- Artificers no longer have novice medical skill
- Bronze Prosthetics now have 110 HP, 10 higher than a normal arm, instead of 20. Weaknesses and restrictions to healing are in the works as downsides to this.
- Pitchforks count as polearms
- Reverted Multi-bar smelting: Due to the mining update, this buff to smelting is no longer needed.
Necessary changes for balance discussed with maintainer team.

Balance Patch - 03/10/2024

---

code/__DEFINES/jobs.dm
roguetown.dme

Fixes Tailor not being selectable.
Turns out, it was mainly due to the fact the tailor.dm already existed, but someone removed it from the roguetown.dme by force. I re-added it manually, and it is fine now.
Patch to make it selectable.

Fixes Tailor not being available

---

code/modules/roguetown/roguejobs/blacksmith/smelter.dm

When reverting multi-bar smelting, the product and ore were backwards, which led to smelting being entirely broken.
Oops. I was tired when I reverted it because I was asked to, so have mercy on me for this one.. (I am a smith main so I suffered most.)
Critical bugfix.

Fixes Smelting not working

---

code/modules/farming/seeds.dm

Adds a Journeyman-level check for Farming to the process of left-clicking dirt with seeds to make a mound, this can still be done with a hoe at any skill level.

Farming skill check for crafting a seedmound by hand

---

code/modules/roguetown/roguecrafting/items.dm

Just corrects the Unstrung Long Bow crafting name, it was called Unstrung Recurve Bow by accident.
Because I said so.

Long Bow Crafting Correction

---

code/game/objects/items/rogueweapons/melee/axes.dm
code/game/objects/items/rogueweapons/melee/swords.dm

Increases the armor penetration of axes when cutting from 10 --> 20
Increases the ~~armor penetration of axes when chopping from 20 --> 50~~ (This attack has long swing delay.)
Increases the armor penetration of the battleaxe when cutting from 15 --> 25
Increases the one-handed force of the steel sword and it's children from 18 --> 22. The two-handed force remains unchanged.
Increases the damage factor of cutting with swords from 1.0 --> 1.1
Increases the ~~armor penetration of swords when chopping from 10 --> 50~~ (This attack also has a long swing delay and 0.8 damage mod)
EDITS:
Axe chop to 35
Battleaxe chop to 40
Sword chop to 30 but removes its damage malus. Making it deal normal damage instead of 0.8 damage.
Swords and axes are some of the least whelming weapons in the game right …

Buffs Swords and Axes a little bit.

---

code/datums/character_flaw/_character_flaw.dm

Turns out that character flaws are attached to a mob before it has a mind in almost all circumstances, meaning that the +1 reading buff that the bad eyesight flaw was *supposed* to give hasn't been applying. Possibly ever.
Ten second dirty fix to make this happen: it now checks 5 seconds after mob creation to see if a mind is attached.
Fixes a bug, albeit a minor one, and allows people to use a flaw to give their characters access to reading (as apparently intended) in exchange for a particularly gruesome downside. 
Did you know that not having your glasses imposes a permanent screen blur, -20 PER and -5 SPD?

Bad eyesight flaw actually applies its reading bonus

---

code/modules/jobs/job_types/roguetown/church/druid.dm

Follow up to #492 with some extras.  ~~Druids get a farm key. they can  climb in effortlessly (well not effortlessly but if your clever) It's in their job description to help the farms. Are old map never had a sealed up farm thus they never needed one.~~
~~Even throwing aside all that I have never once asked a steward for a farm key without getting one as a druid.~~
specifics:
~~Gives druids a farm key.~~
~~Adjusts the druid job desc to discouraged overstepping with soilgang~~
Gives druids swimming 2 (just something I forgot when I filled in the gaps in their skills just makes sense)
Changes druids farming skill from 1 to 3 with the new addition of a minimum skillcheck for hand farming.
We like fun around here.

Druid skills for PR #492 (and extras)

---

code/controllers/subsystem/rogue/humannpc.dm

Restores the previous delay on NPCs. There was no noticeable effect on behaviour on live server.
We'll see if this helps with the lag.

Re-Lobotomises NPCs

---

code/modules/jobs/job_types/roguetown/youngfolk/squire.dm

a hand main requested that i rename the squire subclasses to make it easier to figure out who needs to get paid, so i did that. while i was in there i shuffled a few things around without significant changes; the chain legs were moved to the base class so that you won't be pantsless in the character creator, and the coif was moved to the satchel so that it won't cause bald squires in the round end credit scroll. this is stuff they had before, it just makes the CC look better and ensures you don't have to remember to click set credit portrait every round
uhm. its good. :)

they can't keep letting kittysmooch get away with this! - squire hotfixes

---

code/game/objects/items/rogueitems/natural/clothfibersthorn.dm
code/modules/mob/living/simple_animal/rogue/farm/cow.dm
code/modules/roguetown/roguecrafting/items.dm

* Bulls additionally drop hides when butchered.
* Right clicking multiple cloth in one tile gathers it into a bundle. 
* Bulk crafting 5x cloth and 5x bag added from https://github.com/Tree445/Hearthstone/pull/496/files
QoL

Cloth QoL and hide drop from butchering bulls

---

code/game/objects/items/rogueitems/natural/stones.dm
modular_azurepeak/code/game/objects/items/spellbooks.dm

Expanding upon the amazing work laid out in https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/473 (and with the author's blessing), this PR adds/changes the following:
- Spellbooks can now also be made with magic stones (the funny glowing & traited stones sometimes lying around). A +10 stone with a high personality score gives a maximum of 15% chance in this manner, up from the 1% chance **per gem** previously. You can also still make them with gems.
- Making spellbooks with magic stones causes a 20% reduction in your success chance when studying them, applied multiplicatively (20% becomes 16%). The stones are fickle and their power is untested. Gems will always be better.
- Non-arcyne characters using a spellbook that they themselves created have their success chance reduced …

Spellbooks can be made with magic stones + non-arcyne study buffs

---

code/modules/jobs/job_types/roguetown/courtier/physician.dm
code/modules/surgery/surgeries/healing.dm

Reworked with the aid of EvenInDeathIStillServe (they now pretty much did the work) Tend damage surgery steps now use multipliers based off skill level. Base healing is 10
journeyman is 1.2x aka 12 damage per use
Expert is 1.4x
Master is 1.7x
Legendary is 2x 
I've also removed a likely unintended rot eater (Pestra patron blessing) perk from the physician since their patron is no longer locked to Pestra as of PR #474 . Dunno why it doubled up. Don't see why they should get to double up on divine traits. They can obviously still obtain this normally. Seemed unintended to me.
Small note. I originally intended to block this behind a perk that only specific roles got but....that was difficult this is lazy and works well enough. But that would be a better solution if someone's up to it.
No more …

lets physicians compete with healing magic (maybe)

---

code/modules/mob/living/carbon/human/npc/skeleton.dm
code/modules/mob/living/simple_animal/hostile/simple_skeleton.dm
code/modules/spells/roguetown/necromancer.dm

Simplemob Skeletons will now go into retaliate-only mode if a mob in their "friends" list uses the Beckon emote on them, and go back to normal if a "friend" uses the Shoo emote.
This targets any Simplemob Skeletons that can see the emoting mob.
Summon Lesser Undead now adds the caster to the simplemob's "friends" list.
Summon Greater Undead will now delete the blank Skeleton mob if no player accepts the offer and skip the cooldown.
Summon Greater Undead's summoned Player Skeletons' now have intents.
Summon Greater Undead's summoned Player Skeletons' now recieve a custom outfit when spawning:
Novice skills in Carpentry, Crafting, Masonry and Sewing to let them work as manual labor.
9 CON instead of 4.
Various weapon skills approximating the Warrior Adventurer class.
Armor randomization …

Simplemob Skeleton tiny features and Lich Greater (Player) Skeleton changes

---

code/game/gamemodes/roguetown/roguetown.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/blackoak.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/steppesman.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/underdweller.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm
code/modules/jobs/job_types/roguetown/mercenaries/mercenary.dm
code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/dragon.dm

So, funny thing. The minimum number of bandit slots was 25. Isn't that crazy? Haha.
Anyways, when bandits roll, the minimum is now 4, increased by 1 for every 5 players readied up beyond 20, with a maximum of 6 bandits.
Buffed dragon damage. Gave them proper butcher results. Removed the necropolis chest from the boss version.
Mercenary slots increased to 8. There are no more class slot maximums for mercs.

The Bandit Culling

---

code/__DEFINES/lighting.dm
code/modules/mob/living/carbon/carbon.dm

* Buffs Noc Sight trait from 243 to 225.
* Buffs Dark Vision (the spell) from 220 to 215.
Noc Sight wasn't actually all that sightly, you couldn't see much and most resort to raise the gamma on their monitors. This should hopefully kill some of the incentive to do so, while properly playing into the thematics of a Noc worshipper.

I Can See Sounds: Buffs Noc Sight

---

_maps/map_files/dun_manor/smalldecap.dmm
code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/dragon.dm

PR fixes the dragons on mount decap and stops them from breaking out of their own arena. Also disables the lava swoop ability, which had a tendency to permanently break tiles because some of the sprites related to the ability were missing.
I also made a few small adjustments to loot spawns and reduced the amount of random money spawners around mount decap, since there were a few too many in hindsight.
The dragon broodmother was breaking out of its arena/dungeon area every round; which was silly. This should fix that!

Dragon fixes and general mount decap adjustments

---

code/controllers/subsystem/mobs.dm
code/controllers/subsystem/rogue/humannpc.dm
code/datums/status_effects/debuffs.dm
code/game/objects/inhands_rogue.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/living/carbon/human/npc/_npc.dm
code/modules/mob/living/carbon/human/update_icons.dm
code/modules/mob/living/carbon/update_icons.dm
code/modules/mob/living/life.dm
code/modules/recycling/conveyor2.dm

- AI-controlled mobs now regenerate stamina (and do some other misc. processing).
- Human NPCs will no longer take actions while busy (i.e. getting up).
- Tries to optimise build_appearance_list.
- Makes the sleeping status effect slightly less expensive by removing a redundant update_health call.
- Optimises inhand generation by cacheing an IconStates call.
- Removes the indefatigable trait from NPCs.
- Fixes me breaking conveyors because I didn't understand something.
The AI should be less overpowered, and the game should run a good bit faster. Also fixes conveyors moving you at lightspeed LMAO

Tweak human AI, readd stamina to NPCs, misc. optimisations

---

code/modules/roguetown/roguecrafting/items.dm

fixes crafting pyro arrows
arrows are `/obj/item/ammo_casing/caseless/rogue/arrow/iron` not `/obj/item/ammo_casing/caseless/rogue/arrow` 
oops :(
pyro arrow crafting wasn't working...

Pyroclastic arrow crafting fix

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
code/modules/jobs/job_types/roguetown/church/monk.dm
modular_hearthstone/code/game/objects/items/clothes/neck.dm
roguetown.dme

Ports https://github.com/Tree445/Hearthstone/pull/339 by @Ephemeralis
- "Using MMB on a worn psycross causes you to start doing a devotion prayer if you have the ability to, otherwise it does nothing new. Purely a convenience/QoL thing to make people need to look at the verb panel less.
- A new Adventurer subclass has been added for the Cleric: Cloistered Devout.
- Cloistered Devout is a spellcaster-focused variant of the cleric that foregoes all of the armor and weapon buffs it gets in exchange for gaining half the passive devotion gain that Priest gets (0.5) and access to T3 spells like an Acolyte. It does not gain Churn like ordinary clerics do to compensate for this.
- It gets a gambeson, some devotional robes (matched to your chosen patron where possible) and a wooden staff as …

PORT: Cloistered Devout, new Cleric subclass

---

_maps/map_files/dun_manor/dun_manor.dmm

These should not exist in the map, their sprites are also broken, please fix them and reflavor them before putting them in.

Removes Dreamer/Maniac/Trey Liam cutscene pants from map

---

code/game/turfs/closed/minerals.dm

Lowers the probability of copper spawning when mining.
Yea so the addition of copper dilutes the pool a bit much.
This leads to smiths having to resort to importing iron which is less than ideal, given how often iron items are made when compared to copper.
Also dropped down tin a smidgen.

lowers copper & tin ore spawn rate

---

modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Message has been lowered to 1 point cost but now emits a visible_message in addition to its previous whisper indicator.
Darkvision cooldown reduced to 1 minute from 2 minutes.
Longstrider cooldown reduced to 1.5 minutes from 2 minutes.
Haste cooldown reduced to 1.5 minutes from 5 minutes.

Tiny spell touches

---

code/controllers/subsystem/rogue/devotion.dm
code/modules/mob/living/say.dm
modular_azurepeak/code/modules/spells/orison.dm
roguetown.dme

As mages have cantrips (prestidigitation), so too shall divine casters have orisons.
This adds a multi-functional hand touch spell to *all* divine casters (including churchlings) that has the following functionality:
- FILL intent creates water inside any container that can normally hold water, consuming a little bit of devotion and fatigue each time. It will continue to cycle of its own accord until you either stop it, the container is full, or you run out of devotion. Higher levels of holy magic skill increase the amount of water you make per devotion, and also decrease the fatigue component - accomplished holy casters will find this effortless.
- You can also use the hand touch on a cloth to wet it, with higher holy levels increasing how much. This is significantly cheaper in all …

Add create water, thaumaturgy and light orison for all divine casters

---

_maps/map_files/dun_manor/smalldecap.dmm
modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/dragon.dm

This PR replaces the ash drake on Mount Decap with a new variant of dragon known as the "dragon broodmother" - which is simply a beef up simplemob dragon capable of casting a buffed version of greater fireball known as dragon's breath.
The three smaller dragons have had their health increased a bit to compensate for the fact that the boss fight is now a fair bit easier.
After watching players attempt to clear the dragon arena for the past week, I've come to the conclusion that a whole ass ash drake is probably too much. 
The ash drake would repeatedly get aggro'd by players, immediately kill whoever aggro'd it, and then wander around Mount Decap for the next 2 hours killing pretty much anyone it came in contact with. 
This PR should hopefully make it a challenging, but possible fight - …

Mount Decapitation Dragon Adjustments

---

code/datums/mob_descriptors/descriptors/other.dm
code/datums/sexcon/sexcon_helpers.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/living_descriptors.dm

Removes the defiant descriptor, since we've rules to put in your preferences in your OOC notes.

Removes Defiant Description

---

code/modules/mob/living/carbon/human/examine.dm

Examining a bandit will no longer give you the GET YOUR VALIDS HERE!!! text.

[TESTMERGED] Removes Bandit Examine Message

---

code/modules/clothing/rogueclothes/feet.dm
code/modules/clothing/rogueclothes/gloves.dm
code/modules/clothing/rogueclothes/pants.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm

So like. Chausses, gauntlets and boots all had the same integrity, no matter whether they were iron, steel or blacksteel. And basically the same armour values. So they pretty much were literally just cosmetic. That's funny. Anyway this is no longer the case. Steel is more resistant than iron, and blacksteel even more.
Also adds weapon choices to the knight errant. Bastard sword, steel flail or spear.

Adds Integrity Values To Some Armour Parts

---

code/controllers/subsystem/rogue/treasury.dm
code/modules/roguetown/roguemachine/steward.dm

Your bank account is no longer independent from the treasury. Being paid or fined will affect your balance without affecting the treasury. Withdrawing will drain the funds from both your account and the treasury. Putting money in adds money to both, also.
So basically this means you can pay people with money you don't have. Like a bank! Wow!
You can now put coins directly into the NERVE MASTER to add funds to the treasury.
The treasury log will correctly mention the names of account owners.

Bank Accounts Tied To The Treasury

---

code/modules/roguetown/roguemachine/scomm.dm

It's kind of incredible that this hasn't happened more often given the SCOM volume we've got in our current map. Messages over 200 characters used to spawn a pissed off rous once per SCOM, now they don't.
Roleplay server and all that.
I shouldn't really need to explain why spawning hostile mobs on people who are longform roleplaying is a bad thing. (Also, you could totally abuse this for free early mats and annoy everyone in the process if you wanted to.)

Don't spawn rous from the SCOM at >200 chars

---

code/modules/jobs/job_types/roguetown/courtier/butler.dm
code/modules/jobs/job_types/roguetown/youngfolk/servant.dm

SERVANT
* Mildly buffs knives, sneaking, sewing. Adds climbing, crafting, and lockpicking.
* Adds small speed buff.
* Adds peasant cap to servant loadout.
* Removes constitution debuff.
BUTLER
* Removes constitution debuff, replaced with strength debuff.
* Adds small speed buff.
* Adds climbing, lockpicking and stealing.
Steers the servant class into a more lithe direction, while also empowering their crafting capabilities. They'll be in a position to work against the keep as ears for outside sources, or prove themselves a household asset against the keeps' enemies. Should also incentivize royals not to be heavy handed with abuse larp now that a good servant is equipped with the means to really ruin their day.
This also really sucks.

Fukc Mine Sisyphean Serf Lyfe: Buffs Servant

---

code/__DEFINES/role_preferences.dm
code/modules/admin/sql_ban_system.dm
code/modules/spells/roguetown/necromancer.dm
html/admin/banpanel.css

Adds Roguetown roles to the roleban menu. Removes the base SS13 roles, including antags. Adds a roleban type define for necromancer skeletons. Tweaks the banning panel CSS to be easier to read.
I can't actually test this very much locally because I don't have a database set up, but I didn't get Javascript errors when I clicked the buttons or anything, at least. You could testmerge it I guess. Maybe back up the database just in case?

Add Roguetown roles to roleban menu

---

code/game/objects/items/rogueweapons/melee/knives.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/vaquero.dm

This changes the description of the navaja knife, grants said knife to the vaquero and slightly buffs the vaquero's climbing stat, to better fill the swashbuckler archetype.
The navaja is a very iconic weapon originating in Iberia due to the conditions of its time. It has a very strong reason to be invented in the Iberian-Italian Etrusca, rather than the more middle-eastern inspired Zybantian. It would still find its way to the latter through large amounts of trade.
I think it is much more flavourful for the vaquero to receive this knife, rather than the current steel-dagger. It also directly ties the class to the other Etruscan class, the condottieri, who also uses the knife!
Finally, the slight buff to climbing allows the Vaquero to be the dexterous and dashing fencer of all of our …

Vaquero Flavour Pack woooooo!!

---

code/game/objects/items/rogueweapons/melee/swords.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm

Changes the desert rider's sword's name from 'kilij scimitar' to the more appropriate 'shamshir'. Also slightly tweaks the class' description to reflect this.
"Kilij scimitar" is an anachronistic name. A kilij is a similar yet different sword to a shamshir, and a 'scimitar' is a european spelling of 'shamshir' which would not be used by the native wielders of the weapon. Simply renaming the sword to 'shamshir' is more reflective of the weapon type, and more appropriate for the culture it emerges from in-game.

Changes the Desert Rider sword's name

---

code/game/objects/structures/roguewindow.dm

Changes the description of windows and reinforced windows to remove a reference to glass' rarity.
This is a holdover in the code from other server's lore. Glass is plentiful in our server and is not more expensive than you'd expect. Glass bottles do not cost a lord's ransom, so the reference is inaccurate to our lore.

Changes window descriptions

---

code/modules/jobs/job_types/roguetown/garrison/villagechief.dm

Changes up many of the Village Elder's skills to be the counterpart of the Veteran rather than a duplicate of them. The Elder is knowledge of trades over combat, after all.
The PR removes references to the Bog Guard and replaced it with the Wardens, giving her a Warden furcoat rather than the default white one. A little PQ restriction is added too, since the whole job slot revolves around conflict de-escalation, which is not something everyone is well aware of.
We have the Veteran to act as a mentor to the combat-oriented roles, but if anyone wants aid in a specific crafting skill? Good luck!
The Elder's ability to wear both medium and heavy armor has also been removed, replace instead with the Empathy and (poor) Price-Seeing traits.
As such, everything combat-oriented save for the …

Silly little Village Elder skills change

---

code/__DEFINES/lighting.dm
code/datums/mind.dm
code/datums/special_traits/traits/traits.dm
code/modules/clothing/rogueclothes/armor.dm
code/modules/mob/living/carbon/carbon.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Back-end adjustment to Nocvision to make it not overwrite and give it a define
Fixes the learnspell auto-removal since I wrote it badly OOPS
Fixes a typo in Arsonist special
Fixes iron breastplate description

small things

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm

Adds a new sub-class to the Desert Rider mercenary.
The move away from deft, dual blade fighters toward a more static shield based combat style has caused a mixed reaction amongst players with Desert Rider characters. To ensure everyone can play their character in a style that suits them, I've separated the class into two archetypes.
Janissaries, mace-and-shield wielding frontliners. They have decreased mobility, but heavier weaponry and protection including a chain coif.
Blade Dancers, who are more fitting for a 'scout/skirmish' role. They are better at climbing, sneaking etc. and wield swords and daggers. They do not get a shield, nor the chain coif, and are less physically imposing than janissaries though retain an edge through their mobility.
This is the loadout for the janissary …

Desert Rider Archetypes wowowow

---

code/modules/mob/living/carbon/human/npc/_npc.dm
code/modules/mob/living/living.dm

Addresses the 'stand spam for 700 years' thing we've had for a while. Downed NPCs will now try to fight back and flee where appropriate. I've marked this as testmerge only because it kind of makes a lot of encounters significantly more challenging now that things just don't let you kill them all the time.
Additionally, when idle, they will attempt to stand up every 5-20 seconds, and **will heal for 25% of their Constitution stat** every 6-10 seconds **UNLESS THEY HAVE MORE TOX DAMAGE THAN THEIR CONSTITUTION STAT.** You should be able to semi-effectively whittle down tougher NPCs with poison hit and run attacks now, to mirror poison's usefulness on simplemobs.
I've put the regeneration in to give mobs a bit of a chance to recuperate if they manage to get away from you and you don't push …

[TESTMERGE ONLY] NPC stand-spam fix and idle mode health regeneration

---

_maps/map_files/dun_manor/dun_manor.dmm

This adds a few extra braziers along the southern road leading into town from the forest.
https://github.com/user-attachments/assets/4c8f3a1c-6da6-4e2d-93ff-e824f0ebb0d0
The latejoin towner spawn location was recently moved further south. The road leading into the town from the latejoin spawn carriage is really dark and most towner roles do not spawn with a torch or lantern. While this isn't exactly a massive issue if you know where you're going, this should make it just a little bit easier for new players to navigate to town, especially if spawning at night.

adds braziers along the southern road =)

---

code/_onclick/other_mobs.dm

Theft is pretty spartan. The way it currently works is that the game checks to see if you're in the standard sight exclusion cone drawn behind someone, and if you are, it lets you try to steal.
This PR makes the following changes:
- Stealing can now be attempted if:
- ...you are within the standard sight exclusion cone (as before)
- ...your victim is not standing (from any direction)
- ...your victim is unconscious (from any direction)
- ...your victim's eyes are closed (from any direction)
- ...your victim is blind (from any direction)
- ...your victim's eyes are blurry (from any direction)
- Stealing should now no longer play a pickup sound & animation when successfully stealing something for nearby observers.
- This always irked me since a *huge* number of people often immediately …

Stealing position and XP updates

---

code/game/objects/items/rogueweapons/melee/swords.dm

The lord rapier previously had 2 more damage than the average rapier. Since swords have been buffed... it ended up being 2 damage weaker than a normal rapier.
Oops my bad.
Making it identical to normal rapiers at the very least.
The fancy gem-encrusted one-of-a-kind rapier probably shouldn't be the weakest rapier in the game.

Lord Rapier Fix

---

_maps/map_files/dun_manor/azure_forest.dmm
code/modules/antagonists/roguetown/villain/vampire.dm
code/modules/antagonists/roguetown/villain/vampirelord.dm
code/modules/antagonists/roguetown/villain/werewolf/werewolf.dm
code/modules/antagonists/roguetown/villain/werewolf/werewolf_spells.dm
code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/brigand.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/hedgeknight.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/roguemage.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/sawbones.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/sellsword.dm
code/modules/mob/living/carbon/human/species_types/vampire.dm
code/modules/roguetown/roguemachine/lottery.dm

a few things:
- antag balance pass so they're actual threats
- map fixes
- let's go gambling!! fixes/changes
Antags overall had generally worse stats than their townie counterparts.
The most egregious example of this was the bandit subclasses, which were all objectively worse than their merc counterparts in both gear and skills. Their skills probably need another poke, but their stats are now better, and generally on-par with the captain's. (Bandits will almost always be outnumbered; giving them extra stats as a cushion is fine.) They also get some extra fortune to offset the stress that they will inevitably accumulate, and because...hey, you kind of have to be a bit lucky to make it out there, right?
Only subclass im super concerned abt is hedge knight, but I don't rly foresee it being …

Bear PR Improvement Blast!!

---

code/modules/clothing/head/misc.dm
code/modules/clothing/rogueclothes/cloaks.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
code/modules/vending/wardrobes.dm
tools/UpdatePaths/Scripts/70060_hats_repath.txt

Changes the descriptions of several tabards + surcoats and removes some buried chudcode for good measure.
The previous description of these items mentioned that they were 'medieval garments', which sounds like a historian writing about a period in the past rather than someone living within that period. Tabards are not historical artifacts, to our characters, they are things they see commonly in every day life being worn. 
The item which references to have been removed was not in game, so served no purpose and had a nasty name. It will not be missed.
ALSO gives the warrior class for adventurer some reading skill and flail proficiency, as requested.

Pendantic tabard description change + chudcode removal + warrior class tweak

---

code/modules/jobs/job_types/roguetown/yeomen/archivist.dm

One of those "I Play This Job A Lot And These Things Annoy Me" PRs.
- Archivist gets a serfstone at roundstart (they can already afford one 95% of the time thanks to their starting mid pouch, but it's just an annoyance on no-merchant rounds)
- Archivist arcane skill is now hard-set at 2 so you consistently have the same spellpoints to play with each round
A gentle balancejak massage for a not-especially played or prominent keep-adjacent role.

Archivist tweaks: gets a serfstone, consistent arcane skill

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm

The bard's taken a liking to singing about their favorite god.. someone tell the Necran Hymnist that heavy metal is still unacceptable on church grounds.
Adds a 'miracle' alternative to the arcanist, giving the bard a paladin-level of miracles, sans churn undead. Their stats are similar to arcanist, with a bit of stat shuffling.
Filling out holes in the adventurer's roster is always a good thing in my eyes! Much like my Arcyne Knight update, I will always think more is customization and options is better. I'll try to make some town alternatives in the future as well if these make it through at all, who knows. First stabs at making prs for roguetown stuff so I probably mucked it up for not being modular or something.

Hymnist, the Gospel-Toting Bard

---

code/datums/gods/patrons/divine_pantheon.dm
code/modules/spells/spell.dm
modular_azurepeak/code/modules/spells/pantheon/divine/necra.dm
roguetown.dme

I felt a little bad with Zizo getting all of the cool shit and Necra's still out here with like, two broken spells, so. I'm mulling over changes to Churn and a suitable t3 replacement for Necra still, but this'll do as a stopgap.
Replaces Burial Rites with a new Borrowed Time spell.
Borrowed Time allows you to channel a steady flow of fatigue and devotion into an adjacent target, during which time, they physically cannot die. They gain the NODEATH trait and have their blood set to a minimum-survivable level every tick, alongside a big wad of oxyloss healing. You can use this on people who are very alive too, for whatever reason - and this is entirely intentional. I'm sure some of you will find interesting (and horrible) ways to exploit selective invulnerability for your amusement and the …

Add Borrowed Time spell to Necra (replaces Burial Rites)

---

code/datums/gods/patrons/inhumen_pantheon.dm
code/modules/spells/roguetown/acolyte/general.dm

Two quick fixes:
Inhumen pantheon never had a T0 set, so some roles that can spawn as inhumen devotionals (such as vagabond's Excommunicated subclass) weren't getting lesser miracle. This is fixed.
In addition, Zizo's miracle conditional bonus was treating an entire stack of bones as just 1 bone. It now handles this properly.
Inhumen devotionists should be able to heal when they're not churchlings! Definite oversight.

Ascendent/inhuman pantheon miracle fix + zizo miracle fix

---

code/modules/cargo/packsrogue/Brigand.dm
code/modules/cargo/packsrogue/Knave.dm
code/modules/cargo/packsrogue/Mage.dm
code/modules/cargo/packsrogue/Sawbones.dm
code/modules/cargo/packsrogue/Sellsword.dm
code/modules/cargo/packsrogue/Things.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/sawbones.dm

Fixes some broken items in the HOARDMASTER. Arrows, steel cuirass, and any item that had multiples has been reduced to singles. The cost of Pyroclastic arrows and bolts has gone up TREMENDOUSLY. I didn't realize they were so good! Dragonscale necklace has gone from 750 base favor to 900, being the ultimate 'End Game' of the Favor list. Sellsword's 'old merc cosplay' buy lists have been fixed and cheapened. Bottle bombs down to 30 from 50 favor, the INSANELY lethal high-lethal poison up from 50->100. Sawbones' playstyle actually restored, they now have the proper spd, sword skill, and dodge bonus I intended for.
yeag jus' some fixes pretty much? Sawbones is balance but, It was mentioned in the og post and just got fucked up because merge stuff awawa. Little bit of balance stuff for FAVOR …

Hoardmaster fixes/tweaks

---

code/modules/projectiles/projectile/magic.dm

Really simple: if you have CATCH mode enabled while casting Fetch at an item, you will attempt to catch whatever you're trying to fetch. Note: throw_at is not perfect, especially on diagonals. 
If you cannot catch it, it will be thrown at you directly instead. Be smart.
Sick wizard parkour. Makes fetch 100% more cool.

Fetch improvements: caster can catch items

---

code/modules/mob/living/carbon/human/npc/goblin.dm
code/modules/surgery/organs/eyes.dm

Barber doctors making a business out of putting undead eyes on people is wonderfully thematic, but full night vision is a pretty strong thing to have with no downsides.
So, I've added one.
Non-undead creatures with undead eyes will suffer a very slow poisoning effect that should make them need to manage it over the course of a round with leech use, slow, ongoing healing potion consumption, or periodically visiting a nearby priest.
It will not kill you immediately or even quickly - I don't want to discourage people from doing this still, I just want them to have to engage with other game mechanics to support it.
More mechanical interactions are a good thing!

Undead & NPC goblin eyes slowly poison player recipients

---

code/modules/jobs/job_types/roguetown/peasants/beggar.dm
modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/beggar.dm
roguetown.dme

Translates the Beggar job into a Vagabond subclass and makes the actual Beggar job not selectable at roundstart anymore.
I didn't bother porting the wise beggar thing since I don't think a single soul will miss it. Applied STALUC clamping to 5-15 instead of 1-20 as per the original vagabond rework, everything else is unchanged.
This is more or less an organizational refactor thing. Little functional change outside of making the job selection screen slightly less cluttered.

The Beggarocalypse: squash beggar into a vagabond advclass

---

code/datums/gods/_patron.dm
code/modules/mob/living/simple_animal/hostile/simple_skeleton.dm
code/modules/spells/roguetown/necromancer.dm
modular_azurepeak/code/modules/spells/pantheon/inhumen/zizo.dm

Fixes Rituos not updating body parts after the skeletonization process (visually, the underlying logic was fine).
Also fixes summoned skeletons not considering their summoners as friends. This has been broken in roguecode for possibly years before now.
In addition, skeletons summoned via Raise Lesser Undead will not be hostile to all Zizoites if their summoner is also of Zizo. This does not affect existing map-spawned skeletons in any way.
Rituos completion also grants access to Prestidigitation as well.
Zizo work good. Skeleton changes let the Cabal form creepy... well, cabals, allowing them to make spontaneous dungeons to endanger other wayward souls for fun and profit.

Minor Zizo fixes + Zizo-summoned skeletons are friendly to the Cabal

---

code/modules/admin/playerquality.dm
code/modules/jobs/job_types/roguetown/youngfolk/orphan.dm
code/modules/mob/mob.dm
strings/changelog.txt

okay so umm im a silly goober and RCP used to give you PQ only if you had *more* than 10 PQ. haha
ANYWAYS.
RCP will give you PQ if either of the conditions are valid:
- You have less than 10 PQ.
- You have less than 100 RCP.
Also gives vagabond 2 RCP.
And because I'm the worst person ever I'm making the MC tab accessible to coders through the debug flag instead of admin.

RCP Gives Up To 10 PQ

---

code/__DEFINES/tools.dm
code/game/objects/items/rogueitems/natural/wood.dm
code/modules/roguetown/roguejobs/alchemist/reagents.dm
code/modules/roguetown/roguejobs/blacksmith/tools.dm
code/modules/spells/roguetown/acolyte/pestra.dm
code/modules/surgery/_surgery_step.dm
code/modules/surgery/surgeries/organic_steps.dm

Does a few things:
- Tongs (inc. stone) and stakes are usable as improvised retractors and improvised hemostats respectively, at a low success chance.
- Failing surgery steps adds a simulated infection reagent to your patient/victim that slowly poisons them over time, scaling depending on how bad your success chances are at that particular step.
- Infection causes slow ticks of toxin damage over time and raises your temperature relative to how much infection you have in you.
- Major infections can raise your body temperature to levels where it can kill you.
- Major infections can also potentially self-sustain themselves in you if you're very unlucky, so take care of your Fortune levels when you think you're super sick (indulge your vices, handle your stress, etc).
- The Cure Rot miracle …

Infection & improvised surgery updates

---

code/modules/roguetown/roguecrafting/alchemy.dm

Lowers the cost of crafting:
Ozium (From 2 ash, 0,66 Oz of Berry Poison, 2 swampweed to 2 ash, 0,66 Oz of Berry Poison, 1 swampweed)
Moondust (From 2 ash, 0,66 Oz of Berry Poison, 2 pipe leaf to 2 ash, 0,66 Oz of Berry Poison, 1 pipe leaf)
And adds bulk crafting recipes for them, with costs of:
3 ash, 1 Oz of berry poison, two swampweeds for Ozium
3 ash, 1 Oz of berry poison, two pipe leaves for Moondust.
Crafting drugs has not been done  a lot (If at all) due to the merchant selling them for VERY cheap. This hopefully will make it so that producing drugs by yourself is more enticing instead of a waste of time, also also makes it so that you don't need to have a garden as an alchemist to make drugs, foraging will give you all you need, baby!

Lowers the crafting cost of Moondust and Ozium

---

modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/vagabond.dm

The orphan job Vagabond is derived from was previously only accessible for adult chars - it's now accessible for all of the older age ranges, too.
Self explanatory.

Allow all char age ranges for Vagabond

---

modular_azurepeak/code/modules/spells/orison.dm

When casting Orison and using the Fill function, if your patron is Ascendant (technically, if their undead_hater variable is false), you will create "cursed water" instead of holy water (please suggest a better name than cursed water, literally nothing else but "profaned water" came to mind and that just sounds like you peed in it). Instead of healing the living and burning the undead, cursed water heals those who are undead and/or whose patron is Ascendant. Anyone else drinking it takes minor stamina drain.
Clerics of Zizo, having a spell to make themselves undead, are deathly allergic to their own holy water. That doesn't really make sense.

Clerics of Zizo are no longer set on fire by their own holy water

---

code/modules/surgery/surgeries/organ_manipulation.dm
modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/excommunicado.dm

Just a quick fix to allow for organ manipulation with improvised hemostats, and gives Excommunicated vagabond acolyte-level medical skill for them to do things with.
Fixes and very basic rebalancing. Kind of weird that a cleric role had no medicine.

Improv surgery fixes & excommunicated adjustment

---

code/datums/status_effects/rogue/roguebuff.dm
modular_azurepeak/code/modules/spells/orison.dm

At the request of dongwaiver from Discord, both blessings of light and healing miracles now show a slight outline around their target to indicate that they're active. In addition, healing miracles now also have a show line on examine.
Healing miracle:
Light blessing:
Knowing what's happening to people on your screen at a glance is always a good thing.

Orison blessings & miracle healing show special outlines

---

_maps/map_files/dun_manor/azure_forest.dmm
code/game/objects/items/rogueitems/keyrings.dm
code/game/objects/items/rogueitems/keys.dm

This gives the warden their own 'watchtower' key and removes the extra garrison keys from the watchtower, replacing them with spare watchtower keys. 
The warden watchtower is now opened with a watchtower key as opposed to a garrison key.
I also threw a few palisades around the watchtower as well because I think they look cute. They don't really add a whole lot of security, in truth - I just like them.
There aren't many people that play warden; and the watchtower is often rushed early into the round and looted for the free garrison keys inside - which sucks. This should hopefully give people less incentive to break in near round start just to rush the free set of keys inside.
Wardens are still a part of the garrison and still spawn with garrison keys in their key ring as well as a …

Gives the wardens their own tower key

---

code/game/objects/effects/glowshroom.dm
code/game/objects/items/handcuffs.dm
code/game/objects/items/rogueitems/natural/animals.dm
code/game/objects/items/rogueitems/natural/clothfibersthorn.dm
code/game/objects/items/rogueitems/natural/wood.dm
code/modules/mob/living/carbon/human/npc/_npc.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/rogue/creacher/volf.dm

Previously, NPCs did not give a solitary shit if you were sneaking or not - they just got up in your shit. Now, they do!
Based on a patented blend(tm) of the mob's perception, the manner of your sneakiness/invisibility, the equipment you're wearing and a good ol' dash of luck (both good and bad), NPCs will now interact meaningfully with your visibility or lack thereof, allowing you to potentially sneak past them, stab them violently in the back, or whatever it is you wish to do.
Naturally, magical invisibility is a little bit better at hiding you than mundane invisibility. Who would've thunk?
In addition, stepping on twigs and thorns also causes you to briefly leave your stealth, including if you're invisible. Tread carefully, wanderer!
Sneak around dungeons for loot and glory. Frustrate …

NPCs now respect and interact with stealth/sneaking

---

code/modules/spells/roguetown/acolyte/astrata.dm
code/modules/spells/roguetown/acolyte/eora.dm
code/modules/spells/roguetown/acolyte/general.dm
code/modules/spells/roguetown/acolyte/noc.dm
code/modules/spells/roguetown/acolyte/pestra.dm

We don't really use the spell pipeline properly in a lot of cases for most currently coded spells, so we rely on `revert_cast()` being called manually inside spell blocks to refund resources and reset cooldowns if a given target isn't supplied correctly.
I've gone through a bunch of the older miracles still in play and applied this behavior where appropriate.
tl;dr: most miracles will refund devotion and not go on cooldown if you target the wrong thing with them now.
Just a straight up quality of life thing.

Older miracles properly return devotion & reset cooldown on failed cast

---

code/modules/mob/living/carbon/human/examine.dm

Does what it says on the tin: shift-clicking someone will now show if they have any especially large (*) items lodged in their body somewhere.
Especially large in this case means "larger than tiny w_class", so really small things like darts, splinters, throwing stars etc should remain hidden. Arrows, swords, knives and all that should be pretty obviously stuck in you.
It was needlessly obtuse before to find out if someone say, had a sword sticking out of their chest. You'd notice that normally. Now you do.

Show embedded items larger than tiny on human examine

---

modular_azurepeak/code/modules/spells/orison.dm

Apparently people are sitting inside the church spamming create water on barrels for 30-90 minutes instead of playing the game to max holy magic levels. Clearly not the intention when orison was added.
I've given orison the same expert skill ceiling cap as prestidigitation, and also limited it to a maximum of 50 xp per cast (which should roughly equate to about 10 ticks of water, which is what I'd consider the median use case). You can now spend 30-90 minutes doing the roguetown equivalent of tick manipulation if you want your fat XP gains.
Or you know, you could just go play the game. Or the administrators could beat people with hammers who are doing this kinda thing. I don't know.
It just is.

Limit orison create water xp ticks and prevent orison from skilling above expert miracles

---

code/modules/mob/living/living.dm

Adds in a basic pixel shift for when someone is grabbing something, similar to base TG. Roguecode's offsets are a mess and I really can't be bothered fixing them so this plays up in some circumstances, but it's better than nothing and you can *usually* clearly see when someone's passively or aggressively grabbing someone on screen now.
Being able to see what's up is kind of important.

Adds basic pull/dragging offsets to carbon mobs

---

code/controllers/subsystem/overlays.dm

Has a decent chance of breaking overlay-related stuff in insidious ways, but local testing (spawning in and walking around/doing stuff that should affect overlays like clothing hiding etc) seems to be working okay. Let's be real though, *something* is going to break or someone would've done this already.
More or less ported from up-to-date modern TGcode - not entirely my work.
My limited understanding of this suggests that loc overlays may have been being compiled twice (subsystem already does it every tick) which is not great. It's possible that our ten morbillion sunlight objects applying overlays to every tile might've been triggering this a similar number of morbillion times, so now they only do it ten morbillion times instead of twenty morbillion times. Progress? Maybe?
Make sure you …

[TESTMERGE] Attempt build_apperance_list optimization

---

modular/Neu_Food/code/cooked/NeuFood_snacks.dm

I went and checked all other instances of add_sleep_experience, all the rest of them seem to be nested in a do_after or in an appropriate proccall. This one recipe was just outside of the do_after, an anomaly.
Just a tiny one liner bug fix.

fix for infinite cooking experience by adding onion

---

code/datums/gods/patrons/divine_pantheon.dm
code/datums/special_traits/traits/traits.dm
code/modules/antagonists/roguetown/villain/werewolf/werewolf_spells.dm
code/modules/spells/roguetown/acolyte/dendor.dm

Spitballing in general chat on Discord revealed the funny idea of giving Dendor access to the werewolf howl via their missing T4 spell. So, I've gone ahead and done the following:
- The werewolf howl SFX is now **half** the volume that it was. That shit was loud as hell because it spawns directly on the turf underneath you, and it was also 100 volume before.
- Anyone with the Beast language can now understand werewolf howls.
- The Polyglot special no longer awards the Beast language.
- Dendor devotionists/druids get access to a modified version of the werewolf howl spell titled as Call of the Moon as their T4 spell.
- It is only usable at night.
- The first time you use it, you'll gain understanding of the Beast language if you don't already have it.
This also has the neat side effect of …

Something In The Air Tonight: Werewolf howl adjustments and Dendor T4 spell

---

code/modules/jobs/job_types/roguetown/nobility/lady.dm

Consort had no riding skill levels, so I gave them two levels of riding skill. I think nobles, specially one like the high status as consort, would know how to ride.
Added two Riding skill levels to the consort (same riding level as non-squire prince), where previously there was none.
The consort is a noble of high status. It makes sense to me that they would have learned how to ride while growing up.

Update lady skills Riding.dm

---

code/modules/jobs/job_types/roguetown/church/templar.dm

Reduces templar's strength modifier from +3 to +2, but removes their -2 speed debuff.
Every other non-antag +3 strength heavy armor class has had their strength modifier reduced to +2, templar retaining their +3 strength mod was apparently an oversight. More than +2 strength is supposed to be reserved for antags and/or roles that do not have armor proficiencies like monk/barbarian.

Templar Stat Tweaks

---

code/modules/mob/living/carbon/rogfatstam.dm
code/modules/roguetown/roguejobs/alchemist/reagents.dm

Nutrition is a bit of a squandered gameplay mechanic in this codebase.
Not a whole lot of stuff interacts with it like you'd expect, so I've gone ahead and taken the liberty of putting in some very basic mechanical interactions that make hunger deplete slightly/significantly faster depending on your character's stats and level of physical activity.
To help explain this, max nutrition (full) is 1000 nutrition.
Anything that causes you to gain fatigue also causes you to lose nutrition/hunger. A 10 fatigue strike causes you to lose 10 nutrition, adjusted by the following values below:
- If you have any toxin damage above 20% of your max health, 10% of that damage is added on to the base nutrition you lose.
- If you have less than 30% fatigue remaining, the amount of nutrition consumed is …

Feast & Famine: Nutrition changes

---

code/datums/character_flaw/_character_flaw.dm

The 'greedy' flaw no longer gives you the 'skilled appraiser' trait. Instead, you get the normal 'appraiser' trait.
The 'greedy' flaw currently gives you skilled appraiser for free - which is a pretty rare trait that only a handful of jobs actually spawn with. (Steward, merchant, court mage, consort, and treasure hunter are the only non-antag jobs that normally get it.)
Flaws probably shouldn't give you rare skills for free - this swaps out the 'skilled appraiser' trait with the significantly more common 'appraiser' trait - which still lets you estimate item value - but with much less accuracy.

Greedy no longer gives skilled appraiser

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm

Gives the desert rider steel chain pants, rather than iron.
As demonstrated by the image below, with the new loadout for the Blade Dancer particularly, the shades of metal between the torso and legs on the Desert Rider was mismatched. And UGLY.
My poor screenshotting skills mean you may have to squint, but it's very visible in-game. Left is before, right is after.
Unplayable!!!!!!!!!

Fixes desert rider's pants (oops)

---

_maps/map_files/dun_manor/dun_manor.dmm
code/modules/clothing/rogueclothes/hats.dm
code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm

changes mage apprentice to have 3 slots, and edits the mage tower to have 4 rooms for apprentices
Also Gives Apprentices Random Wizard Hats :]
<image src=https://github.com/user-attachments/assets/57825350-8424-4057-a41b-c4daebbce891 width=600>
i regularly now see up to 4 players rolling for the two slots, making it questionably competitive to even play mage apprentice despite how relatively low stakes it is as a role. more people should be able to play it; it's a good role for new players.
i dont think this interrupts game balance that much, as mage apprentice is a relatively low stakes role.

LET ME PLAY MAGE APPRENTICE AGAIN

---

_maps/map_files/dun_manor/dun_manor.dmm

the bookshelves actually have density flags now so you can't walk through them
also these two windows had no floors underneath them, i fixed them
This PR makes meaningful improvements to the game’s environment by addressing both functional and aesthetic issues. The addition of density flags to bookshelves introduces a level of physical realism; bookshelves are now physical barriers that players cannot simply walk through. This aligns player movement with intuitive expectations, reinforcing the idea that objects in the game world have real mass and presence. As a result, the game environment becomes more engaging and consistent for players, deepening the sense of immersion.
In addition to the bookshelf density changes, this PR fixes an issue where two windows had no floors underneath them. …

library fixes

---

code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
code/modules/jobs/job_types/roguetown/nobility/captain.dm
code/modules/jobs/job_types/roguetown/nobility/hand.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm

This PR increases PQ requirements for man at arms, royal guard, guard captain, marshal, and the hand.
We've had an influx of new players as of late and this should help prevent those new players from immediately rushing into roles that are often required to interact with antagonists and call for a good understanding of escalation rules, in-roleplay criminal sentencing, and general conflict resolution. 
@Lutowski suggested a PQ minimum increase for royal guards in the comments of another PR, so I thought I'd go ahead and increase the minimum PQ values for RG and a few other guard/guard-adjacent roles while I was at it. 
Exact PQ minimum values can be adjusted as needed if this is maybe too much.

Bumps PQ requirements for a few guard/guard adjacent roles

---

code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/valuables.dm

The dragon ring recipe now requires a single blacksteel bar instead of 2 regular steel bars, as well as specifically a silver psycross as opposed to *any* psycross. No longer can you simply use wooden psycrosses for a dragon ring.
Due to the amount of dungeons here that spawn with random gems, gems are a lot easier to acquire here than on other RT servers. This means dragon rings are currently fairly easy to make and give you a ridiculously strong stat buff for how easy they are to acquire. 
This should make dragon rings still plausible to make in-round if you put a good deal of effort into acquiring one; but they should be a fair bit rarer and harder to acquire.

Changes dragon ring recipe

---

_maps/map_files/dun_manor/dun_manor.dmm
code/__DEFINES/roguetown.dm
code/game/objects/effects/landmarks.dm
code/modules/clothing/rogueclothes/gloves.dm
code/modules/jobs/job_types/roguetown/courtier/butler.dm
code/modules/jobs/job_types/roguetown/youngfolk/servant.dm
code/modules/jobs/jobs.dm

Unfortunately the DLC is smothered a bit by sprite works, but oh well.
This changes the Head Butler/Maid to the more gender neutral Seneschal! Which, by the end of this, very much does not seem like a word anymore! The Seneschal is the administrator and steward of a noble estate, overseeing everything. Another, if more 16th century, title for it is major-domo, but I hate that word. The Seneschal picks up classes, allowing them to look like an admittedly somewhat flabby noble administrator, or their head butler/maid trappings of the past. They also picked up a serfring along the way. As they are officially a leadership character of the ever popular newbie-bait servant role (and to a lesser extent all keep roles by adjacency) they get a RCP bonus as well as the usual fortune carrot. …

Sensual Seneschals; the servitude dlc

---

code/modules/mob/living/carbon/human/species_types/roguetown/roguetown_species.dm
modular_azurepeak/code/datums/autopunctuation.dm
roguetown.dme

Enforces periods at the end of sentences except where another marker (~ or + or -, etc) is present. Identical implementation to my work on other SS13 servers.
Also capitalizes lowercase i's in the middle of sentences.
Objective readability improvements, practically no performance hit.

Autopunctuation

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/blackoak.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm

This was originally suggested as a quality of life improvement for them, and the crafting recipe isn't _so_ bad that they can't manage it themselves. So, our elfy-polearm and pretzel mercenary friends both spawn with a strap, so they may carry freely. The other great weapon classes, like warrior MAA and knight, all have to source one themselves, still.
It removes a round chore from a pair who'd want to do it, and are already otherwise equipped.

Relevant mercenaries get a GW strap

---

code/modules/mob/living/carbon/human/inventory.dm
code/modules/mob/living/carbon/rogfatstam.dm
code/modules/roguetown/roguejobs/alchemist/reagents.dm

It appears my prior testing methodology of "spawn in as vagabond and whack five trees with a stone knife" is not an especially great thing for ballparking something that affects every corner of the game. Who would've thought?
Anyway, fatigue consumes nutrition, as before, with the following changes:
- Baseline nutrition consumption compared to the **forbidden rounds** has been reduced by 85%.
- Athletics skill now factors in quite significantly to nutrition loss.
- If your athletics skill plus 2 is greater than the amount **base** fatigue you lose in a single action, you have a 16% chance per athletics rank to just not consume any nutrition at all.
- Athletics skill now applies a 5% reduction per rank to all nutrition loss from physical actions.
- When running, you have a 5% chance per …

[TESTMERGE] Feast And Famine 2: PSYDON above those numbers were high

---

code/_onclick/click.dm
code/game/objects/items/rogueitems/natural/animals.dm
code/modules/mob/living/simple_animal/rogue/farm/goat.dm
code/modules/mob/living/simple_animal/simple_animal.dm
modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/goatherd.dm

Few changes:
- Saddles are now containers. Not especially big ones, but they are containers. You could totally wear one on your left back slot if you wanted to. Not sure why you'd want to, but you can!
- You can access a saddle's inventory by middle-clicking on a mob that has a saddle attached to it.
- If you're riding the mob at the time of doing this, it is three times faster to access.
- Goats are now saddleable and ridable, complete with sprites that they've always had but were never actually used for whatever reason.
- I've adjusted the south dir layering on goats to look far more realistic than it previously did.
- Goatherd vagabonds now spawn with a tame male goat so they can actually begin creating a herd of goats. You know, the thing that goatherds should be doing.
Maintainer …

Saddle Up: Working storage inside saddles & goat saddling (plus goatherd tweaks)

---

code/modules/projectiles/projectile/magic.dm

Throw speed 4 is the magic number for getting things stuck in people, it seems. This changes it to be 3 in catch mode, which is a bit slower but also safer.
As funny as mages embedding goblets into random body parts was, it was ultimately stopping people from using arguably one of the mage's coolest spells.

Fetch no longer embeds things in catch mode

---

code/modules/mob/living/grabbing.dm
code/modules/surgery/surgeries/prosthetic_replacement.dm

A copy of limb amputation surgery step that targets RT prosthetics to remove them without medical damage to the mob. The saw felt like the right tool for the job, and it does not collide with any other surgical steps. Just 1 step because non-organic limbs don't play nice with incision / clamping bleeders and so on.
Right now, people have to hit prosthetic limbs until they sever like a normal limb. Doing so triggers the normal limb severing damage, like profuse bleeding in the chest, which would not be the medically responsible method for removing a prosthetic from a stump. This gives a surgical step to remove (saw off) the base of the prosthetic, dropping the limb without damage to it or the patient.
https://github.com/user-attachments/assets/298d1a1b-c0a1-48a6-bb2c-192c2df1bb61

Adds a surgery to use a saw to remove a prosthetic limb

---

code/modules/roguetown/roguejobs/alchemist/reagents.dm

Feast & Famine added nutrition drain to red healing potions. After reviewing some feedback from the recent dev surveys and tracing back people with a negative opinion to mostly guard mains, I've identified that one of the biggest contributors is probably red elixir use.
This tones down dated red's nutrition drain from -5 to -2.5, and player-crafted red's nutrition drain from -2.5 to -0.5.
In practice, this should make red use a little less punishing than before, and player-crafted red's drain is almost negligible overall, which gives it a lot more value for those willing to spend the time to make it.

Reduce healing potion nutrition loss

---

code/datums/components/crafting/crafting.dm

Admins requesting fingerprints being added to items spawned by crafting code. Since there is no "forensic" link to things created, this may have caused some frustration in seeing who exactly constructed whatever. Now there is a link in forensics code.
Looks to work just fine on objs and turfs.
Helps admins figure out who made those 100 wooden [redacted].

Adds fingerprints of crafter to items/turfs created using crafting code

---

code/datums/components/crafting/crafting.dm

Here is a runtime that happens when you try to make water to wine with only a single bottle filled with water.
Some liquid reagent crafting recipes trigger a runtime, like water to wine. I guess because it consumes the container that the reagent is in, and then makes another loop trying to look inside the consumed bottle? I'm not sure. In testing this seems to fix it, though it might be a little redundant. 
Very obscure runtime fix. Feels like this fixes what is causing issue #736. Tested with this solution and didn't find the same issue (it consumed a bottle as expected).

Preventing a null reference lookup in crafting for liquid contents access

---

_maps/map_files/dun_manor/dun_manor.dmm

Various map fixes for the town.
-  Replaces a missing wall in the keep near the training yard.
- Fixes a missing floor tile in the bathhouse.
- Makes the bookshelves on the lower floor of the library opaque so that the sewer entrance isn't visible from inside. Not exactly very cozy with a rous staring you down through the sewer grates.
- Replaces all instances of **area/rogue/indoors** in town with **area/rogue/indoors/town**. This means the guard buff MAA get in town will actually apply in the entire town and won't randomly disappear when entering places like the tailor's shop, the library, and the artificer's building.
fixes good

Various town mapping fixes

---

code/__DEFINES/roguetown.dm
code/modules/jobs/job_types/roguetown/nobility/captain.dm

tors wanted the captain role to have the RG weapon selection. i said ya and then discovered a ui bug involving injecting a weapon selection menu into a class that doesn't have advclasses. thus, the captain now has advclasses too. they're basically the same but one lost a wrestling point to get a riding point and lost a riding point get a wrestling point. in other words this is a stealth buff to infantry captains that WILL destroy balance forever. oh yeah i kinda tidied the code a little too.
sabres are cringe idk

gives da captain two classes + weapon selection

---

code/modules/jobs/job_types/roguetown/church/druid.dm

Arranged starting gear more logically, starts with staff/whip and skills for them for forest wandering and self-defense, upped tracking. 
Not many classes utilize the whip, and a whip seems to fit the animalistic them of druids nicely. Allows them to defend against mob attacks without spamming kneestingers while roaming the lands and being wild-folks. A staff is added to help them parry and wonder the rough forests more fluidly. Tracking is an under-utilized skill that seems appropriate to emphasize for a forest-dwelling Druid that would know when the vegetation has been disturbed.
The pouch being on a belt slot is wasted space, as not many things can go in the neck spot, but many many things go in belt slots.
I'm considering giving them the bog-runner trait in addition to/instead of the …

Druid tweaks

---

code/modules/clothing/rogueclothes/hats.dm
code/modules/roguetown/roguecrafting/leather.dm

Allows you to craft volf helmets with 3 hide and 2 fur. Also changes the item's description to no longer mention volf helmets being associated with bandits.
These aren't actually very strong and don't offer much protection - but they're currently only available to bandits and serve as essentially a dead giveaway that someone is a bandit. Making these helmets craftable should help bandits be less immediately-recognizable and should hopefully make it just a little harder to metagame bandits.

Craftable volf helmets

---

code/modules/reagents/reagent_containers/glass.dm

> Can have so that you can FULLY empty a bucket in a barrel without having to always click on it?
Increases the pour / fill loop by 1 so that buckets can be entirely filled or entirely poured with one click.
Saves wear and tear on your mouse from needless clicking.

Increases pour / fill loop by 1 for the sake of buckets

---

code/_onclick/hud/ghost.dm
code/_onclick/hud/hud.dm
code/_onclick/hud/human.dm
code/_onclick/hud/screen_objects.dm
code/modules/client/preferences.dm
code/modules/client/verbs/ghost.dm
code/modules/mob/living/carbon/stress.dm
interface/interface.dm

* Grain filter is now a toggle under Options.
* Adds back respawn verb for when skull HUD breaks.
* Ready-ups are logged, credit to https://github.com/Darkrp-community/OpenKeep/pull/980. Would appreciate admins test this live because I've never been an admin and don't actually know where logs are kept.
grimshart is a choice

[TESTMERGE] Grain Toggle & Ready Logging

---

modular_hearthstone/code/modules/spells/roguetown/wizard.dm

i'm doing the equivalent of buying bubblegum (new spell!!!) with other embarrassing gas-station purchases (balance-jakking)
let's go over the boring stuff first.
--- **WARNING, BALANCE-JAKKING AHEAD**---
Big one: blade burst, lost 20 damage (negligible), more importantly, it now follows its spell description about having a delay before the swords cut you to bits. It's more than double what it is on live, from 7 to 18. I'm not **certain** on how this'll do with lag. But on live it's more or less impossible to react to blade bursts, and my attempt here is to make it hit you if you are 
a. slowed (foreshadowing)
b. not paying attention
c. got read like a book
If this doesn't make bladeburst not free damage on people at least it lost twenty of its damage. 
Other small stuff, Entangle: got …

magick-jakking. (+2!!! new spell)

---

code/modules/mob/living/carbon/life.dm

Ports https://github.com/Tree445/Hearthstone/pull/365 from Hearthstone.
You can now sleep comfortably so long as you are prone and on a tile with a bed; you no longer need to be buckled to the bed.
This allows multiple people to sleep in the same bed. Someone requested this in the suggestions channel on Discord and it seems fine.

Sleeping on beds no longer requires you to be buckled

---

code/modules/clothing/rogueclothes/quiver.dm

Before, intents would not correctly update on a player when a bolt/arrow is loaded into a quiver, leading to some annoying inconveniences for bow/crossbow enjoyers. This fixes that.
It's nice when quivers work exactly as you expect them to!

Fixes intents not updating when putting a bolt/arrow into a quiver

---

_maps/map_files/dun_manor/dun_manor.dmm

This makes the underground arena more spacious and roomy, and adds a small room to tend to wounded combatants.
During highpop, tournaments hosted in this arena get downright claustrophobic. Spectators barely have any wiggle room to move about, and it leads to a look of awkwardly standing around each other, occasionally breaking the flow of tournaments. Furthermore, people always opt to build a space to tend to wounded fighters in her. This provides a more isolated and dedicated space for the wounded to be treated that also keeps them away from where the crowds are more likely to be, making it a bit easier for healers to tend to them in peace.

Expands the underground arena

---

code/datums/status_effects/rogue/roguebuff.dm
code/modules/mob/living/carbon/life.dm
code/modules/spells/roguetown/acolyte/general.dm
code/modules/spells/roguetown/acolyte/noc.dm
code/modules/spells/roguetown/necromancer.dm

* Lowers Blindness spell effect from 6 to 5 seconds.
* Lowers cooldown to Raise Lesser Undead from 60 to 30 seconds.
* Fixes a runtime associated with Miracle healing.
* Fixes a runtime associated with buckle sleeping.
Big thanks to @noelle-lavenza for assistance with runtime fixes.
Undead are too easy to kill to be worth the cooldown.
Blindness is a bit too good in PVP. Will try five seconds but never lower than four, otherwise there's no point buffing it in the first place.

Spells N' Runtimes

---

_maps/map_files/dun_manor/dun_manor.dmm

Adds a set of six spoons, six forks, and a few extra platters and bowls to the keep's kitchens.
It's kind of absurd for there to be plates and bowls in the manor but not so much as a single spoon or fork in the entire keep, especially now that silverware is a physiological need for nobles. Also, not only should servants not be expected to make cruddy wooden forks and knives for the richest people in Azure Peak, but if they can afford to have three separate private baths, they can probably afford to come pre-stocked with metal silverware.

Adds silverware to the keep

---

code/modules/mob/living/carbon/human/npc/searaider.dm

Adds an admin-spawn-only subtype of sea raider that doesn't say any of its voice lines OR point at people.
Great for graggarite-heavy events where the chat (and server) isn't spammed with ungodly amounts of graggarite screaming! Probably great for server performance, too!
... They do still do the *rage emote because I think they should at least still do that.

Makes a silent type of sea raider that doesn't spam chat logs (as much)

---

code/game/objects/items/rogueweapons/melee/knives.dm
code/modules/roguetown/roguecrafting/items.dm

removes the cog requirement from prosthetic arm recipes because it doesn't make sense. also changes their skill to basic crafting because you don't need an engineer to whittle a bad prosthetic. reflavors the combat knife to a seax because the sprite pretty much fits and that name kind of annoyed me. reflavors the nite elf dagger to a dark elf dagger.
if you have cogs and an artificer you aren't going to make wood arms, you're going to make bronze ones. this allows wood arms, which suck, to serve as an ersatz solution for when you don't have an arty to make the good stuff. the knife changes are just because seeing the name 'combat knife' makes me think of some ww1 shit at the absolute earliest, so now it's medieval. and. what yon fucke are nite elves?

wood armz r cheaper, reflavors a couple knives

---

code/modules/mob/living/carbon/human/npc/searaider.dm

gives viking npcs armor proficiency trait so that they can actually wear the chainmail they spawn with without getting pwned
bugfix

gives viking npcs armor trait

---

code/modules/jobs/job_types/roguetown/youngfolk/prince.dm

Adds a new subclass to heir called "Introverted Bookworm" (keeping along with the theme of subclass names for heirs being incredibly insulting)
Essentially a nerfed version of mage apprentice with one less starting point to play with, no free starting gem, reduced strength and constitution and no free lightning bolt.
Starts with spectacles because they're a nerd.
It's fun. It's not particularly strong, it's not gonna kill game balance. Prince subclass options are already a little sad at the moment and there are more than a few regular princess players that would LOVE to play a subclass like this.
If anyone thinks this is somehow too crazy I will nerf as many more stats as needed.

Adds a new subclass, "Introverted Bookworm" to heir. 

---

_maps/map_files/dun_manor/dun_manor.dmm
code/modules/clothing/rogueclothes/hats.dm

At present, the Inquisition Templars have the choice of both an armet and the Psydonian barbute. Both are heavy helms with a 90 degree cone of FOV. However, this pretty severely limits visibility for a role that starts with some pretty weak armour and a shield- and visibility is necessary to use that shield to any decent effect.
After discussing with Ambrose and Onut, we agreed on the change of the barbute to have a 180 cone of vision, whilst losing its status as a heavy helm in recompense. This removes some of the crit protection of the helm. This also makes more sense given the larger viewslits shown on the sprite of the barbute, and offers the Otavan templars an option between less visibility for the more armoured warrior, and more visibility for those more light on their feet and …

Alters Psydon barbute FOV

---

code/modules/mob/living/living.dm

There was a bug where forcefully removing FOV restricting helmets would cause the victim to be "stuck" with that fov restriction until a helmet was put back on / taken back off. This calls update on all removals, so it fixes that and any other removal-fov issues.
Just a one liner bug fix.

Bug Fix for removing helmets causing stuck FOV

---

code/modules/roguetown/roguemachine/titan.dm

This should prevent people from summoning the crown while it's being worn and creating that buggy double crown. 
Keyword: "Should"
Probably better to have people actually able to wear the crown rather than being forced to hold it in their hands to prevent summoning

Fixes Crown being summonable off of a head (maybe)

---

code/datums/mind.dm
code/modules/mob/living/carbon/human/examine.dm

This adds a feature where, in the "People I Know" menu, Ascendant worshippers can see an indicator of fellow Ascendant worshippers, denoted by a bright yellow unicode symbol that depends on which ascendant they worship.
People who do not follow the same Ascendant patron cannot see this.
This will make it much easier for fellow heretics to organize themselves and plan Big Schemes!

Adds indicators for fellow ascendant worshippers in "people I know" menu

---

code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/aasimar.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halforc.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm

allows non-furry races play with some markings. (tiger stripes, sock hands, and belly marks.) I use them often to add scars and skin texture to characters. It's applied to everyone but dwarfs/goblins bc I have no idea how to make those play nice with the smaller folk.

gives humanoid races tiger strips/belly marks

---

code/datums/mind.dm

See title.
Skills that are able to be ranked up in the skill menu will now have a simple indicator next to them in the character skills list.
One rank up being available is denoted by a **`(!)`**, Two rank ups are indicated with a **`(!!)`**
A nice QoL feature that makes it more obvious when we can rank up a skill. Now for example squires will no longer have to guess if they actually learned something from a sparring session after the rank up message is immediately drowned by combat messages!

Adds "rank up available" indicator in skills list printout

---

code/modules/roguetown/roguejobs/blacksmith/tools.dm
code/modules/roguetown/roguejobs/engineer/prostheticarm.dm

Adds an overload of the normal hammer/anvil item repair to handle prosthetics, fixing their damage and wound conditions. Carpentry for wooden, engineering for bronze. The artificer can do both handily. Also lets you put the bronze limbs in the smelter for a return of 1 bronze bar.
The only other way to repair prosthetic limbs was a weird interaction with surgery "tend damage" code, which can probably be hunted down after this.

Prosthetics, anvil repair and smelting to bars

---

_maps/templates/sewers.dm
code/game/objects/effects/spawners/roguemapgen.dm

well, alright then!
this pr severely nerfs the sewer loot spawners because we've all been acting out of pocket about them. specifically, it:
- drops the loot count to 3 items from the list instead of 5
- (basically) doubles the probability of the sewer spawners dropping random trash or utility items over gear and money
- removes piles of silver and gold coins from the spawner entirely. single coins of each can still spawn
- creates a parent object of /obj/effect/spawner/lootdrop/roguetown and sets fan_out_items to TRUE so that loot will be in slightly less neat little piles across the board, not just for sewer spawners
everyone in the damn town running down there to find piles of coin and grab a bunch of steel daggers to throw at the smith is getting a little silly. i'll cook something …

fuck sewers

---

code/modules/mob/living/ambush.dm

See title.
The % chance of a player being ambushed has been raised from 5% to 10%.
The GLOBAL cooldown for ambushes has been reduced from 5 minutes to 3 minutes.
These variables have also been made into global variables which admins can freely change as they wish, (`ambush_chance_pct`, `ambush_global_cooldown`, and `ambush_mobconsider_cooldown`)
Let's be honest, the bogs and forests aren't dangerous enough, nor are their dangers able to persist in any meaningful capacity. That latter part is something I really believe needs fixing. I've talked about this in the discord already, but soon I'd like to implement a mechanic that procedurally spawns more hostile mobs in key locations in the bogs/coasts as a round goes on.
But, until I get to that, I think this is a good first step. As it …

Raises ambush chance + reduces cooldown, makes ambush variables admin configurable

---

code/game/objects/structures/mineral_doors.dm

Adds a check to mineral door bump to see if you're carrying a keychain. Automatically try the door with the keychain in your hand. If it works, it keeps you in memory as the last bumper, and if you are next to the door when it closes, it auto-tries to lock with the keys in your active hand.
I think this doesn't runtime viciously in a play environment on account of simplemobs with nohands bumping doors. Tested with 10 volfs in a closet, bumped the door with no issues.
Quality of life, helps with the inventory juggling of opening a door with a keychain in hand. You could already kick the door open/shut, so, this brings down the tech floor.
https://github.com/user-attachments/assets/d53a7691-a62a-4da6-9bc6-b1805f945257

Auto unlock and lock for bumping into doors with keys in active hand

---

code/game/objects/items/rogueitems/bait.dm

See title. This is uh, all it does really.
So, apparently using baits probably takes as long as it does because in OG roguecode there was a planned hunting skill that never saw the light of day that presumably would influence the speed of deploying/retrieving bait. This skill was never really implemented, so all we have are very inconveniently lengthy bait usage times. This long usage time doesn't really add anything to the gameplay experience at all and really shouldn't be as long as it is anyway, so let's just speed it up.

speeds up bait deploying time to 2 seconds

---

modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Gives both gravity and snapfreeze anti-magic checks. 
these uhhhhhhhhhh don't work? but neither do the ones on the og spells (entangle)  
I think it's a larger problem with antimagic in total. It's a little beyond my scope. But assuming it does get fixed (talking to people smarter than me), this pr will nullify these spells if that happens.

fixes? gravity and snapfreeze

---

code/game/objects/items/rogueitems/natural.dm
code/game/objects/items/rogueitems/natural/clothfibersthorn.dm
code/modules/clothing/rogueclothes/quiver.dm

Also minor proofread on quiver messages
You know how you can quickly refill a quiver with all arrows on a turf by clicking on a turf with the quiver?
This change lets you do that with ALL item bundles!!!
All you need to do is take an item bundle and click on a turf with it, and if the turf has and items that go into the bundle, your character will quickly gather them all up!
Also allows players to cut stakes from bundles of sticks. Because that's nice to have for people making lots of palisades!
It's a nice QoL feature that will hopefully streamline the process of gathering items into a bundle.

QoL: Lets players quick-fill item bundles by using them on a turf

---

code/__DEFINES/traits.dm
code/datums/status_effects/rogue/roguebuff.dm
code/game/area/roguetownareas.dm
code/modules/jobs/job_types/roguetown/garrison/bogguard.dm

Adds a Warden unique garrison trait, much like GUARDSMAN or KNIGHTSMAN - Called WOODSMAN. Woodsman grants +1 spd, +3 per, and longstrider while in relevant outdoors areas(the grove and coast)
Additionally buffs Warden's skills to better allow them to utilize their environment to their advantage, as they lack in traditional combat strength of MAA/RG. Settling their 'style' of being around wood ambushes and using their environment is probably the best way to give them an actual identity mechanically.
Athletics -> 4
Climbing ->4
Swimming ->4(Hasselhof Aho!)
Sneaking ->4
New Woodsman Trait(Longstrider in relevant areas, +3 per, +1 spd)
Warden is currently mechanically worse at actually engaging in the Wilds than the other garrison members. Despite being literally meant for it. Also area buffs …

Wardentime

---

code/modules/clothing/rogueclothes/hats.dm
modular_azurepeak/code/modules/clothing/rogueclothes/hats.dm

All helmets that would give you 90 vision now have 180, save for the froggemund.
Integrity adjustments:
Pigface: 200 -> 300
Knight: 400 -> 300
Froggemund: 400 -> 450
Heavy helmet default is 400.
You know why the 90° vision is fucking bullshit??? Because you can't parry or dodge attacks unless you FULLY SEE the target.
Nope. Can't parry that. He doesn't exist.
This is why templars get sodomised by werewolves so often. Unless they swap out their epic cool patron helmet with a meta sallet or something.
And it's super annoying that you can't even see people you're speaking to unless they're directly in front of you.

Helmet FOV Adjustements

---

code/game/objects/items/rogueweapons/melee/polearms.dm

Naledi warstaves, despitely looking so poggy, were entirely identical to wooden staves. I've increased their damage and integrity to rectify this.

Buffs Naledi Warstaff

---

code/game/objects/items/rogueweapons/melee/axes.dm
code/game/objects/items/rogueweapons/melee/blunt.dm
code/game/objects/items/rogueweapons/melee/knives.dm
code/game/objects/items/rogueweapons/melee/polearms.dm
code/game/objects/items/rogueweapons/melee/swords.dm

this pr broadens the spread of weapons that receive a weaker blunt intent for less lethal takedowns, similar to the bastard's sword pommel strike. specifically, it:
- creates a new intent for combat oriented daggers called sucker punch. sucker punches are quite weak, but bypass blocks and dodges. in return they have a length recovery and clickcd, making them unspammable and risky.
- adds the pommel strike to the base sword, meaning most swords now have a blunt strike option. exceptions are one handed swords, like shortswords and rapiers, which wouldn't be used for pommel striking anyway.
- adds a bash intent for axes, to simulate hitting someone with the broad end like a hammer. functionally similar to the pommel strike from swords.
- reorganizes a bunch of .dms so that intent datums come …

ensures proper use of force compliance by generalizing some bash intents

---

_maps/map_files/dun_manor/dun_manor.dmm
code/modules/farming/produce.dm
code/modules/roguetown/mapgen/forest.dm
code/modules/roguetown/mapgen/rogueoutdoors.dm
modular_azurepeak/code/game/objects/items/quicksilver.dm

Adds a letter for how to make the quicksilver poultice to the Inquisition's bunker table. Gives them a single fyritius for expediency, and bumps up wild fyritius bushes to 3 in the grove + 3 in the basin (was 1 and 1 before). Fixed the on-click overwrite so that you can feed the flowers to victims again, easy fire stacks.
This puts the spawn-in poultice "in reach" if there's any orthodoxists / no inquisitor (often the case), so that they can hand it off if necessary. It would be just 1 use with no Inquisitor, so maybe not too overpowered, plus the orthodoxists can't make use of it themselves. Also preempts the urge to break deep into the Inquisitor's office for the stuff if someone was fiending for it. Now it's just two doors in.

Quicksilver poultice modify, adding more fyritius to mapgen

---

code/modules/client/customizer/customizers/organ/ears.dm
code/modules/client/customizer/customizers/organ/frills.dm
code/modules/client/customizer/customizers/organ/horns.dm
code/modules/mob/living/carbon/human/species_types/furry/dracon.dm
code/modules/mob/living/carbon/human/species_types/furry/lizardfolk.dm
code/modules/mob/living/carbon/human/species_types/furry/tabaxi.dm
code/modules/mob/living/carbon/human/species_types/furry/vulpkanin.dm

Lets Tabaxi and Vulpkanin use wild-kin neckfluff. Also gives Sisseans and Drakians a "Hood" selection which just contains the two cobra hood sprites. Also ALSO makes frills optional for Sisseans, Drakians, and Kobolds, while also making horns optional for the latter.
Customization good. Fluffy cats and foxes are cool. Snakes are cool.

Tiny customization additions (fluff, cobra hoods, removable frills/horns)

---

code/modules/roguetown/roguestock/stockpile.dm

Takes rocks from the stockpile at the request of Luto. All hail Luto.
Takes rocks out of the stockpile entirely.
No more will alchemists be able to buy stones, turn them to gold, and sell them for exhorbitant prices. The funny mammon number need not go up for fun to be had.

stockpile changes - TURN ON THE ORB, ANY CHANNEL, THEY TOOK THE ROCKS!

---

code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/client/preferences_toggles.dm
code/modules/mob/living/carbon/human/examine.dm

adds a preferences toggle to make it so people can "look closer" when examining you even if you're masked.
it starts off by default

Adds Toggle To Make "Look Closer" Viewable When Masked

---

_maps/map_files/dun_manor/dun_manor.dmm

Adds a trap door to the throne room. Remaps the keep basement so that the trap door sits directly above a small cell underneath the keep. There's a lever beside the throne that opens the trap door and dumps anyone standing on it into the cell below.
https://github.com/user-attachments/assets/e24866ff-8435-4488-89e2-0c309c5cbafd
<details>
<summary> SDMM Screenshot: </summary>
</details>
its funny and gives the crown an easy but ultimately pretty inconsequential way to punish peasants who speak out of line in the throne room
there's no wolves down there or anything, its just a little cell you can dump people in for comedic effect

gives the keep a trap door again

---

_maps/map_files/dun_manor/dun_manor.dmm

Moves the zizo church in the sewers to a more discreet location outside of the town and expands it a bit.
https://github.com/user-attachments/assets/038e0735-06f4-4baf-b266-e9914deec3bc
Screenshots below.
<details> 
</details>
Having a chapel dedicated to zizo directly below the church of the ten was kinda weird. This moves it somewhere a bit more hidden and further away from the actual church; while also making it a bit larger to accommodate for people actually gathering/roleplaying inside it.
It's still in the same zone as the town; just a bit further away and outside of the town itself. The idea here's just to have a cool little roleplay space for heretics to gather and potentially get up to shenanigans.

Moves & expands zhurch

---

code/modules/mob/living/carbon/human/human_helpers.dm
code/modules/mob/living/carbon/human/npc/skeleton.dm

There is a bug where lich-spawned greater skeletons sound as "Skeleton" even with their face covered since they do not init with a voice type, so there is no substitution. This slaps a voice type in their init so they spin up with one. Also puts a special case in for skeleton type mobs to prevent constant reversions of `name` to "Unknown" each check.
Prevents meta of hearing a face-covered Skeleton's speech revealing their true nature.

Defines lich spawned skeleton voicetype so masks properly obfuscate

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/forlorn.dm

Removes the cap on Forlorn Mercs so people don't get japed while joining. I think I just left it in on mistake while porting.
no other merc has a cap ;3e

Removes the Random Forlorn Cap

---

code/modules/spells/roguetown/acolyte/general.dm

> Zizo miracles are currently bugged and thus are not receiving the conditional bonus right now.
> Zizo miracles are meant to receive a conditional bonus based on the number of bones you have nearby, but are currently searching for obj/item/stack/sheet/bone/O, however, the variable name for a bone stack is /obj/item/natural/bundle/bone
Throwing Zizo clerics a bone (bugfix)

Fixes typepath to bone for zizo situational bonus miracle healing

---

code/modules/antagonists/roguetown/villain/bandit.dm

They just don't have to. I one line deleted it.
There's no reason they should be obligated to be. There's more reasons than 'I worship matthios' that someone might be a bandit. They're, regardless, more than likely a member of the freefolk and players should be able to think of reasons why they might be there.
I've seen people want to play otherwise criminal characters as bandits and be unable to do so because of the forced worship, when they'd genuinely prefer to be. There are graggarites who want to be- I saw someone play a zizite wizard as bandit but have to just kinda half-ass the whole matthios part. I saw a couple genuine psydonite bandits.

Bandits no longer have to be matthios worshippers

---

code/__DEFINES/colors.dm
code/__HELPERS/lordcolor.dm

Adjusts the hexcodes of the heraldry colors, as well as those in the colors.dm of roguetown, to fit better visually.
<details>
Old ones:
New ones:
</details>
No more piss-yellow carpets in the Keep.
Plus they're better on the eyes.

Adjustment | Heraldry Colors

---

_maps/map_files/dun_manor/dun_manor.dmm

Removes the manor trapdoor.
Trap door was removed because it explicitly ended RP in an extremely shitty-to-be-on-the-receiving-end-of-manner. Lord already has the scepter to punish people. No need for another. Ratwood/Roguetown-ism 'oops too bad so sad sucks to be you!' garbage. Lowkey the goofiest shit in the world. This isn't looneytoons. If a peasant is disrespecting you, order them beaten. Or use your silencing, insta-stun infini-shock scepter. Who knows- you might even get roleplay out of it. And if you want to end the roleplay? Point at guard. 'Out of my sight with this peasant'. Boom.

Removes the trapdoor in the keep (again)

---

code/datums/sexcon/sex_actions/sex/vaginal_ride_sex.dm

This pr fixes the pronoun of the instigator being used instead of the targets for a sentence when you use a certain mechanic in Azure.
Uses now target.p_them() during that action, instead of user.p_them().
Don't look inside files changed unless you want to see the **evil** code.
I hate bugs enough that it nagged me into doing this.

Fix | Wrong pronouns during /mechanics/

---

code/datums/gods/patrons/divine_pantheon.dm
code/datums/status_effects/neutral.dm
code/modules/spells/roguetown/acolyte/xylix.dm

Gives the Vicious Mockery miracle to Xylix acolytes at t2 devotion
Creates, and adds a new miracle for Xylix acolytes, "The Wheel"
Changes the targets fortune for 5 minutes by a random value between -5 and 5. Requires a 3 second charge up, with a five minute cooldown
Gives Xylix Acolytes actual miracles, instead of only having the default miracles

Xylix Patron Miracles

---

code/__HELPERS/cmp.dm
code/game/atoms.dm

Somewhat of an edge case.
When you have two or more filters applied to a character, it would case a runtime error because the function in atoms wanted it to be sorted to determine which would show first. 
The comparator used was default which would be fine in most cases. However, in the case of filters, it was passed two lists which the default comparator could not accurately compare.
Added a comparator to check the 'priority' key of those lists.
Less runtime errors, no issues on my end.

bugfix update_filter runtime 

---

_maps/map_files/dun_manor/dun_manor.dmm

Lets you lock pillories with a town watch key. They didn't have their lockids set before.
We love locking pillories!!

Fixes pillory locks

---

code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm

if you have the naledi-born halfelf identity, you get their language! thanks to my bestie paxilmaniac for helping me learn code for this <3
half-elves of naledi heritage are able to speak their language, which is nice flavor. 
^ non-naledi born
^ naledi born

naledi-born language addition

---

code/modules/jobs/job_types/roguetown/courtier/magician.dm
code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm

Hiiii baby's first PR and it's just a small change. Please Go Easy On Me.
**Changes:**
Zizo-aligned court mages have both the cultist combat music AND Zurch key, for when they wish to bring their (hopefully Z-aligned) apprentices to a field trip
Zizo-aligned mage apprentices DO NOT have the key, but at least have the cultist music. 
Edit: Had to add a + BC Zizo mages lacked the potions and instead had a key. NOW that isn't the case.
Tested both as well and non-Zizo aligned folk don't have the music, nor the key for the court mage. Ten users aren't allowed, ever.
It'd make things a little interesting for those wishing to come together and do some heretical things in the Zurch, which is seldom-visited to begin with in my time playing a Zizoid adventurer mage. Having the court mage be able …

ZIZO BLAST!! Gives ZIZOID court mage a Zurch key for EVIL field trips (With Music)

---

code/modules/clothing/rogueclothes/armor.dm

Someone set the Blacksteel Fullplate to have the same durability of the Blacksteel Cuirass, which makes no sense. Fixed it though.
400 >> 600 durability now. 100 more than Full Plate, as is customary for the other Blacksteel armour pieces.
Because I'm fixing a coding oversight, and I wont see people walking about in full Blacksteel except for the actual armour slot.

Makes Blacksteel Fullplate actually better than regular fullplate

---

code/game/objects/items/rogueweapons/melee/polearms.dm
code/modules/clothing/rogueclothes/hats.dm

Small oversight on the helmets.
Add QoL buffs to the bardiche, makes it a weapon people actually can use now.
updates it to be in line with all the other helmets of its class, removing the cone FOV.
Gives bardiche their own cutting intent for adjusting, now instead of the bardiche having an abysmal 1 second delay for a cutting atack, the weapon works like any other polearm, with a charge one.
buffed its 0.9x damage modifier to 1.0x (making it slightly better than the halberd cutting attack), its still worse off than every other cutting attack (1.1x damage) but should do its job due to the reach advantage.

Quick QoL fix for otavan helmets, changes bardiche to not be dogwater

---

code/modules/jobs/job_types/roguetown/nobility/knight.dm

Gives tracking to RGs.
- They're the Keeprats
- Keep has a lot of trackable tiles
- People like to trespass the Keep / break into the Vault
- The main Keep Guards are unable to track / identify anything about said break-ins
- This fixes that.
It's pretty inconsequential, I waaaanna say, but obviously I'm not confident in these things. It just felt odd when I was made aware of a break-in / garrison trespass, but had no means of tracking it down in any way. If an RG shouldn't, who should?

Gives tracking to Royal Guards

---

code/__DEFINES/traits.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm
code/modules/mob/living/roguetownprocs.dm

Adds a new trait to Royal Guard that allows them to train others to match their own skill level.
Currently squires can get better results training with the Guard Captain than they can with Royal Guards, which discourages squires from actually learning from and training with the role that is meant to be training them.
This PR makes Royal Guards able to train the squires equally well as the Captain can, without also increasing Royal Guard's weaponskill to Master. Which would be a little much.
PR that affects squires so it's the most controversial thing in existence. Yay.

Adds new trait that allows a character to train others to match their own skill level. Adds that trait to Royal Guard.

---

_maps/map_files/dun_manor/azure_forest.dmm
_maps/map_files/rockhill/rockhill.dmm
code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
code/modules/mob/living/carbon/life.dm

Alters soap use and fixes bathwater moodlet
Allows all variants of soap to be used for bathing and alters the 'Relaxing' moodlet to not require you to lay down and subsequently drown in the bathwater. 
Gives most soap a use beyond being a worse rag and gives a general bonus to being in the bathhouse.

Hot Water and Suds

---

code/modules/spells/roguetown/acolyte/pestra.dm

Puts a switch chain in the Pestra diagnosis / secular diagnosis to tell toxins in a body.
Deobfuscates toxin damage in patients, in a way that would be suitable for learned physicians to recognize. This doesn't show up on the heart-click self-inspect, only on the run of the miracle.

Adding toxins report to diagnosis miracles

---

code/modules/clothing/rogueclothes/cloaks.dm
modular/code/modules/living/emote.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/issues/1043
The icon is still missing but the spell now correctly assigns a buff after casting. (need to channel then target someone)
Dragonscale necklace buffs could be stacked by wearing one in the neck slot and holding one. Code now checks the slot before assigning buff
They are bugs

Bugfixes: guidance spell, double dragonscale necklaces, subtle emote for revived

---

code/_onclick/drag_drop.dm
code/modules/spells/roguetown/_roguetown.dm

I have no idea how tracking mouse clicks works here or how the spell system works.
The original issue is that you can, via repeated clicks, bypass into: /obj/effect/proc_holder/spell/invoked/InterceptClickOn by attempting to cast repeatedly. Once it's there, neither of the conditional checking functions in:
can_cast
cast_check
check for how long the spell is casting nor whether the spell is set to not be released early so the spell simply insta casts, This fixes it with some caveats.
Firstly, the spell icons have a chance to be set to be on cooldown if you cancel your cast after starting it. I suspect there's a flag in a function I'm missing
Somehow the 'doneset' variable accurately tracks the min-cast time of the spell that's being cast and when it's up, the spells is fully charged and …

Silent casting fix

---

code/modules/jobs/job_types/roguetown/garrison/bogguard.dm

Did you know that Wardens have been meaning to spawn with a spear since their creation? Yet, through an oversight, their spear was set to the back slot. As spears cannot spawn in the back slot... well, Wardens don't get their spear. 
They don't have a great weapon strap, so they'll have to craft one to holster it, or just carry it around like a proper bog guard wannabe. If people want, I can give them a spawning strap, it's one line change, I just wasn't sure if I should or not.
Spears cannot spawn in the back slot.

The Great Peasant Militia Era Arrives (Warden Spear Bugfixing)

---

code/game/objects/items/rogueitems/natural/feather.dm
code/game/objects/items/rogueweapons/ranged/bows.dm
code/game/objects/items/rogueweapons/ranged/crossbows.dm
code/game/objects/items/rogueweapons/rogueweapon.dm
code/modules/clothing/clothing.dm

you can now rename anything childed to rogueweapon by using a feather on it. yay!
its cool :3c

allows renaming of everything childed to obj/item/rogueweapon, crossbows and bows, and all clothing and armor items

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/vaquero.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/witchhunter.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm

So I'll preface by saying:
I play Adventurer! Often, dare I say. I got about 4 characters dedicated to Adventuring. Another 2-3 whom go Adventurer when I dont do their town job.
So I do think I'm not wrong when I say _**it's a bit weird when the most played combat-related adventurer roles have Expert weapon skills**_, which just... makes other roles redundant?
Mercenaries exist as "better adventurers" but-- not really???
Have you SEEN Rogue Assassin?
So! I've nerfed some of them. Namely **every Rogue subclass** as well as Vaquero (just 1 skill) and Witch Hunter (1 skill too). This includes both combat skills and some utility skills for the classes MEANT to be more combat focused, allegedly.
_This should be "Rogue Expert Skill Nerf", really._
I also took away the elven dagger from Assassin …

Adventurer Classes Expert Skill Nerf

---

code/modules/spells/roguetown/acolyte/xylix.dm

Makes it so that the wheel (the one xylix miracle we have right now) doesn't require an amulet to cast.
Xylix doesn't have an amulet for his worshippers, meaning that anyone who spawns as a Xylix miracle-caster will not have the option to actually.. well, cast the miracle. They have to go find a psicross (is it psycross like psydon or psicross? who knows) or the amulet of another god in order to cast their one miracle. While, yeah, we could add a xylix amulet or just give them a generic psycross, that feels against the spirit of it. Xylix worshippers tend not to advertise their status. I don't think this'll really break balance, since the wheel is particularly mediocre.
Unrelated, while making this PR, I found that "what miracles need an amulet" is incredibly inconsistent. Noc miracles …

Powercreeps Xylix Miracles Greatly (not really)

---

code/game/objects/items/rogueweapons/intents.dm
code/game/objects/items/rogueweapons/melee/axes.dm

something something first commit
Warden's axe and pickaxes never actually had any AP innately due to the datum/intent pick never having it in the first place. I THINK this should be right, let me know if 60 is too high. This should affect only pickaxes, pulowski axes, and the warden's axes? (other pick types use either icepick or warhammer pick)
as above 
quite literally just adds ap to the pick intent datum (i hope i did that right?)
Why It's Good For The Game
Gives the pulowski and warden's axes actual pen on their pick intents, and some to picks. If that's too powerful on pickaxes then it can probably be slapped down?? stuff like the warhammer already has something like it, but this has no chargeup.

finally giving regular pick intent AP 

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
code/modules/language/roguetown/grenzelhoftian.dm
code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
code/modules/surgery/organs/tongue.dm
roguetown.dme

As stated in the title, adds the GRENZELHOFTIAN language (truly the best language).
Steals the visuals of the Lupian language, I did this because according to the Lupian language the two are meant to be similar. (and not because I'm lazy I swear)
Currently, Humans/Half-kins with the Grenzelhoft ancestry, archivists, and Grenzelhoftian Mercs spawn with this language.

The wurst update ever: Adds the Grenzelhoftian language

---

code/modules/jobs/job_types/roguetown/nobility/knight.dm

Adds a new subclass to Royal Guard that notably does not have plate training, starts with medium armor and can optionally use light armor to make use of dodge expert. Skills and stats modified to ones that seemed appropriate.
Irregular squire, a dodge-expert class. Does not have a corresponding dodge-expert Royal Guard that players can promote to without a drastic change in both their character and their playstyle. This discourages players from ever promoting their squire, which is generally something we want to avoid. The other two squires: Footman and Lancer. Both already have counterparts in Footknight and Mounted Knight. This adds a similar counterpart for Irregular squire.

Adds the "Royal Champion" subclass to Royal Guard.

---

code/game/objects/items/rogueweapons/rogueweapon.dm

Fixes weapons not being able to be hit with a hammer due to obj_flags overwrite from the weapon naming PR.
You gotta fix your weapons

Fix for hammer repair for rogueweapons

---

code/modules/jobs/job_types/roguetown/youngfolk/squire.dm

Gives squires jupons with the lord's colors on spawn. They're a part of the duke's garrison, after all - even if they're still in training!
MAA/RG both spawn with tabards/jupons with the duke's colors on them - this gives squires jupons as well - as they're also technically a part of the garrison. Also means squires no longer have their genitalia hanging out on the character setup screen.

Gives squires jupons

---

_maps/map_files/dun_manor/azure_forest.dmm
_maps/map_files/rockhill/rockhill.dmm
code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
code/modules/mob/living/carbon/life.dm

Reverts GeneralPantsuIsBadAtCoding/Azure-Peak#1039 because it broke soap cleaning.

Revert "Hot Water and Suds"

---

code/__DEFINES/jobs.dm
code/modules/jobs/job_types/roguetown/adventurer/types/special/courtagent.dm
code/modules/jobs/jobs.dm

By partial request:
It is no longer roundstart only.
Consequently, it means you can tell when there are (or aren't) any court agents in a round.
Any latejoin court agents will also not have their names beamed to the mind of the Hand, unfortunately.
Not everyone gets to roll the dice and be available on a specific time every three hours.

Adds Court Agent latejoin

---

code/modules/jobs/job_types/roguetown/garrison/veteran.dm

Gives each Veteran Subclass their own unique niche in terms of training skills! 
Takes care of a few bugfixes and code oversights for the Veteran role:
- Veterans now have the Steelhearted Trait (they're hardened from decades of battle)
- Veteran Subclass clothes actually spawn in now (no more spawning in with a chainmail set and plated boots as Scout/Spy Vet.
Also Reworks the Five Subclass offshoots for Veteran:
- Tarnished Knight has actual knightly armor now! They get half-plate armor and a fancy knight's helmet, as well as a bastard sword instead of a regular one. Also, noble combat music!
- Footman Vet gets a visored sallet instead of a regular sallet. 
- Battlemaster Vet gets a /small/ 1-point boost to Endurance if they're old to offset the age issue. Also, new fancy music!
- Former …

SENIOR BENEFITS - Veteran Subclass Reworks and Fixes (NOT A BALANCEJAK)

---

code/modules/mob/living/roguetownprocs.dm

Dodges themselves were unaffected by the "feinted" status effect. Making the earlier PR mostly redundant.
Fixes thing that not work as intended.

Fix for the "Feinting Speedsters" PR

---

code/game/objects/effects/landmarks.dm
code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm

Magicians Associates should now spawn in the correct places round-start, and no longer in random places like the inn's bed chambers, or the VAMPIRE LORDS MANSION. The Landmark name needed to be changed. Presti has also been re-added. Don't code at 3 in the morning y'all.
Known bugs, round start mage associates still spawn with two staves for some reason and I cannot figure out why.
Fixes bugs (funny bugs, but still bugs)

Magicians Associates are no longer on a sabbatical (FIXES THEIR SPAWN LOCATION)

---

code/modules/roguetown/roguemachine/steward.dm

Nerve master machine didn't interact politely with the master key or keyrings. This lets those things lock and unlock it.
Keyrings are cool

fixes nervemaster interaction with keyrings and master key

---

_maps/map_files/dun_manor/dun_manor.dmm

This is a tiny PR that differentiates the Stall i by the soilson compound and Stall i, the stall directly northeast of the south gate in town. The stall next to the farm has been renamed to the Soilson Stall to prevent confusion.
I've seen no less than 8 people get caught by this minor confusion when planning where to meet later. This fixes that by properly naming a spot in town.

Rename stall i to Soilson Stall

---

code/modules/jobs/job_types/roguetown/garrison/dungeoneer.dm

Spotted a spelling error in the dungeoneer stat defines. Figured I would touch that and buff dungeoneer up a little so that it's on the level with other keep roles. Not a very attractive role, due to social stigma and perceived inadequacies compared to other garrison/keep roles.
Severian needs a little love. Yet another stats pull request. Other classes with 5 wrestle are Guard Captain and Iconoclast and Vampire Lord. Keep balance kind of ran away from Dungeoneer, this catches him up.

Buffs dungeoneer. buffs wrestle, fixes constitution, adds guardsman

---

code/modules/clothing/rogueclothes/rings.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/hostile/simple_skeleton.dm
code/modules/mob/mob_movement.dm
code/modules/reagents/chemistry/holder.dm
modular/Mapping/icons/Mapping_aides.dm
modular_hearthstone/code/modules/mob/living/simple_animal/rogue/orc.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Existing bullet damage projectiles replaced by piercing / magic.
Unusual null turf reference in sneaking code - I say unusual because it never happened pre-debloat.
Baothan trait (TRAIT_CRACKHEAD) reimplemented
TRAIT_NORUN for deadites and inbred princes is now implemented. This primarily means deadites will not be able to run.
Spiderweb integrity nerfed to 30 from 300 (the original /obj/structure/spider was lost in debloat)
Bugs
Unsure about the NORUN for deadites. It's listed as a zombie trait but was never implemented properly. Hopefully it doesn't kneecap the antag too much.

small bugfixes, baothan & trait_norun implementation

---

code/modules/mob/living/carbon/human/npc/goblin.dm

goblins have 1 in bows and crossbows now so that they can shoot them without creating runtimes. closes #1043 
also closes a few out of date or unnecessary bug reports:
closes #502 - fixed by #806 
closes #863 - seems to be fixed
closes #1027 - not a bug, just a change in visual style. someone can pr a change if they have a preference for a different color temperature.
fixes a runtime 👍

fixes an obscure goblin runtime, closes a few bugs

---

code/game/area/roguetownareas.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm

By partial revival of a bug that was neat.
Reminder, no game sense, so use your own best judgement to decide if it's warranted, but the horse (especially if they get anything from #1078) will be a lot more usable, and this would turn the RG MK into a more defined "cavalry" guy, at least, if players consider buffs as incentive / justification to be in places.
Is this going too far? I'unno. It's really a statjak PR hidden behind code.
Oh, this also stops the two buffs being stacked ever, but to my knowledge no role uses both.

Gives the Mounted Knight RG the MaA buff (does not stack w/ keep buff)

---

code/modules/jobs/job_types/roguetown/youngfolk/prince.dm

Daring twit now gets some climbing, slightly better athletics and a Sabre instead of a sword.
Introverted bookworm gets the +1 fortune every other heir gets, a steel dagger instead of an iron one, pronoun-based clothes and no longer looks like a homeless person
Sheltered Aristocrat now gets the fabled Satchel, and their outfit is now pronoun-based instead of gender-based. They also got some sewing skill, because it seemed appropriate.
Male wastrels no longer have mechanically better belts than female wastrels.
Introverted bookworm needed to look less like some random homeless person that was plucked off the street, I also initially gave them an iron dagger for some vague sense of "Balance" but it's just dumb having the rich child of royalty not have at least steel.
Daring Twit basically …

Various changes to the heir subclasses (Satchel Powercreep)

---

code/game/objects/structures/stairs.dm

They now respect whether you were fireman carrying or piggyback carrying.
Bug bad.

Fixes fireman carry and piggyback z level transitions

---

code/game/objects/items/rogueweapons/melee/flail.dm

Hello. This is the first _(and likely only time)_ that I'll be making a pull request.
Merry Christmas to those that're reading this, by the way! I hope you're all staying warm, festive, and jovial.
This pull request - assuming I haven't accidentally messed anything - tweaks the Flail's performance..
- ..by removing the **'swingdelay'** variable, which determines how long it takes for an attack to be attempted post-release, and..
- ..by adding the **'chargedrain'** variable from the bows, which gradually drains stamina while the weapon is being 'charged' up.
In addition, the damage modifier for the Peasant War Flail has been brought down to be in-line with the regular Flail.
A couple months ago, Kavrick made a pull request that nerfed the Flail's effectiveness. This was done because Flails …

A Yuletide Tweak - Alters 'flail.dmi' by removing the 'swingdelay' variable, and by introducing the 'chargedrain' variable.

---

code/modules/mob/living/carbon/carbon.dm
code/modules/reagents/chemistry/reagents/toxin_reagents.dm

Takes away Spewium's gimmick of upchucking organs, since this could lead to round removal from vomiting brain. Tucked in a bit of toxin damage on the overdose so that it's not completely neutered.
Someone vomited up their penis.

Nerfing spewium to not hurl brain

---

code/game/objects/lighting/rogue_fires.dm

Adjusts brightness of candles, braziers, and sconces. Before and after pics below.
<details>
Before:
After:
Before:
After:
</details>
Debloat PR overhauled our lighting system and left the town looking very dark in certain areas. This brightens things back up a bit.

Lighting fixes

---

_maps/map_files/dun_manor/dun_manor.dmm

Makes a particular Keep door ridethrough (for mounts)

---

code/modules/mob/living/carbon/human/npc/goblin.dm
code/modules/spells/roguetown/_roguetown.dm

Fixes mbutton->right click interaction with validly charged spells
stops giving 'mind'less goblins archery skills for now
bugfixes

spellcast rightclick fix, comment out goblin carbon archery

---

_maps/map_files/dun_manor/dun_manor.dmm
code/game/objects/items/rogueitems/keyrings.dm
code/game/objects/items/rogueitems/keys.dm

TLDR; touches up the garrison building and gatehouse a bit, makes the keep and the garrison building a bit harder to break into, gives the armory a separate keyset from the rest of the garrison building.
<details>
<summary>Screenshots:</summary>
Downstairs:
Upstairs:
</details>
<details>
<summary>Full list of changes:</summary>
- Reworks the downstairs area of the garrison building into a common room with tables for eating/drinking and hanging out. 
- Replaces the windows in the garrison building with reinforced windows, the same kind the merchant & steward's buildings get.
- Moves the extra manor/garrison keys into locked closets/chests.
- The squire room actually has four beds now - for four squires.
- Moves some things around upstairs. All of the food and random cooking equipment that …

Garrison barracks overhaul + armory keys

---

code/modules/antagonists/roguetown/villain/lich.dm
code/modules/antagonists/roguetown/villain/zombie/zombie.dm
code/modules/mob/living/carbon/human/death.dm

deadite snapshots on antag mind gain (to set reset it on cure) however, STA[stat] are all affected by the temporary status effects.
so when people turned into a deadite with heavy bleeding, hunger or thirst their stats were snapshot in that state and then set to that on cure
this clears all debuffs on antag gain to get an accurate snapshot
yay

deadite stat snapshot fix, lich faction fix

---

code/__DEFINES/traits.dm
code/datums/gods/patrons/divine_pantheon.dm
code/game/turfs/open/water.dm
code/modules/mob/living/carbon/human/species_types/furry/akula.dm
code/modules/reagents/chemistry/reagents/other_reagents.dm

This PR changes water reagents for some sources to more be more accurate, as well as giving some extra utility to some.
The current list of changed liquids is not very high, but it paves the way for some variety in them.
Changed water types:
**Salt water (ocean water) and it's deep variant:** 
Actually saltwater now, instead of killing you when drinking it, it will simply dehydrate you, similarly to real ocean water.
Can be boiled in a full pot (on a hearth, unless you can place pots on fires in the future) to purify it into drinkable water, as well as a few piles of salt.
Axians and Abyssorites can drink saltwater without any negative effects as well. (This is given by "Denizen of the Deep" trait)
You can also wash in deep saltwater tiles now, cuz why not.
Tastes salty now. …

Water Reagent Changes (mainly the ocean)

---

_maps/map_files/dun_manor/dun_manor.dmm

fixes this
oops grilles don't have density flags by default mb

Fixes keep gatehouse grilles

---

code/modules/roguetown/roguestock/stockpile.dm

Chop up the fish and put it in the stockpile.
Instead of snowflaking a bunch of different fish in the stockpile datum, we have the almighty assorted fish product. Selling whole fish to the balloon via merchant is phenomenally more profitable. This is to let the stockpile in #1170 have something to be put in it other than salt. Tooled with numbers approximate to jacksberries so the economy doesn't flounder.

Adds fish mince to stockpile list

---

code/modules/roguetown/roguemachine/scomm.dm

Bad assignment operator turns people's jobs into squires in the logic check for if they can garriscom. This fixes the comparison.
Princess Squire, we will miss you

Fixes assignment operator overwriting jobs with squire in scom middlemouseclick

---

modular/Neu_Food/code/cooked/NeuFood_pies.dm

There was a reported bug where berry poisoned pies were not coming through correctly, especially when cut into slices. This aims to fix it by changing the logic so that any poisoned berry in a berry pie procs the poison pie. The poison reagents properly fall down to slices through initialize_slice 
Put some elses in front of ifs.
Sire, this pie is poisoned!

Logic changes to fix poison pies bug

---

code/game/objects/structures/mineral_doors.dm

Master key had a weird lockhash copy property onclick that was sometimes troublesome when compared to the usual understanding of keys. This short-circuits the bump check so that master key is always valid to lock/unlock any door (which is effectively the case already with the lockhash copy onclick), letting it be used like a normal key in-hand walking around. Also should prevent weird can't-lock situation-bugs that have been reported.
Gotta protect the all access ID

Buffs master key to make it work on bump

---

_maps/map_files/dun_manor/dun_manor.dmm
code/modules/jobs/job_types/roguetown/youngfolk/apothecary.dm
code/modules/reagents/chemistry/reagents/roguetown.dm

Gives a check to the physician mask to make it useful, and not just rogue fashion. Also hands two of them to the apothecary desks, they need it more than the actual physician since they don't spawn with the nostink trait.
Physician mask had a strange collision with glasses on spawn, so near-sighted physicians never got a mask. A couple spares for him and his two apothecaries is cool, also means it's useful fashion.

Makes Physician mask work vs miasma, adds 3 masks to map

---

code/game/objects/structures/walldeco.dm

Alarms lost their sleep call in the debloat due to issues. This reimplements their "silence for a bit" functionality, with a var tracking ticks passed with respect to world.time.

Adds alarm silence, cooldown based on world time

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm

Gives the 'ancient key' to followers of Zizo who pick the Hymnist bard class.  Does not give them the zizo cult theme because I find it annoying and I like the bard theme better.
It arguably fits into the category of 'person associated with magic, holy or arcane in nature' who get access to the Zurch. It also adds some more love for those who pick Hymnist but aren't followers of the Divine Pantheon.

Gives the zurch key to hymnist Zizo followers.

---

code/modules/roguetown/roguemachine/titan.dm

Puts in a logic check to the throat so that if the crown is in the vault, only the current ruler (Grand Duke) can summon it. Everybody else has to go get it.
There was admin concern about someone sniping the crown from the vault with the throat, which is a risk on lower pop. Admittedly, the risk was with the "fake" throat that spawns in the Mad Duke's room on the coast. But this addresses that concern. Not entirely sure about this one. Needs some discussion.

Lets the crown sit in the vault unless the duke calls for it

---

code/modules/mob/living/carbon/human/human.dm

mob/living/carbon/human/canUseTopic was only checking mobility, having lost some of its checks with respect to parent typing. This redefines those checks further up. I *should* return ..() at the end, but, the monkey dexterity checks are depreciated and it feels nasty.
Prevents things like using Vomitoriums while far away from them / unconscious. Probably need to gut monkey dexterity checks for canUseTopic at some point. Who uses inheritance in BYOND anyway, it's not like that's the whole point

Uplifts mob/living/canUseTopic functionality to mob/living/carbon/human

---

code/datums/stress/positive_events.dm
code/modules/admin/verbs/schizohelp.dm
code/modules/mob/living/emote.dm
interface/interface.dm

There are complaints of people using meditate as prayer, and thus loading mentorhelp with false queries. This unties mentorhelp from the meditate verb (for some reason it was doubled in the IC emote verb snowflake and also an Admin tab verb); and adds a token destress if you spend a minute meditating. Now it is more clear that mentorhelp is an "OOC" verb.
Anything to give the end user enough information to prevent a skill issue.

Removes mentorhelp from meditate verb, adds token destress

---

code/modules/antagonists/roguetown/villain/zombie/zombie.dm

Bug with the "station" faction being added to un-deadited individuals, making aggressive NPCs in dungeons non-aggro. This removes the station flags from un-deaditing, which is probably deprecated. They have their own zombie faction stuff anyway.
Should prevent anomalies with un-zombified people being friends with sea raiders, etc.

Bugfix: Removing zombie faction "station" add/neg for deadites

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/steppesman.dm

Steppe dropped their bucklers when they spawned. This annoys me.
I also removed a duplicate coin pouch while I was here, steppe is already probably unironically the strongest class in the game they don't need to double dip money too smirk smirk
stops litter bugs

Rearranges Steppe's starting equipment.

---

modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Ports one of my favorite spells from the Hearthstone 5e spell additions. Poison Spray (Renamed Aerosolize) 
Aerosolize does the following:
Turns a container of liquid into a smoke containing the reagents of that liquid.
Simple spell, very versatile in its uses. Thirsty? Aerosolize some water. Want to try and poison someone (pretty obviously)? Aerosolize some poison on them. Someone on the ground dying but you're too busy trying to not die yourself? Aerosolize a health potion to let them slowly heal.
Fun fact, Deathless cannot benefit from this spell because they don't breath! Anyone who does not breath cannot be affected.
More spells, fun spells.

Are you smoking yet? | Ports Poison Spray from Hearthstones 5e spells.

---

code/modules/roguetown/roguemachine/drugmachine.dm

Window content was being overwritten by Bathmaster jobslot, preventing Bathmaster from being able to access mammon inserted in the machine. This fixes that. Also tightens up some of the withdraw cut logic to ensure payout.

Bugfix: Touches Purity machine to fix some bathmaster interactions

---

code/game/objects/structures/guillotine.dm

It was always a bug being stripped being put on the guillotine because a regenerate icons call needed to be made after a cut overlay call.
No more naked hobo executions unless you request to be a naked hobo...and they let you.
You do you..

Fixes: Guillotine Bug

---

code/modules/roguetown/roguecrafting/structure.dm

This lets you craft the blue standing fire you see in some places. We have engineers that can make colored bronze lanterns, self-purifying things, I am sure that aesthetic blue standing fire (I added a component to it more than normal standing fire) will probably be fine, especially for those that want to decorate underground with a softer color, or replace ones that get all messed up. (Like 5 people will probably ever use this.)

craft blue standing fire

---

_maps/map_files/dun_manor/dun_manor.dmm
code/game/objects/items/rogueitems/keys.dm

also known as wish fulfillment
Converts stable 3 into a mercenary keyed stable, so the various merc riders can park their car freely. For reference, the other two stables are locked behind respective stable keys, which are in turn tucked in the nearby shack that's under the soilson key.
With that in mind, I also populated the stalls with a male and female saiga, respectively, so a would-be farmer can do hor-- antelope things. Right now they have a mating pair of goats and cows, but any saiga has to be procured on site. Or just bought from the steward for a hundred, so it's whatever.
I also put a saiga in the mercenary stable. They get one for free, as a treat. These are the only three saiga on the map.
Mercenaries don't have anywhere to park their cars without bringing them inside, so now …

Merc stable

---

code/modules/roguetown/roguecrafting/leather.dm

Leather Sea Jackets and Leather Vests shared the same crafting path making Leather Vests unable to be crafted.
fixes a bug.

Simple leather vest crafting fix.

---

modular_hearthstone/code/modules/spells/roguetown/wizard.dm

https://github.com/user-attachments/assets/41804ddc-7bed-42c3-a4cf-ad1da0262c00
If you're in throw mode, and are holding something in your active hand (that isn't a grab) it'll get flung out much the same as if it were hit by repel itself.
By request, it sounds kinda cool, if a bit janky.

Repel now flings whatever you're holding on cast out of your hands

---

code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/disciple.dm
code/modules/jobs/job_types/roguetown/church/templar.dm

Disciple was an actual 1:1 copy of Templar Monks and that included being bare butt naked and having Miracles at 2 (despite being a Psydonite)
This shifts Disciple to something similar to a Naledi Warscholar, turning them into a quasi melee utility class that's the frailest of them all, and a muscle wizard Otavan Brute.
Naledi- trained scholar gets:
- Same statline as a Templar Monk
- With pre-set spells (fetch, message, sickness ray, forcewall, blade of psydon)
Otavan Brute
- Crit resistance
- No pain stun
- No dodge expert or any armor (spawns literally shirtless)
- 2 CON and 2 END
The general idea behind War Scholars was cool, and looked like a fun template to shift an inquis. role towards, without also copying war scholars 1:1. If the spells are too much feel free to point it out, as …

Reworks (buffs) Orthodoxist Disciple. Adds Otavan Brute Archetype

---

code/modules/roguetown/roguejobs/tailor/dyer.dm

What it says on the tin. Every color that the Lord can choose for their banner has been added to the dye bin as a "Royal [color]".
By request. By me. Cus I got annoyed that I can't rep my Big G on da throne with accurate hex colors.

Adds every Lord banner color to the dye bin

---

code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/disciple.dm

This subclass didn't spawn with a key when they should. This fixes it.
If you are so great a wizard, why don't you spell yourself up a key

Fixes Nadeli Orthos lacking an inquisition key

---

code/modules/cargo/packsrogue/luxury.dm

Bumps up the price of riddles of steel in the goldface a bit in order to patch an exploit that allows the merchant to generate literal infinite amounts of money by buying riddles of steel from the goldface and then immediately selling them at the balloon for a net profit.
Riddles of steel currently have the same base sell value as their base buy value in the vendor, and because of price/value variation, riddles of steel can occasionally be significantly cheaper in the goldface vendor than what they actually sell for at the balloon if the merchant gets lucky - which allows the merchant to generate infinite amounts of money by repeatedly buying and immediately selling them at the balloon.

Fixes Merchant infinite money glitch

---

code/game/objects/items/granters.dm

Fringe situation where the final do_after for reading an arcyne book would be interrupted and then lock the reading sanity var to true. This adds a catch to the end that should prevent it from happening.
There appeared to be an issue with used/oneuse logic that I also tried to fix. But that is only pertinent to spell granting scrolls I think.
Arcane tomes do arcane things

Bugfix for reading var in arcane tomes locking up as true

---

code/modules/mob/mob_movement.dm

This is a very finnicky thing because the visual lighting does not intuitively connect with "dark" areas. That said, if you've high Sneak, you should be able to notice **slight** difference in your favor.
NO Sneak
Journeyman Sneak
(yes, no difference)
Legendary Sneak
This is also very sensitive, because if you go too hard you'll be able to vanish mid combat or w/e into literal thin air. Not good, I think.
I obviously can't in any reasonable way test every circumstance here, because lumcount is the most insane proc with incredibly varied, inconsistent results. You might be able to vanish in some weird, unexpected spots with high enough skill, or this might affect a total of 5 tiles across every single map. It's really hard to say.
Sneak skill meaning something more tangibly! Woo!

Buffs sneaking (sneak skill now lets you sneak in slightly brighter conditions)

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm

- Master Swords ---> Expert Swords/Knives/Whips/Athletics
- No more strength buff
- Pick between Shamshir or Whips + Parrying Dagger
The fact I'm taking Master swords off of everyone's favorite meta mercenary is going to cause like 20 comments from people who want to keep their precious meta pick.
1. A disproportionate amount of Mercenaries in-game are Blade Dancers (I wonder why) 
2. A mercenary class shouldn't have Bandit-tier or Middle-Aged Veteran-tier skills in swords (Master).
3. This PR will actually encourage people to play literally anything else in the Mercenary category.
4. Because Blade Dancers are THE Meta Merc class for Fragging. 
5. They singlehandedly outclass 80% of roles in combat situations. 
6. It's stupid that they:
- Get dodge expert and +3 Speed
- Master-tier …

Blade Dancer is no longer meta (No more master skill fragging)

---

code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm

Fish spear implementation overwrote the define of the eagle beak datum, meaning eagle beaks could no longer be smithed. This fixes that. 
Eagle beak my beloved

Bugfix: Defines fishspear as fishspear and not eagle beak duplicate

---

code/modules/mob/living/simple_animal/rogue/game/saiga.dm

With the help of our friend GOAT RIDING CODE i fixed it so you no longer look like you are sitting on a saigas head while facing south. Now someone add ridable mossbacks so sunglade stops pulling a gun to my head.
This same bug happens to guillotine and while out of scope i will leave my findings here as i did on discord for anyone else wanting to go figure out the Guillotine layering.
" upon compareing to the pillory code i saw it uses a icon state for being over/on someone all well and good for the fact the pillory is a standing game punishment(Litterly you are standing). FOR GUILLOTINES to make you look 'behind' the sprite properly you would need an icon state like that, remove ' H.layer += GUILLOTINE_LAYER_DIFF' in the code and somehow figure out how to not make it look goofy cause …

Visual Fix: South Facing Saiga riding.

---

code/modules/client/preferences.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/living.dm
modular_azurepeak/statpacks/wildcard.dm
modular_azurepeak/virtues/size.dm

Comments out the virtue/statpack restrictions. Now you can take both. Also nerfs Giant, since it used to be a statpack + also some mechanical bonuses. Now It's just door ramming and the larger sprite. Also removed its triumph cost. I think the other virtues should be fine when combined with statpacks? Only other problematic one might be acrobatic, but I havent really seen anyone abuse the z-level fall yet so probably fine? We will c.
Now people can choose their Neat Flavor Options without being at a disadvantage statswise. Virtues are really cool for flavor, and I imagine we'll see more people taking stuff like Beautiful, or Rich, or etc now. Also reigns in Giant, which was a statpack + alot of boons already.

Virtues + Statpacks

---

code/modules/cargo/packsrogue/Brigand.dm
code/modules/cargo/packsrogue/Knave.dm
code/modules/cargo/packsrogue/Knight.dm
code/modules/cargo/packsrogue/Sawbones.dm
code/modules/cargo/packsrogue/Sellsword.dm
code/modules/jobs/job_types/roguetown/adventurer/types/antag/sawbones.dm

Adds in some stuff to the Hoardmaster lists of relevant classes. Knaves get tossblades, brigands and sellswords get the wolf plate helmet, brigands get warhammers + heater shields. 
Buffs Sawbones to master swords, gives them deceiving meekness, no stink, and empathy + legendary medicine. Pretty much a doctor/duelist on steroids. Also gives them the Cool Outfit:tm: in their hoardmaster + cheapens bottle bombs.
Sawbones has been a bit bleak for a time. Also just adds some little things to hoardmaster lists. I'll probably buff rogue mage after arcane decoupling is done? And try to figure out something for sellsword? These three being the less popular/less good bandit classes.

Hoardmaster additions + Sawbones buff

---

code/modules/roguetown/roguemachine/steward.dm

Quick ternary check to swap the nerve master's icon state, whether his eye is illuminated or not based on whether he's locked. Sprite was already there, just wasn't used for whatever reason.
this is what ternary operators were made for

Visual feedback on whether nerve master is locked or not

---

modular/Neu_Food/code/raw/NeuFood_dough.dm

The plateable rework missed setting cheesecake and honeycake slices as plateable. This fixes that.

Defines cheesecake slice and honeycake slice as plateable

---

code/modules/clothing/clothing.dm
code/modules/clothing/rogueclothes/hats.dm

Allows you to recover feathers or cloths from helmets that have been decorated by middleclicking on it.
Imagine this: 
You spend 50 mammons on a helmet you've never used before and want to add a cloth or feather to it, then realize the color doesn't match your outfit. Now, you can middleclick on it and recover the decorator item.

Adds a way to remove feathers or cloth from helmets.

---

code/game/objects/items/rogueitems/dmusicbox.dm

The music channel was being used by bard instruments to host their music, causing it to be interrupted by change of day/zone which also used the music channel. This moves instruments over to the CMUSIC channel, which is free and unused, removing the interruptions.
I JUST WANT TO PLAY A FULL SONG ZIZO PLEASE I BEG OF YOU

Bard Bug SQUASHENING

---

code/modules/jobs/job_types/_job.dm

Briefly reverts GeneralPantsuIsBadAtCoding/Azure-Peak#1285 because no one's showing up in Actors now.

Revert "Bandits are hidden in Actors List"

---

_maps/map_files/dun_manor/dun_manor.dmm
code/_globalvars/special_traits.dm
code/modules/clothing/rogueclothes/shirts.dm

Few bugfixes. Stops weener from showing through archivist robe. Puts addition assignment in loadout stashed items so that they cooperate properly with virtue added stashed items. Maps in spare golden spectacles for artificers in their bedroom.
Just some bugfixes

bugfixes for artificer robes, stash additions, and golden spectacles mapped in

---

modular_azurepeak/virtues/combat.dm

To briefly explain how miracles work, miracles are unlocked through an invisible 'progress' stat that is an accumulated total of how much devotion you've gained through prayer in the round; except unlike devotion, 'progress' never gets lowered or spent at all when you cast miracles.
Devotee currently raises your progress cap by a single tier if you already spawn with miracles - this PR makes it also raise your devotion cap by a single tier if you already spawn with miracles.
Devotee currently raises your progress cap by 1 tier (for templars/paladins this goes from 100 to 250) but doesn't raise your actual devotion cap, meaning you can /technically/ unlock tier 2 miracles as a paladin/templar with devotee, but doing so would require you to pray until you hit your cap of 100 devotion, spam …

Devotee raises your devotion cap to the next tier if you already have miracles

---

code/datums/actions/mobs/dragonbreath.dm
code/modules/mob/living/simple_animal/animal_defense.dm

Explosions could give simplemobs infinite health if an explosion that hit it had no epicenter: 
get_dist() will return -1 when Loc1 and Loc2 are the same object. If one or both of them is not on the map, an infinite value is returned.
bugfix

bugfix: explosions and simplemobs

---

modular/Neu_Food/code/raw/NeuFood_veggies.dm

Buffs veggies by increasing potato and onion slices to 2 instead of 1.
Veggies are a little cheaper to eat than meat. Make your mammon last longer.

Onion and Potato cut into 2 slices

---

_maps/map_files/dun_manor/dun_manor.dmm

- Fixed a missing turf under one of the tables.
- Added a stockpile in the kitchen.
- Gave them a rolling pin and an extra table.
- Deleted the extra spawn locations to have a single one in the office for the steward, and another in the clerk room for the clerk.
- Changed the direction from where the viewport opens in the main Stewardry door.
- Added the stables keys to the chest, and the archives one.
Quality of life is good.

Fixes | Stewardry Oversights

---

code/__DEFINES/ai/_ai.dm
code/__DEFINES/ai/hostile.dm
code/datums/ai/behaviors/hostile/find_potential_targets.dm
code/datums/ai/behaviors/hunger.dm
code/datums/ai/controllers/spider.dm
code/datums/ai/controllers/volf.dm
code/datums/ai/subtrees/call_reinforcements.dm
code/datums/ai/subtrees/eat_body.dm
code/datums/ai/subtrees/eat_food.dm
code/datums/ai/subtrees/find_food.dm
code/datums/ai/subtrees/retaliate_subtree.dm
code/datums/ai/targetting_datum/simple_targetting_datum.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/simple_animal/rogue/creacher/honeyspider.dm
code/modules/mob/living/simple_animal/rogue/creacher/mossback.dm
code/modules/spells/roguetown/acolyte/dendor.dm

Bugfix for the dendorite tame beast spell and gives them some feedback to the spell
tame beast spell is now limited to these animal families: ("saiga", "chickens", "cows", "goats", "wolfs", "spiders")
account for tamed animals in the targetting
bugfixes + dendor's power no longer extends to every retaliate animal

dendor tame beast fix/change for simples, eat_food/eat_body/retal subtree cleanup

---

code/game/objects/items/rogueweapons/melee/swords.dm

Cherry pick of https://github.com/Rotwood-Vale/Ratwood-Keep/pull/2358 credit to [john-pawson](https://github.com/john-pawson)
Fixes longsword on-belt sprites to be sensible.
-AP: removes executioner sword from belt slot since it is gnarly, and touches marshal's oathkeeper sword too

New longsword belt sprite calcs

---

_maps/map_files/dun_manor/dun_manor.dmm

adds a few more drip options for guards in the armory (capes and regular tabards) that are automatically colored to w/ever colors the duke selects 4 the round
more drip options for guards, this stuff is entirely cosmetic

adds regular guard tabards and guard capes in armory

---

code/datums/stress/_stressevent.dm
code/datums/stress/negative_events.dm
code/datums/stress/positive_events.dm
code/game/objects/items/soap.dm
code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm
code/modules/mob/living/carbon/life.dm

Goof dropped the soap but now, with great assistance, learned better. 
Introducing second attempt two.
--
Fixed the soap types so both soap and herbal soap should do the same things - clean objects and other people. 
Adds moodlet buffs to being washed and washing yourself with soap. 
Furthermore - FIXED the 'get bathed' moodlet to actually properly  apply and exist in the first place. 
Changed it so you don't have to lay down in bathwater to get the bathwater-relaxing moodlet, thus drowning yourself. 
Fixes a typo in the stressevent info tab, where the values were flipped
Lastly, made it so trudging through sewer water actually has a negative. ATM it makes you sad, but I'd like to expand on it in the future.
Bath'ers (gender neutral) now can actually do their namesake. It provides them …

Soaps, Sewers, and Soothers

---

_maps/map_files/dun_manor/dun_manor.dmm

Big Steward chest of keys conspiracy pulls ahead with the Innkeeper's key, which only goes to the Innkeeper's room, which is filled with more tavern keys.
Better than breaking this window.

Adds innkeeper's key to steward chest of keys

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/ranger.dm

gives ranger sentinels apprentice cooking
i gave them apprentice in a few other survival-themed skills but forgot cooking

sentinels can have apprentice cooking as a treat

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/atgervi.dm

the patron is now randomized w/ Inhumen if you try to play an Atgervi without having one selected
The shaman hood no longer obscures your identity, just like the Vangarian helmet (they don't have toggle states, so it's the best compromise imo)
oops

atgervi fixes

---

code/modules/mob/living/carbon/human/species_types/furry/akula.dm
code/modules/mob/living/carbon/human/species_types/furry/anthromorph.dm
code/modules/mob/living/carbon/human/species_types/furry/anthromorphsmall.dm
code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
code/modules/mob/living/carbon/human/species_types/furry/dracon.dm
code/modules/mob/living/carbon/human/species_types/furry/kobold.dm
code/modules/mob/living/carbon/human/species_types/furry/lizardfolk.dm
code/modules/mob/living/carbon/human/species_types/furry/lupian.dm
code/modules/mob/living/carbon/human/species_types/furry/moth.dm
code/modules/mob/living/carbon/human/species_types/furry/tabaxi.dm
code/modules/mob/living/carbon/human/species_types/furry/vulpkanin.dm
code/modules/mob/living/carbon/human/species_types/roguetown/dwarf/dwarfm.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfs.dm
code/modules/mob/living/carbon/human/species_types/roguetown/goblin/goblinp.dm
code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/aasimar.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halforc.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm

I recently did a poll in the dev-general asking people's thoughts on how people viewed the current racial stat balancing. There was a pretty split consensus between two ideas:
- Some people like the stat boosts because it creates flavor and identity between the races.
- Some people disliked the stat boosts because it forced them to be inherently worse mechanically for classes they wished to write their characters in.
To this end, I propose a change that does a 1 stat point shift for all races, removing malices from STR/SPD/FORT races and adding lower tier stats to other races to compensate. STR and SPD are incredibly strong in current meta, so this **does not add STR or SPD to any races.** It only adds int/perc/con/end.
Do note that these are my opinions and observations. There are too …

Racial Stat Rebalance

---

code/game/objects/items/rogueitems/needle.dm

Prevents clothing integrity from going below 0 and into the negatives when failing a repair.
Reduces sewing repair failure damage by half.
Increases the amount of durability repaired per success across the board.
This was really harsh by comparison to blacksmithing repairs. This should make repairing leather armor a bit less punishing.

Tweaks some math with sewing repairs

---

code/game/objects/items.dm
code/modules/roguetown/roguejobs/blacksmith/tools.dm

- Repairing armor/weapons now requires a table or an anvil.
- Failing to repair armor/weapons now damages them a bit.
Makes blacksmithing skills a bit more impactful. It's probably pretty hard to repair your own armor if you have literally no experience smithing whatsoever.

Armor repair tweaks

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm

Adventurer mages now have subclass preview hover-over text.
bugfix, i somehow missed this one, its the only adventurer class that doesn't have any subclass preview descriptions

Adds adventurer mage subclass preview

---

code/modules/client/verbs/ghost.dm

Returntolobby (journey to the underworld) was calling a deletion of the src atom after the ckey exchange, which meant bodies would go POOF from existence upon returning to lobby. 
hey I was going to loot that corpse!

removes qdel(src) from returntolobby

---

code/_globalvars/lists/flavor_misc.dm
code/controllers/subsystem/rogue/soundloopers.dm
code/datums/looping_sounds/_looping_sound.dm
code/game/objects/items/devices/flashlight.dm
code/game/objects/items/rogueitems/dmusicbox.dm
code/game/objects/items/rogueitems/instruments.dm
code/game/objects/lighting/_base_roguelight.dm
code/game/objects/lighting/rogue_fires.dm
code/game/objects/structures/roguetown/musicbox.dm
code/game/sound.dm

Looping sounds were causing a massive amount of unnecessary overhead due to someone removing a timer and bombarding the game with sounds (20,000 per second to be exact). The looper now instead loops through clients rather than objects, puts repeating sounds (music boxes + instruments) on a global list for speed and fixes a few other outstanding bugs  in the sound code.
Note this could break sound things in strange and unexpected ways, but it should still be many times more efficient than what nonsense was going on before. 
This should probably be testmerged and checked in case something does in fact explode. Instruments and music boxes are most affected by this change. 
Should ease a lot of current lag, fixes a few oddities with the sound system.

Fixes to looping sounds

---

_maps/map_files/dun_manor/azure_forest.dmm

Adds extra recurve bows and quivers to the warden's tower, as there were currently only *two* bows and there are more warden slots than that. Also added some spare chains, and steel daggers for anti-grapple(as every other garrison member gets)
Weyyy cant really play the warden gimmick without a bow.

Adds some things to the warden tower

---

code/controllers/subsystem/rogue/role_class_handler/class_select_handler/class_select_handler.dm
code/controllers/subsystem/rogue/triumphs/triumph_buy_menu.dm
code/modules/admin/admin.dm

Beta branch of BYOND was not agreeing with the meta tags being outside of the \<head\>, this places them where they need to be. Checked advanced role selection menu, plus sleep menu, on 515 and 516. No issues that I could find.
Fixes one of the big issues with playing AP on 516.

Fixing advmenu display for BYOND 516

---

_maps/map_files/dun_manor/dun_manor.dmm

> Window of Stall 2(?) the southern one attached to the tavern, has one window that locks and opens from the outside
Opens from the inside now, as PSYDON intended

Map: fixes stall 2 window opening dir

---

code/modules/mob/living/carbon/life.dm

Armor burden when trying to sleep now works off of armor class rather than blunt resist stat. Haubergeons and other items in the shirt slot rather than the armor slot won't count.
Helmets still function the same as before and still just work off the blunt resist stat, because none of them have armor class flags.
Leather armors had their blunt damage values increased recently and they prevent you from sleeping now. Oops. It makes more sense that armor sleep prevention would just work off of weight class rather than the blunt resist stat, anyways.

Armor sleep fix

---

code/modules/clothing/rogueclothes/cloaks.dm
code/modules/mob/living/carbon/human/update_icons.dm

You can now toggle tabards of all sorts to wear either under or over your armor by middleclicking them. Commissioned by Dongwaiver. A selection:
Drip or drown

[BOUNTY]Tabard toggle over/under armor

---

code/modules/roguetown/roguecrafting/alchemy/ingredients.dm

Rosewater potion is no longer an impossibility, you can brew it with just one rose as the major, med and minor mods are all set to rosewater. This type of single ingredient potion brewing is already present in the transisdust. Considered adding minor roses to two other items but, it's already worse than regular healing potions and strong healing potions only need two ingredients that are laughably easy.
Rose water flavoring fun for everyone.

Makes Rosewater potion brewable.

---

code/controllers/subsystem/rogue/devotion.dm
code/datums/gods/_patron.dm
code/datums/gods/patrons/divine_pantheon.dm
code/modules/jobs/job_types/roguetown/church/monk.dm
code/modules/jobs/job_types/roguetown/church/templar.dm

Gee Malum, how come Aeon lets you have TWO T0 spells?
In all seriousness, this just adds support for adding spells that don't fit into available T0-4 slots. Malum's fire is basically just sacred flame but without a slot, this adds in proper support. It works as far as I can tell.
Less snowflake code is good, and this allows for more creative spells in the future given how constricting a 4 spell limit can sometimes be, especially if many users cannot use every single spell (templars, looking @ you.)

Removes snowflake malum's fire code, adds support for Extra Spells.

---

code/modules/jobs/job_types/roguetown/nobility/knight.dm

This replaces the mounted Royal Guard class' sabre with a bastard sword. Let me know if I fucked up somewhere. I'm rusty. This PR is tested, though, and it appears in-game just fine.
Sabres aren't a very fitting weapon for a knight. When you think of a knight on horseback, it comes to polearms, lances, straight swords, skull-smashing weapons like maces and warhammers. Sabres are designed for speedy classes, it'd make more sense for a mounted mercenary like a Steppesman or something. Those folk should feel different from a traditional knight. All for soul.

Replaced Mounted Knight Sabre w/ Bastard Sword

---

code/__DEFINES/traits.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/wretch.dm
code/modules/jobs/job_types/roguetown/church/monk.dm
code/modules/jobs/job_types/roguetown/church/priest.dm
code/modules/roguetown/roguejobs/gravedigger/hole.dm

Adds Experienced Grave Robber, which allows Treasure Hunters and Zizo aligned Heretics as well as Necromancers resist the cursed effect placed upon you when you go grave robbing.
Grave robbing is literally not worth it. You have a like 1/4 chance to spawn a skeleton NPC or get nothing in addition to getting the Cursed effect which is absolutely debilitating since it gives about -3 Fortune. 
Also, this will strengthen the local economy. And give Necrans something to screech at adventurers about.

Introduces the Experienced Grave Robber trait.

---

code/game/objects/effects/decals/remains.dm

This adds the ability to clean up the remains you often find in places like the Zurch and other places by clicking on them, waiting 5 seconds and then salvaging bones and skulls from the piles.
These things were impossible to clean, even if you WANTED to restore an area - they just didn't go away.

Adds the ability to clean up remains by clicking on them.

---

code/modules/roguetown/roguestock/stockpile.dm

The way stockpile handles istype checks, cured leather was going into the machine as hide. This fixes that by defining cured leather earlier in the file before hide, which populates cured leather into ssTreasury before hide, meaning it gets the istype check first, which satisfies the stockpile logic. Yes, it's terrifying

Fixes stockpile for cured leather by defining it before hide

---

code/modules/mob/living/living.dm
code/modules/mob/mob_defines.dm

Sprinting's dir change to reset the sprinted_tiles increment happened after proc/Move, which meant you could charge into someone by juking into them at the termination of your charge. This adds var/sprint_dir to track dir that increments with sprinted_tiles++, which lets us check at the end. Fixes the issue.
https://github.com/user-attachments/assets/348e8939-1b5d-454b-8846-08930fc5735c

Fixes omni-run consequence of last-step dir change supercharge

---

code/modules/roguetown/roguejobs/tailor/dyer.dm

Someone was being naughty and spamming down invincible dye stations that were not able to be destroyed, because of a runtime of integrity reaching 0 while Inserted was null. This fixes that runtime and lets dye stations be destroyed normally.
No more invincible non-crossable dye machines

Fixes runtime in dye station destruction causing invincible dye stations

---

code/modules/antagonists/roguetown/villain/zombie/remove_rot.dm

Wild barber surgeons in the brush were taking dead ambush carbon skeletons, using the cautery on their chest to invoke cure_rot, spawning the skeletons a flesh suit, then butchering the flesh body for meat. This fixes that.
You can still do that with a Pestran miracle if you like though!
Soul removal.

Prevents surgery cauterization spawning flesh for carbon skeletons

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm

Xylix adventuring Paladins weren't spawning with a psicross, which meant no abrogation. This gives them a random psicross.
Let's go gambling

Randomizes xylix adv paladin psicross

---

code/game/objects/shapeshift_holder.dm

Vampire powers meant that VLs got a free full heal out of their escape shapeshift, if their simplemob took no damage in the escape. Which is redundant since VLs have blood point heal anyhow. Anyhow, it trickled into Witch zad, which is not intended. This removes that.
It's dangerous being a zad

Removes full heal from shapeshift restore damage transfer

---

_maps/map_files/dun_manor/dun_manor.dmm

Spare key was still left mapped in from when mercenaries bunked in the inn. Now that they have a guild, this key shouldn't be here anymore.

Removes mercenary key from inn's basement spare keys

---

modular/code/modules/living/emote.dm

Subtle emotes were hitting a hard return false due to restraint_check. Removes that, letting people subtle emote while restrained.

Removes restraint_check define from subtle emote

---

_maps/map_files/dun_manor/dun_manor.dmm

Two turfs mapped here meant a dirt tile with a wall sprite. Setting it just to a wall turf.

Fixes double-turfed wall at dun manor north gate

---

code/datums/stress/positive_events.dm
code/game/objects/lighting/rogue_fires.dm

Small change, basically adds a little buff of healing when you rest at a campfire, like a worse version of just sleeping, but you know, you can sit around a bonfire and heal while chatting with friends.
I like this better than being an actual dent brain and sticking your hand in the fire when interacting with it, getting 5 points of burn.
Another tiny way to top off superfluous damage, also gives campfires a little more use.
https://github.com/user-attachments/assets/00079007-5360-4c59-b467-9fdec30dc4d5

Learning not to touch fire (Campfire healing)

---

code/modules/farming/produce.dm

This change will add five units of water to both regular and poison Jacksberries (This comes out to 1 unit per bite)
Jacksberries are the "foraging" food and giving them a slight boost to hydration will allow players to get by for a bit longer in the wild without having to seek the main river.

Added water reagent to jacksberries

---

code/modules/jobs/job_types/roguetown/nobility/lady.dm
code/modules/jobs/job_types/roguetown/nobility/lord.dm

Adds the ability to grant/remove nobility to the Duke/Consort, but does not allow it to be removed if one has the nobility virtue (because they can be a noble from outside the Duke's perview)
Adds the ability to recruit wardens, much like the watchman, to the duke.
Adds the scaffolding of the mercenary recruitment, but doesn't give to anyone. Merc-master role in the future?
Just a little taste of what was lost for the HS players.

Ports some Hearthstone duke spells

---

modular_azurepeak/virtues/utility.dm

This makes the nighteyed virtue work by giving you the Dark Vision trait. I don't know why this was implemented like it was but it disappeared upon receiving an aheal. It's literally equivalent to the darkvision trait.
Tested it by taking the virtue and ahealing myself.
I lag a lot, okay?

Makes Night-eyed not disappear upon an aheal.

---

code/__DEFINES/traits.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/witch.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/surgery/_surgery_step.dm

Heresy should be a mark of those actively pursued by the Inquisition, not a label for the merely tolerated. To call the barely accepted 'heretics' waters down its meaning, heresy is hunted, not endured.

***Ready for merge*** Removes witches heretic status, gives them unique examine text

---

code/game/objects/structures/well.dm

Cuts the time it takes to fill a bucket from a well in half
Filling a barrel from a bucket via a well takes _fucking ages_ and doesn't really benefit RP. Wells make up the majority of water sources in the town, and yet people often bypass them for standing water, which fills buckets instantly. This retains that benefit, while also minimizing the amount of "sit-and-wait" time.

[Tested]Halves well filling time

---

code/modules/jobs/job_types/roguetown/nobility/knight.dm

Adds a visored sallet and a proper SCOM stone to the Royal Guard role, bringing it to parity with the Sergeant.
The Royal Guard is higher than the Sergeant role in importance to the Keep, below the Captain, and yet doesn't get a proper SCOM stone. As for the helmet choice, the reason is simple. All the other helmets in the selections are visored or have face protection built in, the fact that the sallet stands alone to be the only unvisored helmet doesn't make sense, especially since the Sergeant role gets the visored variant and it breaks the pattern of RG-loadout helms.

Minor RG role touch-up

---

modular_azurepeak/code/game/objects/structures/fartravel.dm

So this works for Wretch and any other class with limited slots. It just checks what class you were and lowers the total amount of slots currently occupied.
I have had several times where I have round-destroying bugs on my end that cannot be fixed except for respawning just TODAY. Two in a ROW. And the idea that you HAVE to stay in round as a wretch is harmful because you are taking other people's potential spot. If you far travel at round start you're screwing yourself and everyone else.

Allows class slots to open  back up.

---

code/modules/jobs/job_types/roguetown/garrison/villagechief.dm

Gives Town Elders the missing alchemy skill they didn't have yet.
Bug bad.

Fix | Town Elder alchemy oversight.

---

code/__DEFINES/misc.dm
code/modules/clothing/rogueclothes/hats.dm
code/modules/clothing/rogueclothes/mask.dm

**_What it does?_**
Re-adjust hair overlay layers for most hoods and masks, except the dessert raider one.
It only changes the way the hood looks when they are not being worn over the head, and also how masks look in general.
**_Why?_** 
So women (and long-haired folks) can actually WEAR HOODS without it being ugly and overlapped over the hair sprite, and it looks much better imo.
It's weird how hoods/masks sprites are OVER and not UNDER the hair.
Note that it inevitably changes the way hoods looks as they are being worn with helmets (It never looked good).

Hair Overlay Index Tweak [SUGGESTION]

---

code/datums/components/rotting.dm
code/modules/antagonists/roguetown/villain/zombie/remove_rot.dm

The issue was raised that bodies are turning deadite too quickly due to lowered ticklag. Also, upon inspection, I spotted the rot modularization lost the feature of pre-emptively "cleaning" the rot out of a corpse to reset the deadite timer. This bumps the rot time up to 5 minutes and also shuffles body cleaning / rot reset before the rot_removal FALSE return, which will let surgeons keep the rot at bay like it used to be.
I did run into a funny bug where I miracle cure-rotted someone immediately as they rotted, which left them in deadite skin. This should fix that collision, too.

Sets zombie rot to 5 minutes, shuffles rot remove to work preemptively

---

code/modules/antagonists/roguetown/villain/bandit.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/wretch.dm

- Allows for every Wretch subclass to write out their own bounty, like only Outlaws can currently do.
- Gives starting bounties to heretics and necromancers (also customizable)
- Does the same for bandits and also raises their bounty value to a range that's double that of wretches, it was set to a flat 80 mammon bounty for some reason. They're big bads, they should have big bounties.
Lets people roleplay whatever crimes they want. Maybe the poacher class doesn't want to be just known for poaching. Maybe they insulted a noble. Maybe they consorted with heretics. Also encourages heretics/necromancers to actually be naughty since now they have bounties.

Custom bounties + bounties changes

---

modular_hearthstone/code/modules/spells/roguetown/wizard.dm

For the message spell, this change makes it no longer need you to type in the exact case sensitive name of who you are trying to message, only pick their name from a list. The list should contain only names of people who are in your mind.known_people.
If I have to manually type Hubbobbert Skrinklebonken of Grenzelfops one more time for this spell I may just krill myself.

Adds Message Spell Contact List

---

code/modules/admin/admin.dm
code/modules/admin/topic.dm

Neither the Debug verb 'Return to Lobby' nor the Player Panel command 'Send to Lobby' accounted for job slots, bounties, or 'known' status. This updates them to automatically account for and remove these things.
Admins no longer inadvertently freeze job slots when they send players back to lobby. Bounties won't get stuck uncompleted either.

Updates Admin Send to Lobby Tools

---

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/herald.dm
roguetown.dme

-Is a towner class that can make announcements in the tavern, same way that duke/priest can.
-This requires them to be still and interrupted for a while.
-Has the mage's message spell.
-Can only be 1.

Adds herald towner

---

code/modules/clothing/rogueclothes/mask.dm

Ritualists are now neutered for 30 minutes after being excidium'd. No longer able to use a ritual to get out of their mask, or do any other Silly rituals:tm: in the future.
No more free mask escapes.

Excidium masks now apply rites expended to ritualists

---

code/__DEFINES/misc.dm

Adjusts the arm marking layer to below armor and shirts. This was previously above them, so it was visible through armor.
look man it's just stupid

Stops arm markings from showing up through armor and shirts.

---

code/modules/roguetown/roguemachine/scomm.dm

Wraps the garrison SCOM messages in a red html color span, allowing for differentiation of things sent on general or garrison frequency. Unfortunately this causes the chat draw on screen to lose the speaker's voice color, but, that information is still available in the name that prints in the side bar. 
SCOMs probably need their procs revisited if there's anything more complicated done to them, but hopefully this is a good bandaid until then.

Wraps garrison SCOM line in red for easier identification

---

code/game/objects/items/devices/flashlight.dm
code/modules/jobs/job_types/roguetown/adventurer/wretch.dm

Wretches spawn in some very dark places, so this gives them a prelit lamptern they can use to see around.
Puts the lamptern in the satchel so there's no collision with weapons spawning in hands.
Edit: Attempts to fix deserter satchel eater, too. 
https://www.youtube.com/watch?v=zng5kRle4FA

Adds prelit lantern, gives it to wretches

---

code/controllers/subsystem/ai_controller.dm
code/modules/spells/roguetown/acolyte/dendor.dm

* Reverts a portion of ai_controller changes because posessing an animal or shapeshifting into one as a Druid doesn't overwrite AI control. will look at why later, it's late

small ai_controller revert

---

code/game/area/roguetownareas.dm
code/modules/roguetown/roguejobs/gravedigger/hole.dm

Simple fix that makes it so areas can prevent digging into them from above. Until now the fix seemed to have been "put some undiggable turfs on top" so this should free up some mapping real estate.
Marks two areas (the orc ruins and the labyrinth of the ten) as protected.
Right now you can simply dig into loot-filled dungeons, skipping every single mob on the way there. This fixes that. Frees up some space that was reserved for cheese protection, as well.

Shovel Cheese Prevention: lets mappers protect areas against digging

---

code/game/objects/items/rogueweapons/melee/swords.dm
code/modules/cargo/packsrogue/Sellsword.dm
code/modules/cargo/packsrogue/weapons.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm

Alters the classification and utility of the shamshir to reflect the sword it should actually be.
The current shamshir is incredibly misleading. The description states it is a 'deadly one handed sword' yet, in the code, it is a subtype of longsword and is meant to be two-handed. This goes against the power fantasy of all of the classes who use it, as well as the logic of the weapon itself.
I have based the new statline off of the sabre, because these two weapons are very similar and fulfil a similar niche in terms of power fantasy. In order to make them unique, however, the shamshir retains 2 more force than the sabre with one less defence, to reflect a heavier blade but less hand protection.
_A sabre on top, shamshir on bottom. Very similar swords. A shamshir and longsword? Not so much._ …

Desert Rider/Naledi Sword Fix

---

_maps/map_files/dun_manor/dun_manor.dmm

Takes the cooling table and puts it in a cubby in the town wall between the farm and the inn's back garden. Puts in some shutters on the inn side to close in the case of defense.
Do you remember the little window between botany and the kitchen hey that's what this is
Offloading some of the inn's gardening to the soilsons gives the farm some purpose, and disincentivizes the need of tapsters being 2nd-rate soilsons.

Adds cooling table of friendship between farm and inn

---

code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm

Gives the inquisitor's test faith/extract confession verbs a small do_mob timer - and makes both of them require a large psycross structure nearby.
Paired with a few other small clean-up related tweaks like changing mentions of 'the ten' to 'the allfather' to better fit the inquisitor thematically and clearer visible messages/emotes to better telegraph the entire process.
More sanity checks to ensure inquisitors aren't faith-checking people on the spot with little to no roleplay. This should require them to actually bring someone to the church, or at least to a psycross structure. There's a good few around the city - so it's not exactly a huge ask.
Also this just looks a lot cooler with the do_mob timer and the extra visible messages/emotes.

Test faith verb clean-up

---

_maps/map_files/dun_manor/dun_manor.dmm
code/game/area/roguetownareas.dm
code/modules/roguetown/roguemachine/bathmaster.dm

Adds in vault gain for the Bathmaster's vault. This income goes directly into the BRASSFACE. Having double(30%) the interest rate of the steward's vault due to the Bmaster having less easy access to the resources to fill it.  Commissioned by Cleric, and the finale of a 3 part Bathmaster Sweet stuff package <3
Should hopefully encourage Bathmaster's to have more mammon-power to start stuff up. Further reinforcing their role as a sort of underground master.

Bathmaster Vault[PT3 Bathmaster stuff]

---

_maps/templates/smalldungeons.dm
code/game/objects/items/granters.dm

Adds a bunch of new spell scrolls that can spawn in dungeons because loot variety is good.
More variety in spell scrolls found in dungeons instead of the same 6 spells spawning in every dungeon with spell scroll spawners. Randomized loot is good.
Also made greater fireball scrolls a lot rarer - they were way too common.

Adjusts spell scroll dungeon loot table

---

_maps/map_files/dun_manor/azure_coast.dmm
_maps/map_files/dun_manor/azure_forest.dmm
_maps/map_files/dun_manor/dun_manor.dmm
code/modules/admin/admin_verbs.dm
code/modules/clothing/rogueclothes/mask.dm
code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/wanted.dm

- Adds a 'remove bounty' verb for admins.
- Fixes some grammatical errors in the Excidium.
- Adds a few more Excidium stations around the map outside of the city to better enable antagonistic characters to potentially use the bounty system.
- Fixes the penance timer being 10 minutes longer than intended due to an oversight. The 100 mammon bounty minimum meant the timer minimum was actually 40 minutes instead of the intended 30.
Fixes for the Excidium along with better tools for admins to curb people potentially abusing the system.

Excidium fixes

---

code/game/objects/items/rogueweapons/melee/blunt.dm

Updates Cudgel sizes to be _proper_, blunt-enjoyers rejoice.
The Cudgel has always been a "Secondary" weapon, intended to be stowed and used if you wish (usually) not kill someone.
This PR makes the "stubby little clubs" into "stubby little clubs" for your inventory. 
(As they were intended)
-Originally, such clubs were INVENTORY hogs, taking up half your satchel. (Shameful when compared to arguably larger weapons) Now they can sit all nice and neat among your other small bits of gear. The Watchman's best friend just got a whole lot better.

Cudgel size change
