code/modules/client/preferences_customizers.dm

Reverts GeneralPantsuIsBadAtCoding/Azure-Peak#4

Revert "Fix"

---

code/modules/client/preferences.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/human_defines.dm
code/modules/mob/living/carbon/human/human_topic.dm

Adds flavortext and OOC notes to character creation and makes them show up in the headshot popup, and renames some things to make sense for it (i.e. "view headshot" is now "Examine closer".) Headshots were resized and the headshot window was rearranged to, I believe, look a little nicer and cleaner than it does on Hearthstone. The "Examine closer" option SHOULD appear whether you have only a headshot, only flavortext, or both, but not with only OOC notes (which shouldn't be relevant anyways as characters should have at least one of the former period.)
And so, to demonstrate what it looks like, for Azure Peak's very first character profile, meet Corbus.
I really, really hope this works correctly. I am not an experienced coder - please check to make sure things aren't horrendously broken. I …

Adds flavortext and OOC notes + Introduces my OC, Corbus

---

code/modules/antagonists/roguetown/villain/vampire.dm
code/modules/antagonists/roguetown/villain/vampirelord.dm

title. vamp lord still gets own zoned by the sun; someone else needs to give them the disguise ability idk how to do that.
You now no longer need to kill to survive. Yippie!

Disables passive vitae drain for vampires and the sun no longer spurns lesser vampires

---

code/modules/jobs/job_types/roguetown/church/mortician.dm
code/modules/jobs/job_types/roguetown/church/priest.dm
code/modules/jobs/job_types/roguetown/church/puritan.dm
code/modules/jobs/job_types/roguetown/church/templar.dm
code/modules/jobs/job_types/roguetown/courtier/councillor.dm
code/modules/jobs/job_types/roguetown/courtier/magician.dm
code/modules/jobs/job_types/roguetown/courtier/physician.dm
code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
code/modules/jobs/job_types/roguetown/garrison/dungeoneer.dm
code/modules/jobs/job_types/roguetown/garrison/gatemaster.dm
code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
code/modules/jobs/job_types/roguetown/garrison/sheriff.dm
code/modules/jobs/job_types/roguetown/garrison/townguard.dm
code/modules/jobs/job_types/roguetown/garrison/veteran.dm
code/modules/jobs/job_types/roguetown/garrison/villagechief.dm
code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
code/modules/jobs/job_types/roguetown/nobility/captain.dm
code/modules/jobs/job_types/roguetown/nobility/hand.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm
code/modules/jobs/job_types/roguetown/nobility/lady.dm
code/modules/jobs/job_types/roguetown/nobility/lord.dm
code/modules/jobs/job_types/roguetown/nobility/steward.dm
code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm
code/modules/jobs/job_types/roguetown/yeomen/merchant.dm

All roles that used to have a positive pq requirement now do not.
We have a whitelist that should be at least somewhat better maintained than alternative servers, making PQ redundant and a waste of time for everyone.
If someone is acting poorly in a role, simply remove them from the game. It's that simple.

Changes PQ requirement on all roles that used to have a positive requirement to 0

---

code/__DEFINES/preferences.dm
code/__HELPERS/mobs.dm
code/__HELPERS/pronouns.dm
code/datums/emotes.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/carbon/human/human_defines.dm
code/modules/mob/living/living_descriptors.dm

There's your fucking femboys.
Also adds pronouns.

Femboy Update

---

code/datums/migrants/migrant_role.dm
code/modules/jobs/job_types/roguetown/adventurer/adventurer.dm
code/modules/jobs/job_types/roguetown/adventurer/pilgrim.dm

You get the max number of available classes as pilgrim and adventurer.

Maxes out pilgrim and adventurer choices

---

code/datums/character_flaw/addiction.dm

Removes the stat malus from addictions.

No addiction malus

---

code/modules/client/preferences_savefile.dm

Makes flavour text and OOC notes actually save LOL.

Fixes flavour text and OOC notes saving

---

code/modules/jobs/job_types/_job.dm

Makes all roles have the potential for nonstandard genital distribution, instead of just the bourgeois.
As it should be.

Democratisation of Gock

---

code/game/objects/structures/fluff.dm

Another port PR, this time of Stonekeep's PR
I don't normally plan to port Stonekeep's work, out of respect the devs on there, but this one was requested and it's just easier to do this as it's just fluff. All this does is re-factor marriage to be a bit neater and allows for marriage regardless of sex, including assigning last name of character to other character properly.
Fluff marriage stuff.

Ports Changes to Marriage

---

code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
code/modules/jobs/job_types/roguetown/garrison/townguard.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm

Fixes the skill-stacking error and removes the forced female hairstyle due to more than those hairstyles existing. Pre-emptatively fixed watch and men-at-arms skill stacking too.
Forgor to port the fixes as well as the basics.

Fixes Guard Skill Stacks + Hairstyle Issue

---

code/modules/mob/living/carbon/human/species_types/furry/akula.dm
code/modules/mob/living/carbon/human/species_types/furry/anthromorph.dm
code/modules/mob/living/carbon/human/species_types/furry/anthromorphsmall.dm
code/modules/mob/living/carbon/human/species_types/furry/dracon.dm
code/modules/mob/living/carbon/human/species_types/furry/kobold.dm
code/modules/mob/living/carbon/human/species_types/furry/lizardfolk.dm
code/modules/mob/living/carbon/human/species_types/furry/lupian.dm
code/modules/mob/living/carbon/human/species_types/furry/moth.dm
code/modules/mob/living/carbon/human/species_types/furry/tabaxi.dm
code/modules/mob/living/carbon/human/species_types/furry/vulpkanin.dm
code/modules/mob/living/carbon/human/species_types/roguetown/goblin/goblinp.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halforc.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/werewolf.dm

Comments out the organs being hardcoded into species other than humans.
Bugs are bad

Fixes Certain species having all genitals at once.

---

code/datums/character_flaw/_character_flaw.dm
code/datums/character_flaw/addiction.dm
code/game/objects/structures/fluff.dm
code/modules/paperwork/rogue.dm

Something overwrote these changes. Updated my local files to make everything up to date, and re-implemented them. 
Changes widely requested by the community and administration.

RE-re-adds Devout Follower and Colorblind

---

code/modules/mob/living/carbon/life.dm

Makes it so that any armour or helmet with more protection than leather blocks you from sleeping when worn.

No More Full-Plate Pajamas

---

code/modules/mob/living/emote.dm

Either I forgot this line or something overwrote it. We really need to get our shit together. Makes Devout Follower as an addiction _possible_ to satiate through prayers.

RE-re-reimplements Devout Follower

---

code/controllers/subsystem/ticker.dm
code/modules/jobs/job_types/roguetown/church/priest.dm
code/modules/mob/living/emote.dm
code/modules/roguetown/roguemachine/throne.dm

Somebody spawned as monarch and the Throne didn't recognize them - they had to be recorinated to make it work. I think this is why. Also, we're de-Rockhilling Rockhill, so while I'm at it...
bugs can suck me off good n hard tru my jorts

Hopefully, fixes latejoin monarchs (???) - makes Throne of Rockhill the Throne of Azure Peak

---

code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/human_topic.dm

Should hopefully fix unclickable examines when you don't have a headshot, neatly displaying your name with your flavortext OR headshot regardless of which one you have, along with any OOC notes.
Working functions good.

Fixes headshot/FT popup

---

code/modules/client/preferences.dm

Makes it so that uhhhhhhhh Removes Character Randomisation When Changing Bodytype.
Because why. It still gives you the """"""appropriate"""""" genitalia when you swap, though.

Removes Character Randomisation When Changing Bodytype

---

code/modules/clothing/rogueclothes/armor.dm

Allows Changing Brigandine Colours

---

code/game/gamemodes/roguetown/roguetown.dm

Antagonists need at least 10 players readied to roll.
Also disables maniac. Fuck maniac all my homies hate maniac.

Adds Population Minimum To Rolling Antags

---

code/modules/mob/living/simple_animal/friendly/farm_animals.dm

milking an animal used to occur when you cancel the progress, this fixes it

fixed milking process

---

modular_azurepeak/code/game/objects/structures/fartravel.dm

You no longer get blocked by fart travel tiles. Any rumors that they make a fart sound when you use them is rebel propaganda.

fixes fart travel

---

code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm

FIXES FOOTKNIGHTS AND MEN AT ARMS SPAWNING WITH STACKING LEGENDARY SKILLS.
Swaps a little bit of the armor between men at arms and foot knights, because - did you know chain coifs are actually better neck protection than gorgets? Why did men at arms, part of whose specialization is specifically in crossbows, get better armor than the knights?
Gives knights steel booties as it's kind of just a source of pointless tedium, but also nerfs their armor SOMEWHAT. Before, they used the "steel cuirass", which was actually a very high-durability medium-weight armor which protects the chest - now, MOST of them get "coat of arms", which are actually less durability, but makes proper use of knights' heavy armor trait, and protects slightly more.
Heavy knights get a proper bervor and half-plate to make …

fixes knights

---

code/controllers/subsystem/vote.dm
code/game/gamemodes/extended/extended.dm
code/game/gamemodes/game_mode.dm
code/game/gamemodes/roguetown/roguetown.dm

Adds Round End Votes to Extended

---

code/game/objects/items/rogueitems/keyrings.dm

Lists a keyring's keys on examine

---

code/controllers/subsystem/ticker.dm
code/game/objects/structures/roguetown/gate.dm

if theres less than 10 people playing then thee gates open up so that people dont have 2 start scaling walls and shit to actually get to roleplay with the only other person in the seever

Makes Gates Start Open If It's Lowpop

---

code/modules/jobs/job_types/roguetown/nobility/captain.dm

gives the guard captain a metal tower shield, and increases their mace skill from 3 to 4 so they're actually on the same level as royal guards
also removes the part that messes with your hair if you're female. i love women btw

Puts Guard Captains In Line With Royal Guards

---

code/game/objects/items/rogueitems/natural.dm
code/game/objects/items/rogueitems/natural/clothfibersthorn.dm
code/game/objects/items/rogueitems/natural/wood.dm

NOBODY should say what the word for this is. It's not funny. It's not okay. See something, say something. 
Not having to drop your bundle of sticks every time you create one is good.

Makes twig stacking smoother

---

_maps/map_files/rockhill/rockhill.dmm
code/modules/clothing/rogueclothes/hats.dm
code/modules/jobs/job_types/roguetown/church/monk.dm
code/modules/roguetown/roguecrafting/weaving.dm

this makes it so that you can't adjust nochoods. they dont have icons for that.

fixes noc hoods

---

code/game/objects/structures/roguetown/gate.dm

so umm instead of gates gibbing you. they just mangle you real bad now.
oh yeah did you know that the barred gates didnt actually do anything to you?? the only gates that actually could harm.. well, GIB you, were the heavy throne room gates. wacky code, right?!

Crushes You Cutely

---

code/_onclick/hud/ghost.dm
code/modules/mob/living/carbon/spirit/spirit.dm

You no longer have to take part in this sad excuse for a """""""minigame"""""". God I hate uninspired LFWB ripoffs so much. Unlike my LFWB recreations which are super soulful.
Anyway you get a toll coin after a whopping 10 seconds of loitering.
What do you mean I could have just mapped in a pile of one hundred toll coins near the boatman....?

Makes The Underworld Optional

---

code/game/objects/items/rogueweapons/shields.dm

You get a prompt to confirm whether you want to keep your shield heraldry. You also have to right click shields to set their heraldry now.

Confirming Shield Heraldry

---

code/modules/roguetown/roguemachine/scomm.dm

SCOM uses Monarch instead of King now.

Gender Neutral SCOM

---

code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm

so that u  cant keep charging into a werewolf to stun them LOL

Gives Werewolves Stats

---

code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm

Oopsie doopsie, that's the wrong name!

Fixes the Frogslop helm recipe

---

code/datums/sexcon.dm
code/datums/sexcon/sexcon_helpers.dm
code/modules/client/customizer/customizers/organ/genitals.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/surgery/organs/feature_organs/genitals.dm
code/modules/surgery/organs/organ_dna/_organ_dna.dm

You can set fertility and virility for your pussay and bawls. It determines whether impregnation is possible.

Fertility & Verility Toggles

---

code/_onclick/other_mobs.dm
code/game/objects/structures/ladders.dm
code/game/objects/structures/stairs.dm
code/modules/mob/living/carbon/carbon_defense.dm
code/modules/mob/living/carbon/carbon_defines.dm
code/modules/mob/living/grabbing.dm
code/modules/mob/living/living.dm

Brings together a bunch of merged grabbing tweaks and fixes from Ratwood into one PR. These include:
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/588
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/627
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/631
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/669
Keeping up to date with Ratwood is good and I'm going on a porting spree.

A variety of grab tweaks and fixes compiled from Ratwood.

---

_maps/dun_manor.json

chat i might be stupid, i forgot to hit save
probably nothing bad would happen if it was kept in other than maybe having lava dumped on your head out in the forest but yknow

dun manor json hotfix

---

_maps/map_files/rockhill/rockhill.dmm

Forgor. Church has the new surgeon's bags.

Maps in Surgeon's Bags

---

code/game/turfs/closed/wall/roguewalls.dm

Allows Climbing All Walls

---

code/modules/roguetown/roguecrafting/leather.dm

fixes lighht tear cloak tcrafitng

Fixes Light Bearcloak Crafting

---

code/controllers/subsystem/ticker.dm

Can be longer if requested, I just wanted to get the code out there and on the table for headmins to make any further requests they like. DO NOT merge until like 3 hours from now when I've successfully tested this as it's kind of a major important server function. Just making people aware rounds are being considered so if anyone wants to discuss the change, we can while I'm testing that this is what does it.
We're an RP server and rounds should be slightly more drawn-out. Requested by many. Makes it easier to time our organized rounds.

Changes end round vote to 3 hours

---

code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm

forgot about this one
consistency

weapon smith pq req to zero

---

code/modules/jobs/job_types/roguetown/garrison/sheriff.dm
code/modules/jobs/job_types/roguetown/nobility/captain.dm

Allows all ages on sheriff and captain. Sheriff, because... why not? And Guard Captain because they are literally a knight.
If the knights can be young, so should these.
Maybe people will play these roles now...

Allows all ages on sheriff and guard captain

---

code/modules/mob/living/carbon/human/human_topic.dm
code/modules/mob/say.dm

uhhh you get big emotes by pressing , on your keyboard. at least on mine

Newlines for Flavor Text, OOC Notes, and Big Emotes

---

code/modules/client/preferences_savefile.dm
code/modules/client/preferences_toggles.dm
code/modules/client/verbs/ooc.dm

Lobby music, screen shake, and the ERP menu preferences now get saved.

Options Tab Preference Saving

---

code/__DEFINES/preferences.dm
code/datums/emotes.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/living_defines.dm

You can select your voice pitch in char creation now. It's no longer affected by strength.

Adds Selectable Voice Pitch

---

code/datums/sexcon/sexcon.dm

Ummm you just moan now. You can cry and whimper manually if it feels appropriate.

Removes Whimpering/Crying From Roughplay

---

code/modules/jobs/job_types/roguetown/peasants/nightman.dm

Gives Nightmaster Apprentice Alchemy

---

code/modules/mob/living/carbon/human/species_types/roguetown/other/tiefling.dm

This adds anthro horns to tieflings. There are a tiny handful of odd choices, but they're not too impossible, and overall all the horns look great on tieflings.
Reasonable character customization good. Handlebars, good...

Gettin Horny: Adds horn customization to tieflings

---

code/modules/farming/crafting_recipes.dm
code/modules/paperwork/paper.dm
code/modules/paperwork/rogue.dm

Rolling zigs needs parchment now.
Parchments and scrolls had their max text limit increased.
You can cut a scroll into two parchments with a bladed implement.
I love you.

Paper Changes

---

code/modules/clothing/rogueclothes/robes.dm

they only show off your gock and galls if radical

Stops Eoran Robes From Showing Your Coochie

---

_maps/map_files/dun_manor/azure_forest.dmm

i love the black parade by mcr

the hill of golgotha - new smol explorable area

---

code/datums/migrants/migrant_waves/fablefield roles.dm
code/datums/migrants/migrant_waves/heartfelt roles.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelt.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelthand.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/witchhunter.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/minstrel.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/noble.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
code/modules/jobs/job_types/roguetown/church/templar.dm
code/modules/jobs/job_types/roguetown/courtier/physician.dm
code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
code/modules/jobs/job_types/roguetown/garrison/veteran.dm
code/modules/jobs/job_types/roguetown/yeomen/blacksmith.dm

I pointed out verminvolk cant be physicians. Ended up noticing theres a LOT of odd jobs they cant be. This PR removes every example of  race restriction from every single job, Idk if theres a tangible reason for any of these to be restricted. If there is suggest away.  But come on now. I can be a funny short Bailiff, Councillor, Guard Captain, so on? But not a doctor?
Consistency, Short fluffer funny. More short fluffer = dopamine

Removes the last scraps of race restriction

---

code/modules/roguetown/roguestock/stockpile.dm

Fixes the stockpile im so sorry

Stockpile Fix

---

sound/music/credits.txt

Relevation 6 12-17:
When he opened the sixth seal, I looked, and behold, there was a great earthquake, and the sun became black as sackcloth, the full moon became like blood, and the stars of the sky fell to the earth as the fig tree sheds its winter fruit when shaken by a gale. The sky vanished like a scroll that is being rolled up, and every mountain and island was removed from its place. Then the kings of the earth and the great ones and the generals and the rich and the powerful, and everyone, slave and free, hid themselves in the caves and among the rocks of the mountains, calling to the mountains and rocks, “Fall on us and hide us from the face of him who is seated on the throne, and from the wrath of the Lamb, for the great day of their wrath has come, and who can stand?
1 …

Improves the bathhouse theme

---

code/datums/skills/combat.dm
code/datums/skills/craft.dm
code/datums/skills/labor.dm
code/datums/skills/misc.dm

every skill that is levelable now gets very lovely dream messages
thank you @oblyvious on the discord for writing all these

Dream Messages For All Skills

---

_maps/map_files/dun_manor/azure_coast.dmm

also makes more of the map minable
It kind of sucked. It still sucks but its an acceptable amount. When I'm not feeling lazy I'll redo it completely.

Updates the coastal village

---

modular/Neu_Food/code/cooked/NeuFood_pies.dm
modular/Neu_Food/code/raw/NeuFood_processed.dm

Salo is no longer an infinite source of nutrition that makes you vomit.
Also fixes a minor typographical mistake.

Fixes Salo

---

modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/gethsmane.dm

i hate roguetown
mobs dont attack eaqch other = good

don't talk to me

---

sound/music/credits.txt

Haha funny meme.
But no. This kind of shit only hurts us as a HRP server, for the love of fucking god.

Revert "Improves the bathhouse theme"

---

sound/music/credits.txt

Less memey but gets the tone across.
It has an abrupt start butuhmm lol.
https://github.com/user-attachments/assets/e315a4e8-ae6e-4926-9181-af559afd8657
Video Game Music?? No... Music.

New new bath music track

---

code/modules/roguetown/roguemachine/ATM.dm
code/modules/roguetown/roguemachine/stockpile.dm

Too meister becaiuse nooo racism

Renames Shylocks

---

code/game/objects/structures/fluff.dm
code/modules/roguetown/roguemachine/scomm.dm

mathhios eats a bunch of things now like riddless of steel and the big crown.
can still summon anyother crown but damn how u maange to lose the whole ass crown to buncha crummy badnits
scomstones have their value upped from likE. 35 up to 250. emerald chokers were 200 i ncomparison

hungy hungy matrthios

---

_maps/map_files/dun_manor/dun_manor.dmm

adds a plough to the farm

---

modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/dragon.dm
roguetown.dme

These dragons have melee attack AI and growling sounds, but if you spawn one as an admin, you still have to shift it's sprite to the left like 30 or 40 pixels, and it needs to get hurt in order for sounds to start. If it uses too many spells, it stops being able to use them properly after a while. Why? I DON'T KNOW. But otherwise, they work, and have AI!
Fantasy staple good. Base "ash drakes" which fuck up the game and too-brutally murderize people baaaad.

Adds less janky but still slightly janky dragons

---

code/modules/farming/trash.dm
code/modules/roguetown/roguejobs/fisher/leeches.dm
code/modules/roguetown/roguejobs/fisher/rod.dm

Fixes leeches from sucking you across the map even if you remove them. Oops.
Increases bait power of apple cores and leeches.
Makes fishing more descriptive in that you need to **move away** to pull the fish in.

Fixes Leeches

---

modular_azurepeak/code/game/area/areas.dm

'why isn't the first time text popping up' yeah ok
things working is good actually

actual gethsmane fix

---

modular_azurepeak/code/modules/mob/living/simple_animal/rogue/creacher/dragon.dm

Bunch of fixes to dragons. Makes them not die to stupid things that a powerful dragon shouldn't die to, massively improves their sound design.
People like the dragon, but it's a little wimpy because I rushed it. Let's fix that.

Dragon fixes, notably sounds

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/barbarian.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/heartfelt.dm
code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm
code/modules/jobs/job_types/roguetown/courtier/jester.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm

yep
effected roles:
jester
barbarian
desert rider merc
crusader
also lord of heartfelt isnt a virgin anymore
your character is actually what you make it, good!

Removes some residual forced character customization from various roles

---

code/modules/jobs/job_types/roguetown/adventurer/types/special/nakedandafraid.dm
code/modules/jobs/job_types/roguetown/adventurer/types/special/torso.dm

Nudist is now an actual adventurer class instead of being a challenge class that forces you to be naked.
You have some rebalanced skills, however the stat buffs are slightly worse and the strength bonus is now speed instead.
You also have a belt, sandals, and spawn with a knife.
Torso was disabled because it is exclusively a gamey meme class from blackstone. There is really no good roleplay to be had with it, it only exists to be heehee funny limbless man with legendary skills.
Consistency.

Nudist changes + disables torso

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/blackoak.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/underdweller.dm

see above. formatting and other errors
things working right = good

fixes racial merc classes!!!

---

code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
code/modules/mob/living/carbon/human/species_types/roguetown/dwarf/dwarfm.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfs.dm
code/modules/mob/living/carbon/human/species_types/roguetown/human/humen.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halforc.dm

Reverts GeneralPantsuIsBadAtCoding/Azure-Peak#208

Revert "De-Chuddifies skin color selection"

---

code/__DEFINES/traits.dm
code/datums/gods/patrons/divine_pantheon.dm
code/game/turfs/open/water.dm

u can swim better now
technically this means you are now able to regen stamina if you have swimming 5 but this already happened with swimming 6 and nobody even has swimming 5
yeah

adds abyssor trait

---

code/modules/mob/living/carbon/human/life.dm

You now get triumphs on all gamemodes for sleeping each night.

Triumphs On Sleep

---

code/modules/mob/living/carbon/human/species_types/roguetown/roguetown_species.dm

Stops Strongdmm From Crashing

---

code/modules/clothing/rogueclothes/armor.dm
code/modules/mob/living/carbon/human/species.dm
modular/code/game/objects/items/items.dm
roguetown.dme

Armours have both an equip and unequip delay now.
Most are at 2.5 seconds.
Half-plate is at 4 seconds.
Cuirasses and scalemail at 4 seconds.
Full plate is at 12 seconds. 3 seconds to equip by others, 6 seconds to strip.

Equip/Unequip Delay for Armour

---

code/modules/jobs/job_types/roguetown/youngfolk/shophand.dm

prince got buffed, shoppy now
used to be youngfolk. still worse than adventurers/townies in most ways still. but makes it so that they are at least usable lmao

buffs shophand

---

code/modules/antagonists/roguetown/villain/vampire.dm
code/modules/mob/living/carbon/rogfatstam.dm

So that vampires don't get fuckin winded so easily.
Also restores vamp's stamina when using celerity and fortitude.

NOSLEEP Trait removes fatigue

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/barbarian.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/sentinel.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/treasurehunter.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/witchhunter.dm
code/modules/jobs/job_types/roguetown/church/puritan.dm

Adds ravager as a barbarian subclass. They're good at wrestling. They also got nasty chompers.
Witch hunter, treasure hunter, and sentinel have been rendered always choosable instead of a random roll.
Gave inquisitor one tiny weeny lil speed point because he gets a rapier and it's kinda dependant on that stat.

Adventurer Role Additions

---

code/game/objects/structures/bedsheet_bin.dm

Fixes Bedsheet Layering

---

code/_globalvars/logging.dm
code/controllers/subsystem/migrants.dm
code/modules/client/preferences.dm
code/modules/client/roundendmanifest.dm
code/modules/jobs/job_types/_job.dm

Lobby Manifest

---

code/datums/character_flaw/_character_flaw.dm
code/modules/client/preferences.dm

Re-enables Bad Vision Flaw

---

code/modules/clothing/rogueclothes/armor.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm

Ports the bard arcanist class from Hearthstone. They get light magic.

Arcanist Bard Class

---

code/modules/clothing/rogueclothes/cloaks.dm

they used 2 make ur arms invisible.. no logner.. suns out guns out woahh..

Fixes Tabard Sleeves

---

modular_hearthstone/code/modules/spells/roguetown/wizard.dm

this is a possible fix to apostrophes and such becoming a garbled mess inside Messages
i cant test this locally with a dual client setup so im praying it at the minimum does not break even more

possible message fix

---

code/modules/spells/roguetown/acolyte/general.dm

adds conditional bonuses to lesser miracle heals

---

code/modules/roguetown/roguejobs/fisher/leeches.dm

cheeles now transfer blood at 5 units at a time, up from 2

Increases Cheele Blood Throughput

---

code/game/objects/structures/mineral_doors.dm

using keys on a door will now unlock on LMB, and lock on RMB.

Doors Lock on RMB

---

code/modules/client/preferences.dm
code/modules/mob/dead/new_player/new_player.dm

You can go to the underworld in the spirit tab to respawn.

Adds Observe Button

---

code/datums/character_flaw/_character_flaw.dm
code/datums/stress/negative_events.dm

Adds Clingy & Isolationist Flaws

---

roguetown.dme

OOPS THIS IS FOR THE ALCOHOLS THING

I Forgot The Dme

---

code/modules/jobs/job_types/roguetown/courtier/butler.dm

Buffs butler utility skills to actually do butler stuff and comments out the weird slut-wear that specifically Eoran female butlers  got. As funny as it is, do kinda need to curtail the 'Eoran is the slut god' stuff, also it's weird as a leadership keep role.

Butler/Maid Stuff

---

modular_hearthstone/code/modules/spells/roguetown/wizard.dm

im stupid and forgot to rename a condition after testing OOPS

fixes hitting cancel in the spell preview

---

_maps/map_files/dun_manor/azure_forest.dmm
_maps/map_files/dun_manor/dun_manor.dmm
code/modules/clothing/rogueclothes/cloaks.dm
code/modules/jobs/job_types/roguetown/garrison/bogguard.dm

Don't merge yet, initial code for the Wardens, doing mapping next.

Wardens, ungoofed hopefully.

---

code/modules/clothing/rogueclothes/cloaks.dm
code/modules/roguetown/roguemachine/ATM.dm

Fixes Tabards AGAIN. Fixes Meisters AGAIN

---

code/datums/migrants/migrant_waves/heartfelt roles.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
code/modules/jobs/job_types/roguetown/church/monk.dm
code/modules/jobs/job_types/roguetown/church/priest.dm
code/modules/jobs/job_types/roguetown/church/templar.dm
code/modules/jobs/job_types/roguetown/yeomen/archivist.dm

I flirt with all of the church and nerd-keep roles. I'll take this hit this one time even if they're dudes it ok.
Virginity is a silly thing that just serves to punish players with a turnip loss and lets vampires double-dip on vitae gain.
And I fucking hate vampires.

/me erps u

---

code/modules/jobs/jobs.dm

I feel like we are getting a PR going "uwaaaah sorry, fixing late join" everytime now, uwah
I hate this file.
I even tested this but I think I renamed the title after, whee
howdy pardner

Fixes neo-sheriff late joins

---

code/game/objects/items/rogueitems/keyrings.dm
code/modules/jobs/job_types/roguetown/nobility/lord.dm

and gives them a nice keyring so they're not locked out of their own place..

Makes Monarch Latejoinable

---

code/modules/mob/dead/dead.dm

Ports from Hearthstone the concept of being able to close a lobby as done by someone extremely attractive and cute

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm
code/modules/jobs/job_types/roguetown/church/templar.dm
code/modules/jobs/job_types/roguetown/roguetown.dm
modular_azurepeak/code/datums/loadout.dm

Knight errants get a cuirass instead of halfplate. Bervor replaced with gorgets.
Black knights got their blacksteel stuff replaced with black-coloured armour of the same type.
Removes more chudcode.
Fixes rider cloaks in loadout.

Knight Errant Changes

---

_maps/map_files/dun_manor/dun_manor.dmm
code/modules/roguetown/roguemachine/lottery.dm

also makes em a bit less punishingb
yeah

adds gambling machines to map

---

code/modules/roguetown/roguemachine/lottery.dm

fixes for gambler

---

code/game/objects/items/rogueitems/needle.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm
code/modules/spells/spell.dm
modular/Neu_Food/code/cooked/NeuFood_meals.dm

You can now refill needles even if they're missing less than 5 uses.
Half-Elves get the Elfish Language now too.
The additional stamina penalty for mages wearing armor they're not trained in has been doubled.
Fixes the broken peppermill - baked poultry interaction, also added some spacing.

Various Tweaks

---

code/game/objects/items/rogueitems/natural/wood.dm
code/game/objects/structures/roguetown/newtree.dm

Adds chopping noise when cutting log, small log & treebranch.
Immersion.

Chopping noise when cutting log, small log & treebranch

---

code/modules/roguetown/roguemachine/lottery.dm

oops.
seeing 'your tithe is 3.14159  mammons' is kinda dumb lol

lottery removing fractionals

---

code/modules/client/verbs/ooc.dm
code/modules/mob/living/stats.dm
modular_azurepeak/code/datums/loadout.dm
modular_azurepeak/statpacks/wildcard.dm

You no longer get random stats. We already have statpacks for it.
You want random stats anyway for a laugh? Fated statpack now has -2 and +2 ranges instead of -1 and +1.
Also adds leather vests to loadout mwah mwah.

NUKING STAT RANDOMISATION

---

code/modules/roguetown/roguejobs/cook/tools/grinding.dm
modular/Neu_Food/code/NeuFood.dm

Adds a way to get mineral salts from rocks, not as simple as simply grinding down rocks, but it makes gathering salts more viable for those that aren't miners or alchemists.
Process:
Use a millstone to grind a rock
Add water to the resulting minerals to prepare them for sifting
Use a cloth to sift the prepared minerals
Grind the resulting 'coarse salt' using the millstone to make regular salt
Makes it far more viable for cooks to get salt without needing to go mining specifically for salt-rocks or needing them to learn alchemy to make salt. Also adds coarse salt, which could be used for specific dishes that need larger grains of salt in the future

Mineral Salts

---

code/modules/jobs/job_types/roguetown/nobility/captain.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm

Change broke spawns, can't fix it while people are doing mapping, will at another date.

Revert knight names

---

code/modules/jobs/job_types/roguetown/courtier/physician.dm
code/modules/jobs/job_types/roguetown/garrison/bogguard.dm
code/modules/jobs/job_types/roguetown/youngfolk/apothecary.dm

Gives money to the medic jobs, also serf rings so they can actually hear people shouting out to get help rather than being forced to afk next to a scom.

Medic Money

---

code/game/objects/items/rogueitems/waterskin.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/cheesemaker.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lchef.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/rare/Lfish.dm
code/modules/jobs/job_types/roguetown/peasants/cook.dm
code/modules/mob/living/simple_animal/rogue/farm/goat.dm

ports: https://github.com/Darkrp-community/OpenKeep/pull/712 mostly intact, give or take a skill or two
don't read code? here's the important stuff:
**cheesemaker** gets improvements to their gear and skills, with the most important addition being a backpack full of cheesemaking stuff
**fishermen** get slightly improved gear and some stat or skill buffs
**cooks** get improved skills
**legendary cooks** get improved skills and gear
**legendary fishers** get improved skills and gear
**goats** get to eat berries now
also i edited the style of some of the lists because i was raised to write readable code and having to scroll sideways subsequently subsumes my will to live
i think it was karl marx who said, "The history of all hitherto existing roguetown servers is that no one plays any towne …

makes cheesemakers, cooks, and fishers more gooder

---

code/modules/jobs/job_types/roguetown/church/templar.dm

re-adds gambesons to templars that were lost in the shuffle around the monk subclass PR

templar gambeson

---

modular_azurepeak/statpacks/agile.dm
modular_azurepeak/statpacks/physical.dm

gives thuggish and muscular -2 speed. 
>join server
>50-70% of players running muscular 
>:dread:
they are only exceptionally powerful on classes that would already rather parry, so this shouldn't affect too much other than their speed, and i want to see how it is received. maybe people play something else than 1 stat pack?? hopefully??!!

extremely tentative first statpack changes

---

roguetown.dme

Wasn't sure I should be editing the dme file, but this is needed for the fertilizer recipe to actually work. Will make the fertilizer recipe actually craftable.

farming craft fix

---

code/modules/clothing/rogueclothes/rings.dm

Fixes the Signet Ring sprite, so it will show now.
Bug fix.

fixes the signet ring sprite

---

code/modules/mob/living/carbon/human/species_types/furry/tabaxi.dm

Slaps ears on Tabaxi; specifically cat (Small) and cat (Big). Essentially a test PR to see if I'm doing this shit right.
Tabaxi earscratching provokes purring. This is a universal benefit to anyone and everyone.

Ears For Cats

---

code/__DEFINES/say.dm

Fixes celestial font.
Prior to this, it just looked like normal text if you were speaking it. The fort was misnamed.

Fixes celestial font.

---

code/modules/jobs/job_types/roguetown/peasants/bathmaid.dm

whoops
if lusty bitches want to draw a bath and read slutty novels they can
we probably should delete the reading skill but it's midnight and that's a battle for another day

Power creeps bathmaids, lets them read

---

code/game/objects/items/rogueweapons/melee/blunt.dm
code/game/objects/items/rogueweapons/melee/flail.dm

Bandaid nerf to maces/flails until I do my armor rework. Flails had a goddamn 1.5x multiplier on smash intent, which was scaling with strength damage bonus and destroying people. I upped the base force and lowered the multiplier. Maces also got nerfed because they had some of the best force in the game while also having 80% pen

Maces and Flails, too cool fo' school.

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/steppesman.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/underdweller.dm

Fucks with Mercenary numbers a bit, to nestle them more firmly into their specific niches and give them more distinct flavors.
Grenzel: Brutish heavy melee, untouched (For now). Koboldbear is considering fucking with their strength again, and I'm not gonna step on their toes.
Desert Rider: Sword-and-shield, fairly agile. Intended to be the more defensive, nimble counterpart to Grenzels.
Steppesman: Bow-centric, with expert riding and whips. Low-damage, reliable ranged skirmisher that can go Cavalry mode if they can actually get a saiga.
Underdweller: Largely unchanged, literally just gave them Shields 3 and Alchemy 2. Sapper-miner that produces their own explosives.
Condotierro: Completely adjusted into a mercenary-rogue, with a focus on the murderous side. Hard-hitting Crossbow ranged …

Mercenary Niche-ening

---

modular_hearthstone/code/game/objects/items/signal_horn.dm

Slays an errant bracket, changes meters-> paces, and makes horns work for Marshall.
Fixes INCOMPETENT ROGUE CODER(ONUTSIO'S) WORK !!! 1,000,000 LASHES UPON HER!

Horn fixes

---

code/datums/skills/misc.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/seamstress.dm
code/modules/jobs/job_types/roguetown/adventurer/types/special/whitecheesemaker.dm
code/modules/jobs/job_types/roguetown/church/druid.dm
code/modules/jobs/job_types/roguetown/church/monk.dm
code/modules/jobs/job_types/roguetown/church/priest.dm
code/modules/jobs/job_types/roguetown/youngfolk/churchling.dm
code/modules/jobs/job_types/roguetown/youngfolk/clerk.dm
code/modules/roguetown/roguecrafting/weaving.dm

I could have sworn we did this already. Anyway;
Removes the weaving skill, absorbing it into the sewing skill. It's unnecessary skillbloat, and just makes grinding up silk things (if you wanna do that) all the more tedious for the sake of it. Silk is already rare due to the input, so it's fine.
Begone, skill bloat.
Also every single other codebase did this already, to the point we didn't have a dream message for it.

Strikes down the weaving skill

---

code/game/objects/items/rogueweapons/melee/flail.dm

The steel flail's icon state was incorrect.
Bugfix

Fixes the steel flail's invisible sprite.

---

code/_onclick/hud/ghost.dm
code/datums/special_traits/traits/traits.dm
code/modules/client/verbs/ghost.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/spirit/spirit.dm
code/modules/mob/say.dm

Removes xenophobia as a special and bad moods related to examining certain races.
Removes extranumerary "Journey to underworld" verb in the spirit tab. The HUD icon to the left should work fine.

The Anti-Racism Update: Director's Cut

---

code/modules/mob/living/living.dm

* Enables tileswap with tamed animals.
https://github.com/user-attachments/assets/30fa4191-598c-42ec-aee3-17bfd640bd02
Tileswap was tested live and didn't work out for a variety of reasons. I went back to the drawing board with Bear and we both agreed the silver lining from that chaos was animal tileswap. It was received well by soilers and homesteaders with overcrowded barns.

Moove Out The Way: Enables tileswap for livestock

---

code/datums/migrants/migrant_waves/fablefield roles.dm
code/datums/migrants/migrant_waves/heartfelt roles.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/barbarian.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/necromancer.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/sorceress.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/drunkard.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/noble.dm
code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/towndoctor.dm
code/modules/jobs/job_types/roguetown/adventurer/types/special/nakedandafraid.dm
code/modules/jobs/job_types/roguetown/adventurer/types/special/torso.dm
code/modules/jobs/job_types/roguetown/courtier/jester.dm
code/modules/jobs/job_types/roguetown/courtier/magician.dm
code/modules/jobs/job_types/roguetown/courtier/physician.dm
code/modules/jobs/job_types/roguetown/nobility/hand.dm
code/modules/jobs/job_types/roguetown/nobility/lord.dm
code/modules/jobs/job_types/roguetown/nobility/steward.dm
code/modules/jobs/job_types/roguetown/peasants/hostage.dm
code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm

* Removes the deity requirements from all of the non-religious jobs. Acolyte, paladin, priestess, templar, inquisitor, cleric, and witch-hunter (the adv class) all keep it. Also none of the tribal files, fuck 'em.
* **ADDS** a divine faith requirement for the monarch. Speaking from experience, the divinely ordained monarch turning out to be a zizoite tends to be v silly and just lead to them getting promptly offed.
* Removes all the "this role allows for full customization text."
If someone wants to spin their mage as the countless drilling rune work of Malum or something go nuts. The ones where the change has a mechanical effect, ie divine, unfortunately still need the leash until content is added. One day, maybe.
god up

Removed deity requirements and desc text

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm

Gives female/fembody Nadeli a regular gambeson rather than an arming jacket, because Roguetown's coders are fucking evil and never made a female version.
Nadeli no longer spawning with they THANGS out.

Warscholar: CHUDCODE, WHY!!!

---

code/game/objects/items/rogueitems/instruments.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/roguetownprocs.dm
code/modules/mob/mob.dm

Respawning using the SKULL after dying should work properly now.
Playing instruments will give you music experience for every person who hears you.
Having your attack parried will give you XP for the weapon you are using to attack, and not the weapon that your target used to parry with.

Fixes Respawning

---

README.md

please click these buttons for us tyvm:
also fixes the wiki link bcuz webedit lol
---
edit:
hey add the diffbots too please n thank u
https://github.com/apps/icondiffbot-2
https://github.com/apps/mapdiffbot-2
keeping track of bugs is good actually

Fixes everything 👍

---

code/controllers/subsystem/migrants.dm
code/modules/mob/dead/new_player/new_player.dm

See title. Not tested locally but like, this should probably do it

Fix latejoin characters ignoring anonymised status

---

code/__DEFINES/preferences.dm
code/datums/emotes.dm
code/game/say.dm
code/modules/client/client_procs.dm
code/modules/jobs/job_types/roguetown/peasants/soilson.dm
code/modules/mob/living/carbon/human/say.dm

Adds androgynous voice option.
Fixes runtime with soilsons. There was a missing number for their unarmed skill. Plugged a 3 in there.

Androgynous Voicetype

---

code/modules/clothing/rogueclothes/cloaks.dm

Renames some Hedge Knight armor pieces that were called blacksteel to clear up some confusion.

renames bandit hedge knight armor pieces

---

code/modules/jobs/job_types/roguetown/nobility/lord.dm

Re-allows full patron choice to monarch.
If a monarch is abusing their status as 'evil' to make the round generally unenjoyable for people rather than creating drama and intrigue, that can be a player issue with admins involved. Otherwise, there is little reason to restrict the creativity. The Priest/Priestess is the leadership role required to be 'good' and the source of morals. Monarch can be distasteful.

Let monarch be inhumen again.

---

code/modules/antagonists/roguetown/villain/ascendant/ascendant_altar.dm

Cleans up Ascendant code.
Untested, @bearrrrrrrr please test this I have no clue how to do your antag stuff sorry

Clean up Ascendant code

---

code/__HELPERS/roundend.dm

At the end of the round, if there was no monarch, the message displayed would be one of seven statements along the lines of 'Monarch is gone, everyone dies or suffers.' This replaces those. 
Old:
"Without a Monarch, they were doomed to become slaves of Zizo.",
"Without a Monarch, they were doomed to be eaten by nite creachers.",
"Without a Monarch, they were doomed to become victims of Gehenna.",
"Without a Monarch, they were doomed to enjoy a mass-suicide.",
"Without a Monarch, the Lich made them his playthings.",
"Without a Monarch, some jealous rival reigned in tyranny.",
"Without a Monarch, the town was abandoned."
New:
"So concluded another chapter of the story. Another begins shortly.",
"A blank page is filled; a new canvas presented.",
"Our actors hang up their masks. A new cast …

No, group suicide is not the answer.

---

code/game/objects/structures/guillotine.dm
code/modules/antagonists/roguetown/villain/zomble.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/mob.dm
code/modules/surgery/bodyparts/_bodyparts.dm
code/modules/surgery/surgeries/prosthetic_replacement.dm

Zombies no longer force ghost you.
Zombies retain their features.
Fixes ghost-orbiting.
Level required for organ reattachment lowered to Journeyman from Expert.
Guillotine no longer forces people to clap. Holy teegee !!

Zombie-Pocalypse

---

_maps/map_files/dun_manor/smalldecap.dmm

for reasons i cannot surmise the winch in the throne room was opening/closing the gates in one of my dungeons instead of the throne room gates. oops.
sorry

fixes the throne room gate

---

config/example/config.txt

Adds an entry to the config to log LOOC.

Enables LOOC Logging

---

code/modules/jobs/job_types/roguetown/adventurer/bandit.dm
code/modules/jobs/job_types/roguetown/church/priest.dm
code/modules/jobs/job_types/roguetown/courtier/councillor.dm
code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
code/modules/jobs/job_types/roguetown/nobility/captain.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm
code/modules/jobs/job_types/roguetown/nobility/lady.dm
code/modules/jobs/job_types/roguetown/nobility/lord.dm
code/modules/jobs/job_types/roguetown/nobility/steward.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm

adds PQ locks tosome jobs
i literally saw someone play monarch on their 2nd round, you can't make this shit up
most of these locks just ensure you are not hopping immediately into leadership roles upon joining

adds PQ reqs to some jobs

---

code/modules/roguetown/roguemachine/titan.dm

Makes the description match the required command.

Fixes throat description.

---

code/game/objects/structures/roguetown/rogueflora.dm

Fix pyroclastic flora runtiming

---

code/_onclick/item_attack.dm
code/game/turfs/closed/minerals.dm
code/game/turfs/turf.dm

Right clicking a mineral turf with an item on PICK intent while having Journeyman+ skill in Mining will let the user do a 4X damage attack after a delay, should be slightly lower than manual clicking still, is mostly useful as a way to not have to click rocks 400 times, hopefully.

Automine (Kind Of)

---

code/modules/mob/living/carbon/human/update_icons.dm

Fixes runtimes in icon code. I lazylisted onprop but forgot a few checks.

Fix runtimes in icon code

---

code/modules/roguetown/roguejobs/alchemist/container.dm
code/modules/roguetown/roguejobs/alchemist/powders.dm
code/modules/roguetown/roguejobs/alchemist/reagents.dm

Makes it so freshly made red is far stronger and on-spawn or ordered red is weaker. This is to give alchemists actually a reason to make red rather than it just being bulk-ordered.

Red is the new Black

---

modular/Neu_Food/code/raw/NeuFood_veggies.dm

It really doesn't need dropshrink with the new sprites. They're hard to click as-is.

Removes dropshrink from cabbage. 

---

code/modules/jobs/job_types/roguetown/adventurer/types/antag/knave.dm

ahahaha don't worrry about it.
(i accidentally gave poachers a buckler instead of a bow and arrows. this fixes that)
please stop looking at me i'm a little embarrassed tbh

Whoops: gives poacher, the bandit archer subclass, an actual bow.

---

modular_azurepeak/code/datums/loadout.dm

Yep.
Two users from Discord requested buckled hats and loincloths, and I figured I'd throw nun habits in there anyway since they're a super easy low-skill and low-effort craft.
More loadout choices!

Adds nun habits, buckled hats and loincloths to loadout choices

---

code/modules/roguetown/roguecrafting/items.dm

Merely removes the check so it checks the skills for archery. Thus making people able to craft it and use it.
More people using bows. I think it is fine it still has high difficulty to craft.

Changes that bows now requires crafting skills rather than archery skill

---

modular_azurepeak/code/modules/spells/orison.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

People have reported that prestidigitation mote light scaling isn't working and this should *probably* fix it reliably.
I've also buffed the create water orison by 1oz per tick to make filling a cup as a templar take only 16 seconds instead of 32.
Templars shouldn't be getting flow problems until their late fourties.

Prestidigitation fix & slight create water buff

---

code/datums/gods/faiths/divine_pantheon.dm
code/datums/gods/faiths/inhumen_pantheon.dm
code/datums/gods/faiths/old_god.dm
code/datums/gods/patrons/divine_pantheon.dm
code/datums/gods/patrons/inhumen_pantheon.dm
code/datums/gods/patrons/old_god.dm
code/modules/antagonists/roguetown/villain/ascendant/ascendant.dm

**Remain calm. Psydon lives. Psydonia yet endures.**
yeah.

new god descs

---

code/_onclick/drag_drop.dm

Port of https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1098.
(I tested it, the gif in the linked PR is wrong. The movement actually does move the object where the cursor is rather than askew. It's pretty dang cool.)
QoL for everyone, especially shopkeeps, servants, anyone who needs to make a pretty display.

Ports click-drag relocation.

---

code/controllers/subsystem/npcpool.dm
code/controllers/subsystem/rogue/damoverlays.dm
code/game/objects/items/rogueitems/needle.dm
code/game/objects/structures/roguetown/rogueflora.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/mob/living/carbon/human/update_icons.dm
code/modules/mob/living/life.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

- Fixes the icon runtimes. Ugh.
- Fixes a runtime when attacking a non-item with a needle.
- Fixes a runtime when destroying an evil tree.
- Fixes a runtime from wizard light motes.
- Fixes a runtime when a missing limb is targeted for a grab.

Fixes a bunch of runtimes

---

code/modules/client/customizer/customizers/organ/snout.dm
code/modules/mob/living/carbon/human/species_types/furry/tabaxi.dm

Adds more snouts and markings for tabaxi to choose from
Bruh why TF do i gotta type this shit

Adds more markings for tabaxi

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/amazon.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/dwarfwarrior.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/knighterrant.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/sentinel.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rare/witchhunter.dm
code/modules/jobs/job_types/roguetown/adventurer/types/special/crusader.dm

Removes the limits placed upon select adventurer classes
Allows people to play their preferred adventurer-class without hassle
At the moment, the code is functionally a character roleplay game. Allowing people to play their characters how they wilt is the de-facto status of the game. Until further refinement, depth, and interaction is developed to counter balance than restrictions do more harm than good.

Unlimit-Adventure-Slot

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm

Replaces the current description of the condottieri mercenary class with one more relevant to updated lore.
This description will give players selecting the condottieri class a better idea of its origins and ethos.

Changes condottieri description

---

code/datums/gods/faiths/divine_pantheon.dm
code/datums/gods/faiths/inhumen_pantheon.dm
code/datums/gods/faiths/old_god.dm
code/datums/gods/patrons/inhumen_pantheon.dm

changes god lore slightly
makes less sense for the four to be a huge church, the ten are already recognizable, why change it?

slightly better god lore

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/vaquero.dm

Changes the description of the vaquero class
The old description was a holdover from old code. The new description is more accurate to the server in tone and lore.

Changes vaquero description

---

code/modules/jobs/job_types/roguetown/yeomen/nightmaster.dm

Bathmaster PQ requirement fix

---

_maps/map_files/dun_manor/dun_manor.dmm

fixes a few doors i missed in the bath house that were still locked to tavern keys
ugghhh i'm sorry

nightmaiden door fix

---

_maps/map_files/dun_manor/dun_manor.dmm

unlocks the front door by default, moves all the table-drugs into the staff room so bath attendants can sell them or hand them out to customers, god bless
purity vendor's still publicly accessible. really should've just done one big fix PR my bad oomfies

another bath house fix PR

---

_maps/map_files/dun_manor/dun_manor.dmm
code/game/objects/items/rogueitems/keys.dm

Adds some stables outside of the city for stowing your saiga! They're right across from the soilson's and the soilson's little stall has keys to the stables inside to be sold. (The stall key's inside the butcher building across the street!)
Screenshot of mapping changes:
Cool little spot for stowing your horse when you're not using it - plus it gives the soilsons something extra to do/sell if they're so inclined!

Adds stables just outside the city

---

code/__DEFINES/say.dm
code/__HELPERS/icons.dm
code/__HELPERS/priority_announce.dm
code/__HELPERS/text.dm
code/_globalvars/regexes.dm
code/datums/emotes.dm
code/game/objects/items/rogueitems/books.dm
code/game/objects/structures/fluff.dm
code/modules/client/asset_cache.dm
code/modules/client/preferences_descriptors.dm
code/modules/mob/living/carbon/human/say.dm
code/modules/mob/living/emote.dm
code/modules/mob/mob_helpers.dm
code/modules/modular_computers/file_system/programs/card.dm
code/modules/roguetown/roguemachine/titan.dm

Ports sanitisation fixes by @Cyprex.
Should fix the thanati server-crasher involving burning papers.

Sanitisation Fixes

---

code/modules/cargo/packsrogue/tools.dm
code/modules/roguetown/roguecrafting/farming.dm
code/modules/roguetown/roguestock/import.dm

* Steward can now import animals, comes in chests to prevent runtime.
* Merchants can now purchase hoe and bedrolls.
* 5x Fertilizer bulk recipe added.
QoL, losing animals to verevolf attacks suck a lot. Crown now has the means to offer farmers a gracious, helping hand.

Merchants and Fertilizers: Small QoL

---

code/game/objects/items/rogueitems/bells.dm
code/game/objects/items/rogueitems/coins.dm
code/game/objects/items/rogueitems/devices.dm
code/game/objects/items/rogueitems/flintsparker.dm
code/game/objects/items/rogueitems/gems.dm
code/game/objects/items/rogueitems/keyrings.dm
code/game/objects/items/rogueitems/keys.dm
code/game/objects/items/rogueitems/magic.dm
code/game/objects/items/rogueitems/natural/animals.dm
code/game/objects/items/rogueitems/ropechainbola.dm
code/game/objects/items/rogueweapons/melee/axes.dm
code/game/objects/items/rogueweapons/melee/blunt.dm
code/game/objects/items/rogueweapons/melee/flail.dm
code/game/objects/items/rogueweapons/melee/knives.dm
code/game/objects/items/rogueweapons/melee/polearms.dm
code/game/objects/items/rogueweapons/ranged/crossbows.dm
code/game/objects/items/rogueweapons/rogueweapon.dm
code/modules/clothing/rogueclothes/gloves.dm
code/modules/clothing/rogueclothes/mask.dm
code/modules/clothing/rogueclothes/pants.dm
code/modules/clothing/rogueclothes/quiver.dm
code/modules/clothing/rogueclothes/robes.dm
code/modules/clothing/rogueclothes/storage.dm

adds fire proofyness to a bunch of things that should probably have it. i went through most items i could think of having a reason to wear in your equipment slots and assumed that metal and leather objects are fireproof while cloth and wood objects have no resistance or are outright flammable.
flammable plate legs and keyrings can probably be assumed to be an oversight + fire can be pretty strong without having to melt steel ~~beams~~ armor

fire proofy pass

---

code/game/objects/structures/fluff.dm

i fucking hope it does, at least
uhhhh.

fixes the bandit idol???

---

code/datums/migrants/migrant_waves/heartfelt roles.dm
code/game/objects/items/rogueitems/books.dm
code/game/objects/structures/fluff.dm
code/modules/antagonists/roguetown/villain/maniac/maniac.dm
code/modules/jobs/job_types/roguetown/adventurer/pilgrim.dm
code/modules/roguetown/roguemachine/titan.dm

removes the final few mentions of rockhill that aren't really appropriate. also removes trey liam
Github? No...it doesn't exist...
My name is Trey Liam, SS13 Maintainer...
I'm on the Coderbus discord, a

removes trey liam from the game

---

code/modules/mob/living/carbon/human/species_types/roguetown/roguetown_species.dm

Removes accents temporarily to see if it affects lag. Would appreciate profiler samples taken by admins while this is in.

[TESTMERGE ONLY] Remove accents

---

_maps/map_files/dun_manor/dun_manor.dmm

* Puts SCOM in farm kitchen.
* Stall keys in merchants' replaced with ones that actually work.
* Containers in Stewards' start out locked with steward ID.
* Windows in stewardry and 2nd floor merchant replaced with reinforced.

Dun Manor fixes

---

code/modules/research/xenobiology/crossbreeding/_clothing.dm

You can't lynch me for this god awful PR title because you're all unable to take off the eoran buds you're wearing after this fix.
Suffer.
Also, a very slight grammar fix.
Condemned to pacifist goodtimes.

Bud Light: Fixes Eoran buds being removable via drag-drop

---

code/game/objects/items/rogueitems/natural.dm
modular_azurepeak/code/modules/spells/pantheon/inhumen/zizo.dm

Fixes Rituos skeletonizing your head when it shouldn't.
Fixes Profane not working with the type of bones everybody actually has access to. Roguecode reimplemented stacks as bundles despite there already being a working stack implementation on its ancestral TGcode, and I was using those stacks instead when testing this feature. Sigh.
Zizo work good.

Profane & Rituos fixes

---

strings/changelog.txt

So that I hopefully won't have to explain it each time.

Adds Round Contribution Points to the changelog

---

code/game/objects/items/rogueitems/instruments.dm

I can't for the life of me remember which song is which when they're all labeled song 1-7, so here you go. I tried my best to give these songs some proper names for the setting. I have no idea what the source of them is, except all the flute ones are from skyrim, so they're all elder scroll meme names.
Yes I went through and listened to every single one of them.
Lute Songs:
1: A Knight's Return
2: Amongst Fare Friends
3: The Road Traveled by Few
4: Tip Thine Tankard
5: A Reed On the Wind
6: Jests On Steel Ears
7: Merchant in the Mire
Accordion Songs:
1: Her Healing Tears
2: Peddler's Tale
3: We Toil Together
4: Just One More, Tavern Wench
5: Moonlight Carnival
6: 'Ye Best Be Goin'
Guitar Songs:
1: Fire-Cast Shadows
2: The Forced Hand
3: Regrets Unpaid
4: 'Took the Mammon and Ran'
5: Poor …

Gives Instrument Songs Names

---

code/datums/gods/patrons/divine_pantheon.dm
code/datums/gods/patrons/inhumen_pantheon.dm
code/game/objects/items/rogueitems/books.dm
code/modules/roguetown/roguemachine/lottery.dm
strings/books/law_2.json

FUCKING FINALLY, LAW BOOK IS DONE. HOLY SHIT.
clarifies some god stuff
bi-weekly gambling update
elt's go gamblnig

bear misc lore bundle

---

code/game/objects/structures/walldeco.dm
code/modules/roguetown/roguejobs/blacksmith/smelter.dm
roguetown.dme

actually re-adds clerk. does some alarm stuff. makes it so you can't SHIT OUT blacksteel, an ADMIN/EXTREME SCARCITY-SPAWN item that is supposed to be an age of enlightenment material. will re-introduce it when i start my mount decap lore makeover (literally starting tomorrow)
whoever thought of this was fucking insane, genuinely. adventurers are now not only running around in full plate, but BLACKSTEEL fullplate. No. Enough.

bear stuff part 34i9553

---

code/_onclick/hud/screen_objects.dm
code/datums/keybinding/carbon.dm

Adds RMB Intent Keybinds.
1. Select Feint Intent (Default: Shift+1)
2. Select Aimed Intent (Default: Shift+2)
3. Select Strong Intent (Default: Shift+3)
4. Select Swift Intent (Default: Shift+4)
5. Select Defend Intent (Default: Shift+5)
6. Select Weak Intent (Default: Shift+6)
7. Cycle RMB Intent (Default: N)
https://github.com/user-attachments/assets/2eff17a4-fb7f-4f28-9a12-4c21d5a177c9
Less clicking more gaming.

Adds RMB Keybinds

---

code/game/objects/items/rogueitems/keys.dm
code/modules/antagonists/roguetown/villain/aspirant.dm
code/modules/clothing/rogueclothes/cloaks.dm
code/modules/events/rogue/_rogue.dm
code/modules/jobs/job_types/roguetown/adventurer/bandit.dm
code/modules/jobs/job_types/roguetown/courtier/physician.dm
code/modules/jobs/job_types/roguetown/garrison/townguard.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm
code/modules/jobs/job_types/roguetown/nobility/lady.dm
code/modules/jobs/job_types/roguetown/yeomen/archivist.dm
code/modules/roguetown/roguemachine/scomm.dm

I forgor some more thingies that refered to the monarch.
Also gives 5 RCP to bandits. I love u my adorable lil matthiosian blorbos

more instances of monarchy gone

---

code/__DEFINES/preferences.dm

Made more clear they/them options really only affect clothing (and titles)
Binary options? In _my_ good Psydonian NB options?

Clarified They/them Prefs Option

---

code/_onclick/drag_drop.dm
code/modules/admin/admin_verbs.dm

Yep.
This gets asked for **frequently**.

Allow admins to toggle aghost invis on/off (off by default)

---

code/game/objects/structures/roguetown/rogueflora.dm
code/modules/spells/roguetown/acolyte/general.dm

Widened Dendor Miracle to consider kneestingers and other unlikely vanilla trees, as well as using the rare Mystic tree as an ultra bonus. Increased Astrata Miracle bonus during day
1. Ensures all flora types that make sense--including kneestingers--are considered for Dendor bonus. Allows Druids to sacrifice extra devotion, a cooldown, and risk to their patients, to summon kneestingers for a boost in their healing abilities/give them a reasonable ability to heal indoors. Of course, it's still much more effective to haul them outside if able, but now Dendorites can at least stabilize critically wounded players in caves/buildings at the cost of complicating the extrication of the wounded by needing to carry them over the stingers. The four stingers will yield a mere 0.4/tick bonus, compared …

Sacred Druid Tree, Dendor Miracle considers more flora, Increased Astrata day-healing

---

_maps/map_files/dun_manor/dun_manor.dmm
code/datums/status_effects/rogue/roguebuff.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm

Tweaks RG stats, RG no longer spawn with objectively worse stats than most martial adventurer classes.
Heavy Knights get more con/endurance than other classes but suffer a speed debuff.
Foot Knights have well-rounded stats, less con/end than Heavy Knight but have no speed or perception debuff.
Mounted Knights get less strength/con/end than both other classes, but have increased perception and a small buff to speed.
Mounted Knight spawn loadouts have also been adjusted with three options.
Sword + Recurve Bow
Mace + Crossbow
Spear + Shield
I've included a few small mapping changes to the keep as well - I added some stables outside the garrison building in the event the keep wants to actually buy saigas for the mounted knights. I thought it was kind of strange that the keep doesn't really …

Royal Guard balance pass

---

code/modules/jobs/job_types/roguetown/church/templar.dm

Moves generic psicross to templar's wrist like it is for any other deity, adds Eora gear for templar
Eoran Templars rejoice

Add Eora gear to Templar

---

code/modules/cargo/packsrogue/Sellsword.dm

can I be done with hoardmaster now, god? Applies the prior hoardmaster item fixes to the sellsword list, as I only applied them to the brigand's, who have similar items.
Luca can perhaps, be done with HOARDMASTER fixes, as a treat.

Hoardmaster item fixes Final Exasperated Edition

---

code/game/turfs/open/lava.dm

drinking lava kills you

---

code/datums/special_traits/traits/traits.dm
code/modules/clothing/rogueclothes/pants.dm
code/modules/clothing/rogueclothes/shirts.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/grenzelhoft.dm
modular_azurepeak/code/datums/loadout.dm

AGHHHHHH
- grenzelhoft shirt armor, grenzie pant not garbage (equiv to leather roughly), also changes their stats to be on par with other classes (warrior adventurer), because we are also doing:
- v experimental desert mirage changes (they aint got shit going on man this is desperation)
- strapless dress loadout fix oops oops oops

bearundle part 96-p06

---

_maps/map_files/dun_manor/dun_manor.dmm

Apparently my fault, as the map fix pr felt the need to add one. I don't remember ever so much as selecting a scom, though, so that's pretty fucking weird.
i hate shark people

Aqua force scom deleted

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm

literally just https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/735 without merge conflicts that i forgot to add on to my last pr
I DON'T KNOW WHAT THE FUCK TO DO WITH THESE GUYS

desert rider stuff

---

code/modules/roguetown/roguecrafting/alchemy.dm

Bulk ozium and moondust alchemy recipes were not only replacing the single versions, but they weren't actually producing bulk versions of their given drugs. Fixed this after it was pointed out on Discord.
Game work good.

Fixes broken ozium & moondust alchemy recipes

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

forgot to push last commit, oh well
yeah

oops - fix for last pr

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm

https://www.youtube.com/watch?v=YVlcADaT94o
not selecting classes is really bad actually.

call me daytona 500 cuz im speed merging

---

code/modules/jobs/job_types/roguetown/yeomen/nightmaster.dm

Brings stats/skills up to at least what the attendants have if not more. Gave Journeyman whips, and loads in with swaggier clothes, whip, and a satchel full of extracurricular activities. Also get shitty see-price.
Oh, and they get nutcracker for those handy patrons.
Works towards bath house not being (just) a fuckpalace.

Bathmaster Glow Up

---

code/modules/jobs/job_types/roguetown/courtier/butler.dm
code/modules/roguetown/roguejobs/cook/tools/pot.dm

Doubles Iron Pots size. Also names them "Iron Pot" instead of just "Pot" for clarity. Gives Head butler better skills as they age (like most roles)
Everybody should fucking love soup. Truly the superior meta. Also old maids.

You've got big bowls (of soup)

---

code/__DEFINES/food.dm
code/datums/stress/negative_events.dm
code/datums/stress/positive_events.dm
code/modules/farming/produce.dm
code/modules/food_and_drinks/food.dm
code/modules/food_and_drinks/food/snacks.dm
code/modules/mob/living/carbon/human/human_helpers.dm
code/modules/reagents/reagent_containers/glass.dm
code/modules/roguetown/roguejobs/fisher/fish.dm
modular/Neu_Food/code/cooked/NeuFood_meals.dm
modular/Neu_Food/code/cooked/NeuFood_pies.dm
modular/Neu_Food/code/cooked/NeuFood_snacks.dm
modular/Neu_Food/code/raw/NeuFood_dough.dm
modular/Neu_Food/code/raw/NeuFood_processed.dm

Broke drinking, reverting for now.

Revert "Manners Maketh The Man: Nobles have food quality & manner requirements"

---

code/modules/jobs/job_types/roguetown/courtier/butler.dm
code/modules/roguetown/roguejobs/cook/tools/pot.dm

Reverts GeneralPantsuIsBadAtCoding/Azure-Peak#784

Revert "You've got big bowls (of soup)"

---

code/modules/mob/living/carbon/rogfatstam.dm
code/modules/roguetown/roguejobs/alchemist/reagents.dm

Hits starving within five minutes, will need adjustment

Revert "Feast & Famine: Nutrition changes"

---

modular_azurepeak/code/datums/loadout.dm

Adds the two new hats to the loadout menu
So people can wear the hats on their heads I think :)

hats in da loadout baby

---

modular/Neu_Food/code/cooked/NeuFood_meals.dm
modular/Neu_Food/code/raw/NeuFood_dough.dm

Luto discovered that we had the sprites for these all along, they just weren't entered and pathed properly.
Being able to see things in-game is pretty sweet.

Fix missing plated fish & cheesecake icons

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
modular/Neu_Food/code/cooked/NeuFood_meals.dm

* combat_cult.ogg plays for Zizo Clerics when in combat mode.
* Fixes missing icon for plated fried rat.
antag powercreep

rats for zizo

---

code/modules/mob/living/living.dm

Ports https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1506#issue-2644434088
Allows for sneaky grabs by sneaky, unscrupulous types

Port Behind Grab

---

code/datums/sexcon/sexcon.dm
code/modules/client/customizer/customizers/organ/genitals.dm
code/modules/surgery/organs/feature_organs/genitals.dm
code/modules/surgery/organs/organ_dna/_organ_dna.dm

You can select whether your penor is functional or not. Basically you can choose to have the limpdick trait. It means you can't penetrate. And also you can't get hard. Limpdick trait didn't stop you from getting erect but now it does.

Selectable Penile Limpness

---

code/__DEFINES/food.dm
code/datums/stress/negative_events.dm
code/datums/stress/positive_events.dm
code/modules/farming/produce.dm
code/modules/food_and_drinks/food.dm
code/modules/food_and_drinks/food/snacks.dm
code/modules/mob/living/carbon/human/human_helpers.dm
code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
code/modules/reagents/chemistry/reagents/food_reagents.dm
code/modules/reagents/reagent_containers/glass.dm
code/modules/roguetown/roguejobs/fisher/fish.dm
modular/Neu_Food/code/cooked/NeuFood_meals.dm
modular/Neu_Food/code/cooked/NeuFood_pies.dm
modular/Neu_Food/code/cooked/NeuFood_snacks.dm
modular/Neu_Food/code/raw/NeuFood_dough.dm
modular/Neu_Food/code/raw/NeuFood_processed.dm

Horrendously botched merge stopped people from drinking things from most containers themselves - my bad. See #780 for details.
I've also lowered the nausea that eating impoverished food gives nobles, so that you don't immediately puke upon eating a bite of delectable room temperature medieval butter on the royal carpet in front of your entire retinue. Now you have to eat three!
**Testmerge this first, please.**
Yep.

[TESTMERGE] Manners Maketh The Man 2: I Can Feed Myself Again

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/vaquero.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm

Tweaks the vaquero's skills to be a bit more appropriate. Also changes the vaquero's cloak to be different to the duelist's, and the duelist's hat to be different to the vaquero's. 
As it exists today, Vaquero - beyond some aesthetics (though not much considering they still used the same hat!) - was an objectively shittier rogue-duelist. They have less unarmed, wrestling, sneaking, stealing, lockpicking, swimming, knives, athletics, maces than the duelist. Not to mention, where the duelist begins with some armour in the form of hide and leather, the vaquero begins with no armour bar the awful leather vest. The saiga is more often a detriment than a boon for the vaquero's playstyle, serving mostly as flavour and inevitably being left in a stable and forgotten about.
Of course, the vaquero …

Vaquero tweaks + new hat for duelist rogue

---

code/modules/jobs/job_types/roguetown/peasants/butcher.dm

Butcher didn't spawn with a coinpurse, nor key to the house he lives in? Strange guy indeed.
Half-baked loadouts aren't fun.
Drafted until I properly test this. Also didn't spawn with cleaver on live branch.

Butcher fix

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/bard.dm

frick I forgot to add the line choice pointers for bard.

[bug fix] Hurdy-gurdy/viola

---

modular/Neu_Food/code/raw/NeuFood_dough.dm

Oversight.
Pastries aren't disgusting!

Fix pastry missing a fare type

---

code/modules/jobs/job_types/roguetown/courtier/butler.dm
code/modules/jobs/job_types/roguetown/youngfolk/servant.dm

whoops
short; skills were nested in base pre_equip, but making a class called it again and everyone got double skills and were super strong. can't have that in our working class.
apparently when i clicked the skills button it was only before picking a class whee

servant pay to win over

---

code/modules/antagonists/roguetown/villain/choosename.dm
code/modules/mob/living/roguetownprocs.dm

uh
- antags can choose names for longer (we've had 3 ahelps about this in the last week)
- more importantly - training has been reverted so now you can't gain levels from LITERALLY EVERYTHING
YEAH.

training pack

---

code/game/objects/items/rogueweapons/rmb_intents.dm

Ports https://github.com/Rotwood-Vale/Ratwood-Keep/pull/756 without SPD scaling.
Adds scaling with INT (10% chance per point of difference). 
Increases duration of immobilized debuff if feint is done from the dedicated feint intent. It is still possible to feint while using any other intent, but to much less effect.
Many commits cause I'm stoopid and never used github before.
Makes INT a little more viable for combat outside of magic. There is now a bit of a downside to dumping INT.

Ports Ratwood's feint buffs

---

code/modules/jobs/job_types/roguetown/church/puritan.dm

oopsies 
i broke something with my last PR that just got merged

extract confession fix

---

code/modules/mob/living/roguetownprocs.dm

things working right = good
yeah

fixes training PR, oops.

---

code/modules/roguetown/roguecrafting/leather.dm

apropros of being eepy sleepy when i did it the leather armor pr had some oversights on the craft recipes, this just fixes it so that crafting recipes work properly.

fixes busted stuff

---

modular_azurepeak/code/datums/loadout.dm

This PR adds hoods and fur cloaks to loadout options.
more loadout customization options good

Adds hoods and fur cloaks to loadout options

---

code/modules/roguetown/roguecrafting/leather.dm

please kill me

---

modular/Neu_Food/code/cooked/NeuFood_meals.dm

The noble palate suffers without platters. Buffs some plated versions of wieners so that nobility can stomach them.
Brings wieners up to stuff with the general trend that plating a food item increases its fare by a step.

Wieners on plates are fine fare

---

modular_hearthstone/code/modules/spells/roguetown/wizard.dm

went too far on my last pr with bladeburst, makes it a smidge faster and gives it's full damage back. should make everyone happy. 
(sorry for the number pr)

minor spell correction

---

code/modules/farming/produce.dm

Increases wheat distill amount from 24 to 36.
I'd like to see beer be MUCH more available than any other alcohol in the game, specially for the poor folk. I think increasing the amount of beer obtained per wheat would make it more plentiful and hence, cheaper!
I wish there was a way to make it so it also gave you nutrition, so you could sate your hunger from beer alone and not get as drunk, but im not that smart.

Update produce Wheat Distill_Amt.dm

---

code/modules/jobs/job_types/roguetown/nobility/captain.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm

https://github.com/user-attachments/assets/41a7d3f6-6d3c-43e5-b796-2645b37f3f0e
captain's loadout works now waow

fixes captain

---

code/modules/clothing/rogueclothes/armor.dm
code/modules/clothing/rogueclothes/pants.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
code/modules/jobs/job_types/roguetown/nobility/lady.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
code/modules/jobs/job_types/roguetown/youngfolk/squire.dm
code/modules/mob/mob_movement.dm
code/modules/roguetown/roguecrafting/leather.dm

This PR adjusts some armor-related stuff.
- Adds armor class flags for leg armors.
- Leather/Heavy Leather armor is considered light class, chainmail armor is medium, plate armor is heavy. Bikinis/skirts remain a bit lighter at the cost of less armor coverage than actual chausses/shirts.
- In keeping with the above, changes chainmail shirts/haubergeons to medium armor. Light classes will have to use gambesons under their leathers!
- Adjusts loadouts for a handful of classes that spawn with chainmail stuff without medium/heavy armor proficiency. (Namely squires, desert riders, and the prince/consort.)
- Some smaller tweaks to armor values. Leather armors and gambesons are now slightly better at negating blunt damage than chainmail, but fare worse against cuts/stabs.
Light armor classes are …

Armor Class adjustments

---

code/modules/client/preferences_savefile.dm

* Grain Filter toggle should remember your preference the next time you open the client.
forgot lol

Grain Toggle remembers your pref

---

code/modules/jobs/job_types/roguetown/garrison/villagechief.dm

This PR, through a highly technical and complex series of code and hours of countless effort, gives village elder the ability to cook.
Someone complained about village elder having no cooking skill, this fixes this. They have a kitchen in their home and they're meant to be an old wise fellow, I feel like they've probably learnt to cook at some point in their life.

Gives village elder the ability to cook.

---

code/modules/jobs/job_types/roguetown/youngfolk/squire.dm

irregular squires now actually spawn with leather pants instead of chain ones
i made an oopsie in my armor class PR

fixes squires pants

---

code/__HELPERS/time.dm

as the title says. can be tips, lore, whatever.
i wish i could do it cleaner for my own ego (maybe with a .json or .txt) but honestly this works fine

adds tips to day transitions

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/mage.dm

Gives Zizoan Adventurer mages the Zurch key and combat_cultist combat music
She's the god of left handed magicks. Magisters are important too <3

Take me to Zurch

---

_maps/map_files/dun_manor/dun_manor.dmm

Makes the armory bigger, adds some of our new leather armors to the armory and a few more weapon options for variety.
<details>
<summary> Screenshot, I guess: </summary>
</details>
The armory's cramped as fuck. On highpop, when people are in there roundstart grabbing their gear it gets CROWDED. This makes it a bit bigger and hopefully significantly less cramped when half the garrison's down there nabbing gear.

Armory Biggening

---

_maps/map_files/dun_manor/dun_manor.dmm

doesn't really do a whole lot; condenses the little moat-escape-hallway and the underground bar thing into one, unburies 2 goblin camps, gets rid of 2 buried goblin camps that nobody really went to except for the sole purpose of shutting those fucking goblins up
also makes it so that the ores near the zizo chapel aren't naked rarespawns so ppl will go to the zizo chapel less so it's more sneaky
i really don't know

minor dunn manor stuff

---

_maps/map_files/dun_manor/azure_coast.dmm

Title
Probably shouldn't be able to get two scrolls by clicking 5 times with a shovel.

Prevents bypassing dragon room in the dungeon of the ten.

---

code/modules/surgery/surgeries/prosthetic_replacement.dm

Since prosthetic legs were put in, adds those as valid targets for the prosthetic removal surgery.
Maintaining the secret saw technique.

Saw off prosthetic legs, too

---

_maps/map_files/dun_manor/dun_manor.dmm
_maps/templates/sewers.dm
_maps/templates/smalldungeons.dm
code/game/objects/items/rogueweapons/melee/knives.dm
code/modules/clothing/rogueclothes/storage.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/rogue.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/condottiero.dm
code/modules/roguetown/roguecrafting/leather.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
modular_azurepeak/code/game/objects/items/mundanities.dm
strings/books/law_2.json
strings/rt/timechangetips.txt

- fixes knife belts spawning w/ double stuff sometimes
- fixes some classes starting w/ EMPTY knife belt
- adds knifebelt loot to certain spawners
- makes some stuff more likely to spawn in spawners (MY STUFF!!!)
- changes royal puzzle box to be easier and give a better stat boost
- adds knifebelt to merchant's
- can craft tossblades and knifebelt
- https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/947 does this since im working on the same map and i want to avoid merge conflicts, they seem frightening
- more tips
- fuck it, fixes the lawbook while i'm here
i think it's p good

fixes, oops

---

modular/code/modules/living/say.dm

fixes a really bad bug
thanks @EvenInDeathIStillServe

subtler bug fix

---

code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm

fix steel tossblade

---

code/modules/roguetown/roguemachine/lottery.dm

typo fix machine

---

code/modules/antagonists/roguetown/villain/ascendant/ascendant.dm
code/modules/mob/living/carbon/stress.dm
strings/rt/stress_messages.txt
strings/rt/timechangetips.txt

throws stress messages up in chat when ur close to freaking out (big scream) but not all the way there
also removes the minecraft parkour reference from day tips cuz ppl didnt like :[
i think it's nice

eris reference omg ?! adds stress messages

---

code/modules/cargo/packsrogue/food.dm

Merchant was getting the base version of the pepper mill, not the kind you can use to season food
fix

Merchant imports the right kind of peppermill

---

code/modules/cargo/packsrogue/Sellsword.dm

just fixes sellsword bevors

---

code/game/objects/items/rogueweapons/melee/knives.dm
code/modules/clothing/rogueclothes/storage.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm

Fixes iron tossblades not fitting into tossblade belts. Also adds a little chat message whenever slipping one in (only to the user, it's still hidden from everyone else).
Bugfix and feedback, yippee!

Fixes unstorable iron tossblades & adds a feedback message

---

_maps/map_files/dun_manor/dun_manor.dmm
code/modules/roguetown/roguecrafting/leather.dm
code/modules/roguetown/roguecrafting/sewing.dm

- Gives the tailor shop some hide, fur, and tallow to start the round with.
- Adds a few new sewing/leatherworking recipes for items that didn't have any prior (mainly a few new hats, boots, and cloaks.)
QoL for tailor. It's already a pretty niche job and having to go collect hides/fur/tallow to even get your business started stinks! This gives them some materials mapped in so that they have an easier start to the round and can make a bit more cash to then in turn spend on more hide/fur from the stockpile once their roundstart supply runs low.

Tailor QoL

---

code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfd.dm
code/modules/mob/living/carbon/human/species_types/roguetown/elf/elfs.dm

What it says on the tin. Not sure why they didn't have those markings, as the sprites seem compatible.
More customisation, more elf whores (you know who you are.)

Adds flushed cheeks, eyeliner and tiger stripes to Elves and Dark Elves

---

code/_compile_options.dm
code/game/objects/items/rogueweapons/melee/knives.dm
code/modules/antagonists/roguetown/villain/maniac/maniac.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm

fixes the seax inhand transforms. it was inheriting the inhand transforms from the cleaver which was fucking up the inhand sprite, so, this fixes that
fixed sprite

fixes seax inhand transforms

---

code/modules/jobs/job_types/roguetown/Inquisition/orthodoxist.dm

Gives them an account as per request
They now have an account to get paid to.

Gives orthodoxist a meister account

---

code/__DEFINES/admin.dm
code/modules/admin/verbs/randomverbs.dm
code/modules/antagonists/roguetown/villain/maniac/maniac.dm

https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/683 was a mistake we pay for every day - re-adds trey liam
(adds in a trey liam smite)
Bleak? No...it doesn't exist...

re adds trey liam

---

code/__DEFINES/medical.dm
code/__HELPERS/type2type.dm
code/game/objects/items.dm

No more codediving to see which parts of your body get covered by armor. Yippee!
Example:
More in-game information = Good! Great!

Shows the armor's coverage on its inspect text

---

code/modules/admin/verbs/randomverbs.dm

fixe
fixes sprepy pliam smi
fixe trey lem smite
fixes trey liam smite

fixes trey laim spime- fi- trey liam smite fix

---

code/game/objects/structures/fluff.dm
modular_hearthstone/code/modules/reagents/reagent_containers/lux.dm

Adds lux to the list of sellable items at the bandit statue and increases its value a bit. Around 90 mammon sounds like a fair price for someone's soul - especially considering its a pretty significant effort to actually extract lux from people.
Bandit has a whole class themed around surgery/medicine - this makes picking sawbones and stealing lux from people a viable means to gain favor. A shady back-alley doctor stealing your kidney is flavorful and can make for interesting roleplay - this makes it so bandits can actually benefit from doing this.

Bandits can sell lux now

---

code/modules/roguetown/roguejobs/blacksmith/tools.dm

Reduces the blacksmith fail volume

---

code/game/objects/items/rogueweapons/shields.dm

Just cranks up DF on shields. You give up alot of offense to even carry a shield as compared to just two handing a weapon. The things should actually be the arm ur parrying with.
Kite shield to 11
Wood/tower/heater to 10
buckler to 9
shields currently just - are never actually used as the parrying weapon. This has been a problem for awhile. Leads to people who wanted to sword/board basically having no benefit from such. Shields now are quite good, I think? We'll see.

Shield Balancejak(I get one)

---

code/game/objects/items/rogueitems/natural/animals.dm
code/game/objects/items/rogueitems/natural/clothfibersthorn.dm
code/game/objects/items/rogueweapons/melee/polearms.dm
code/game/objects/structures/bearpelt.dm
code/game/objects/structures/signs/signs_plaques.dm
code/modules/cargo/packsrogue/armor.dm
code/modules/cargo/packsrogue/food.dm
code/modules/cargo/packsrogue/wardrobe.dm
code/modules/farming/soil.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
code/modules/roguetown/roguejobs/blacksmith/items.dm
code/modules/roguetown/roguejobs/blacksmith/smelter.dm
code/modules/roguetown/roguestock/stockpile.dm
modular_hearthstone/code/game/objects/items/clothes/stockings.dm

Changes:
-   Recipe for iron->steel (3 iron, 1 coal) now results in 3 steel ingots instead of 4.
-   Added hide as a component of the half-plate and full-plate armours.
-   Changes the value of steel (60 to 40) and iron statues (40 to 20).
-   Changes the item values of hide (20 -> 8) and fur (40 -> 18). The stockpile values have also changed. 
The stockpile at default now buys hide at 5 and sells it at 8.    (previously it purchased hides at 10 and sold at 15 by default)
The stockpile at default now buys fur at 10 and sells it at 15.  (previously it purchased fur at 15 and sold at 23 by default)
-  Adds iron chain leggings and steel plate leggings to the merchant machine. Changed the prices for armours upward. Also, rearranged some of the items to make more sense. (eg: for clothing, …

Steel, blacksmithing/merchant adjustments, hide/fur price changes

---

code/modules/food_and_drinks/food/snacks.dm

Have you ever wanted to play a Graggarite knight (usually) yet felt like SHIT because you can't commit Graggar's number 1 fav past time (eating organs) without throwing up?
NOW YOU CAN DO IT!!!
With this SIMPLE FIX!!!
Graggarite nobles ('n knights) can now eat organs and raw flesh without worrying about breaking character.
Also images to show that it still works if you:
Are a non-Graggarite noble that tries to eat organs!
Or!!!
Are a NOBODY (non-noble but non-Graggarite) trying to eat organs.

Nobles & Food: The Graggar Conundrum

---

code/modules/clothing/rogueclothes/armor.dm

As the title says. That's literally it. I must've missed this during the port.
yeag

Lets dwarf-types wear arming jackets

---

_maps/map_files/dun_manor/azure_forest.dmm
_maps/map_files/dun_manor/dun_manor.dmm
code/game/objects/effects/landmarks.dm

no more spawning in bandit camp
that's a deep cover bro

Adds court agent spawns

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/paladin.dm

People hate playing Paladin because as it stands right now they are lacking armor, even though they have the heavy armor trait too like Templars... spawning with a single hauberk. The Cleric gets better armor than they do. What's up with that?
This PR does the following hence:
- Changed the hauberk for a chain coif + half-plate (the armor clerics get)
- Switches the cloak for the templar variety whenever possible, which is much more fancy, for 𝓯𝓪𝓼𝓱𝓲𝓸𝓷 purposes.
- Gives them their God helmet. If you don't have a helmet variety for your God, well... bad luck bozo.
- Gives them the axes skill because I forgot. Tee-hee.
<details>
</details>
Avoid the syndrome of people going Templar then evaporating from the church because truly all they wanted to play was non-ass Paladin.

QoL | Paladins Drip Upgrade

---

code/game/objects/items/rogueweapons/rmb_intents.dm

You can now feint people on dodge intent. That's it! Don't mind the branch name, I was planning to make a trait but I actually think feinting is pretty good right now and just needed this little touch perhaps.
Feinting is cool. Lets int based people do something vs speed.

Feinting Speedsters

---

code/modules/jobs/job_types/roguetown/nobility/knight.dm

Gives mounted knights a saiga on spawn and adjusts their spawn loadouts/stats a bit to lean into them utilizing a mixture of bows and polearms on horseback.
Nobody plays Mounted Knight! Hopefully these changes give the subclass a bit more of an identity of its own. Playstyle should largely revolve around utilizing hit and run tactics with your mount. Designing an entire class themed around mounted combat without actually giving them a mount was kind of odd and left Mounted Knight lacking any real identity as a subclass.

Mounted knight glow up

---

code/modules/mob/living/carbon/human/examine.dm

Fixes ghost examine of court agents

---

code/modules/jobs/job_types/roguetown/adventurer/types/special/courtagent.dm

fixes court agents appearing in latejoin menu when slots are full

---

code/modules/mob/living/carbon/human/human.dm

You guys had it the whole time. It just had weird self-blocking logic.
- Aggro grab someone's chest.
- Have THEM clickdrag THEMSELVES onto YOU.
I dunno but you guys had it and it seems like it was supposed to work, but just didn't.

fixes piggyback riding

---

code/modules/clothing/rogueclothes/hats.dm

helmets no longer hide hair and other sprite accessories when worn on your belt

---

code/_onclick/other_mobs.dm
code/game/objects/items/rogueitems/waterskin.dm
code/modules/reagents/reagent_containers/bottle.dm

* Adds a return to exclude waterskins from bottle's throw_impact.
* Resizes waterskin to an easily identifiable size.
* Adds shatter sound to bottle when thrown.
* Adds A to AttackingTarget().

fix for waterskin shattering to glass upon throw impact

---

code/modules/mob/living/carbon/human/examine.dm

murphy's law
anything that isn't null checked
will runtime
I wasn't able to recreate whatever circumstances led to a connected player to get a null mind, but this should stop it either way

fixes court agent ghost examine runtime again

---

code/modules/jobs/job_types/roguetown/church/monk.dm

Gives Abyssor Acolytes journeyman fishing and water breathing, gives all Acolytes a satchel (FINALLY)

Super MASSIVE Abyssor (and normal) Acolyte buff. (Absolutely game changing) (Massive update) (Definitely not clickbait!!!)

---

code/modules/mob/living/living.dm

By request.
It's a pretty scrappy band-aid, but it works.
It's undesirable to have a Werewolf be able to cheese point blank charges mid-combat, or for anyone else.

Point blank charges always fail

---

code/modules/surgery/bodyparts/bodypart_dismemberment.dm

It was being deleted, I don't think it needs to be
Hopefully fixes some things associated with decapitations and resurrections

Keep mind in brain after decapitation

---

code/modules/reagents/reagent_containers/bottle.dm

Puts a message in the chat when you cap/uncap bottles.
QoL change. Makes it a bit easier to tell whether the bottle of red you're trying to drink from still has a cap on it without shift-clicking it.

Better bottle feedback

---

code/datums/gods/patrons/divine_pantheon.dm
code/modules/jobs/job_types/roguetown/church/monk.dm
code/modules/jobs/job_types/roguetown/church/templar.dm

Gives malum-worshippers lesser miracle
bugfix, i forgot about lesser miracle

Malum miracles bugfix

---

code/modules/jobs/job_types/roguetown/church/templar.dm

Gives templars half plate and plated boots
Puts them on a level playing field as most frag roles that fuck with Church
By request of Eve it's not my problem ping him if you are malding

Templar Armor Balancejak

---

code/modules/jobs/job_types/roguetown/church/templar.dm

By request, they're no longer naked.
I totally didn't start playing templar guys I swear

Templar Monk gets armor, katar and steel bracers

---

_maps/map_files/dun_manor/smallforest.dmm
_maps/map_files/rockhill/rockhill.dmm
code/game/objects/items/rogueitems/bait.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/donator/vaquero.dm
code/modules/jobs/job_types/roguetown/adventurer/types/special/whitecheesemaker.dm
code/modules/jobs/job_types/roguetown/nobility/captain.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm
code/modules/mob/living/simple_animal/rogue/game/saiga.dm
code/modules/roguetown/roguestock/import.dm

a couple of broken paths from a previous pr that got missed by my compiler and weren't spitting runtimes. it flagged other ones when i repathed saiga bucks, but for whatever reason these ones just worked lol
fixes bugs 👍

quick fixes some broken paths

---

code/modules/reagents/reagent_containers/bottle.dm

[src] already calls a 'the' so this fixes that so it won't be 'the the bottle'.

A bottle fix

---

code/controllers/subsystem/fire_burning.dm
code/datums/wounds/types/fractures.dm
code/modules/atmospherics/environmental/LINDA_fire.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/spells/roguetown/acolyte/noc.dm
code/modules/spells/roguetown/wizard.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Ports the following, huge thanks to them:
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1086
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1865
https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1516
* Fire stacks should hopefully be less absurd now. Hotspots still crit you if you're in it for too long.
* You roll if prone resisting.
* Can't feel your limbs if they're paralyzed.
* Lowers strength requirement on gravity from 13 to 11.
* Adds cooldown to Repel, roughly same as Blade Burst.
* Lightning Bolt no longer hard stuns, and paralyzes you instead.
* Blindness lasts 4 seconds instead of 5.
powergamers go to hell

spells & fire is less absurd

---

code/game/objects/items/rogueweapons/melee/special.dm

Adds a lightning effect to master rod

---

code/modules/mob/living/living.dm

Better to prevent it immediately than after a do after.

Fixes being able to strip people at a distance

---

code/modules/mob/living/carbon/human/damage_procs.dm
code/modules/mob/mob_movement.dm

I figured me being lazy with my merge conflict testing left something unattended.
Violent dismounting and sprinting now work as intended on horseback

Fixes mount bugs

---

code/controllers/subsystem/fire_burning.dm

It now takes, roughly, 30 seconds to ash something.

makes fire do 100x more damage to objects

---

code/modules/jobs/job_types/roguetown/church/templar.dm

Took it out of the Disciple PR and made it a separate thing so the pants wouldn't be held hostage by unrelated changes
Request! Target Leg meta = Leg armor in default combat gear meta

Gives templar monks armored pants

---

code/modules/jobs/job_types/roguetown/nobility/knight.dm

Changes the Crownstone RG currently get into a Houndstone
Oopsies, I fucked up an item path while fixing merge conflicts. They weren't meant to get crownstones. Only leadership roles do! :3e

Nerfs RG into unplayability(real, not bait)

---

_maps/map_files/dun_manor/dun_manor.dmm

This door had a closed turf underneath it, now it's cobble.
mysterious void underneath the door is leaking again

(Mapfix) Fixes void tile in garrison cell

---

code/datums/sexcon/sex_actions/oral/kissing.dm
roguetown.dme

ports kissing from ratwood ( https://github.com/Rotwood-Vale/Ratwood-Keep/pull/2085 )

sloppy make out pr

---

code/__DEFINES/preferences.dm
code/modules/mob/dead/new_player/new_player.dm

Admin request because people are joining in without anything in their OOC notes, violation of Rule 3
saves admin headache

Copies flavortext minimum for ooc notes, set to 5 chars

---

modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/vagabond.dm

Vagabond latejoining is no longer announced over SCOMs
kinda weird innit

Azure Peak is no longer informed of hobos arriving

---

code/modules/roguetown/roguemachine/scomm.dm

Dukes, Marshalls, and GCs can now use stationary gscoms.

---

code/modules/client/preferences.dm

From 20 -> 40 for normal players
30 -> 60 for members
On a server like this with so many job slots and job hopping rules, it was sort of inevitable that 20 will be deemed too few for more than a small minority of players, especially longer-playing ones.

Doubles the amount of char slots available

---

_maps/map_files/dun_manor/dun_manor.dmm

Mostly unchanged, just added easier pathing and made the Nerve Master seem more important at a glance. Easier to enter with more people.
Basically entirely remapped to look like an actual housing / dining area.
Office and Bath, all Steward's domain.
Overall it should feel and look better, at least to my own eyes.

Remaps steward

---

code/__DEFINES/qdel.dm
code/controllers/subsystem.dm
code/controllers/subsystem/garbage.dm
code/controllers/subsystem/processing/wet_floors.dm
code/datums/chatmessage.dm
code/modules/unit_tests/create_and_destroy.dm

Reverts GeneralPantsuIsBadAtCoding/Azure-Peak#1203

Revert "Reverts subsystem changes"

---

_maps/map_files/dun_manor/dun_manor.dmm

fixes tavern staff door having wrong lockid

---

_maps/map_files/dun_manor/dun_manor.dmm

Minor tweaks, most notably to the pillories and the Nerve Master bulge. It no longer juts out into the core street of the town.
You can sprint to and from the Keep without smashing into a wall!

Steward re-remap (minor)

---

_maps/map_files/dun_manor/dun_manor.dmm

Swaps the closet that has black variants of clothes that already exist in every other closet, to be full of herbal soap instead.
The Bath doesn't have /soap/. What.

Oversight Fix | Adds herbal soaps 

---

code/game/sound.dm

This makes it so if a sound is designated to NOT ignore walls, it will not propagate through floors / ceilings at all.
This is mostly relevant to one particular category of sounds, and by consequence certain locations (inn) will be a lot less awkward.
Quieter! Sorta. You may still need to cover your mouth for complete silence.

Makes the Tavern a lot more quieter and more decent (sound propagation nerf)

---

code/controllers/subsystem/garbage.dm
code/game/turfs/closed/minerals.dm

environment destruction runtime when killed by splash damage
revert a revert (increase time before warning about a del)

one bug + one revert

---

modular_azurepeak/virtues/utility.dm

I don't think the intention behind this virtue was to give Jman dedicated crafters Master
You get a CARPET of skills, you can grind up the ones you want, man

Caps crafter's apprentice at apprentice

---

modular_azurepeak/virtues/combat.dm

Fixes Toxophiliate and Duelist Apprentice not giving a +1 when you start as Apprentice

---

code/modules/client/customizer/customizers/organ/ears.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/aasimar.dm

Gives Aasimar half-kin wings and two optional elven ears.
By request! Le angles don't have le angle wings.

Adds wings and elf ears (optional) to aasimar

---

code/controllers/subsystem/ticker.dm

this isn't a fix for the underlying issue, but at least it won't break the entire readied playerbase, instead just that one guy:tm: who's causing it

"Fixes" the roundstart transfer char runtime

---

code/modules/jobs/job_types/roguetown/yeomen/archivist.dm

Luto damn you're fast
no arcane cheesing, but get some other misc stuff that's ass to train as an option

Changes Tutor's Calling to exclude arcane, include more skills

---

code/modules/surgery/surgeries/plastic_surgery.dm

Reshape face was throwing a runtime and just, not working at all when trying to use it for its 'Change identity' function. Corrects that runtime.
Surgeons can now hide people's identities!

BUGFIX: Reshape Face now functions

---

code/modules/roguetown/roguejobs/tailor/dyer.dm

oops it turned into a dupe by accident

Fixes the red color in the dye bin

---

code/modules/roguetown/roguecrafting/structure.dm

This makes operating table craftable. Really, there are only a few of them in the game and it's a relatively simple thing.

Operating Table Crafting

---

code/modules/mob/living/carbon/human/examine.dm

Junkie
Smoker
Nympho
Alcoholic
Paranoid at Paranoid of the same species
Paranoid at Paranoid of a different species
Masochist looking at a Sadist
Sadist looking at a Masochist
let the homies get together for group (substance abuse) therapy

Addicts (and racists) recognise each other on examine

---

modular/code/datums/character_flaw.dm

The server environment doesn't really allow for 3-4 scenes per round. This makes it trigger ~2x per 3h round.
If you believe other addictions could stand to be increased, feel free to put it here, this one seemed particularly warranting it.
Give 'em hoes a bone y'know

Changes the love fiend addiction timer to 90 minutes from 45

---

code/modules/mob/living/carbon/human/npc/deadite.dm
roguetown.dme

barebones deadite summon, auto aggressive

---

code/modules/mob/living/carbon/human/examine.dm
modular_azurepeak/virtues/combat.dm

This is weird. Bad.
Also makes it so Guarded flaw can't have their flaws noticed.
Self-examine doesn't need junk like that. Also added Guarded stuff that no one would pick it for, but fits the general idea of the trait.

You don't see your own flaw on self examine. Guarded prevents your flaw from being seen.

---

code/modules/clothing/rogueclothes/hats.dm

Putting those on will no longer balden you the first time.

heavy hood and hijab fix

---

code/modules/jobs/job_types/roguetown/courtier/jester.dm

By giving them wildkin tongue on spawn.
By request.

Allows Jester to make animal noises

---

code/__DEFINES/combat.dm
code/game/objects/items/rogueweapons/melee/polearms.dm

YIPEPE!!!!
Allows you to FISH with FISHING SPEARS. Also makes them one-handed.
Fishing. Spear.

FISHING SPEAR FISHING

---

code/game/objects/items/devices/flashlight.dm
code/game/objects/items/rogueitems/bags.dm
code/game/objects/items/rogueitems/natural/wood.dm
code/modules/clothing/rogueclothes/rings.dm
code/modules/roguetown/roguemachine/scomm.dm

Resizes inventory grid to:
* Stick
* Sack
* Lampterns
* Scomstones
* Emerald Choker
* Speaker Ring
* Listener
* Matthian Scomcoin
* Assigns appropriate drop sound to rings and scomstones.

resizes grid for some items

---

modular_azurepeak/statpacks/wildcard.dm

For them homies who don't want to be forced to get a -X in stats.

Adds a neutral statpack

---

code/modules/mob/living/carbon/carbon.dm

By semi-request. I'm fairly neutral on it, but someone asked to make a PR. And admittedly, I haven't heard of anyone causing issues with it (though the main argument against it was that it COULD be abusable).

Returns the easy throw to Giant virtue

---

code/datums/gods/patrons/divine_pantheon.dm

Gives Eorans the Good-Lover trait.
I mean I feel like this is just a given. Yeah she doesn't stand for DO THE SEX but when one does impart their love, let it be great.

Eoran Viagra

---

code/controllers/subsystem/particle_weather.dm

stops deleting weatherEffect (we need that)
fixes weather

weather fix

---

code/modules/jobs/job_types/_job.dm

Bandits are hidden in Actors List

---

code/modules/jobs/job_types/_job.dm

it works now I swear (bandit hiding)

---

code/game/objects/items/rogueitems/bombs.dm
code/modules/farming/composter.dm
code/modules/mob/living/ambush.dm
code/modules/roguetown/mapgen/forest.dm

Adjusted inventory grid to:
* Compost
* Fertilizer
* Bottle Bombs
* Increased herb & grass mapgen in Azure Forest.
* Slightly increased ambush chance.

inventory tweak & increased herb n grass spawn

---

code/modules/roguetown/roguecrafting/alchemy.dm

proper count
fixes alch bottle recipe to properly give six flasks instead of one
it was meant to.

fixes alchemy bottle recipe

---

code/modules/roguetown/roguecrafting/alchemy.dm
code/modules/roguetown/roguecrafting/alchemy/grind_recipes.dm
code/modules/roguetown/roguecrafting/alchemy/ingredients.dm
code/modules/roguetown/roguecrafting/structure.dm

tweaks verbage of alchemy ingredients to make them make more sense.
we dont HAVE runes. also we need to be able to make bottles.

alchemy verbage tweaks, glass bottle re-added. whoops.

---

code/modules/clothing/rogueclothes/armor.dm
code/modules/clothing/rogueclothes/feet.dm
code/modules/clothing/rogueclothes/gloves.dm
code/modules/clothing/rogueclothes/hats.dm
code/modules/clothing/rogueclothes/pants.dm
code/modules/roguetown/roguecrafting/sewing.dm

Normalizes capitalization for gear names.
The main offenders were the blacksteel armor I made a while ago (oops) and the heavy hood/hijab.
They've been normalized to lower case names.
Consistency.

Normalizes capitalization for names

---

_maps/map_files/dun_manor/dun_manor.dmm

i missed a few doors in some of the existing houses
fix good

quick town house door fix

---

_maps/map_files/dun_manor/dun_manor.dmm

fixes a bug that connects the bathhouse and the new gate-house via stairs

Fixes west gatehouse staircase

---

code/modules/mob/living/life.dm

handles temperature again
temperature is once again handled when not on fire

bugfix: handle temperature

---

code/modules/antagonists/roguetown/villain/vampirelord.dm

VL thralls were choosing from a list of the old adventurer classes, which don't exist anymore
bug fix
to be honest there's a lot of other bugs/issues with vampires that i should probably look into fixing but

Quick vampire class select fix

---

_maps/map_files/dun_manor/dun_manor.dmm

Adds 2 of each of the following to the church's clothing storage area:
Malumite Tabard
Astratan Tabard
Necran Tabard 
Abyssor Robes and Hoods
Abyssor Amulet
These can't be crafted and they're cool as shit.
most of the tabards monks (templar monks) start with are kinda ugly.

Adds tabards and Abyssor amulets to the church storage room.

---

code/__DEFINES/qdel.dm
code/controllers/subsystem.dm
code/controllers/subsystem/garbage.dm

reverts some changes to a subsystem
not entirely sure. might be amazing, might make no difference at all

reverts some SS changes

---

code/controllers/subsystem/rogue/triumphs/triumphs.dm
code/modules/admin/admin.dm
code/modules/admin/topic.dm
code/modules/admin/verbs/randomverbs.dm

Trying to pin down a Triumph disappearing issue, did something sickening to the WRITE_FILE for triumphs to try and stop them from disappearing. Also adds Player Quality and Triumph counter / manipulation to PP, where it probably should have been forever.

Adds player quality and triumph counter and modifiers to player panel

---

_maps/map_files/dun_manor/dun_manor.dmm

Adds missing soap to the baths closet.
How the fuck are the bath maidens washing people without soap?

Fix | Adds back missing soap

---

roguetown.dme

Ticked, unticked, why don't we tick off some inquisitors amiright fellas
oopsie

Enables Atgervi Mercs

---

code/modules/jobs/job_types/roguetown/nobility/hand.dm

What it says on the tin. 4 points, Apprentice Arcyne
By request! I presume it's to make the Hand Advisor, like, uh, worth picking, but not make them equivalent to a real mage.

Gives Hand Advisor Apprentice Arcyne (4 points total)

---

code/controllers/subsystem/rogue/triumphs/triumphs.dm

Triumphs aren't writing to disk, oopsie doodle. This fixes it.
Did you know the evil byond fcopy() will return TRUE despite not doing anything?

String literals for evil byond fcopy in Triumph redundancy

---

code/controllers/subsystem/adjacent_air.dm

used for smoke spreading - pyroclastic arrows, aerosolize
gm smoke spread command 
some lost functionality from atmos subsystem removal

calculate atmos adjacency manually

---

code/modules/jobs/job_types/roguetown/church/templar.dm

Forgor that templars had subclasses
working as intended:tm:

Gives regular templars ritualist

---

code/datums/status_effects/rogue/roguebuff.dm

Strong bite actually removed on end of dendor duration.
Guiding light's per buff should go away now
yea

Ritual bugfixes

---

code/modules/clothing/rogueclothes/hats.dm
code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm
code/modules/jobs/job_types/roguetown/church/templar.dm

adds a helmet for ravox paladins and templars

---

code/modules/jobs/job_types/roguetown/nobility/captain.dm

Changed the GC Infantry class to have a tabard and a bucket helmet instead.
<details>
</details>
Requested (also it looks cooler).

Update | Guard Captain helm change.

---

code/modules/jobs/job_types/roguetown/nobility/hand.dm

Gives each hand class a crownstone.
Why would the right hand of the Duke not be able to hear the garrison and the SCOMline?

Addition | Gives hands crownstones

---

_maps/map_files/generic/CentCom.dmm

As per https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/587 (god its been so long ago now)
Adds two covetous crowns to the bandit hoardmaster room
By request - And also, a old feature bandits were intended to get some while ago.

Covetous Crown added to the map

---

code/modules/client/verbs/ghost.dm

Continuation of #1424 - don't want a bunch of ghosts floating around.
Your player panel may thank you?

Delete ghosts when they returntolobby

---

code/game/objects/items/devices/flashlight.dm
code/game/objects/lighting/rogue_fires.dm

Gives torches a special 'weather_resistant' flag when they're in a sconce, preventing them from being extinguished by rain. Torches held in-hand still get extinguished as normal.
Half the lights in the city going out every time it rains is annoying.

Sconced torches no longer extinguish in the rain

---

_maps/map_files/dun_manor/dun_manor.dmm

Screens :
<details>
</details>
The mercenaries, as one of the most played classes in the game, could use a meeting and resting area of their own that isn't an inn room, forgotten on the second floor. This PR aims to improve those mappings.

Mercenaries house and inn staff room expansion

---

_maps/map_files/dun_manor/dun_manor.dmm

Makes some relatively small mapping changes to the archivist's bedroom and gives them a door leading into the physician's alchemy room. It's a shared space.
<details>
<summary>Screenshots:</summary>
</details>
#dev-suggestions feedback on the discord
The archivist gets alchemy skills but doesn't have a proper alchemy setup.
I was going to give them their own alchemy area, but I think it might be cooler if they just share one with the physician since they're so close to one another and they both technically work for the court anyways. Jolly co-operation.

The archivist and the physician now share an alchemy lab

---

code/__DEFINES/admin.dm
code/__HELPERS/roundend.dm
code/__HELPERS/text.dm
code/game/objects/items/rogueweapons/intents.dm
code/game/objects/items/rogueweapons/ranged/bows.dm
code/game/objects/items/rogueweapons/ranged/crossbows.dm
code/modules/admin/admin.dm
code/modules/admin/verbs/randomverbs.dm
code/modules/mob/living/life.dm
code/modules/mob/mob_helpers.dm
code/modules/mob/mob_movement.dm
code/modules/reagents/reagent_containers.dm
code/modules/reagents/reagent_containers/bottle.dm
modular_hearthstone/code/interface/LOOC.dm

Ports a couple of fixes & changes from Vanderlin, Dreamkeep.
* Runtime fixes to bows, crossbows, intent, hotspot, lumcount (hopefully).
* Reagent containers now gather rainwater outdoors.
* Can now have a comma in your character's name.
* You can turn while running.
* Adds LOOC mute (for admins).

Runtymes and small QoL

---

code/__DEFINES/admin.dm
code/modules/admin/admin.dm
code/modules/admin/verbs/randomverbs.dm
modular_hearthstone/code/interface/LOOC.dm

briefly reverts it because it's midnight and I'd rather figure it out tomorrow

briefly reverts looc changes

---

modular_azurepeak/virtues/utility.dm

Puts callback on input-required virtues (linguist/intellectual, performer) for runtime sanity.
chasing runtimes

Adds proc callbacks for virtues that were requesting input

---

code/controllers/subsystem/ticker.dm

Nasty strange runtime on this line on a server init where nobody could move, hopefully this fixes the access error.
round has to start somehow

Prevents null runtime on access of notransform in release_characters

---

code/modules/roguetown/roguecrafting/leather.dm

Corsets didn't have any reqs, this adds some.
get out of my crafting menu forever, corset!

Gives new corset recipe some reqs

---

code/modules/cargo/packsrogue/weapons.dm

Fixes Sail Daggers and Shamshir paths in the merchant buylist
yea

Merchant list fixes

---

code/__DEFINES/inventory.dm
code/modules/clothing/masks/miscellaneous.dm
code/modules/clothing/rogueclothes/hats.dm
code/modules/clothing/rogueclothes/mask.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/atgervi.dm
code/modules/mob/dead/new_player/sprite_accessory/snouts.dm
modular_azurepeak/code/modules/clothing/rogueclothes/hats.dm

Creates a seperate tag for 'snouts' to allow for them to show from under hoods and other open faced helmets. Went through every helmet/mask I could find to make sure they worked appropriately.
Edit: Checked the cloaks too, they're fine.
Dewit
No more strange human faces for beast folk under their masks.

Gives snouters back their snoots

---

code/modules/roguetown/roguecrafting/weaving.dm

Read the title.
They're cool? And the actual inquisitors have different capes now I think.

Makes puritan capes craftable.

---

code/modules/clothing/rogueclothes/hats.dm

I'M SORRY I DELETED YOUR FACE FORGIVE ME

Big fix snout pr oopsie

---

code/__HELPERS/unsorted.dm
modular_hearthstone/code/modules/spells/roguetown/wizard.dm

Makes it so washing yourself also washes your cloak. Simple as.
Also, un-snowflakes the prestidigitation cleaning code so it uses wash_atom like the rest of the game does.
We loooove washing.

The Washing PR (Cloak washing, Prestidigitation cleaning)

---

_maps/map_files/dun_manor/dun_manor.dmm

Edited the captain bedroom to be bigger.
Before:
<details>
</details>
After:
<details>
</details>
Also gave the marshal a bigger bed like the Hand and Seneschal have.
The itty bitty tiny room stressed me the fuck out.

Map Change | Updates the Guard Captain quarters

---

code/modules/clothing/rogueclothes/hats.dm
code/modules/clothing/rogueclothes/mask.dm

Just a few more missed ones. Still no clue how. Went through every line of flags_inv with HIDEFACE
Pls let this be the last one Ludo's gonna lynch me

More Snout Cleanup

---

code/game/objects/items/rogueweapons/ranged/ammo.dm
code/modules/clothing/rogueclothes/quiver.dm

Fixed an error with being able to load 20 javelins into a bag. Also added armor pen to the javelins so they can actually damage through some armors.
Bug fixing, basically.

Javelin Bag Fix + Armor Penetration

---

_maps/map_files/dun_manor/dun_manor.dmm

I forgot about a very important thing.
No sudden bandits/rain dropping on your head while you sleep.

FIX | Adds a roof onto the GC quarters

---

modular_hearthstone/code/interface/LOOC.dm

You know exactly what this does.
You know EXACTLY why I made it.

LOOC no longer wallpierces, added LOOC (Wallpierce)

---

code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm

I forgor to add the new crafting paths for javelins after changing them from weapons to caseless projectiles. Plus never added the silver one.
Woopsy.

Javelin Smithing Addition

---

code/controllers/subsystem/particle_weather.dm
code/controllers/subsystem/rogue/soundloopers.dm
code/datums/looping_sounds/_looping_sound.dm
code/datums/particle_weathers/_base.dm
code/game/objects/items/rogueitems/instruments.dm
code/game/sound.dm

Some more fixes to looping sounds, particularly fixing small issues with music boxes, instruments, and weather.
Also adds a custom sound group to instruments which should allow for multiple instruments playing at once.
Todo: rain sounds from inside a building, this will require a bit more work but should be doable. Will put it in a separate PR.
Bugfixes yay. Should stop things like ghost music box sounds in different z-levels, weather sounds bugging out, etc.

Looping sounds 2: electric boogaloo

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/vaquero.dm

Reverts the Vaquero class' description to the spicier version.
The current class description is serviceable, but I feel fails to capture the feelings of excitement and adventure the Vaquero fantasy should appeal to. This description is one I wrote for the class some time ago but was lost when the class was temporarily removed from the game. Now that We're So Back as mercenaries, I think re-spicing the description will make it more appealing.

New Vaquero Description bby

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/wretch.dm

Whoops. The Castifico update came after my PR so here's a fix.
Also a tiny correction on the blurb text.

Puts bounties on Poachers

---

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/witch.dm

Double, double toil and trouble;
Fire burn and caldron bubble.
Fillet of a fenny snake,
In the caldron boil and bake;
Eye of newt and toe of frog,
Wool of bat and tongue of dog,
Adder's fork and blind-worm's sting,
Lizard's leg and howlet's wing,
For a charm of powerful trouble,
Like a hell-broth boil and bubble.
Oversight

Gives Witch the Cauldron Alchemy skill

---

code/game/objects/items/rogueweapons/melee/swords.dm

Puts the right chop intent on the astratan executioner
yea

Astrata sword correct chop

---

code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm
code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm

* solves a really bad runtime with shapeshift deaths where the game tries to rot something that doesn't exist
* sets intent on gaseous mist

shapeshift runtime

---

code/modules/mob/living/simple_animal/hostile/retaliate/bat.dm

Prevents bat / crow from being able to traverse Z levels while grabbed. Also a slight nudge for VL bat so that it can zip around faster than witch crow.
Hopefully the pulledby check is robust enough for grabbing onto simpleanimals..

Touches bat/crow fly procs, putting in stops when pulled/grabbed.

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm

Gives Zizo Missionary the ability to control their bone men with the minion-order spell.
First PR here, or in general, ever, so if something's screwed lemme know.
Was told this was probably an oversight, thought it's time to fix that for the sake of it.

Giving Zizo Missionary control of their bone men.

---

_maps/map_files/dun_manor/dun_manor.dmm
code/game/objects/effects/landmarks.dm
code/modules/jobs/job_types/roguetown/peasants/lunatic.dm

What if Lunatics were good, actually?
Sets Lunatic min PR to 100, letting them be a prestige / illuminated fool "Chorus" class for the general publick. Gives them some towner-esque stats for their hard lifestyle.
I hope it is.

Spruces lunatic up to a prestige class
